### ISSUE TITLE
Write a JavaScript program to print hello world

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#10]
### Description

Write a JavaScript program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.js` file
- Add `PrintHelloWorld.js` file in `print-hello-world` folder

</details>

**Comment by KaptainCS3** [comment]
assign me

**Comment by KaptainCS3** [comment]
!assign
