### ISSUE TITLE
Write a Ruby program to find volume of a cuboid

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#100]
### Description

Write a Ruby program to find volume of a cuboid

Volume of a cuboid = `Length` × `Width` × `Height`

```
Length : 2
Width  : 3
Height : 4

Volume : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfACuboid.rb` file
- Add `FindVolumeOfACuboid.rb` file in `find-volume-of-a-cuboid` folder

</details>

**Comment by PraaneshSelvaraj** [comment]
!assign
