### ISSUE TITLE
Write a C program to convert minutes to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1005]
### Description

Write a C program to convert minutes to weeks

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 50400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMinutesToWeeks.c` file
- Add `ConvertMinutesToWeeks.c` file in `convert-minutes-to-weeks` folder

</details>

**Comment by anxkhn** [comment]
!assign

**Comment by pokharel-nishan** [comment]
!assign
