### ISSUE TITLE
Write a C++ program to convert minutes to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1007]
### Description

Write a C++ program to convert minutes to weeks

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 50400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMinutesToWeeks.cpp` file
- Add `ConvertMinutesToWeeks.cpp` file in `convert-minutes-to-weeks` folder

</details>

**Comment by Mahak008** [comment]
!assign

**Comment by Taanvee** [comment]
Can you assign it to me?

**Comment by shivampipalwa** [comment]
!assign
