### ISSUE TITLE
Write a Rust program to find volume of a cuboid

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#101]
### Description

Write a Rust program to find volume of a cuboid

Volume of a cuboid = `Length` × `Width` × `Height`

```
Length : 2
Width  : 3
Height : 4

Volume : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_volume_of_a_cuboid.rs` file
- Add `find_volume_of_a_cuboid.rs` file in `find-volume-of-a-cuboid` folder

</details>

**Comment by esivakumar18** [comment]
!assign
