### ISSUE TITLE
Write a GO program to convert minutes to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1010]
### Description

Write a GO program to convert minutes to weeks

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 50400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_minutes_to_weeks.go` file
- Add `convert_minutes_to_weeks.go` file in `convert-minutes-to-weeks` folder

</details>

**Comment by nickdark** [comment]
I'd like to be assigned this issue.

**Comment by harshraj8843** [comment]
> I'd like to be assigned this issue.

Hey @nickdark 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by MadhuS-1605** [comment]
!assign
