### ISSUE TITLE
Write a JavaScript program to convert minutes to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1012]
### Description

Write a JavaScript program to convert minutes to weeks

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 50400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMinutesToWeeks.js` file
- Add `ConvertMinutesToWeeks.js` file in `convert-minutes-to-weeks` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
