### ISSUE TITLE
Write a Julia program to convert minutes to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1013]
### Description

Write a Julia program to convert minutes to weeks

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 50400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-minutes-to-weeks.jl` file
- Add `convert-minutes-to-weeks.jl` file in `convert-minutes-to-weeks` folder

</details>

**Comment by RiteshK-611** [comment]
!assign

**Comment by RiteshK-611** [comment]
Hey @harshraj8843 
Please close this issue as it's been solved.
Here is the file link for this issue [Minutes to Weeks in Julia ](https://github.com/codinasion/program/blob/master/program/convert-minutes-to-weeks/convert-minutes-to-weeks.jl)

Also there is one more such issue: [Write a Julia program to convert seconds to days #3654](https://github.com/codinasion/program/issues/3654)

**Comment by harshraj8843** [comment]
Hey @RiteshK-611 

Thanks for noticing this 👍🏻
