### ISSUE TITLE
Write a Kotlin program to convert minutes to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1014]
### Description

Write a Kotlin program to convert minutes to weeks

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 50400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMinutesToWeeks.kt` file
- Add `ConvertMinutesToWeeks.kt` file in `convert-minutes-to-weeks` folder

</details>

**Comment by rksp25** [comment]
!assign
