### ISSUE TITLE
Write a Python program to convert minutes to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1017]
### Description

Write a Python program to convert minutes to weeks

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 50400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-minutes-to-weeks.py` file
- Add `convert-minutes-to-weeks.py` file in `convert-minutes-to-weeks` folder

</details>

**Comment by saroshfarhan** [comment]
!assign
