### ISSUE TITLE
Write a Scala program to convert minutes to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1021]
### Description

Write a Scala program to convert minutes to weeks

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 50400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convertMinutesToWeeks.scala` file
- Add `convertMinutesToWeeks.scala` file in `convert-minutes-to-weeks` folder

</details>

**Comment by nickdark** [comment]
I'd like to be assigned this issue.

**Comment by esivakumar18** [comment]
!assign
