### ISSUE TITLE
Write a C program to print character of an ascii value

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1027]
### Description

Write a C program to print character of an ascii value

ASCII value is the numeric representation of a character. For example, the ASCII value of the character 'A' is 65. The ASCII value of the character 'a' is 97. The ASCII value of the character '0' is 48. The ASCII value of the character ' ' is 32.

```
Input  : 65
Output : A
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintCharacterOfAnAsciiValue.c` file
- Add `PrintCharacterOfAnAsciiValue.c` file in `print-character-of-an-ascii-value` folder

</details>

**Comment by grraghav120** [comment]
I want to work on this issue

**Comment by grraghav120** [comment]
!assign

**Comment by Kushagra-a** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Kushagra-a, this issue is already assigned to @grraghav120 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
