### ISSUE TITLE
Write a C++ program to print character of an ascii value

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1029]
### Description

Write a C++ program to print character of an ascii value

ASCII value is the numeric representation of a character. For example, the ASCII value of the character 'A' is 65. The ASCII value of the character 'a' is 97. The ASCII value of the character '0' is 48. The ASCII value of the character ' ' is 32.

```
Input  : 65
Output : A
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintCharacterOfAnAsciiValue.cpp` file
- Add `PrintCharacterOfAnAsciiValue.cpp` file in `print-character-of-an-ascii-value` folder

</details>

**Comment by grraghav120** [comment]
kindly assign me for this task. i want to on this

**Comment by grraghav120** [comment]
!assign
