### ISSUE TITLE
Write a Java program to print character of an ascii value

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1033]
### Description

Write a Java program to print character of an ascii value

ASCII value is the numeric representation of a character. For example, the ASCII value of the character 'A' is 65. The ASCII value of the character 'a' is 97. The ASCII value of the character '0' is 48. The ASCII value of the character ' ' is 32.

```
Input  : 65
Output : A
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintCharacterOfAnAsciiValue.java` file
- Add `PrintCharacterOfAnAsciiValue.java` file in `print-character-of-an-ascii-value` folder

</details>

**Comment by anshu-6537** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @anshu-6537,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by pokharel-nishan** [comment]
!assign

**Comment by pokharel-nishan** [comment]
the file PrintCharacterOfAnAsciiValue.java already exists in the directory. But there are some errors in that file. Now, should I make changes to that file or leave that as it is?

**Comment by harshraj8843** [comment]
@pokharel-nishan you can contribute the updated code 🤗
