### ISSUE TITLE
Write a JavaScript program to print character of an ascii value

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1034]
### Description

Write a JavaScript program to print character of an ascii value

ASCII value is the numeric representation of a character. For example, the ASCII value of the character 'A' is 65. The ASCII value of the character 'a' is 97. The ASCII value of the character '0' is 48. The ASCII value of the character ' ' is 32.

```
Input  : 65
Output : A
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintCharacterOfAnAsciiValue.js` file
- Add `PrintCharacterOfAnAsciiValue.js` file in `print-character-of-an-ascii-value` folder

</details>

**Comment by Kushagra-a** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Kushagra-a,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by erezcal1** [comment]
Why is this issue still open? The file exist...

**Comment by harshraj8843** [comment]
Hey @erezcal1 

I am unable to find the file here 👉🏻 `https://github.com/codinasion/program/tree/master/program/print-character-of-an-ascii-value`

Could you please provide the link to the file?

**Comment by erezcal1** [comment]
Sorry I saw the opposite.
!assign
