### ISSUE TITLE
Write a TypeScript program to find volume of a cuboid

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#104]
### Description

Write a TypeScript program to find volume of a cuboid

Volume of a cuboid = `Length` × `Width` × `Height`

```
Length : 2
Width  : 3
Height : 4

Volume : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfACuboid.ts` file
- Add `FindVolumeOfACuboid.ts` file in `find-volume-of-a-cuboid` folder

</details>

**Comment by harshraj8843** [comment]
!assign

**Comment by harshraj8843** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @harshraj8843, this issue is already assigned to @harshraj8843 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
!assign me

**Comment by harshraj8843** [comment]
Hey @harshraj8843, this issue is already assigned to @harshraj8843 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by MuhammadJufri** [comment]
!assign
