### ISSUE TITLE
Write a C++ program to check consonant

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1057]
### Description

Write a C++ program to check consonant

Check if a character is a consonant.

```
Input  : b
Output : Consonant
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckConsonant.cpp` file
- Add `CheckConsonant.cpp` file in `check-consonant` folder

</details>

**Comment by kashyapkumar-pdf** [comment]
!assign
