### ISSUE TITLE
Write a Java program to check consonant

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1061]
### Description

Write a Java program to check consonant

Check if a character is a consonant.

```
Input  : b
Output : Consonant
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckConsonant.java` file
- Add `CheckConsonant.java` file in `check-consonant` folder

</details>

**Comment by sahooankeeta** [comment]
!assign

**Comment by anuragwadhwa22** [comment]
Please assign this to me!
