### ISSUE TITLE
Write a JavaScript program to check consonant

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1062]
### Description

Write a JavaScript program to check consonant

Check if a character is a consonant.

```
Input  : b
Output : Consonant
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckConsonant.js` file
- Add `CheckConsonant.js` file in `check-consonant` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by Emmanuel-webDev** [comment]
Can you assign this to me
