### ISSUE TITLE
Write a Python program to check consonant

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1067]
### Description

Write a Python program to check consonant

Check if a character is a consonant.

```
Input  : b
Output : Consonant
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check-consonant.py` file
- Add `check-consonant.py` file in `check-consonant` folder

</details>

**Comment by venkat-siddarth** [comment]
I want to do this could you please assign it to me

**Comment by venkat-siddarth** [comment]
!assign
