### ISSUE TITLE
Write a C# program to divide two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#107]
### Description

Write a C# program to divide two numbers

```
Input  : 2 4
Output : 0.5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `DivideTwoNumbers.cs` file
- Add `DivideTwoNumbers.cs` file in `divide-two-numbers` folder

</details>

**Comment by Zeuhz-Droid** [comment]
!assign
