### ISSUE TITLE
Write a Scala program to check consonant

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1072]
### Description

Write a Scala program to check consonant

Check if a character is a consonant.

```
Input  : b
Output : Consonant
```
<details>
<summary>How to contribute</summary>

- Save the solution in `checkConsonant.scala` file
- Add `checkConsonant.scala` file in `check-consonant` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
