### ISSUE TITLE
Write a Swift program to check consonant

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1073]
### Description

Write a Swift program to check consonant

Check if a character is a consonant.

```
Input  : b
Output : Consonant
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckConsonant.swift` file
- Add `CheckConsonant.swift` file in `check-consonant` folder

</details>

**Comment by toukirkhan** [comment]
assign me!

**Comment by esivakumar18** [comment]
!assign
