### ISSUE TITLE
Write a TypeScript program to check consonant

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1074]
### Description

Write a TypeScript program to check consonant

Check if a character is a consonant.

```
Input  : b
Output : Consonant
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckConsonant.ts` file
- Add `CheckConsonant.ts` file in `check-consonant` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
