### ISSUE TITLE
Write a C++ program to divide two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#108]
### Description

Write a C++ program to divide two numbers

```
Input  : 2 4
Output : 0.5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `DivideTwoNumbers.cpp` file
- Add `DivideTwoNumbers.cpp` file in `divide-two-numbers` folder

</details>

**Comment by KaptainCS3** [comment]
assign me

**Comment by akansharai2023** [comment]
!assign

**Comment by Osher160** [comment]
!assign
