### ISSUE TITLE
Write a C program to convert weeks to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1081]
### Description

Write a C program to convert weeks to minutes

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 5
Output : 50400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToMinutes.c` file
- Add `ConvertWeeksToMinutes.c` file in `convert-weeks-to-minutes` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
i Would like to work on this as well.

**Comment by rwlc** [comment]
you'll have to reply with <exclamation>assign

**Comment by anxkhn** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @anxkhn,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by pokharel-nishan** [comment]
!assign
