### ISSUE TITLE
Write a GO program to convert weeks to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1086]
### Description

Write a GO program to convert weeks to minutes

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 5
Output : 50400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_weeks_to_minutes.go` file
- Add `convert_weeks_to_minutes.go` file in `convert-weeks-to-minutes` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign
