### ISSUE TITLE
Write a Java program to convert weeks to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1087]
### Description

Write a Java program to convert weeks to minutes

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 5
Output : 50400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToMinutes.java` file
- Add `ConvertWeeksToMinutes.java` file in `convert-weeks-to-minutes` folder

</details>

**Comment by imtiyaz786** [comment]
!assign
