### ISSUE TITLE
Write a Julia program to convert weeks to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1089]
### Description

Write a Julia program to convert weeks to minutes

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 5
Output : 50400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-weeks-to-minutes.jl` file
- Add `convert-weeks-to-minutes.jl` file in `convert-weeks-to-minutes` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
