### ISSUE TITLE
Write a Kotlin program to convert weeks to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1090]
### Description

Write a Kotlin program to convert weeks to minutes

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 5
Output : 50400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToMinutes.kt` file
- Add `ConvertWeeksToMinutes.kt` file in `convert-weeks-to-minutes` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
I would like to work on this. please assign it to me.
