### ISSUE TITLE
Write a PHP program to convert weeks to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1092]
### Description

Write a PHP program to convert weeks to minutes

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 5
Output : 50400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_weeks_to_minutes.php` file
- Add `convert_weeks_to_minutes.php` file in `convert-weeks-to-minutes` folder

</details>

**Comment by rizkytegar** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @rizkytegar,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
