### ISSUE TITLE
Write a R program to convert weeks to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1094]
### Description

Write a R program to convert weeks to minutes

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 5
Output : 50400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_weeks_to_minutes.r` file
- Add `convert_weeks_to_minutes.r` file in `convert-weeks-to-minutes` folder

</details>

**Comment by venkat-siddarth** [comment]
!assign
