### ISSUE TITLE
Write a Swift program to convert weeks to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1098]
### Description

Write a Swift program to convert weeks to minutes

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 5
Output : 50400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToMinutes.swift` file
- Add `ConvertWeeksToMinutes.swift` file in `convert-weeks-to-minutes` folder

</details>

**Comment by esivakumar18** [comment]
!assign

**Comment by esivakumar18** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @esivakumar18, this issue is already assigned to @esivakumar18 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
