### ISSUE TITLE
Write a TypeScript program to convert weeks to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1099]
### Description

Write a TypeScript program to convert weeks to minutes

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 5
Output : 50400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToMinutes.ts` file
- Add `ConvertWeeksToMinutes.ts` file in `convert-weeks-to-minutes` folder

</details>

**Comment by rwlc** [comment]
!assign
