### ISSUE TITLE
Write a Java program to convert miles to kilometers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1109]
### Description

Write a Java program to convert miles to kilometers

1 mile = 1.609 kilometers

```
Input  : 5
Output : 8.04672
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMilesToKilometers.java` file
- Add `ConvertMilesToKilometers.java` file in `convert-miles-to-kilometers` folder

</details>

**Comment by Mahak008** [comment]
!assign

**Comment by sumeetk10** [comment]
!assign
