### ISSUE TITLE
Write a GO program to divide two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#111]
### Description

Write a GO program to divide two numbers

```
Input  : 2 4
Output : 0.5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `divide_two_numbers.go` file
- Add `divide_two_numbers.go` file in `divide-two-numbers` folder

</details>

**Comment by renanlmiranda** [comment]
Done!

**Comment by renanlmiranda** [comment]
!assign
