### ISSUE TITLE
Write a JavaScript program to convert miles to kilometers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1110]
### Description

Write a JavaScript program to convert miles to kilometers

1 mile = 1.609 kilometers

```
Input  : 5
Output : 8.04672
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMilesToKilometers.js` file
- Add `ConvertMilesToKilometers.js` file in `convert-miles-to-kilometers` folder

</details>

**Comment by harshraj8843** [comment]
Hey @Greeshma-frontier,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by ShivamK2002** [comment]
!assign
