### ISSUE TITLE
Write a Kotlin program to convert miles to kilometers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1112]
### Description

Write a Kotlin program to convert miles to kilometers

1 mile = 1.609 kilometers

```
Input  : 5
Output : 8.04672
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMilesToKilometers.kt` file
- Add `ConvertMilesToKilometers.kt` file in `convert-miles-to-kilometers` folder

</details>

**Comment by rksp25** [comment]
!assign
