### ISSUE TITLE
Write a Python program to convert miles to kilometers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1115]
### Description

Write a Python program to convert miles to kilometers

1 mile = 1.609 kilometers

```
Input  : 5
Output : 8.04672
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-miles-to-kilometers.py` file
- Add `convert-miles-to-kilometers.py` file in `convert-miles-to-kilometers` folder

</details>

**Comment by mak650650** [comment]
!assign

**Comment by mak650650** [comment]
#1147  check it
