### ISSUE TITLE
Write a Swift program to convert miles to kilometers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1120]
### Description

Write a Swift program to convert miles to kilometers

1 mile = 1.609 kilometers

```
Input  : 5
Output : 8.04672
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMilesToKilometers.swift` file
- Add `ConvertMilesToKilometers.swift` file in `convert-miles-to-kilometers` folder

</details>

**Comment by esivakumar18** [comment]
!assign
