### ISSUE TITLE
Write a C++ program to check upper case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1129]
### Description

Write a C++ program to check upper case

Check if the given character is upper case (A-Z).

```
Input  : A
Output : Upper Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckUpperCase.cpp` file
- Add `CheckUpperCase.cpp` file in `check-upper-case` folder

</details>

**Comment by krishan-here** [comment]
!assign
