### ISSUE TITLE
Write a JavaScript program to divide two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#113]
### Description

Write a JavaScript program to divide two numbers

```
Input  : 2 4
Output : 0.5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `DivideTwoNumbers.js` file
- Add `DivideTwoNumbers.js` file in `divide-two-numbers` folder

</details>

**Comment by praveenscience** [comment]
!assign

**Comment by praveenscience** [comment]
I have started working on this, and I am planning to propose my PR on Oct 1st, so others kindly leave this for me. Thank you! 😁

**Comment by praveenscience** [comment]
Hey @harshraj8843, is everything okay in this PR? #318

**Comment by harshraj8843** [comment]
> Hey @harshraj8843, is everything okay in this PR? #318

Yes, it will be merged shortly 👍🏻
