### ISSUE TITLE
Write a GO program to check upper case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1132]
### Description

Write a GO program to check upper case

Check if the given character is upper case (A-Z).

```
Input  : A
Output : Upper Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check_upper_case.go` file
- Add `check_upper_case.go` file in `check-upper-case` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign
