### ISSUE TITLE
Write a JavaScript program to check upper case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1134]
### Description

Write a JavaScript program to check upper case

Check if the given character is upper case (A-Z).

```
Input  : A
Output : Upper Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckUpperCase.js` file
- Add `CheckUpperCase.js` file in `check-upper-case` folder

</details>

**Comment by rwlc** [comment]
!assign
