### ISSUE TITLE
Write a Kotlin program to check upper case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1136]
### Description

Write a Kotlin program to check upper case

Check if the given character is upper case (A-Z).

```
Input  : A
Output : Upper Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckUpperCase.kt` file
- Add `CheckUpperCase.kt` file in `check-upper-case` folder

</details>

**Comment by esivakumar18** [comment]
!assign
