### ISSUE TITLE
Write a Python program to check upper case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1139]
### Description

Write a Python program to check upper case

Check if the given character is upper case (A-Z).

```
Input  : A
Output : Upper Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check-upper-case.py` file
- Add `check-upper-case.py` file in `check-upper-case` folder

</details>

**Comment by mak650650** [comment]
!assign

**Comment by Forsigg** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Forsigg, this issue is already assigned to @mak650650 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
