### ISSUE TITLE
Write a Julia program to divide two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#114]
### Description

Write a Julia program to divide two numbers

```
Input  : 2 4
Output : 0.5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `divide-two-numbers.jl` file
- Add `divide-two-numbers.jl` file in `divide-two-numbers` folder

</details>

**Comment by LukasMikolaj** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @LukasMikolaj,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by nicoleSosa** [comment]
!assign
