### ISSUE TITLE
Write a Ruby program to check upper case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1141]
### Description

Write a Ruby program to check upper case

Check if the given character is upper case (A-Z).

```
Input  : A
Output : Upper Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckUpperCase.rb` file
- Add `CheckUpperCase.rb` file in `check-upper-case` folder

</details>

**Comment by jfinley6** [comment]
!assign
