### ISSUE TITLE
Write a Rust program to check upper case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1142]
### Description

Write a Rust program to check upper case

Check if the given character is upper case (A-Z).

```
Input  : A
Output : Upper Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check_upper_case.rs` file
- Add `check_upper_case.rs` file in `check-upper-case` folder

</details>

**Comment by rwlc** [comment]
!assign
