### ISSUE TITLE
Write a Scala program to check upper case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1143]
### Description

Write a Scala program to check upper case

Check if the given character is upper case (A-Z).

```
Input  : A
Output : Upper Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `checkUpperCase.scala` file
- Add `checkUpperCase.scala` file in `check-upper-case` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
