### ISSUE TITLE
Write a TypeScript program to check upper case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1145]
### Description

Write a TypeScript program to check upper case

Check if the given character is upper case (A-Z).

```
Input  : A
Output : Upper Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckUpperCase.ts` file
- Add `CheckUpperCase.ts` file in `check-upper-case` folder

</details>

**Comment by rwlc** [comment]
!assign
