### ISSUE TITLE
Write a Kotlin program to divide two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#115]
### Description

Write a Kotlin program to divide two numbers

```
Input  : 2 4
Output : 0.5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `DivideTwoNumbers.kt` file
- Add `DivideTwoNumbers.kt` file in `divide-two-numbers` folder

</details>

**Comment by esivakumar18** [comment]
!assign
