### ISSUE TITLE
Write a C++ program to convert hours to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1155]
### Description

Write a C++ program to convert hours to seconds

1 hour = 60 minutes = 3600 seconds

```
Input  : 5
Output : 18000
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertHoursToSeconds.cpp` file
- Add `ConvertHoursToSeconds.cpp` file in `convert-hours-to-seconds` folder

</details>

**Comment by Taanvee** [comment]
Can you assign it to me?

**Comment by shivampipalwa** [comment]
!assign
