### ISSUE TITLE
Write a GO program to convert hours to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1158]
### Description

Write a GO program to convert hours to seconds

1 hour = 60 minutes = 3600 seconds

```
Input  : 5
Output : 18000
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_hours_to_seconds.go` file
- Add `convert_hours_to_seconds.go` file in `convert-hours-to-seconds` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by Sairaviteja27** [comment]
!assign
