### ISSUE TITLE
Write a R program to convert hours to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1166]
### Description

Write a R program to convert hours to seconds

1 hour = 60 minutes = 3600 seconds

```
Input  : 5
Output : 18000
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_hours_to_seconds.r` file
- Add `convert_hours_to_seconds.r` file in `convert-hours-to-seconds` folder

</details>

**Comment by esivakumar18** [comment]
!assign
