### ISSUE TITLE
Write a C++ program to convert inches to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1185]
### Description

Write a C++ program to convert inches to miles

1 mile = 63360 inches

```
Input  : 316800
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToMiles.cpp` file
- Add `ConvertInchesToMiles.cpp` file in `convert-inches-to-miles` folder

</details>

**Comment by Mikasa-Ackerman2074** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Mikasa-Ackerman2074,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by AbhinavPrabhat01** [comment]
!assign
