### ISSUE TITLE
Write a GO program to convert inches to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1188]
### Description

Write a GO program to convert inches to miles

1 mile = 63360 inches

```
Input  : 316800
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_inches_to_miles.go` file
- Add `convert_inches_to_miles.go` file in `convert-inches-to-miles` folder

</details>

**Comment by nickdark** [comment]
!assign
