### ISSUE TITLE
Write a JavaScript program to convert inches to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1190]
### Description

Write a JavaScript program to convert inches to miles

1 mile = 63360 inches

```
Input  : 316800
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToMiles.js` file
- Add `ConvertInchesToMiles.js` file in `convert-inches-to-miles` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Greeshma-frontier, this issue is already assigned to @Greeshma-frontier !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
