### ISSUE TITLE
Write a Julia program to convert inches to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1191]
### Description

Write a Julia program to convert inches to miles

1 mile = 63360 inches

```
Input  : 316800
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-inches-to-miles.jl` file
- Add `convert-inches-to-miles.jl` file in `convert-inches-to-miles` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
