### ISSUE TITLE
Write a PHP program to convert inches to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1194]
### Description

Write a PHP program to convert inches to miles

1 mile = 63360 inches

```
Input  : 316800
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_inches_to_miles.php` file
- Add `convert_inches_to_miles.php` file in `convert-inches-to-miles` folder

</details>

**Comment by rahmat-st** [comment]
!assign
