### ISSUE TITLE
Write a Scala program to convert inches to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1199]
### Description

Write a Scala program to convert inches to miles

1 mile = 63360 inches

```
Input  : 316800
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convertInchesToMiles.scala` file
- Add `convertInchesToMiles.scala` file in `convert-inches-to-miles` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by esivakumar18** [comment]
!assign
