### ISSUE TITLE
Write a Ruby program to divide two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#120]
### Description

Write a Ruby program to divide two numbers

```
Input  : 2 4
Output : 0.5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `DivideTwoNumbers.rb` file
- Add `DivideTwoNumbers.rb` file in `divide-two-numbers` folder

</details>

**Comment by PraaneshSelvaraj** [comment]
!assign
