### ISSUE TITLE
Write a Swift program to convert inches to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1200]
### Description

Write a Swift program to convert inches to miles

1 mile = 63360 inches

```
Input  : 316800
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToMiles.swift` file
- Add `ConvertInchesToMiles.swift` file in `convert-inches-to-miles` folder

</details>

**Comment by esivakumar18** [comment]
!assign
