### ISSUE TITLE
Write a TypeScript program to convert inches to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1201]
### Description

Write a TypeScript program to convert inches to miles

1 mile = 63360 inches

```
Input  : 316800
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToMiles.ts` file
- Add `ConvertInchesToMiles.ts` file in `convert-inches-to-miles` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
