### ISSUE TITLE
Write a C++ program to find lcm of two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1211]
### Description

Write a C++ program to find lcm of two numbers

LCM (Least Common Multiple) of two numbers is the smallest number which can be divided by both numbers. For example, the LCM of 15 and 20 is 60 and LCM of 10 and 15 is 30.

```
Input  : 12 18
Output : 36
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindLcmOfTwoNumbers.cpp` file
- Add `FindLcmOfTwoNumbers.cpp` file in `find-lcm-of-two-numbers` folder

</details>

**Comment by Taanvee** [comment]
Can you assign it to me?

**Comment by harshraj8843** [comment]
Hey @Mikasa-Ackerman2074,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by AbhinavPrabhat01** [comment]
!assign
