### ISSUE TITLE
Write a Java program to find lcm of two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1215]
### Description

Write a Java program to find lcm of two numbers

LCM (Least Common Multiple) of two numbers is the smallest number which can be divided by both numbers. For example, the LCM of 15 and 20 is 60 and LCM of 10 and 15 is 30.

```
Input  : 12 18
Output : 36
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindLcmOfTwoNumbers.java` file
- Add `FindLcmOfTwoNumbers.java` file in `find-lcm-of-two-numbers` folder

</details>

**Comment by sumeetk10** [comment]
I would like to work on this, pls assign.

**Comment by LukasBrilla5** [comment]
!assign

**Comment by Vignesh-dev07** [comment]
!assign

**Comment by anshu-6537** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @anshu-6537, this issue is already assigned to @Vignesh-dev07 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
