### ISSUE TITLE
Write a Swift program to divide two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#123]
### Description

Write a Swift program to divide two numbers

```
Input  : 2 4
Output : 0.5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `DivideTwoNumbers.swift` file
- Add `DivideTwoNumbers.swift` file in `divide-two-numbers` folder

</details>

**Comment by esivakumar18** [comment]
!assign
