### ISSUE TITLE
Write a C++ program to check armstrong number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1239]
### Description

Write a C++ program to check armstrong number

An Armstrong number is a number that is equal to the sum of cubes of its digits.

```
Input  : 153
Output : Armstrong Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckArmstrongNumber.cpp` file
- Add `CheckArmstrongNumber.cpp` file in `check-armstrong-number` folder

</details>

**Comment by Taanvee** [comment]
Can you assign it to me?
