### ISSUE TITLE
Write a TypeScript program to divide two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#124]
### Description

Write a TypeScript program to divide two numbers

```
Input  : 2 4
Output : 0.5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `DivideTwoNumbers.ts` file
- Add `DivideTwoNumbers.ts` file in `divide-two-numbers` folder

</details>

**Comment by anastazir** [comment]
!assign
