### ISSUE TITLE
Write a Java program to check armstrong number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1243]
### Description

Write a Java program to check armstrong number

An Armstrong number is a number that is equal to the sum of cubes of its digits.

```
Input  : 153
Output : Armstrong Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckArmstrongNumber.java` file
- Add `CheckArmstrongNumber.java` file in `check-armstrong-number` folder

</details>

**Comment by MufaddalHakim** [comment]
Please assign

**Comment by MufaddalHakim** [comment]
!assign
