### ISSUE TITLE
Write a Python program to check armstrong number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1249]
### Description

Write a Python program to check armstrong number

An Armstrong number is a number that is equal to the sum of cubes of its digits.

```
Input  : 153
Output : Armstrong Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check-armstrong-number.py` file
- Add `check-armstrong-number.py` file in `check-armstrong-number` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign
