### ISSUE TITLE
Write a C program to find cube of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#126]
### Description

Write a C program to find cube of a number

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindCubeOfANumber.c` file
- Add `FindCubeOfANumber.c` file in `find-cube-of-a-number` folder

</details>

**Comment by KaptainCS3** [comment]
assigne me

**Comment by harshraj8843** [comment]
> assigne me

Hey @KaptainCS3 

Please comment `!assign` on any issue you want to contribute to, to be auto-assigned

```
!assign
```

Thanks

**Comment by akansharai2023** [comment]
!assign

**Comment by pokharel-nishan** [comment]
!assign

**Comment by AdityaNarayanPradhan** [comment]
!assign

**Comment by PavanKumarCB** [comment]
!assign
