### ISSUE TITLE
Write a C++ program to check pangram string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1263]
### Description

Write a C++ program to check pangram string

A pangram is a sentence containing every letter in the English Alphabet.

```
Input  : The quick brown fox jumps over the lazy dog
Output : Pangram sentence
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckPangramString.cpp` file
- Add `CheckPangramString.cpp` file in `check-pangram-string` folder

</details>

**Comment by Mikasa-Ackerman2074** [comment]
!assign

**Comment by KingFire25** [comment]
!assing

**Comment by KingFire25** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @KingFire25, this issue is already assigned to @Mikasa-Ackerman2074 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Hey @Mikasa-Ackerman2074,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Osher160** [comment]
!assign
