### ISSUE TITLE
Write a GO program to check pangram string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1266]
### Description

Write a GO program to check pangram string

A pangram is a sentence containing every letter in the English Alphabet.

```
Input  : The quick brown fox jumps over the lazy dog
Output : Pangram sentence
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check_pangram_string.go` file
- Add `check_pangram_string.go` file in `check-pangram-string` folder

</details>

**Comment by amoghrajesh** [comment]
@harshraj8843 I can work on this. Can you assign it to me?

**Comment by harshraj8843** [comment]
Hey @amoghrajesh 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by amoghrajesh** [comment]
!assign
