### ISSUE TITLE
Write a JavaScript program to check pangram string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1268]
### Description

Write a JavaScript program to check pangram string

A pangram is a sentence containing every letter in the English Alphabet.

```
Input  : The quick brown fox jumps over the lazy dog
Output : Pangram sentence
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckPangramString.js` file
- Add `CheckPangramString.js` file in `check-pangram-string` folder

</details>

**Comment by Jordan6794** [comment]
!assign
