### ISSUE TITLE
Write a Python program to check pangram string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1273]
### Description

Write a Python program to check pangram string

A pangram is a sentence containing every letter in the English Alphabet.

```
Input  : The quick brown fox jumps over the lazy dog
Output : Pangram sentence
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check-pangram-string.py` file
- Add `check-pangram-string.py` file in `check-pangram-string` folder

</details>

**Comment by MufaddalHakim** [comment]
I can do this. Please assign this to me.

**Comment by rakibul-islam-raju** [comment]
!assign
