### ISSUE TITLE
Write a Swift program to check pangram string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1278]
### Description

Write a Swift program to check pangram string

A pangram is a sentence containing every letter in the English Alphabet.

```
Input  : The quick brown fox jumps over the lazy dog
Output : Pangram sentence
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckPangramString.swift` file
- Add `CheckPangramString.swift` file in `check-pangram-string` folder

</details>

**Comment by esivakumar18** [comment]
!assign
