### ISSUE TITLE
Write a TypeScript program to check pangram string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1279]
### Description

Write a TypeScript program to check pangram string

A pangram is a sentence containing every letter in the English Alphabet.

```
Input  : The quick brown fox jumps over the lazy dog
Output : Pangram sentence
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckPangramString.ts` file
- Add `CheckPangramString.ts` file in `check-pangram-string` folder

</details>

**Comment by MetalOoze05** [comment]
!assign
