### ISSUE TITLE
Write a C program to print all prime numbers between two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1287]
### Description

Write a C program to print all prime numbers between two numbers

```
Input  : 10 20
Output : 11 13 17 19
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintAllPrimeNumbersBetweenTwoNumbers.c` file
- Add `PrintAllPrimeNumbersBetweenTwoNumbers.c` file in `print-all-prime-numbers-between-two-numbers` folder

</details>

**Comment by Chirag8023** [comment]
assign it to me

**Comment by Chirag8023** [comment]
!assign
