### ISSUE TITLE
Write a Java program to print all prime numbers between two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1293]
### Description

Write a Java program to print all prime numbers between two numbers

```
Input  : 10 20
Output : 11 13 17 19
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintAllPrimeNumbersBetweenTwoNumbers.java` file
- Add `PrintAllPrimeNumbersBetweenTwoNumbers.java` file in `print-all-prime-numbers-between-two-numbers` folder

</details>

**Comment by sumeetk10** [comment]
Can you assign this to me, I will we happy to work on this issue.

**Comment by Ipankaj07** [comment]
!assign
