### ISSUE TITLE
Write a JavaScript program to print all prime numbers between two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1294]
### Description

Write a JavaScript program to print all prime numbers between two numbers

```
Input  : 10 20
Output : 11 13 17 19
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintAllPrimeNumbersBetweenTwoNumbers.js` file
- Add `PrintAllPrimeNumbersBetweenTwoNumbers.js` file in `print-all-prime-numbers-between-two-numbers` folder

</details>

**Comment by jyotik09** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Greeshma-frontier, this issue is already assigned to @jyotik09 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
