### ISSUE TITLE
Write a Kotlin program to print all prime numbers between two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1296]
### Description

Write a Kotlin program to print all prime numbers between two numbers

```
Input  : 10 20
Output : 11 13 17 19
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintAllPrimeNumbersBetweenTwoNumbers.kt` file
- Add `PrintAllPrimeNumbersBetweenTwoNumbers.kt` file in `print-all-prime-numbers-between-two-numbers` folder

</details>

**Comment by rksp25** [comment]
!assign
