### ISSUE TITLE
Write a PHP program to print all prime numbers between two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1298]
### Description

Write a PHP program to print all prime numbers between two numbers

```
Input  : 10 20
Output : 11 13 17 19
```
<details>
<summary>How to contribute</summary>

- Save the solution in `print_all_prime_numbers_between_two_numbers.php` file
- Add `print_all_prime_numbers_between_two_numbers.php` file in `print-all-prime-numbers-between-two-numbers` folder

</details>

**Comment by rahmat-st** [comment]
!assign
