### ISSUE TITLE
Write a Python program to print all prime numbers between two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1299]
### Description

Write a Python program to print all prime numbers between two numbers

```
Input  : 10 20
Output : 11 13 17 19
```
<details>
<summary>How to contribute</summary>

- Save the solution in `print-all-prime-numbers-between-two-numbers.py` file
- Add `print-all-prime-numbers-between-two-numbers.py` file in `print-all-prime-numbers-between-two-numbers` folder

</details>

**Comment by grraghav120** [comment]
!assign
