### ISSUE TITLE
Write a Ruby program to print all prime numbers between two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1301]
### Description

Write a Ruby program to print all prime numbers between two numbers

```
Input  : 10 20
Output : 11 13 17 19
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintAllPrimeNumbersBetweenTwoNumbers.rb` file
- Add `PrintAllPrimeNumbersBetweenTwoNumbers.rb` file in `print-all-prime-numbers-between-two-numbers` folder

</details>

**Comment by jfinley6** [comment]
!assign
