### ISSUE TITLE
Write a TypeScript program to print all prime numbers between two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1306]
### Description

Write a TypeScript program to print all prime numbers between two numbers

```
Input  : 10 20
Output : 11 13 17 19
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintAllPrimeNumbersBetweenTwoNumbers.ts` file
- Add `PrintAllPrimeNumbersBetweenTwoNumbers.ts` file in `print-all-prime-numbers-between-two-numbers` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
