### ISSUE TITLE
Write a C program to print number to words in indian numbering system

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1313]
### Description

Write a C program to print number to words in indian numbering system

```
Input  : 123456789
Output : Twelve Crore Thirty Four Lakh Fifty Six Thousand Seven Hundred Eighty Nine
```

<details>
<summary>How to contribute</summary>

- Save the solution in `PrintNumberToWordsInIndianNumberingSystem.c` file
- Add `PrintNumberToWordsInIndianNumberingSystem.c` file in `print-number-to-words-in-indian-numbering-system` folder

</details>

**Comment by Chirag8023** [comment]
assign it to me

**Comment by GuyEternal** [comment]
> https://github.com/codinasion/program/issues/1313#issue-1395030082

Please edit this sample input/output
from this:
```
Input  : 123456789
Output : One Hundred Twenty Three Crore Forty Five Lakh Sixty Seven Thousand Eight Hundred Ninety
```
to this:

```
Input  : 1234567890
Output : One Hundred Twenty Three Crore Forty Five Lakh Sixty Seven Thousand Eight Hundred Ninety
```

**Comment by harshraj8843** [comment]
Thanks for noticing this 👍🏻

**Comment by pokharel-nishan** [comment]
!assign

**Comment by pandfun** [comment]
!assign
