### ISSUE TITLE
Write a JavaScript program to find cube of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#133]
### Description

Write a JavaScript program to find cube of a number

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindCubeOfANumber.js` file
- Add `FindCubeOfANumber.js` file in `find-cube-of-a-number` folder

</details>

**Comment by heyyayesh** [comment]
!assign
