### ISSUE TITLE
Write a TypeScript program to print number to words in indian numbering system

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1331]
### Description

Write a TypeScript program to print number to words in indian numbering system

```
Input  : 123456789
Output : Twelve Crore Thirty Four Lakh Fifty Six Thousand Seven Hundred Eighty Nine
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintNumberToWordsInIndianNumberingSystem.ts` file
- Add `PrintNumberToWordsInIndianNumberingSystem.ts` file in `print-number-to-words-in-indian-numbering-system` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by Ariel201711** [comment]
!assign
