### ISSUE TITLE
Write a Kotlin program to find cube of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#135]
### Description

Write a Kotlin program to find cube of a number

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindCubeOfANumber.kt` file
- Add `FindCubeOfANumber.kt` file in `find-cube-of-a-number` folder

</details>

**Comment by ashankritwik07** [comment]
!assign

**Comment by esivakumar18** [comment]
!assign
