### ISSUE TITLE
Write a Java program to calculate compound interest

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1362]
### Description

Write a Java program to calculate compound interest

Compound interest = principal amount * (1 + rate of interest) ^ time

```
Principal : 1000
Rate      : 10
Time      : 5

Compound interest : 1610.51
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CalculateCompoundInterest.java` file
- Add `CalculateCompoundInterest.java` file in `calculate-compound-interest` folder

</details>

**Comment by mak650650** [comment]
!assign

**Comment by mak650650** [comment]
Please add hacktoberfest tag

**Comment by sharvil1205** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @sharvil1205, this issue is already assigned to @mak650650 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by pokharel-nishan** [comment]
!assign
