### ISSUE TITLE
Write a JavaScript program to calculate compound interest

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1363]
### Description

Write a JavaScript program to calculate compound interest

Compound interest = principal amount * (1 + rate of interest) ^ time

```
Principal : 1000
Rate      : 10
Time      : 5

Compound interest : 1610.51
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CalculateCompoundInterest.js` file
- Add `CalculateCompoundInterest.js` file in `calculate-compound-interest` folder

</details>

**Comment by 593-ACD** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @593-ACD,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by jfinley6** [comment]
!assign

**Comment by Medmly20208** [comment]
!assign

**Comment by ShivamK2002** [comment]
!assign
