### ISSUE TITLE
Write a PHP program to find cube of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#137]
### Description

Write a PHP program to find cube of a number

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_cube_of_a_number.php` file
- Add `find_cube_of_a_number.php` file in `find-cube-of-a-number` folder

</details>

**Comment by ridsuteri** [comment]
@harshraj8843 I would love to take this issue, can you assign it to me?

**Comment by harshraj8843** [comment]
> @harshraj8843 I would love to take this issue, can you assign it to me?

Hey @ridsuteri 

Thanks for showing your interest 😃 

You can comment `!assign` on any issue you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by ridsuteri** [comment]
!assign
