### ISSUE TITLE
Write a Ruby program to calculate compound interest

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1370]
### Description

Write a Ruby program to calculate compound interest

Compound interest = principal amount * (1 + rate of interest) ^ time

```
Principal : 1000
Rate      : 10
Time      : 5

Compound interest : 1610.51
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CalculateCompoundInterest.rb` file
- Add `CalculateCompoundInterest.rb` file in `calculate-compound-interest` folder

</details>

**Comment by jfinley6** [comment]
!assign
