### ISSUE TITLE
Write a Scala program to calculate compound interest

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1372]
### Description

Write a Scala program to calculate compound interest

Compound interest = principal amount * (1 + rate of interest) ^ time

```
Principal : 1000
Rate      : 10
Time      : 5

Compound interest : 1610.51
```
<details>
<summary>How to contribute</summary>

- Save the solution in `calculateCompoundInterest.scala` file
- Add `calculateCompoundInterest.scala` file in `calculate-compound-interest` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
