### ISSUE TITLE
Compund interest in Python

### ISSUE THREAD

**Issue by deepakkrish212** [codinasion/program#1375]
### Description

Calculates the compound interest in python

**Comment by Vignesh-dev07** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Vignesh-dev07, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by Vignesh-dev07** [comment]
Can you assign this Issue to me?

**Comment by harshraj8843** [comment]
This program is already added
