### ISSUE TITLE
Write a GO program to check even or odd number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1382]
### Description

Write a GO program to check even or odd number

```
Input  : 3
Output : Odd Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check_even_or_odd_number.go` file
- Add `check_even_or_odd_number.go` file in `check-even-or-odd-number` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @TechnicalAmanjeet,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by sancoLgates** [comment]
!assign
