### ISSUE TITLE
Write a Java program to check even or odd number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1384]
### Description

Write a Java program to check even or odd number

```
Input  : 3
Output : Odd Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckEvenOrOddNumber.java` file
- Add `CheckEvenOrOddNumber.java` file in `check-even-or-odd-number` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign
