### ISSUE TITLE
Write a JavaScript program to check even or odd number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1385]
### Description

Write a JavaScript program to check even or odd number

```
Input  : 3
Output : Odd Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckEvenOrOddNumber.js` file
- Add `CheckEvenOrOddNumber.js` file in `check-even-or-odd-number` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
