### ISSUE TITLE
Write a PHP program to check even or odd number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1389]
### Description

Write a PHP program to check even or odd number

```
Input  : 3
Output : Odd Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check_even_or_odd_number.php` file
- Add `check_even_or_odd_number.php` file in `check-even-or-odd-number` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign
