### ISSUE TITLE
Write a Rust program to check even or odd number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1393]
### Description

Write a Rust program to check even or odd number

```
Input  : 3
Output : Odd Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check_even_or_odd_number.rs` file
- Add `check_even_or_odd_number.rs` file in `check-even-or-odd-number` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign
