### ISSUE TITLE
Write a Scala program to check even or odd number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1394]
### Description

Write a Scala program to check even or odd number

```
Input  : 3
Output : Odd Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `checkEvenOrOddNumber.scala` file
- Add `checkEvenOrOddNumber.scala` file in `check-even-or-odd-number` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign
