### ISSUE TITLE
Write a Swift program to check even or odd number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1395]
### Description

Write a Swift program to check even or odd number

```
Input  : 3
Output : Odd Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckEvenOrOddNumber.swift` file
- Add `CheckEvenOrOddNumber.swift` file in `check-even-or-odd-number` folder

</details>

**Comment by esivakumar18** [comment]
!assign
