### ISSUE TITLE
Write a TypeScript program to check even or odd number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1396]
### Description

Write a TypeScript program to check even or odd number

```
Input  : 3
Output : Odd Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckEvenOrOddNumber.ts` file
- Add `CheckEvenOrOddNumber.ts` file in `check-even-or-odd-number` folder

</details>

**Comment by kevinsfernandes** [comment]
!assign
