### ISSUE TITLE
Write a C# program to convert days to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1405]
### Description

Write a C# program to convert days to minutes

1 day = 24 hours = 1440 minutes

```
Input  : 5
Output : 7200
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertDaysToMinutes.cs` file
- Add `ConvertDaysToMinutes.cs` file in `convert-days-to-minutes` folder

</details>

**Comment by anxkhn** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @anxkhn,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
