### ISSUE TITLE
Write a C++ program to convert days to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1406]
### Description

Write a C++ program to convert days to minutes

1 day = 24 hours = 1440 minutes

```
Input  : 5
Output : 7200
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertDaysToMinutes.cpp` file
- Add `ConvertDaysToMinutes.cpp` file in `convert-days-to-minutes` folder

</details>

**Comment by anxkhn** [comment]
!assign

**Comment by Medmly20208** [comment]
!assign
