### ISSUE TITLE
Write a GO program to convert days to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1409]
### Description

Write a GO program to convert days to minutes

1 day = 24 hours = 1440 minutes

```
Input  : 5
Output : 7200
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_days_to_minutes.go` file
- Add `convert_days_to_minutes.go` file in `convert-days-to-minutes` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign
