### ISSUE TITLE
Write a JavaScript program to convert days to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1412]
### Description

Write a JavaScript program to convert days to minutes

1 day = 24 hours = 1440 minutes

```
Input  : 5
Output : 7200
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertDaysToMinutes.js` file
- Add `ConvertDaysToMinutes.js` file in `convert-days-to-minutes` folder

</details>

**Comment by CodingWithHardik** [comment]
Hey 👋,
Please assign me in this issue

**Comment by TechnicalAmanjeet** [comment]
!assign

**Comment by CodingWithHardik** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @CodingWithHardik, this issue is already assigned to @TechnicalAmanjeet !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
