### ISSUE TITLE
Write a Kotlin program to convert days to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1414]
### Description

Write a Kotlin program to convert days to minutes

1 day = 24 hours = 1440 minutes

```
Input  : 5
Output : 7200
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertDaysToMinutes.kt` file
- Add `ConvertDaysToMinutes.kt` file in `convert-days-to-minutes` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign
