### ISSUE TITLE
Write a Python program to convert days to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1417]
### Description

Write a Python program to convert days to minutes

1 day = 24 hours = 1440 minutes

```
Input  : 5
Output : 7200
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-days-to-minutes.py` file
- Add `convert-days-to-minutes.py` file in `convert-days-to-minutes` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign
