### ISSUE TITLE
Write a Scala program to find cube of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#142]
### Description

Write a Scala program to find cube of a number

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `findCubeOfANumber.sc` file
- Add `findCubeOfANumber.sc` file in `find-cube-of-a-number` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
