### ISSUE TITLE
Write a TypeScript program to convert days to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1423]
### Description

Write a TypeScript program to convert days to minutes

1 day = 24 hours = 1440 minutes

```
Input  : 5
Output : 7200
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertDaysToMinutes.ts` file
- Add `ConvertDaysToMinutes.ts` file in `convert-days-to-minutes` folder

</details>

**Comment by jaypavasiya** [comment]
!assign

**Comment by kevinsfernandes** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @kevinsfernandes, this issue is already assigned to @jaypavasiya !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
