### ISSUE TITLE
Write a Swift program to find cube of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#143]
### Description

Write a Swift program to find cube of a number

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindCubeOfANumber.swift` file
- Add `FindCubeOfANumber.swift` file in `find-cube-of-a-number` folder

</details>

**Comment by toddmcintire** [comment]
Would it be alright if I attempted this?

**Comment by harshraj8843** [comment]
> Would it be alright if I attempted this?

Hey @toddmcintire 

Thanks for showing your interest

Please comment `!assign` on any issue you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by toddmcintire** [comment]
> > Would it be alright if I attempted this?
> 
> Hey @toddmcintire
> 
> Thanks for showing your interest
> 
> Please comment `!assign` on any issue you want to contribute to, to be auto-assigned
> 
> ```
> !assign
> ```
Thanks ill see if it works!
!assign
