### ISSUE TITLE
Write a TypeScript program to find cube of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#144]
### Description

Write a TypeScript program to find cube of a number

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindCubeOfANumber.ts` file
- Add `FindCubeOfANumber.ts` file in `find-cube-of-a-number` folder

</details>

**Comment by Lofty-Brambles** [comment]
Hi @harshraj8843, would this be considered as a hacktoberfest issue? I'd like to work on this as well as any JS/TS questions and submit a PR.

**Comment by harshraj8843** [comment]
Yes, all `good first issue` of this repo will be considered for Hacktoberfest 😃 

Comment `!assign` on the issue you want to contribute to, and you will be auto-assigned

```
!assign
```

Thanks for showing your interest in this project 😍 

More issues will be created from 1st October 👍🏻

**Comment by Lofty-Brambles** [comment]
!assign
