### ISSUE TITLE
Write a C program to convert weeks to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1463]
### Description

Write a C program to convert weeks to hours

1 week = 7 days = 168 hours

```
Input  : 5
Output : 840
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToHours.c` file
- Add `ConvertWeeksToHours.c` file in `convert-weeks-to-hours` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign
