### ISSUE TITLE
Write a F# program to convert weeks to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1467]
### Description

Write a F# program to convert weeks to hours

1 week = 7 days = 168 hours

```
Input  : 5
Output : 840
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToHours.fs` file
- Add `ConvertWeeksToHours.fs` file in `convert-weeks-to-hours` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign
