### ISSUE TITLE
Write a Julia program to convert weeks to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1472]
### Description

Write a Julia program to convert weeks to hours

1 week = 7 days = 168 hours

```
Input  : 5
Output : 840
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-weeks-to-hours.jl` file
- Add `convert-weeks-to-hours.jl` file in `convert-weeks-to-hours` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign
