### ISSUE TITLE
Write a Kotlin program to convert weeks to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1473]
### Description

Write a Kotlin program to convert weeks to hours

1 week = 7 days = 168 hours

```
Input  : 5
Output : 840
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToHours.kt` file
- Add `ConvertWeeksToHours.kt` file in `convert-weeks-to-hours` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign

**Comment by rksp25** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @rksp25, this issue is already assigned to @TechnicalAmanjeet !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
