### ISSUE TITLE
Write a TypeScript program to convert weeks to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1483]
### Description

Write a TypeScript program to convert weeks to hours

1 week = 7 days = 168 hours

```
Input  : 5
Output : 840
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToHours.ts` file
- Add `ConvertWeeksToHours.ts` file in `convert-weeks-to-hours` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @TechnicalAmanjeet,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by lukaszmielczarekdev** [comment]
!assign
