### ISSUE TITLE
Write a C program to check alphabet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1513]
### Description

Write a C program to check alphabet

Check that the given character is an alphabet or not (a-z, A-Z).

```
Input  : a
Output : Alphabet
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckAlphabet.c` file
- Add `CheckAlphabet.c` file in `check-alphabet` folder

</details>

**Comment by grraghav120** [comment]
!assign
