### ISSUE TITLE
Write a GO program to check alphabet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1518]
### Description

Write a GO program to check alphabet

Check that the given character is an alphabet or not (a-z, A-Z).

```
Input  : a
Output : Alphabet
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check_alphabet.go` file
- Add `check_alphabet.go` file in `check-alphabet` folder

</details>

**Comment by ravics1721** [comment]
Assign me , I'll work on that.

**Comment by harshraj8843** [comment]
Hey @ravics1721 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto assigned

```
!assign
```

**Comment by harshraj8843** [comment]
Hey @ravics1721,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by sancoLgates** [comment]
!assign
