### ISSUE TITLE
Write a Java program to check alphabet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1520]
### Description

Write a Java program to check alphabet

Check that the given character is an alphabet or not (a-z, A-Z).

```
Input  : a
Output : Alphabet
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckAlphabet.java` file
- Add `CheckAlphabet.java` file in `check-alphabet` folder

</details>

**Comment by Ipankaj07** [comment]
!assign
