### ISSUE TITLE
Write a JavaScript program to check alphabet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1521]
### Description

Write a JavaScript program to check alphabet

Check that the given character is an alphabet or not (a-z, A-Z).

```
Input  : a
Output : Alphabet
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckAlphabet.js` file
- Add `CheckAlphabet.js` file in `check-alphabet` folder

</details>

**Comment by jyotik09** [comment]
!assign

**Comment by MarianCekan** [comment]
Hello is this still available?
