### ISSUE TITLE
Write a Kotlin program to check alphabet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1523]
### Description

Write a Kotlin program to check alphabet

Check that the given character is an alphabet or not (a-z, A-Z).

```
Input  : a
Output : Alphabet
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckAlphabet.kt` file
- Add `CheckAlphabet.kt` file in `check-alphabet` folder

</details>

**Comment by rksp25** [comment]
!assign
