### ISSUE TITLE
Write a Python program to check alphabet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1526]
### Description

Write a Python program to check alphabet

Check that the given character is an alphabet or not (a-z, A-Z).

```
Input  : a
Output : Alphabet
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check-alphabet.py` file
- Add `check-alphabet.py` file in `check-alphabet` folder

</details>

**Comment by mallikpramod** [comment]
can you please assign this issue to me, i want to solve this.

**Comment by PraaneshSelvaraj** [comment]
!assign
