### ISSUE TITLE
Write a Scala program to check alphabet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1530]
### Description

Write a Scala program to check alphabet

Check that the given character is an alphabet or not (a-z, A-Z).

```
Input  : a
Output : Alphabet
```
<details>
<summary>How to contribute</summary>

- Save the solution in `checkAlphabet.scala` file
- Add `checkAlphabet.scala` file in `check-alphabet` folder

</details>

**Comment by Chirag8023** [comment]
!assign
