### ISSUE TITLE
Write a Swift program to check alphabet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1531]
### Description

Write a Swift program to check alphabet

Check that the given character is an alphabet or not (a-z, A-Z).

```
Input  : a
Output : Alphabet
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckAlphabet.swift` file
- Add `CheckAlphabet.swift` file in `check-alphabet` folder

</details>

**Comment by esivakumar18** [comment]
!assign
