### ISSUE TITLE
Write a TypeScript program to check alphabet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1532]
### Description

Write a TypeScript program to check alphabet

Check that the given character is an alphabet or not (a-z, A-Z).

```
Input  : a
Output : Alphabet
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckAlphabet.ts` file
- Add `CheckAlphabet.ts` file in `check-alphabet` folder

</details>

**Comment by jyotik09** [comment]
!assign
