### ISSUE TITLE
Write a GO program to check palindrome string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1545]
### Description

Write a GO program to check palindrome string

Palindrome string is a string that is same when read from left to right and right to left. For example, "aba" is a palindrome string, "abc" is not.

```
Input  : abba
Output : Palindrome String
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check_palindrome_string.go` file
- Add `check_palindrome_string.go` file in `check-palindrome-string` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by sancoLgates** [comment]
!assign
