### ISSUE TITLE
Write a Java program to check palindrome string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1547]
### Description

Write a Java program to check palindrome string

Palindrome string is a string that is same when read from left to right and right to left. For example, "aba" is a palindrome string, "abc" is not.

```
Input  : abba
Output : Palindrome String
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckPalindromeString.java` file
- Add `CheckPalindromeString.java` file in `check-palindrome-string` folder

</details>

**Comment by kavin5kumar** [comment]
!assign

**Comment by kangjung** [comment]
!assign
