### ISSUE TITLE
Write a Ruby program to check palindrome string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1555]
### Description

Write a Ruby program to check palindrome string

Palindrome string is a string that is same when read from left to right and right to left. For example, "aba" is a palindrome string, "abc" is not.

```
Input  : abba
Output : Palindrome String
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckPalindromeString.rb` file
- Add `CheckPalindromeString.rb` file in `check-palindrome-string` folder

</details>

**Comment by Paulo-Rodrigues** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Paulo-Rodrigues,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by jfinley6** [comment]
!assign
