### ISSUE TITLE
Write a Rust program to check palindrome string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1556]
### Description

Write a Rust program to check palindrome string

Palindrome string is a string that is same when read from left to right and right to left. For example, "aba" is a palindrome string, "abc" is not.

```
Input  : abba
Output : Palindrome String
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check_palindrome_string.rs` file
- Add `check_palindrome_string.rs` file in `check-palindrome-string` folder

</details>

**Comment by rahmat-st** [comment]
!assign
