### ISSUE TITLE
Write a Swift program to check palindrome string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1558]
### Description

Write a Swift program to check palindrome string

Palindrome string is a string that is same when read from left to right and right to left. For example, "aba" is a palindrome string, "abc" is not.

```
Input  : abba
Output : Palindrome String
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckPalindromeString.swift` file
- Add `CheckPalindromeString.swift` file in `check-palindrome-string` folder

</details>

**Comment by esivakumar18** [comment]
!assign
