### ISSUE TITLE
Write a C# program to find sum of n natural numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1574]
### Description

Write a C# program to find sum of n natural numbers

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNNaturalNumbers.cs` file
- Add `FindSumOfNNaturalNumbers.cs` file in `find-sum-of-n-natural-numbers` folder

</details>

**Comment by Khushi260** [comment]
!assign
