### ISSUE TITLE
Write a C++ program to find sum of n natural numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1575]
### Description

Write a C++ program to find sum of n natural numbers

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNNaturalNumbers.cpp` file
- Add `FindSumOfNNaturalNumbers.cpp` file in `find-sum-of-n-natural-numbers` folder

</details>

**Comment by grraghav120** [comment]
!assign
