### ISSUE TITLE
Write a Java program to find sum of n natural numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1580]
### Description

Write a Java program to find sum of n natural numbers

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNNaturalNumbers.java` file
- Add `FindSumOfNNaturalNumbers.java` file in `find-sum-of-n-natural-numbers` folder

</details>

**Comment by Harsh3341** [comment]
!assign
