### ISSUE TITLE
Write a JavaScript program to find sum of n natural numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1581]
### Description

Write a JavaScript program to find sum of n natural numbers

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNNaturalNumbers.js` file
- Add `FindSumOfNNaturalNumbers.js` file in `find-sum-of-n-natural-numbers` folder

</details>

**Comment by jyotik09** [comment]
!assign
