### ISSUE TITLE
Write a Kotlin program to find sum of n natural numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1583]
### Description

Write a Kotlin program to find sum of n natural numbers

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNNaturalNumbers.kt` file
- Add `FindSumOfNNaturalNumbers.kt` file in `find-sum-of-n-natural-numbers` folder

</details>

**Comment by rksp25** [comment]
!assign
