### ISSUE TITLE
Write a Python program to find sum of n natural numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1586]
### Description

Write a Python program to find sum of n natural numbers

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-sum-of-n-natural-numbers.py` file
- Add `find-sum-of-n-natural-numbers.py` file in `find-sum-of-n-natural-numbers` folder

</details>

**Comment by rahmat-st** [comment]
!assign
