### ISSUE TITLE
Write a Rust program to find sum of n natural numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1589]
### Description

Write a Rust program to find sum of n natural numbers

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_sum_of_n_natural_numbers.rs` file
- Add `find_sum_of_n_natural_numbers.rs` file in `find-sum-of-n-natural-numbers` folder

</details>

**Comment by rahmat-st** [comment]
!assign
