### ISSUE TITLE
Write a Julia program to convert hours to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1606]
### Description

Write a Julia program to convert hours to weeks

1 week = 7 days = 168 hours

```
Input  : 840
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-hours-to-weeks.jl` file
- Add `convert-hours-to-weeks.jl` file in `convert-hours-to-weeks` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
