### ISSUE TITLE
Write a Kotlin program to convert hours to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1607]
### Description

Write a Kotlin program to convert hours to weeks

1 week = 7 days = 168 hours

```
Input  : 840
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertHoursToWeeks.kt` file
- Add `ConvertHoursToWeeks.kt` file in `convert-hours-to-weeks` folder

</details>

**Comment by rksp25** [comment]
!assign
