### ISSUE TITLE
Write a Python program to convert hours to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1611]
### Description

Write a Python program to convert hours to weeks

1 week = 7 days = 168 hours

```
Input  : 840
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-hours-to-weeks.py` file
- Add `convert-hours-to-weeks.py` file in `convert-hours-to-weeks` folder

</details>

**Comment by grraghav120** [comment]
!assign

**Comment by inorishizuka** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @inorishizuka, this issue is already assigned to @grraghav120 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
