### ISSUE TITLE
Write a Ruby program to convert hours to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1613]
### Description

Write a Ruby program to convert hours to weeks

1 week = 7 days = 168 hours

```
Input  : 840
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertHoursToWeeks.rb` file
- Add `ConvertHoursToWeeks.rb` file in `convert-hours-to-weeks` folder

</details>

**Comment by esivakumar18** [comment]
!assign
