### ISSUE TITLE
Write a Scala program to convert hours to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1615]
### Description

Write a Scala program to convert hours to weeks

1 week = 7 days = 168 hours

```
Input  : 840
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convertHoursToWeeks.scala` file
- Add `convertHoursToWeeks.scala` file in `convert-hours-to-weeks` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
