### ISSUE TITLE
Write a TypeScript program to convert hours to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1617]
### Description

Write a TypeScript program to convert hours to weeks

1 week = 7 days = 168 hours

```
Input  : 840
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertHoursToWeeks.ts` file
- Add `ConvertHoursToWeeks.ts` file in `convert-hours-to-weeks` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
