### ISSUE TITLE
Write a Java program to print string of ascii values

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1639]
### Description

Write a Java program to print string of ascii values

ASCII value is the numeric representation of a character. For example, the ASCII value of the character 'A' is 65. The ASCII value of the character 'a' is 97. The ASCII value of the character '0' is 48. The ASCII value of the character ' ' is 32.

```
Input  : 65 66 67
Output : ABC
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintStringOfAsciiValues.java` file
- Add `PrintStringOfAsciiValues.java` file in `print-string-of-ascii-values` folder

</details>

**Comment by thweetkomputer** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @thweetkomputer,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Sri01729** [comment]
!assign
