### ISSUE TITLE
Write a C++ program to print multiplication table

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1689]
### Description

Write a C++ program to print multiplication table

```
Input  : 2

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintMultiplicationTable.cpp` file
- Add `PrintMultiplicationTable.cpp` file in `print-multiplication-table` folder

</details>

**Comment by codingkush** [comment]
Pls assign me... I'm new in hacktobetfest'22...i want to contribute so can you assign me this

**Comment by codingkush** [comment]
Can you assign me this issue under hacktobetfest'22 pls

**Comment by vishal2376** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @vishal2376,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by AbhinavPrabhat01** [comment]
!assign
