### ISSUE TITLE
Write a Ruby program to print multiplication table

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1702]
### Description

Write a Ruby program to print multiplication table

```
Input  : 2

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintMultiplicationTable.rb` file
- Add `PrintMultiplicationTable.rb` file in `print-multiplication-table` folder

</details>

**Comment by jfinley6** [comment]
!assign
