### ISSUE TITLE
Write a C program to swap two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1713]
### Description

Write a C program to swap two numbers

```
Input  : 10 20
Output : 20 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `SwapTwoNumbers.c` file
- Add `SwapTwoNumbers.c` file in `swap-two-numbers` folder

</details>

**Comment by Chirag8023** [comment]
assign it to me

**Comment by anxkhn** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @anxkhn,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Osher160** [comment]
!assign
