### ISSUE TITLE
Write a GO program to swap two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1718]
### Description

Write a GO program to swap two numbers

```
Input  : 10 20
Output : 20 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `swap_two_numbers.go` file
- Add `swap_two_numbers.go` file in `swap-two-numbers` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by PoweredByCaffein** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @PoweredByCaffein, this issue is already assigned to @Chirag8023 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by PoweredByCaffein** [comment]
Hi @harshraj8843, since the issue was assigned over 4 days ago and it's still open.
Can it take it over?

**Comment by harshraj8843** [comment]
@Chirag8023 will let us know 🤔

**Comment by Chirag8023** [comment]
i am working on this and other issues too. I will submit all PRs altogether !

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by vedantpople4** [comment]
!assign
