### ISSUE TITLE
Write a Java program to swap two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1720]
### Description

Write a Java program to swap two numbers

```
Input  : 10 20
Output : 20 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `SwapTwoNumbers.java` file
- Add `SwapTwoNumbers.java` file in `swap-two-numbers` folder

</details>

**Comment by codingkush** [comment]
! assign

**Comment by codingkush** [comment]
!assign
