### ISSUE TITLE
Write a JavaScript program to swap two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1721]
### Description

Write a JavaScript program to swap two numbers

```
Input  : 10 20
Output : 20 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `SwapTwoNumbers.js` file
- Add `SwapTwoNumbers.js` file in `swap-two-numbers` folder

</details>

**Comment by omagr** [comment]
!assign
