### ISSUE TITLE
Write a Swift program to swap two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1731]
### Description

Write a Swift program to swap two numbers

```
Input  : 10 20
Output : 20 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `SwapTwoNumbers.swift` file
- Add `SwapTwoNumbers.swift` file in `swap-two-numbers` folder

</details>

**Comment by esivakumar18** [comment]
!assign
