### ISSUE TITLE
Write a TypeScript program to swap two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1732]
### Description

Write a TypeScript program to swap two numbers

```
Input  : 10 20
Output : 20 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `SwapTwoNumbers.ts` file
- Add `SwapTwoNumbers.ts` file in `swap-two-numbers` folder

</details>

**Comment by anastazir** [comment]
!assign
