### ISSUE TITLE
Write a Kotlin program to find perimeter of a rectangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1746]
### Description

Write a Kotlin program to find perimeter of a rectangle

Perimeter of rectangle = 2 × (`Length` + `Width`)

```
Length : 2
Width  : 3

Perimeter : 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindPerimeterOfARectangle.kt` file
- Add `FindPerimeterOfARectangle.kt` file in `find-perimeter-of-a-rectangle` folder

</details>

**Comment by prathameshkarambelkar** [comment]
!assign
