### ISSUE TITLE
Write a Scala program to find perimeter of a rectangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1753]
### Description

Write a Scala program to find perimeter of a rectangle

Perimeter of rectangle = 2 × (`Length` + `Width`)

```
Length : 2
Width  : 3

Perimeter : 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `findPerimeterOfARectangle.scala` file
- Add `findPerimeterOfARectangle.scala` file in `find-perimeter-of-a-rectangle` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
