### ISSUE TITLE
Write a C program to check vowel

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1762]
### Description

Write a C program to check vowel

Vowel check is a simple program to check whether a character is a vowel or not.

```
Input  : a
Output : Vowel
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckVowel.c` file
- Add `CheckVowel.c` file in `check-vowel` folder

</details>

**Comment by grraghav120** [comment]
!assign
