### ISSUE TITLE
Write a C++ program to check vowel

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1764]
### Description

Write a C++ program to check vowel

Vowel check is a simple program to check whether a character is a vowel or not.

```
Input  : a
Output : Vowel
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckVowel.cpp` file
- Add `CheckVowel.cpp` file in `check-vowel` folder

</details>

**Comment by mallikpramod** [comment]
@harshraj8843 wanna to work with you , solving this issue.
Can you please elaborate where to write the solution of this problem.

**Comment by grraghav120** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @mallikpramod 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

---

> Can you please elaborate where to write the solution of this problem.

You can check `How to contribute` dropdown on each issue

---

Thanks for contributing 👍🏻
