### ISSUE TITLE
Write a GO program to check vowel

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1767]
### Description

Write a GO program to check vowel

Vowel check is a simple program to check whether a character is a vowel or not.

```
Input  : a
Output : Vowel
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check_vowel.go` file
- Add `check_vowel.go` file in `check-vowel` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by esivakumar18** [comment]
!assign
