### ISSUE TITLE
Write a Java program to check vowel

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1769]
### Description

Write a Java program to check vowel

Vowel check is a simple program to check whether a character is a vowel or not.

```
Input  : a
Output : Vowel
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckVowel.java` file
- Add `CheckVowel.java` file in `check-vowel` folder

</details>

**Comment by kavin5kumar** [comment]
!assign

**Comment by joao-vitor-souza** [comment]
!assign
