### ISSUE TITLE
Write a JavaScript program to check vowel

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1770]
### Description

Write a JavaScript program to check vowel

Vowel check is a simple program to check whether a character is a vowel or not.

```
Input  : a
Output : Vowel
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckVowel.js` file
- Add `CheckVowel.js` file in `check-vowel` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
