### ISSUE TITLE
Write a Kotlin program to check vowel

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1772]
### Description

Write a Kotlin program to check vowel

Vowel check is a simple program to check whether a character is a vowel or not.

```
Input  : a
Output : Vowel
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckVowel.kt` file
- Add `CheckVowel.kt` file in `check-vowel` folder

</details>

**Comment by rksp25** [comment]
!assign
