### ISSUE TITLE
Write a Python program to check vowel

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1775]
### Description

Write a Python program to check vowel

Vowel check is a simple program to check whether a character is a vowel or not.

```
Input  : a
Output : Vowel
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check-vowel.py` file
- Add `check-vowel.py` file in `check-vowel` folder

</details>

**Comment by grraghav120** [comment]
!assign
