### ISSUE TITLE
Write a R program to check vowel

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1776]
### Description

Write a R program to check vowel

Vowel check is a simple program to check whether a character is a vowel or not.

```
Input  : a
Output : Vowel
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check_vowel.r` file
- Add `check_vowel.r` file in `check-vowel` folder

</details>

**Comment by YaSh8202** [comment]
!assign
