### ISSUE TITLE
Write a Ruby program to check vowel

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1777]
### Description

Write a Ruby program to check vowel

Vowel check is a simple program to check whether a character is a vowel or not.

```
Input  : a
Output : Vowel
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckVowel.rb` file
- Add `CheckVowel.rb` file in `check-vowel` folder

</details>

**Comment by harshraj8843** [comment]
Hey @suryapoojary0 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by suryapoojary0** [comment]
!assign
