### ISSUE TITLE
Write a Swift program to check vowel

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1780]
### Description

Write a Swift program to check vowel

Vowel check is a simple program to check whether a character is a vowel or not.

```
Input  : a
Output : Vowel
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckVowel.swift` file
- Add `CheckVowel.swift` file in `check-vowel` folder

</details>

**Comment by esivakumar18** [comment]
!assign
