### ISSUE TITLE
Write a C++ program to find sum of cubes of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1790]
### Description

Write a C++ program to find sum of cubes of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 225
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfCubesOfNumbersByRecursion.cpp` file
- Add `FindSumOfCubesOfNumbersByRecursion.cpp` file in `find-sum-of-cubes-of-numbers-by-recursion` folder

</details>

**Comment by darkbits018** [comment]
I'd like to contribute to this please assign to me

**Comment by grraghav120** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @darkbits018 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto assigned

```
!assign
```

Thanks for contributing 👍🏻

**Comment by darkbits018** [comment]
Ok sure Thank you :)
