### ISSUE TITLE
Write a Java program to find sum of cubes of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1795]
### Description

Write a Java program to find sum of cubes of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 225
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfCubesOfNumbersByRecursion.java` file
- Add `FindSumOfCubesOfNumbersByRecursion.java` file in `find-sum-of-cubes-of-numbers-by-recursion` folder

</details>

**Comment by vedha-vikash-pixel** [comment]
ASSIGN this to me

**Comment by vedha-vikash-pixel** [comment]
!assign
