### ISSUE TITLE
Write a TypeScript program to find sum of cubes of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1807]
### Description

Write a TypeScript program to find sum of cubes of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 225
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfCubesOfNumbersByRecursion.ts` file
- Add `FindSumOfCubesOfNumbersByRecursion.ts` file in `find-sum-of-cubes-of-numbers-by-recursion` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
