### ISSUE TITLE
Write a C# program to find negative of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1812]
### Description

Write a C# program to find negative of a number

```
Input  : 5
Output : -5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindNegativeOfANumber.cs` file
- Add `FindNegativeOfANumber.cs` file in `find-negative-of-a-number` folder

</details>

**Comment by astitva0011** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @astitva0011,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
