### ISSUE TITLE
Write a C++ program to find negative of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1813]
### Description

Write a C++ program to find negative of a number

```
Input  : 5
Output : -5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindNegativeOfANumber.cpp` file
- Add `FindNegativeOfANumber.cpp` file in `find-negative-of-a-number` folder

</details>

**Comment by grraghav120** [comment]
!assign
