### ISSUE TITLE
Write a Java program to find negative of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1818]
### Description

Write a Java program to find negative of a number

```
Input  : 5
Output : -5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindNegativeOfANumber.java` file
- Add `FindNegativeOfANumber.java` file in `find-negative-of-a-number` folder

</details>

**Comment by kavin5kumar** [comment]
!assign

**Comment by joao-vitor-souza** [comment]
!assign
