### ISSUE TITLE
Write a JavaScript program to find negative of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1819]
### Description

Write a JavaScript program to find negative of a number

```
Input  : 5
Output : -5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindNegativeOfANumber.js` file
- Add `FindNegativeOfANumber.js` file in `find-negative-of-a-number` folder

</details>

**Comment by rwlc** [comment]
!assign
