### ISSUE TITLE
Write a Ruby program to find negative of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1826]
### Description

Write a Ruby program to find negative of a number

```
Input  : 5
Output : -5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindNegativeOfANumber.rb` file
- Add `FindNegativeOfANumber.rb` file in `find-negative-of-a-number` folder

</details>

**Comment by PraaneshSelvaraj** [comment]
!assign
