### ISSUE TITLE
Write a Swift program to find negative of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1829]
### Description

Write a Swift program to find negative of a number

```
Input  : 5
Output : -5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindNegativeOfANumber.swift` file
- Add `FindNegativeOfANumber.swift` file in `find-negative-of-a-number` folder

</details>

**Comment by esivakumar18** [comment]
!assign
