### ISSUE TITLE
Write a Java program to check prime number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1840]
### Description

Write a Java program to check prime number

A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.

```
Input  : 5
Output : Prime Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckPrimeNumber.java` file
- Add `CheckPrimeNumber.java` file in `check-prime-number` folder

</details>

**Comment by kavin5kumar** [comment]
!assign

**Comment by Ipankaj07** [comment]
!assign
