### ISSUE TITLE
Write a JavaScript program to check prime number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1841]
### Description

Write a JavaScript program to check prime number

A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.

```
Input  : 5
Output : Prime Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckPrimeNumber.js` file
- Add `CheckPrimeNumber.js` file in `check-prime-number` folder

</details>

**Comment by rwlc** [comment]
!assign
