### ISSUE TITLE
Write a Rust program to check prime number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1849]
### Description

Write a Rust program to check prime number

A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.

```
Input  : 5
Output : Prime Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check_prime_number.rs` file
- Add `check_prime_number.rs` file in `check-prime-number` folder

</details>

**Comment by rwlc** [comment]
!assign
