### ISSUE TITLE
Write a Scala program to check prime number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1850]
### Description

Write a Scala program to check prime number

A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.

```
Input  : 5
Output : Prime Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `checkPrimeNumber.scala` file
- Add `checkPrimeNumber.scala` file in `check-prime-number` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
