### ISSUE TITLE
Write a C program to find average of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1856]
### Description

Write a C program to find average of numbers

Average of numbers is the sum of all numbers divided by the number of numbers.

```
Input  : 1 2 3 4 5
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAverageOfNumbers.c` file
- Add `FindAverageOfNumbers.c` file in `find-average-of-numbers` folder

</details>

**Comment by KaptainCS3** [comment]
!assign
