### ISSUE TITLE
Write a GO program to find average of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1861]
### Description

Write a GO program to find average of numbers

Average of numbers is the sum of all numbers divided by the number of numbers.

```
Input  : 1 2 3 4 5
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_average_of_numbers.go` file
- Add `find_average_of_numbers.go` file in `find-average-of-numbers` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by vedantpople4** [comment]
!assign
