### ISSUE TITLE
Write a JavaScript program to find average of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1864]
### Description

Write a JavaScript program to find average of numbers

Average of numbers is the sum of all numbers divided by the number of numbers.

```
Input  : 1 2 3 4 5
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAverageOfNumbers.js` file
- Add `FindAverageOfNumbers.js` file in `find-average-of-numbers` folder

</details>

**Comment by tanishq-singh-2301** [comment]
_**!Assign**_

**Comment by tanishq-singh-2301** [comment]
!assign
