### ISSUE TITLE
Write a Ruby program to find average of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1871]
### Description

Write a Ruby program to find average of numbers

Average of numbers is the sum of all numbers divided by the number of numbers.

```
Input  : 1 2 3 4 5
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAverageOfNumbers.rb` file
- Add `FindAverageOfNumbers.rb` file in `find-average-of-numbers` folder

</details>

**Comment by jfinley6** [comment]
!assign
