### ISSUE TITLE
Write a Dart program to convert minutes to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1880]
### Description

Write a Dart program to convert minutes to seconds

1 minute = 60 seconds

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_minutes_to_seconds.dart` file
- Add `convert_minutes_to_seconds.dart` file in `convert-minutes-to-seconds` folder

</details>

**Comment by auleki** [comment]
!assign
