### ISSUE TITLE
Write a Haskell program to convert minutes to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1883]
### Description

Write a Haskell program to convert minutes to seconds

1 minute = 60 seconds

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_minutes_to_seconds.hs` file
- Add `convert_minutes_to_seconds.hs` file in `convert-minutes-to-seconds` folder

</details>

**Comment by esivakumar18** [comment]
!assign
