### ISSUE TITLE
Write a Java program to convert minutes to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1884]
### Description

Write a Java program to convert minutes to seconds

1 minute = 60 seconds

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMinutesToSeconds.java` file
- Add `ConvertMinutesToSeconds.java` file in `convert-minutes-to-seconds` folder

</details>

**Comment by codingkush** [comment]
!assign
