### ISSUE TITLE
Write a JavaScript program to convert minutes to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1885]
### Description

Write a JavaScript program to convert minutes to seconds

1 minute = 60 seconds

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMinutesToSeconds.js` file
- Add `ConvertMinutesToSeconds.js` file in `convert-minutes-to-seconds` folder

</details>

**Comment by tanishq-singh-2301** [comment]
_**!Assign**_

**Comment by tanishq-singh-2301** [comment]
!assign
