### ISSUE TITLE
Write a Julia program to convert minutes to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1886]
### Description

Write a Julia program to convert minutes to seconds

1 minute = 60 seconds

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-minutes-to-seconds.jl` file
- Add `convert-minutes-to-seconds.jl` file in `convert-minutes-to-seconds` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
