### ISSUE TITLE
Write a Kotlin program to convert minutes to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1887]
### Description

Write a Kotlin program to convert minutes to seconds

1 minute = 60 seconds

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMinutesToSeconds.kt` file
- Add `ConvertMinutesToSeconds.kt` file in `convert-minutes-to-seconds` folder

</details>

**Comment by anshu-6537** [comment]
!assign
