### ISSUE TITLE
Write a PHP program to convert minutes to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1889]
### Description

Write a PHP program to convert minutes to seconds

1 minute = 60 seconds

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_minutes_to_seconds.php` file
- Add `convert_minutes_to_seconds.php` file in `convert-minutes-to-seconds` folder

</details>

**Comment by esivakumar18** [comment]
!assign
