### ISSUE TITLE
Write a Python program to convert minutes to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1890]
### Description

Write a Python program to convert minutes to seconds

1 minute = 60 seconds

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-minutes-to-seconds.py` file
- Add `convert-minutes-to-seconds.py` file in `convert-minutes-to-seconds` folder

</details>

**Comment by metal-oopa** [comment]
!assign

**Comment by metal-oopa** [comment]
Sending a PR shortly.
