### ISSUE TITLE
Write a R program to convert minutes to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1891]
### Description

Write a R program to convert minutes to seconds

1 minute = 60 seconds

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_minutes_to_seconds.r` file
- Add `convert_minutes_to_seconds.r` file in `convert-minutes-to-seconds` folder

</details>

**Comment by esivakumar18** [comment]
!assign
