### ISSUE TITLE
Write a Ruby program to convert minutes to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1892]
### Description

Write a Ruby program to convert minutes to seconds

1 minute = 60 seconds

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMinutesToSeconds.rb` file
- Add `ConvertMinutesToSeconds.rb` file in `convert-minutes-to-seconds` folder

</details>

**Comment by auleki** [comment]
!assign
