### ISSUE TITLE
Write a Swift program to convert minutes to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1895]
### Description

Write a Swift program to convert minutes to seconds

1 minute = 60 seconds

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMinutesToSeconds.swift` file
- Add `ConvertMinutesToSeconds.swift` file in `convert-minutes-to-seconds` folder

</details>

**Comment by esivakumar18** [comment]
!assign
