### ISSUE TITLE
Write a JavaScript program to convert days to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1909]
### Description

Write a JavaScript program to convert days to seconds

1 day = 24 hours = 1440 minutes = 86400 seconds

```
Input  : 5
Output : 432000
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertDaysToSeconds.js` file
- Add `ConvertDaysToSeconds.js` file in `convert-days-to-seconds` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign
