### ISSUE TITLE
Write a Julia program to convert days to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1910]
### Description

Write a Julia program to convert days to seconds

1 day = 24 hours = 1440 minutes = 86400 seconds

```
Input  : 5
Output : 432000
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-days-to-seconds.jl` file
- Add `convert-days-to-seconds.jl` file in `convert-days-to-seconds` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
