### ISSUE TITLE
Write a Kotlin program to convert days to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1911]
### Description

Write a Kotlin program to convert days to seconds

1 day = 24 hours = 1440 minutes = 86400 seconds

```
Input  : 5
Output : 432000
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertDaysToSeconds.kt` file
- Add `ConvertDaysToSeconds.kt` file in `convert-days-to-seconds` folder

</details>

**Comment by prathameshkarambelkar** [comment]
!assign

**Comment by rksp25** [comment]
!assign

**Comment by rksp25** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @rksp25, this issue is already assigned to @prathameshkarambelkar !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
