### ISSUE TITLE
Write a PHP program to convert days to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1913]
### Description

Write a PHP program to convert days to seconds

1 day = 24 hours = 1440 minutes = 86400 seconds

```
Input  : 5
Output : 432000
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_days_to_seconds.php` file
- Add `convert_days_to_seconds.php` file in `convert-days-to-seconds` folder

</details>

**Comment by esivakumar18** [comment]
!assign
