### ISSUE TITLE
Write a Python program to convert days to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1914]
### Description

Write a Python program to convert days to seconds

1 day = 24 hours = 1440 minutes = 86400 seconds

```
Input  : 5
Output : 432000
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-days-to-seconds.py` file
- Add `convert-days-to-seconds.py` file in `convert-days-to-seconds` folder

</details>

**Comment by grraghav120** [comment]
!assign
