### ISSUE TITLE
Write a Scala program to convert days to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1918]
### Description

Write a Scala program to convert days to seconds

1 day = 24 hours = 1440 minutes = 86400 seconds

```
Input  : 5
Output : 432000
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convertDaysToSeconds.scala` file
- Add `convertDaysToSeconds.scala` file in `convert-days-to-seconds` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
