### ISSUE TITLE
Write a Swift program to convert days to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1919]
### Description

Write a Swift program to convert days to seconds

1 day = 24 hours = 1440 minutes = 86400 seconds

```
Input  : 5
Output : 432000
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertDaysToSeconds.swift` file
- Add `ConvertDaysToSeconds.swift` file in `convert-days-to-seconds` folder

</details>

**Comment by esivakumar18** [comment]
!assign
