### ISSUE TITLE
Write a C++ program to find surface area of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1929]
### Description

Write a C++ program to find surface area of a cube

Surface area of cube = 6 × `Side`^2

```
Side : 2

Surface area : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSurfaceAreaOfACube.cpp` file
- Add `FindSurfaceAreaOfACube.cpp` file in `find-surface-area-of-a-cube` folder

</details>

**Comment by Chaitanya-2804** [comment]
Can u assign this to me ?

**Comment by anxkhn** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @anxkhn,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by roshan798** [comment]
!assign
