### ISSUE TITLE
Write a Dart program to find surface area of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1930]
### Description

Write a Dart program to find surface area of a cube

Surface area of cube = 6 × `Side`^2

```
Side : 2

Surface area : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_surface_area_of_a_cube.dart` file
- Add `find_surface_area_of_a_cube.dart` file in `find-surface-area-of-a-cube` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign
