### ISSUE TITLE
Write a JavaScript program to find surface area of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1935]
### Description

Write a JavaScript program to find surface area of a cube

Surface area of cube = 6 × `Side`^2

```
Side : 2

Surface area : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSurfaceAreaOfACube.js` file
- Add `FindSurfaceAreaOfACube.js` file in `find-surface-area-of-a-cube` folder

</details>

**Comment by tanishq-singh-2301** [comment]
_**!Assign**_

**Comment by tanishq-singh-2301** [comment]
!assign
