### ISSUE TITLE
Write a Kotlin program to find surface area of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1937]
### Description

Write a Kotlin program to find surface area of a cube

Surface area of cube = 6 × `Side`^2

```
Side : 2

Surface area : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSurfaceAreaOfACube.kt` file
- Add `FindSurfaceAreaOfACube.kt` file in `find-surface-area-of-a-cube` folder

</details>

**Comment by hemantsuteri** [comment]
!assign
