### ISSUE TITLE
Write a PHP program to find surface area of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1939]
### Description

Write a PHP program to find surface area of a cube

Surface area of cube = 6 × `Side`^2

```
Side : 2

Surface area : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_surface_area_of_a_cube.php` file
- Add `find_surface_area_of_a_cube.php` file in `find-surface-area-of-a-cube` folder

</details>

**Comment by ridsuteri** [comment]
!assign
