### ISSUE TITLE
Write a Rust program to find surface area of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1943]
### Description

Write a Rust program to find surface area of a cube

Surface area of cube = 6 × `Side`^2

```
Side : 2

Surface area : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_surface_area_of_a_cube.rs` file
- Add `find_surface_area_of_a_cube.rs` file in `find-surface-area-of-a-cube` folder

</details>

**Comment by victoriacheng15** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @victoriacheng15,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
