### ISSUE TITLE
Write a TypeScript program to find surface area of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1946]
### Description

Write a TypeScript program to find surface area of a cube

Surface area of cube = 6 × `Side`^2

```
Side : 2

Surface area : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSurfaceAreaOfACube.ts` file
- Add `FindSurfaceAreaOfACube.ts` file in `find-surface-area-of-a-cube` folder

</details>

**Comment by nickdark** [comment]
!assign
