### ISSUE TITLE
Write a C program to check palindrome number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1982]
### Description

Write a C program to check palindrome number

Palindrome numbers are the numbers for which reverse is exactly same as the original number. For example, 121 is palindrome, but 123 is not palindrome.

```
Input  : 121
Output : Palindrome Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckPalindromeNumber.c` file
- Add `CheckPalindromeNumber.c` file in `check-palindrome-number` folder

</details>

**Comment by KaptainCS3** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @KaptainCS3,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Osher160** [comment]
!assign

**Comment by Osher160** [comment]
there is already a palindrome c file in the folder. it looks like the issue should be closed.

**Comment by PavanKumarCB** [comment]
!assign
