### ISSUE TITLE
Write a C++ program to check palindrome number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1984]
### Description

Write a C++ program to check palindrome number

Palindrome numbers are the numbers for which reverse is exactly same as the original number. For example, 121 is palindrome, but 123 is not palindrome.

```
Input  : 121
Output : Palindrome Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckPalindromeNumber.cpp` file
- Add `CheckPalindromeNumber.cpp` file in `check-palindrome-number` folder

</details>

**Comment by grraghav120** [comment]
!assign

**Comment by AshishSharma1203** [comment]
Can I work upon this ??

**Comment by harshraj8843** [comment]
Hey @AshishSharma1203 

Sorry, but this issue has already been assigned

Please contribute to another issue 👍🏻 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto assigned

```
!assign
```
