### ISSUE TITLE
Write a Perl program to check palindrome number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1993]
### Description

Write a Perl program to check palindrome number

Palindrome numbers are the numbers for which reverse is exactly same as the original number. For example, 121 is palindrome, but 123 is not palindrome.

```
Input  : 121
Output : Palindrome Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check_palindrome_number.pl` file
- Add `check_palindrome_number.pl` file in `check-palindrome-number` folder

</details>

**Comment by gupta-soham** [comment]
!assign
