### ISSUE TITLE
Write a Python program to check palindrome number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1995]
### Description

Write a Python program to check palindrome number

Palindrome numbers are the numbers for which reverse is exactly same as the original number. For example, 121 is palindrome, but 123 is not palindrome.

```
Input  : 121
Output : Palindrome Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check-palindrome-number.py` file
- Add `check-palindrome-number.py` file in `check-palindrome-number` folder

</details>

**Comment by AshishSharma1203** [comment]
Can this issue be assigned to me ??

**Comment by mak650650** [comment]
!assign

**Comment by anupeshverma** [comment]
can you assign me this issue;

**Comment by AshishSharma1203** [comment]
> can you assign me this issue;

I am working on it already 🙂

**Comment by Aaronphilip2003** [comment]
Can you assign this task to me ?
