### ISSUE TITLE
Write a Rust program to check palindrome number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#1998]
### Description

Write a Rust program to check palindrome number

Palindrome numbers are the numbers for which reverse is exactly same as the original number. For example, 121 is palindrome, but 123 is not palindrome.

```
Input  : 121
Output : Palindrome Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check_palindrome_number.rs` file
- Add `check_palindrome_number.rs` file in `check-palindrome-number` folder

</details>

**Comment by rwlc** [comment]
!assign
