### ISSUE TITLE
Write a Swift program to check palindrome number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2000]
### Description

Write a Swift program to check palindrome number

Palindrome numbers are the numbers for which reverse is exactly same as the original number. For example, 121 is palindrome, but 123 is not palindrome.

```
Input  : 121
Output : Palindrome Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CheckPalindromeNumber.swift` file
- Add `CheckPalindromeNumber.swift` file in `check-palindrome-number` folder

</details>

**Comment by MarianCekan** [comment]
Hello is this issue still available please?

**Comment by harshraj8843** [comment]
Hey @MarianCekan 

You can comment `!assign` on any 'good first issue` you want to contribute to, to be auto assigned

```
!assign
```

---

> Hello is this issue still available please?

Yes

---

Thanks for contributing 👍🏻

**Comment by KartikeyDubeyKD** [comment]
!assign

**Comment by shams-rf** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @shams-rf, this issue is already assigned to @KartikeyDubeyKD !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
