### ISSUE TITLE
Write a TypeScript program to print hello world

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#21]
### Description

Write a TypeScript program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.ts` file
- Add `PrintHelloWorld.ts` file in `print-hello-world` folder

</details>

**Comment by anaskhan28** [comment]
assign me

**Comment by harshraj8843** [comment]
Hey @anaskhan28 

You can comment `!assign` on the issues you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by anaskhan28** [comment]
!assign
