### ISSUE TITLE
Write a C program to print fibonacci series without recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2110]
### Description

Write a C program to print fibonacci series without recursion

```
Input  : 5
Output : 0 1 1 2 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintFibonacciSeriesWithoutRecursion.c` file
- Add `PrintFibonacciSeriesWithoutRecursion.c` file in `print-fibonacci-series-without-recursion` folder

</details>

**Comment by PanikaGupta** [comment]
hey! Can I work on this?

**Comment by harshraj8843** [comment]
Hey @Mohitt0 @PanikaGupta 

Please comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

Thanks for contributing 👍🏻

**Comment by Ajaymaurya1008** [comment]
!assign

**Comment by grraghav120** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @thekavikumar, this issue is already assigned to @grraghav120 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by PanikaGupta** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @PanikaGupta, this issue is already assigned to @grraghav120 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
