### ISSUE TITLE
Write a C++ program to print fibonacci series without recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2112]
### Description

Write a C++ program to print fibonacci series without recursion

```
Input  : 5
Output : 0 1 1 2 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintFibonacciSeriesWithoutRecursion.cpp` file
- Add `PrintFibonacciSeriesWithoutRecursion.cpp` file in `print-fibonacci-series-without-recursion` folder

</details>

**Comment by YaSh8202** [comment]
!assign

**Comment by Mohitt0** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Mohitt0, this issue is already assigned to @YaSh8202 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
