### ISSUE TITLE
Write a JavaScript program to print fibonacci series without recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2118]
### Description

Write a JavaScript program to print fibonacci series without recursion

```
Input  : 5
Output : 0 1 1 2 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintFibonacciSeriesWithoutRecursion.js` file
- Add `PrintFibonacciSeriesWithoutRecursion.js` file in `print-fibonacci-series-without-recursion` folder

</details>

**Comment by prajapati-arjun** [comment]
!issue
