### ISSUE TITLE
Write a Python program to print fibonacci series without recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2123]
### Description

Write a Python program to print fibonacci series without recursion

```
Input  : 5
Output : 0 1 1 2 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `print-fibonacci-series-without-recursion.py` file
- Add `print-fibonacci-series-without-recursion.py` file in `print-fibonacci-series-without-recursion` folder

</details>

**Comment by anastazir** [comment]
!assign
