### ISSUE TITLE
Write a Swift program to print fibonacci series without recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2128]
### Description

Write a Swift program to print fibonacci series without recursion

```
Input  : 5
Output : 0 1 1 2 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintFibonacciSeriesWithoutRecursion.swift` file
- Add `PrintFibonacciSeriesWithoutRecursion.swift` file in `print-fibonacci-series-without-recursion` folder

</details>

**Comment by hemantsuteri** [comment]
!assign
