### ISSUE TITLE
Write a TypeScript program to print fibonacci series without recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2129]
### Description

Write a TypeScript program to print fibonacci series without recursion

```
Input  : 5
Output : 0 1 1 2 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintFibonacciSeriesWithoutRecursion.ts` file
- Add `PrintFibonacciSeriesWithoutRecursion.ts` file in `print-fibonacci-series-without-recursion` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by Ariel201711** [comment]
!assign
