### ISSUE TITLE
find-fibonacci-sequence-with-iteration

### ISSUE THREAD

**Issue by icanhaskick** [codinasion/program#2140]
### Description

a program to find the fibonacci sequence with a loop

**Comment by astitva0011** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @astitva0011, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
#2109

---

Fibonacci series without recursion is done by iteration

---

Thanks for contributing 👍🏻
