### ISSUE TITLE
Write a C++ program to find sum of numbers

### ISSUE THREAD

**Issue by icanhaskick** [codinasion/program#2144]
### Description

A C++ program to find sum of numbers

```bash
Input: 1 2 3 4 5
Output: 15
```

**Comment by tanishq-singh-2301** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @tanishq-singh-2301, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by tanishq-singh-2301** [comment]
so how to contribute in this?

**Comment by tanishq-singh-2301** [comment]
can i work on this? @harshraj8843

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.
