### ISSUE TITLE
Write a Java Program to find GCD of two numbers.

### ISSUE THREAD

**Issue by Khushi260** [codinasion/program#2156]
### Description

A number (N1)
A number (N2)
Write a function which returns the GCD of N1 and N2. Print the value returned.

Please assign this issue under Hacktoberfest 2022.

**Comment by sksachin7z2** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @sksachin7z2, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
This program has already been submitted in #186 and the respective issues will be auto-created shortly 🕙 

---

Please check the program list before submitting the new program

https://github.com/codinasion/program/blob/master/data/programs.json

---

Thanks for contributing 👍🏻
