### ISSUE TITLE
Write a C# program for linear search

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2201]
### Description

Write a C# program for linear search

Linear search is a very simple search algorithm. In this type of search, a sequential search is made over all items one by one. Every item is checked and if a match is found then that particular item is returned, otherwise the search continues till the end of the data collection.

```
Input  : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Target : 5

Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `LinearSearch.cs` file
- Add `LinearSearch.cs` file in `dsa/linear-search` folder

</details>

**Comment by astitva0011** [comment]
!assign
