### ISSUE TITLE
Write a GO program for linear search

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2205]
### Description

Write a GO program for linear search

Linear search is a very simple search algorithm. In this type of search, a sequential search is made over all items one by one. Every item is checked and if a match is found then that particular item is returned, otherwise the search continues till the end of the data collection.

```
Input  : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Target : 5

Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `linear_search.go` file
- Add `linear_search.go` file in `dsa/linear-search` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @MadhuS-1605

Sorry but the assignment limit has been set to 20 issues per user.

These limits are set to ensure everyone gets a chance to contribute to Hacktoberfest.

These limits will be lifted after 31st October.

Thank you very much for contributing to this project.

**Comment by harshraj8843** [comment]
Hey @MadhuS-1605 

`auto-assignment` limit has been removed, you can continue contributing to `good first issue`

**Sorry** for the inconvenience caused

Thanks for your awesome contributions 🤗

**Comment by MadhuS-1605** [comment]
Thank you 😊
