### ISSUE TITLE
Write a GO program to find largest and smallest numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2230]
### Description

Write a GO program to find largest and smallest numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 5, 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_largest_and_smallest_numbers_in_an_array.go` file
- Add `find_largest_and_smallest_numbers_in_an_array.go` file in `find-largest-and-smallest-numbers-in-an-array` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @MadhuS-1605

Sorry but the assignment limit has been set to 20 issues per user.

These limits are set to ensure everyone gets a chance to contribute to Hacktoberfest.

These limits will be lifted after 31st October.

Thank you very much for contributing to this project.

**Comment by harshraj8843** [comment]
Hey @MadhuS-1605 

`auto-assignment` limit has been removed, you can continue contributing to `good first issue`

**Sorry** for the inconvenience caused

Thanks for your awesome contributions 🤗

**Comment by MadhuS-1605** [comment]
Thank you
