### ISSUE TITLE
Write a JavaScript program to find largest and smallest numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2233]
### Description

Write a JavaScript program to find largest and smallest numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 5, 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindLargestAndSmallestNumbersInAnArray.js` file
- Add `FindLargestAndSmallestNumbersInAnArray.js` file in `find-largest-and-smallest-numbers-in-an-array` folder

</details>

**Comment by GamerCreator1** [comment]
!assign
