### ISSUE TITLE
Write a Python program to find largest and smallest numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2238]
### Description

Write a Python program to find largest and smallest numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 5, 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-largest-and-smallest-numbers-in-an-array.py` file
- Add `find-largest-and-smallest-numbers-in-an-array.py` file in `find-largest-and-smallest-numbers-in-an-array` folder

</details>

**Comment by destroyer5067** [comment]
!assign
