### ISSUE TITLE
Write a Ruby program to find largest and smallest numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2240]
### Description

Write a Ruby program to find largest and smallest numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 5, 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindLargestAndSmallestNumbersInAnArray.rb` file
- Add `FindLargestAndSmallestNumbersInAnArray.rb` file in `find-largest-and-smallest-numbers-in-an-array` folder

</details>

**Comment by jfinley6** [comment]
!assign
