### ISSUE TITLE
Write a TypeScript program to find largest and smallest numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2244]
### Description

Write a TypeScript program to find largest and smallest numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 5, 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindLargestAndSmallestNumbersInAnArray.ts` file
- Add `FindLargestAndSmallestNumbersInAnArray.ts` file in `find-largest-and-smallest-numbers-in-an-array` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign

**Comment by pelegsch666** [comment]
!assign
