### ISSUE TITLE
Write a C program to find the sum of all numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2254]
### Description

Write a C program to find the sum of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheSumOfAllNumbersInAnArray.c` file
- Add `FindTheSumOfAllNumbersInAnArray.c` file in `find-the-sum-of-all-numbers-in-an-array` folder

</details>

**Comment by Mohitt0** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Mohitt0,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
