### ISSUE TITLE
Write a C++ program to find the sum of all numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2256]
### Description

Write a C++ program to find the sum of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheSumOfAllNumbersInAnArray.cpp` file
- Add `FindTheSumOfAllNumbersInAnArray.cpp` file in `find-the-sum-of-all-numbers-in-an-array` folder

</details>

**Comment by neelesh08** [comment]
Hey @harshraj8843 
I will solve this issue!

**Comment by harshraj8843** [comment]
Hey @neelesh08 

You can comment `!assign` on any `good first issue` you want to contribute, to be auto-assigned

```
!assign
```

**Comment by Aaronphilip2003** [comment]
!assign

**Comment by neelesh08** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @neelesh08, this issue is already assigned to @Aaronphilip2003 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by Ankitrai2204** [comment]
Hello I want to contribute on this project. Can you please assign it to me and tell about our requirements.

**Comment by harshraj8843** [comment]
Hey @Ankitrai2204 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

After the assignment, you can raise a Pull request by adding the solution of the respective issue

For file and folder location please see `How to contribute` dropdown on respective issue

**Comment by harshraj8843** [comment]
Hey @Aaronphilip2003,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by AbhinavPrabhat01** [comment]
!assign
