### ISSUE TITLE
Write a Java program to find the sum of all numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2261]
### Description

Write a Java program to find the sum of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheSumOfAllNumbersInAnArray.java` file
- Add `FindTheSumOfAllNumbersInAnArray.java` file in `find-the-sum-of-all-numbers-in-an-array` folder

</details>

**Comment by Debarpan08** [comment]
@harshraj8843 Sir,I would like to work on this,could you assign this to me?

**Comment by Shivaraj21** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Debarpan08 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by Debarpan08** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Debarpan08, this issue is already assigned to @Shivaraj21 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
