### ISSUE TITLE
Write a JavaScript program to find the sum of all numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2262]
### Description

Write a JavaScript program to find the sum of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheSumOfAllNumbersInAnArray.js` file
- Add `FindTheSumOfAllNumbersInAnArray.js` file in `find-the-sum-of-all-numbers-in-an-array` folder

</details>

**Comment by Debarpan08** [comment]
@harshraj8843 Sir, could you please please assign this task to me

**Comment by harshraj8843** [comment]
Hey @Debarpan08 

You can comment `!assign` on any `good first issue` you want to contribute to , to be auto-assigned

```
!assign
```

Thanks for contributing 👍🏻

**Comment by VictorUkoha** [comment]
!assign

**Comment by VictorChukwudi** [comment]
! assign

**Comment by VictorChukwudi** [comment]
! assign

**Comment by GodWin1100** [comment]
!assign

**Comment by Debarpan08** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Debarpan08, this issue is already assigned to @GodWin1100 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by Debarpan08** [comment]
Sure,Sir.Do you have any other good first issue in your repo which I can be
assigned?

**Comment by harshraj8843** [comment]
Hey @Debarpan08 

There are `709` `good first issues` assigned to nobody

You can contribute to any one of them [👉🏻 List of `good first issue`](https://github.com/codinasion/program/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22+no%3Aassignee)
