### ISSUE TITLE
Write a Python program to find the sum of all numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2267]
### Description

Write a Python program to find the sum of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-the-sum-of-all-numbers-in-an-array.py` file
- Add `find-the-sum-of-all-numbers-in-an-array.py` file in `find-the-sum-of-all-numbers-in-an-array` folder

</details>

**Comment by shashi3000** [comment]
#Hey harshraj8843. I am a newbie. I dont know how to contribute the way you said. So i just wrote the comment. Hope you don't mind.
nums=[1,2,3,4,5]
sum=0
for i in nums:
    sum+=i
print(sum)

**Comment by harshraj8843** [comment]
Hey @shashi3000 

Thanks for contributing 👍🏻 

---

You can follow [👉🏻  the contributing guide](https://github.com/codinasion/program/blob/master/CONTRIBUTING.md#make-changes) for, how to raise a Pull Request for this issue
