### ISSUE TITLE
Write a Ruby program to find the sum of all numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2269]
### Description

Write a Ruby program to find the sum of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheSumOfAllNumbersInAnArray.rb` file
- Add `FindTheSumOfAllNumbersInAnArray.rb` file in `find-the-sum-of-all-numbers-in-an-array` folder

</details>

**Comment by jfinley6** [comment]
!assign
