### ISSUE TITLE
Write a Swift program to find the sum of all numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2272]
### Description

Write a Swift program to find the sum of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheSumOfAllNumbersInAnArray.swift` file
- Add `FindTheSumOfAllNumbersInAnArray.swift` file in `find-the-sum-of-all-numbers-in-an-array` folder

</details>

**Comment by rk-1620** [comment]
@harshraj8843 I would like to contribute to it. Please assign it to me

**Comment by harshraj8843** [comment]
Hey @rk-1620 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

Thanks for contributing 👍🏻

**Comment by rk-1620** [comment]
!assign
