### ISSUE TITLE
Write a TypeScript program to find the sum of all numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2273]
### Description

Write a TypeScript program to find the sum of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheSumOfAllNumbersInAnArray.ts` file
- Add `FindTheSumOfAllNumbersInAnArray.ts` file in `find-the-sum-of-all-numbers-in-an-array` folder

</details>

**Comment by Debarpan08** [comment]
@harshraj8843 ,Sir would you please assign this to me?

**Comment by 25011908vardhan** [comment]
!assign
