### ISSUE TITLE
Write a C program to convert celsius to fahrenheit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2282]
### Description

Write a C program to convert celsius to fahrenheit

fahrerheit = (celsius * 9/5) + 32

```
Input ( C )  : -40
Output ( F ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCelsiusToFahrenheit.c` file
- Add `ConvertCelsiusToFahrenheit.c` file in `convert-celsius-to-fahrenheit` folder

</details>

**Comment by shivanshi-s** [comment]
Hey, i would like to work on this

**Comment by harshraj8843** [comment]
Hey @shivanshi-s 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by neelesh08** [comment]
!assign

**Comment by shivanshi-s** [comment]
@neelesh08 very rude imo

**Comment by neelesh08** [comment]
Hey @shivanshi-s sorry!,
do you know, how to reassign the task to others, I will assign it to you
@harshraj8843  Helps us out here

**Comment by shivanshi-s** [comment]
Its alright, just keep it in mind for the next time.

**Comment by harshraj8843** [comment]
> how to reassign the task to others

@neelesh08 you can remove your assignment and then other users can use the command `!assign` to be auto-assigned

**Comment by neelesh08** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @neelesh08, this issue is already assigned to @neelesh08 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by neelesh08** [comment]
!assign
