### ISSUE TITLE
Write a C++ program to convert celsius to fahrenheit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2284]
### Description

Write a C++ program to convert celsius to fahrenheit

fahrerheit = (celsius * 9/5) + 32

```
Input ( C )  : -40
Output ( F ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCelsiusToFahrenheit.cpp` file
- Add `ConvertCelsiusToFahrenheit.cpp` file in `convert-celsius-to-fahrenheit` folder

</details>

**Comment by grraghav120** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @grraghav120

Sorry but the assignment limit has been set to 20 issues per user.

These limits are set to ensure everyone gets a chance to contribute to Hacktoberfest.

These limits will be lifted after 31st October.

Thank you very much for contributing to this project.

**Comment by neelesh08** [comment]
! assign

**Comment by GodWin1100** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @grraghav120 

`auto-assignment` limit has been removed, you can continue contributing to `good first issue`

**Sorry** for the inconvenience caused

Thanks for your awesome contributions 🤗

**Comment by Ankitrai2204** [comment]
Hello I want to contribute on this project. Can you please assign it to me and tell about our requirements.

**Comment by grraghav120** [comment]
@Ankitrai2204 this issue is already assign to one 
kindly work on the other issues
