### ISSUE TITLE
Write a GO program to convert celsius to fahrenheit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2287]
### Description

Write a GO program to convert celsius to fahrenheit

fahrerheit = (celsius * 9/5) + 32

```
Input ( C )  : -40
Output ( F ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_celsius_to_fahrenheit.go` file
- Add `convert_celsius_to_fahrenheit.go` file in `convert-celsius-to-fahrenheit` folder

</details>

**Comment by Ladam0203** [comment]
Hey, is it okay if I only write a method? Or should I put that method into main and call it as an example? (I'd like to be assigned to this)

**Comment by harshraj8843** [comment]
Hey @Ladam0203 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

---

> is it okay if I only write a method? Or should I put that method into main and call it as an example?

It would be better if you could contribute full working program 👍🏻

**Comment by Ladam0203** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Ladam0203,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
