### ISSUE TITLE
Write a Java program to convert celsius to fahrenheit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2289]
### Description

Write a Java program to convert celsius to fahrenheit

fahrerheit = (celsius * 9/5) + 32

```
Input ( C )  : -40
Output ( F ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCelsiusToFahrenheit.java` file
- Add `ConvertCelsiusToFahrenheit.java` file in `convert-celsius-to-fahrenheit` folder

</details>

**Comment by vedha-vikash-pixel** [comment]
!assign
