### ISSUE TITLE
Write a Python program to convert celsius to fahrenheit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2295]
### Description

Write a Python program to convert celsius to fahrenheit

fahrerheit = (celsius * 9/5) + 32

```
Input ( C )  : -40
Output ( F ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-celsius-to-fahrenheit.py` file
- Add `convert-celsius-to-fahrenheit.py` file in `convert-celsius-to-fahrenheit` folder

</details>

**Comment by GuyEternal** [comment]
!assign
