### ISSUE TITLE
Write a Ruby program to convert celsius to fahrenheit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2297]
### Description

Write a Ruby program to convert celsius to fahrenheit

fahrerheit = (celsius * 9/5) + 32

```
Input ( C )  : -40
Output ( F ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCelsiusToFahrenheit.rb` file
- Add `ConvertCelsiusToFahrenheit.rb` file in `convert-celsius-to-fahrenheit` folder

</details>

**Comment by harshraj8843** [comment]
Hey @ranaprerna,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by rafaover** [comment]
!assign
