### ISSUE TITLE
Write a Rust program to convert celsius to fahrenheit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2298]
### Description

Write a Rust program to convert celsius to fahrenheit

fahrerheit = (celsius * 9/5) + 32

```
Input ( C )  : -40
Output ( F ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_celsius_to_fahrenheit.rs` file
- Add `convert_celsius_to_fahrenheit.rs` file in `convert-celsius-to-fahrenheit` folder

</details>

**Comment by RitoDas1923** [comment]
!assign
