### ISSUE TITLE
Write a Scala program to convert celsius to fahrenheit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2299]
### Description

Write a Scala program to convert celsius to fahrenheit

fahrerheit = (celsius * 9/5) + 32

```
Input ( C )  : -40
Output ( F ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convertCelsiusToFahrenheit.scala` file
- Add `convertCelsiusToFahrenheit.scala` file in `convert-celsius-to-fahrenheit` folder

</details>

**Comment by esivakumar18** [comment]
!assign
