### ISSUE TITLE
Write a Swift program to convert celsius to fahrenheit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2300]
### Description

Write a Swift program to convert celsius to fahrenheit

fahrerheit = (celsius * 9/5) + 32

```
Input ( C )  : -40
Output ( F ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCelsiusToFahrenheit.swift` file
- Add `ConvertCelsiusToFahrenheit.swift` file in `convert-celsius-to-fahrenheit` folder

</details>

**Comment by esivakumar18** [comment]
!assign
