### ISSUE TITLE
Write a Python program to find the maximum sum of a contiguous subarray (circular)

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2323]
### Description

Write a Python program to find the maximum sum of a contiguous subarray (circular)

Maximum sum of a circular subarray is the task of finding the contiguous subarray within a circular one-dimensional array of numbers which has the largest sum. For example, for the sequence of values `10, -3, -4, 7, 6, 5, -4, -1;` the contiguous subarray with the largest sum is `7, 6, 5,` with sum `18`.

```
Input  : [8, -8, 9, -9, 10, -11, 12]
Output : 22
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-the-maximum-sum-of-a-contiguous-subarray-(circular).py` file
- Add `find-the-maximum-sum-of-a-contiguous-subarray-(circular).py` file in `find-the-maximum-sum-of-a-contiguous-subarray-(circular)` folder

</details>

**Comment by GuyEternal** [comment]
Is it alright if the input format is this:
```
Input: 8, -8, 9, -9, 10, -11, 12 
```

**Comment by harshraj8843** [comment]
Sure @GuyEternal 

Please comment `!assign` on the issue you want to contribute to, before raising a PR, to be auto-assigned

```
!assign
```

Thanks for contributing 👍🏻

**Comment by GuyEternal** [comment]
!assign

**Comment by Aaronphilip2003** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Aaronphilip2003, this issue is already assigned to @GuyEternal !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
