### ISSUE TITLE
Write a R program to find the maximum sum of a contiguous subarray (circular)

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2324]
### Description

Write a R program to find the maximum sum of a contiguous subarray (circular)

Maximum sum of a circular subarray is the task of finding the contiguous subarray within a circular one-dimensional array of numbers which has the largest sum. For example, for the sequence of values `10, -3, -4, 7, 6, 5, -4, -1;` the contiguous subarray with the largest sum is `7, 6, 5,` with sum `18`.

```
Input  : [8, -8, 9, -9, 10, -11, 12]
Output : 22
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_the_maximum_sum_of_a_contiguous_subarray_(circular).r` file
- Add `find_the_maximum_sum_of_a_contiguous_subarray_(circular).r` file in `find-the-maximum-sum-of-a-contiguous-subarray-(circular)` folder

</details>

**Comment by jay13makhija** [comment]
I can do it in C++

**Comment by harshraj8843** [comment]
Hey @jay13makhija 

Sorry but #2312 has already been assigned to someone

Please contribute to another `good first issue`

---

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by abdurafeyf** [comment]
!assign
