### ISSUE TITLE
Write a GO program to find the cofactor of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2350]
### Description

Write a GO program to find the cofactor of a matrix

The cofactor of an element a<sub>ij</sub> of a square matrix A is the determinant of the minor of A obtained by deleting the ith row and jth column of A. The cofactor of a matrix A is the matrix of cofactors of A.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
[[-3, 6, -3], [6, -12, 6], [-3, 6, -3]]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_the_cofactor_of_a_matrix.go` file
- Add `find_the_cofactor_of_a_matrix.go` file in `find-the-cofactor-of-a-matrix` folder

</details>

**Comment by PoweredByCaffein** [comment]
Hi @harshraj8843,
The solution should be for a 3x3 matrix only or it should include for a square matrix of any size like 4x4 or 5x5?

**Comment by harshraj8843** [comment]
This issue is limited to `3x3` matrix only

**Comment by PoweredByCaffein** [comment]
!assign
