### ISSUE TITLE
Write a JavaScript program to find the cofactor of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2353]
### Description

Write a JavaScript program to find the cofactor of a matrix

The cofactor of an element a<sub>ij</sub> of a square matrix A is the determinant of the minor of A obtained by deleting the ith row and jth column of A. The cofactor of a matrix A is the matrix of cofactors of A.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
[[-3, 6, -3], [6, -12, 6], [-3, 6, -3]]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheCofactorOfAMatrix.js` file
- Add `FindTheCofactorOfAMatrix.js` file in `find-the-cofactor-of-a-matrix` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign

**Comment by avireni** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @avireni,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by JoshuaT35** [comment]
!assign
