### ISSUE TITLE
Write a C++ program to convert centimeters to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2369]
### Description

Write a C++ program to convert centimeters to feet

1 foot = 30.48 centimeters

```
Input  : 152.4
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCentimetersToFeet.cpp` file
- Add `ConvertCentimetersToFeet.cpp` file in `convert-centimeters-to-feet` folder

</details>

**Comment by grraghav120** [comment]
!assign

**Comment by Ankitrai2204** [comment]
Hello I want to contribute on this project. Can you please assign it to me and tell about our requirements.

**Comment by victoriacheng15** [comment]
@Ankitrai2204 

This issue is assigned to someone else. Please look for other issues to contribute! And make sure you type `!assign`. Thank you!
