### ISSUE TITLE
Write a GO program to convert centimeters to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2372]
### Description

Write a GO program to convert centimeters to feet

1 foot = 30.48 centimeters

```
Input  : 152.4
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_centimeters_to_feet.go` file
- Add `convert_centimeters_to_feet.go` file in `convert-centimeters-to-feet` folder

</details>

**Comment by PoweredByCaffein** [comment]
!assign
