### ISSUE TITLE
Write a Haskell program to convert centimeters to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2373]
### Description

Write a Haskell program to convert centimeters to feet

1 foot = 30.48 centimeters

```
Input  : 152.4
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_centimeters_to_feet.hs` file
- Add `convert_centimeters_to_feet.hs` file in `convert-centimeters-to-feet` folder

</details>

**Comment by esivakumar18** [comment]
!assign
