### ISSUE TITLE
Write a Java program to convert centimeters to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2374]
### Description

Write a Java program to convert centimeters to feet

1 foot = 30.48 centimeters

```
Input  : 152.4
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCentimetersToFeet.java` file
- Add `ConvertCentimetersToFeet.java` file in `convert-centimeters-to-feet` folder

</details>

**Comment by Kunj125** [comment]
!assign

**Comment by Shalevro2** [comment]
!assign
