### ISSUE TITLE
Write a JavaScript program to convert centimeters to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2375]
### Description

Write a JavaScript program to convert centimeters to feet

1 foot = 30.48 centimeters

```
Input  : 152.4
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCentimetersToFeet.js` file
- Add `ConvertCentimetersToFeet.js` file in `convert-centimeters-to-feet` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign
