### ISSUE TITLE
Write a Julia program to convert centimeters to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2376]
### Description

Write a Julia program to convert centimeters to feet

1 foot = 30.48 centimeters

```
Input  : 152.4
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-centimeters-to-feet.jl` file
- Add `convert-centimeters-to-feet.jl` file in `convert-centimeters-to-feet` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
