### ISSUE TITLE
Write a Python program to convert centimeters to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2380]
### Description

Write a Python program to convert centimeters to feet

1 foot = 30.48 centimeters

```
Input  : 152.4
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-centimeters-to-feet.py` file
- Add `convert-centimeters-to-feet.py` file in `convert-centimeters-to-feet` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign
