### ISSUE TITLE
Write a R program to convert centimeters to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2381]
### Description

Write a R program to convert centimeters to feet

1 foot = 30.48 centimeters

```
Input  : 152.4
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_centimeters_to_feet.r` file
- Add `convert_centimeters_to_feet.r` file in `convert-centimeters-to-feet` folder

</details>

**Comment by alfa-m** [comment]
!assign

**Comment by esivakumar18** [comment]
!assign
