### ISSUE TITLE
Write a Swift program to convert centimeters to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2385]
### Description

Write a Swift program to convert centimeters to feet

1 foot = 30.48 centimeters

```
Input  : 152.4
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCentimetersToFeet.swift` file
- Add `ConvertCentimetersToFeet.swift` file in `convert-centimeters-to-feet` folder

</details>

**Comment by esivakumar18** [comment]
!assign
