### ISSUE TITLE
Write a TypeScript program to convert centimeters to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2386]
### Description

Write a TypeScript program to convert centimeters to feet

1 foot = 30.48 centimeters

```
Input  : 152.4
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCentimetersToFeet.ts` file
- Add `ConvertCentimetersToFeet.ts` file in `convert-centimeters-to-feet` folder

</details>

**Comment by victoriacheng15** [comment]
!assign
