### ISSUE TITLE
Write a Haskell program to find area of a rectangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2398]
### Description

Write a Haskell program to find area of a rectangle

Area of rectangle = `Length` × `Width`

```
Length : 2
Width  : 3

Area : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_area_of_a_rectangle.hs` file
- Add `find_area_of_a_rectangle.hs` file in `find-area-of-a-rectangle` folder

</details>

**Comment by esivakumar18** [comment]
!assign
