### ISSUE TITLE
Write a JavaScript program to find area of a rectangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2400]
### Description

Write a JavaScript program to find area of a rectangle

Area of rectangle = `Length` × `Width`

```
Length : 2
Width  : 3

Area : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAreaOfARectangle.js` file
- Add `FindAreaOfARectangle.js` file in `find-area-of-a-rectangle` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign
