### ISSUE TITLE
Write a Kotlin program to find area of a rectangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2402]
### Description

Write a Kotlin program to find area of a rectangle

Area of rectangle = `Length` × `Width`

```
Length : 2
Width  : 3

Area : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAreaOfARectangle.kt` file
- Add `FindAreaOfARectangle.kt` file in `find-area-of-a-rectangle` folder

</details>

**Comment by subashpaul** [comment]
can i work on this?

**Comment by prathameshkarambelkar** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @subashpaul 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto assigned

```
!assign
```

**Comment by subashpaul** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @subashpaul, this issue is already assigned to @prathameshkarambelkar !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
