### ISSUE TITLE
Write a Perl program to find area of a rectangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2403]
### Description

Write a Perl program to find area of a rectangle

Area of rectangle = `Length` × `Width`

```
Length : 2
Width  : 3

Area : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_area_of_a_rectangle.pl` file
- Add `find_area_of_a_rectangle.pl` file in `find-area-of-a-rectangle` folder

</details>

**Comment by DHRUVKHANDELWAL00** [comment]
@harshraj8843 , please assign it to me

**Comment by harshraj8843** [comment]
Hey @DHRUVKHANDELWAL00 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto assigned

```
!assign
```
