### ISSUE TITLE
Write a PHP program to find area of a rectangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2404]
### Description

Write a PHP program to find area of a rectangle

Area of rectangle = `Length` × `Width`

```
Length : 2
Width  : 3

Area : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_area_of_a_rectangle.php` file
- Add `find_area_of_a_rectangle.php` file in `find-area-of-a-rectangle` folder

</details>

**Comment by shweta-ok99** [comment]
Hi, can I work on this

**Comment by rahmat-st** [comment]
!assign
