### ISSUE TITLE
Write a Python program to find area of a rectangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2405]
### Description

Write a Python program to find area of a rectangle

Area of rectangle = `Length` × `Width`

```
Length : 2
Width  : 3

Area : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-area-of-a-rectangle.py` file
- Add `find-area-of-a-rectangle.py` file in `find-area-of-a-rectangle` folder

</details>

**Comment by Shambu-K** [comment]
!assign

**Comment by Shambu-K** [comment]
!unassign

**Comment by harshraj8843** [comment]
Hey @Shambu-K 

There is no command `!unassign` right now, but you can remove your assignment manually

**Comment by Shambu-K** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Shambu-K, this issue is already assigned to @Shambu-K !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
