### ISSUE TITLE
Write a Ruby program to find area of a rectangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2407]
### Description

Write a Ruby program to find area of a rectangle

Area of rectangle = `Length` × `Width`

```
Length : 2
Width  : 3

Area : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAreaOfARectangle.rb` file
- Add `FindAreaOfARectangle.rb` file in `find-area-of-a-rectangle` folder

</details>

**Comment by PraaneshSelvaraj** [comment]
!assign
