### ISSUE TITLE
Write a Rust program to find area of a rectangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2408]
### Description

Write a Rust program to find area of a rectangle

Area of rectangle = `Length` × `Width`

```
Length : 2
Width  : 3

Area : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_area_of_a_rectangle.rs` file
- Add `find_area_of_a_rectangle.rs` file in `find-area-of-a-rectangle` folder

</details>

**Comment by rahmat-st** [comment]
!assign
