### ISSUE TITLE
Write a Scala program to find area of a rectangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2409]
### Description

Write a Scala program to find area of a rectangle

Area of rectangle = `Length` × `Width`

```
Length : 2
Width  : 3

Area : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/findAreaOfARectangle.scala` file
- Add `findAreaOfARectangle.scala` file in `find-area-of-a-rectangle` folder

</details>

**Comment by esivakumar18** [comment]
!assign
