### ISSUE TITLE
Write a Swift program to find area of a rectangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2410]
### Description

Write a Swift program to find area of a rectangle

Area of rectangle = `Length` × `Width`

```
Length : 2
Width  : 3

Area : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAreaOfARectangle.swift` file
- Add `FindAreaOfARectangle.swift` file in `find-area-of-a-rectangle` folder

</details>

**Comment by esivakumar18** [comment]
!assign
