### ISSUE TITLE
Write a C# program to convert string to dotcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2424]
### Description

Write a C# program to convert string to dotcase

Dotcase is a style of writing in which all letters are lowercase and spaces are replaced with periods.

```
Input  : "hello world"
Output : "hello.world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToDotcase.cs` file
- Add `ConvertStringToDotcase.cs` file in `convert-string-to-dotcase` folder

</details>

**Comment by neswatch** [comment]
!assign
