### ISSUE TITLE
Write a Java program to convert string to dotcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2430]
### Description

Write a Java program to convert string to dotcase

Dotcase is a style of writing in which all letters are lowercase and spaces are replaced with periods.

```
Input  : "hello world"
Output : "hello.world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToDotcase.java` file
- Add `ConvertStringToDotcase.java` file in `convert-string-to-dotcase` folder

</details>

**Comment by prasanta10** [comment]
!assign
