### ISSUE TITLE
Write a JavaScript program to convert string to dotcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2431]
### Description

Write a JavaScript program to convert string to dotcase

Dotcase is a style of writing in which all letters are lowercase and spaces are replaced with periods.

```
Input  : "hello world"
Output : "hello.world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToDotcase.js` file
- Add `ConvertStringToDotcase.js` file in `convert-string-to-dotcase` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign
