### ISSUE TITLE
Write a Kotlin program to convert string to dotcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2433]
### Description

Write a Kotlin program to convert string to dotcase

Dotcase is a style of writing in which all letters are lowercase and spaces are replaced with periods.

```
Input  : "hello world"
Output : "hello.world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToDotcase.kt` file
- Add `ConvertStringToDotcase.kt` file in `convert-string-to-dotcase` folder

</details>

**Comment by rahmat-st** [comment]
!assign
