### ISSUE TITLE
Write a PHP program to convert string to dotcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2435]
### Description

Write a PHP program to convert string to dotcase

Dotcase is a style of writing in which all letters are lowercase and spaces are replaced with periods.

```
Input  : "hello world"
Output : "hello.world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_string_to_dotcase.php` file
- Add `convert_string_to_dotcase.php` file in `convert-string-to-dotcase` folder

</details>

**Comment by rahmat-st** [comment]
!assign
