### ISSUE TITLE
Write a Ruby program to convert string to dotcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2438]
### Description

Write a Ruby program to convert string to dotcase

Dotcase is a style of writing in which all letters are lowercase and spaces are replaced with periods.

```
Input  : "hello world"
Output : "hello.world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToDotcase.rb` file
- Add `ConvertStringToDotcase.rb` file in `convert-string-to-dotcase` folder

</details>

**Comment by rafaover** [comment]
!assign
