### ISSUE TITLE
Write a TypeScript program to convert string to dotcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2442]
### Description

Write a TypeScript program to convert string to dotcase

Dotcase is a style of writing in which all letters are lowercase and spaces are replaced with periods.

```
Input  : "hello world"
Output : "hello.world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToDotcase.ts` file
- Add `ConvertStringToDotcase.ts` file in `convert-string-to-dotcase` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Greeshma-frontier, this issue is already assigned to @CodingWithHardik !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
