### ISSUE TITLE
Write a C++ program to convert string to kebabcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2452]
### Description

Write a C++ program to convert string to kebabcase

Kebabcase is a style of writing in which all letters are lowercase and spaces are replaced with hyphens.

```
Input  : "hello world"
Output : "hello-world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToKebabcase.cpp` file
- Add `ConvertStringToKebabcase.cpp` file in `convert-string-to-kebabcase` folder

</details>

**Comment by astitva0011** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @astitva0011,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Osher160** [comment]
!assign
