### ISSUE TITLE
Write a Java program to convert string to kebabcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2458]
### Description

Write a Java program to convert string to kebabcase

Kebabcase is a style of writing in which all letters are lowercase and spaces are replaced with hyphens.

```
Input  : "hello world"
Output : "hello-world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToKebabcase.java` file
- Add `ConvertStringToKebabcase.java` file in `convert-string-to-kebabcase` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign
