### ISSUE TITLE
Write a Kotlin program to convert string to kebabcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2461]
### Description

Write a Kotlin program to convert string to kebabcase

Kebabcase is a style of writing in which all letters are lowercase and spaces are replaced with hyphens.

```
Input  : "hello world"
Output : "hello-world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToKebabcase.kt` file
- Add `ConvertStringToKebabcase.kt` file in `convert-string-to-kebabcase` folder

</details>

**Comment by rahmat-st** [comment]
!assign
