### ISSUE TITLE
Write a Python program to convert string to kebabcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2464]
### Description

Write a Python program to convert string to kebabcase

Kebabcase is a style of writing in which all letters are lowercase and spaces are replaced with hyphens.

```
Input  : "hello world"
Output : "hello-world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-string-to-kebabcase.py` file
- Add `convert-string-to-kebabcase.py` file in `convert-string-to-kebabcase` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign
