### ISSUE TITLE
Write a Ruby program to convert string to kebabcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2466]
### Description

Write a Ruby program to convert string to kebabcase

Kebabcase is a style of writing in which all letters are lowercase and spaces are replaced with hyphens.

```
Input  : "hello world"
Output : "hello-world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToKebabcase.rb` file
- Add `ConvertStringToKebabcase.rb` file in `convert-string-to-kebabcase` folder

</details>

**Comment by jfinley6** [comment]
!assign
