### ISSUE TITLE
Write a Rust program to convert string to kebabcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2467]
### Description

Write a Rust program to convert string to kebabcase

Kebabcase is a style of writing in which all letters are lowercase and spaces are replaced with hyphens.

```
Input  : "hello world"
Output : "hello-world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_string_to_kebabcase.rs` file
- Add `convert_string_to_kebabcase.rs` file in `convert-string-to-kebabcase` folder

</details>

**Comment by rahmat-st** [comment]
!assign
