### ISSUE TITLE
Write a TypeScript program to convert string to kebabcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2470]
### Description

Write a TypeScript program to convert string to kebabcase

Kebabcase is a style of writing in which all letters are lowercase and spaces are replaced with hyphens.

```
Input  : "hello world"
Output : "hello-world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToKebabcase.ts` file
- Add `ConvertStringToKebabcase.ts` file in `convert-string-to-kebabcase` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
