### ISSUE TITLE
Write a C++ program to convert a string to an integer (without using built-in functions)

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2484]
### Description

Write a C++ program to convert a string to an integer (without using built-in functions)

```
Input  : "123"
Output : 123
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertAStringToAnInteger(withoutUsingBuilt-inFunctions).cpp` file
- Add `ConvertAStringToAnInteger(withoutUsingBuilt-inFunctions).cpp` file in `convert-a-string-to-an-integer-(without-using-built-in-functions)` folder

</details>

**Comment by codingkush** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @codingkush,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Yarnacle** [comment]
!assign
