### ISSUE TITLE
Write a JavaScript program to convert a string to an integer (without using built-in functions)

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2490]
### Description

Write a JavaScript program to convert a string to an integer (without using built-in functions)

```
Input  : "123"
Output : 123
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertAStringToAnInteger(withoutUsingBuilt-inFunctions).js` file
- Add `ConvertAStringToAnInteger(withoutUsingBuilt-inFunctions).js` file in `convert-a-string-to-an-integer-(without-using-built-in-functions)` folder

</details>

**Comment by victoriacheng15** [comment]
!assign
