### ISSUE TITLE
Write a Python program to convert a string to an integer (without using built-in functions)

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2495]
### Description

Write a Python program to convert a string to an integer (without using built-in functions)

```
Input  : "123"
Output : 123
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-a-string-to-an-integer-(without-using-built-in-functions).py` file
- Add `convert-a-string-to-an-integer-(without-using-built-in-functions).py` file in `convert-a-string-to-an-integer-(without-using-built-in-functions)` folder

</details>

**Comment by smitioswal** [comment]
!assign
