### ISSUE TITLE
Write a C program to convert string to titlecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2507]
### Description

Write a C program to convert string to titlecase

Titlecase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "Hello World"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToTitlecase.c` file
- Add `ConvertStringToTitlecase.c` file in `convert-string-to-titlecase` folder

</details>

**Comment by codingkush** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @codingkush,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
