### ISSUE TITLE
Write a C# program to convert string to titlecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2508]
### Description

Write a C# program to convert string to titlecase

Titlecase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "Hello World"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToTitlecase.cs` file
- Add `ConvertStringToTitlecase.cs` file in `convert-string-to-titlecase` folder

</details>

**Comment by royninja** [comment]
will be this be a simple console input and console output in the given format?

**Comment by royninja** [comment]
can you assign this issue to me?

**Comment by royninja** [comment]
!assign
