### ISSUE TITLE
Write a Java program to convert string to titlecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2514]
### Description

Write a Java program to convert string to titlecase

Titlecase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "Hello World"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToTitlecase.java` file
- Add `ConvertStringToTitlecase.java` file in `convert-string-to-titlecase` folder

</details>

**Comment by codingkush** [comment]
!assign

**Comment by rksp25** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @rksp25, this issue is already assigned to @codingkush !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Hey @rksp25 

Sorry for the inconvenience, you can contribute to this issue

All assignments older than 20 days will be removed soon

**Comment by harshraj8843** [comment]
Hey @rksp25,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by NEOCLOUD0** [comment]
!assign
