### ISSUE TITLE
Write a JavaScript program to convert string to titlecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2515]
### Description

Write a JavaScript program to convert string to titlecase

Titlecase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "Hello World"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToTitlecase.js` file
- Add `ConvertStringToTitlecase.js` file in `convert-string-to-titlecase` folder

</details>

**Comment by kshitijv256** [comment]
!assign
