### ISSUE TITLE
Write a Julia program to convert string to titlecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2516]
### Description

Write a Julia program to convert string to titlecase

Titlecase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "Hello World"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-string-to-titlecase.jl` file
- Add `convert-string-to-titlecase.jl` file in `convert-string-to-titlecase` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
