### ISSUE TITLE
Write a Kotlin program to convert string to titlecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2517]
### Description

Write a Kotlin program to convert string to titlecase

Titlecase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "Hello World"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToTitlecase.kt` file
- Add `ConvertStringToTitlecase.kt` file in `convert-string-to-titlecase` folder

</details>

**Comment by rahmat-st** [comment]
!assign
