### ISSUE TITLE
Write a PHP program to convert string to titlecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2519]
### Description

Write a PHP program to convert string to titlecase

Titlecase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "Hello World"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_string_to_titlecase.php` file
- Add `convert_string_to_titlecase.php` file in `convert-string-to-titlecase` folder

</details>

**Comment by rahmat-st** [comment]
!assign
