### ISSUE TITLE
Write a Python program to convert string to titlecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2520]
### Description

Write a Python program to convert string to titlecase

Titlecase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "Hello World"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-string-to-titlecase.py` file
- Add `convert-string-to-titlecase.py` file in `convert-string-to-titlecase` folder

</details>

**Comment by grraghav120** [comment]
!assign

**Comment by kshitijv256** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @kshitijv256, this issue is already assigned to @grraghav120 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
