### ISSUE TITLE
Write a Ruby program to convert string to titlecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2522]
### Description

Write a Ruby program to convert string to titlecase

Titlecase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "Hello World"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToTitlecase.rb` file
- Add `ConvertStringToTitlecase.rb` file in `convert-string-to-titlecase` folder

</details>

**Comment by rafaover** [comment]
!assign
