### ISSUE TITLE
Write a C program to split string into array of characters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2536]
### Description

Write a C program to split string into array of characters

```
Input  : "hello world"
Output : ["h", "e", "l", "l", "o", " ", "w", "o", "r", "l", "d"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/SplitStringIntoArrayOfCharacters.c` file
- Add `SplitStringIntoArrayOfCharacters.c` file in `split-string-into-array-of-characters` folder

</details>

**Comment by PravunathSingh** [comment]
!assign
