### ISSUE TITLE
Write a C++ program to split string into array of characters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2538]
### Description

Write a C++ program to split string into array of characters

```
Input  : "hello world"
Output : ["h", "e", "l", "l", "o", " ", "w", "o", "r", "l", "d"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/SplitStringIntoArrayOfCharacters.cpp` file
- Add `SplitStringIntoArrayOfCharacters.cpp` file in `split-string-into-array-of-characters` folder

</details>

**Comment by Sivam2313** [comment]
!assign
