### ISSUE TITLE
Write a Haskell program to split string into array of characters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2542]
### Description

Write a Haskell program to split string into array of characters

```
Input  : "hello world"
Output : ["h", "e", "l", "l", "o", " ", "w", "o", "r", "l", "d"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/split_string_into_array_of_characters.hs` file
- Add `split_string_into_array_of_characters.hs` file in `split-string-into-array-of-characters` folder

</details>

**Comment by anafvana** [comment]
!assign
