### ISSUE TITLE
Write a Java program to split string into array of characters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2543]
### Description

Write a Java program to split string into array of characters

```
Input  : "hello world"
Output : ["h", "e", "l", "l", "o", " ", "w", "o", "r", "l", "d"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/SplitStringIntoArrayOfCharacters.java` file
- Add `SplitStringIntoArrayOfCharacters.java` file in `split-string-into-array-of-characters` folder

</details>

**Comment by mhdsabah** [comment]
!assign
