### ISSUE TITLE
Write a JavaScript program to split string into array of characters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2544]
### Description

Write a JavaScript program to split string into array of characters

```
Input  : "hello world"
Output : ["h", "e", "l", "l", "o", " ", "w", "o", "r", "l", "d"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/SplitStringIntoArrayOfCharacters.js` file
- Add `SplitStringIntoArrayOfCharacters.js` file in `split-string-into-array-of-characters` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
