### ISSUE TITLE
Write a Python program to split string into array of characters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2549]
### Description

Write a Python program to split string into array of characters

```
Input  : "hello world"
Output : ["h", "e", "l", "l", "o", " ", "w", "o", "r", "l", "d"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/split-string-into-array-of-characters.py` file
- Add `split-string-into-array-of-characters.py` file in `split-string-into-array-of-characters` folder

</details>

**Comment by Vignesh-dev07** [comment]
!assign
