### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by PravunathSingh** [codinasion/program#2558]
### Description

Binary search is a search algorithm that finds the position of a target value within a sorted array. Binary search compares the target value to the middle element of the array. If they are not equal, the half in which the target cannot lie is eliminated and the search continues on the remaining half, again taking the middle element to compare to the target value, and repeating this until the target value is found. If the search ends with the remaining half being empty, the target is not in the array.

```bash
Input  : 10 20 30 40 50 60 70 80 90 100
Target : 30

Output : 2
```

### Steps to implement Binary Search

1. Compare x with the middle element.
2. If x matches with middle element, we return the mid index.
3. Else If x is greater than the mid element, then x can only lie in right half subarray after the mid element. So we recur for right half.
4. Else (x is smaller) recur for the left half.
5. End

```text
10 20 30 40 50 60 70 80 90 100
------------------------------
            ^
            30 => Not Found
```

```text
10 20 30 40 50 60 70 80 90 100
--------------
      ^
      30 => Found
```

**Comment by PravunathSingh** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @PravunathSingh, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by PravunathSingh** [comment]
Hey @harshraj8843 can I add a `good first issue` label for this?

**Comment by harshraj8843** [comment]
Hey @PravunathSingh 

The workflow for adding a new dsa program is as follows :

- You created this issue
- This issues will be accepted by a team member by adding `submit-dsa` label
- This issue will be added to dsa list https://github.com/codinasion/program/blob/master/data/dsa.json
- New dsa issues will be created autometically

**Comment by harshraj8843** [comment]
DSA Program added successfully :tada:

Thanks for your contribution :hugs:
