### ISSUE TITLE
Program to check if object is present in a given array

### ISSUE THREAD

**Issue by PravunathSingh** [codinasion/program#2560]
### Description

A Javascript program to check if an object with a given (key, value) pair is present in a given array or not.

**Comment by shailendrakanherkar18** [comment]
@PravunathSingh Given array would be arrayOfObjects / Strings
It would be helpful if you can add sample i/p and o/p

**Comment by harshraj8843** [comment]
The given condition is for Linear Search (#2199) or Binary Search (#2561)
