### ISSUE TITLE
Write a JavaScript program to find area of a cuboid

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2594]
### Description

Write a JavaScript program to find area of a cuboid

Area of cuboid = 2 × (`Length` × `Width` + `Length` × `Height` + `Width` × `Height`)

```
Length : 2
Width  : 3
Height : 4

Area : 52
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAreaOfACuboid.js` file
- Add `FindAreaOfACuboid.js` file in `find-area-of-a-cuboid` folder

</details>

**Comment by vedha-vikash-pixel** [comment]
!assign
