### ISSUE TITLE
Write a PHP program to find area of a cuboid

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2598]
### Description

Write a PHP program to find area of a cuboid

Area of cuboid = 2 × (`Length` × `Width` + `Length` × `Height` + `Width` × `Height`)

```
Length : 2
Width  : 3
Height : 4

Area : 52
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_area_of_a_cuboid.php` file
- Add `find_area_of_a_cuboid.php` file in `find-area-of-a-cuboid` folder

</details>

**Comment by rahmat-st** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @rahmat-dev,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
