### ISSUE TITLE
Write a R program to find area of a cuboid

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2600]
### Description

Write a R program to find area of a cuboid

Area of cuboid = 2 × (`Length` × `Width` + `Length` × `Height` + `Width` × `Height`)

```
Length : 2
Width  : 3
Height : 4

Area : 52
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_area_of_a_cuboid.r` file
- Add `find_area_of_a_cuboid.r` file in `find-area-of-a-cuboid` folder

</details>

**Comment by esivakumar18** [comment]
!assign
