### ISSUE TITLE
Write a TypeScript program to print number to words

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2633]
### Description

Write a TypeScript program to print number to words

```
Input  : 123456789
Output : One Hundred Twenty Three Million Four Hundred Fifty Six Thousand Seven Hundred Eighty Nine
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintNumberToWords.ts` file
- Add `PrintNumberToWords.ts` file in `print-number-to-words` folder

</details>

**Comment by victoriacheng15** [comment]
!assign

**Comment by surajrane42** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @surajrane42,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Ariel201711** [comment]
!assign
