### ISSUE TITLE
Write a Haskell program to convert hours to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2645]
### Description

Write a Haskell program to convert hours to days

1 day = 24 hours

```
Input  : 120
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_hours_to_days.hs` file
- Add `convert_hours_to_days.hs` file in `convert-hours-to-days` folder

</details>

**Comment by jason0kenyon** [comment]
Hey there, I would like to do this. Can I submit a PR?

**Comment by victoriacheng15** [comment]
@jason0kenyon 

Please type `!assign` here!

Thank you!

**Comment by harshraj8843** [comment]
Hey @jason0kenyon 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by jason0kenyon** [comment]
!assign
