### ISSUE TITLE
Write a Java program to convert hours to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2646]
### Description

Write a Java program to convert hours to days

1 day = 24 hours

```
Input  : 120
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertHoursToDays.java` file
- Add `ConvertHoursToDays.java` file in `convert-hours-to-days` folder

</details>

**Comment by binayshaw7777** [comment]
I would like to work on this issue

**Comment by kshitijv256** [comment]
!assign

**Comment by kshitijv256** [comment]
Completed the task https://github.com/codinasion/program/pull/2733 Please review and merge it
