### ISSUE TITLE
Write a JavaScript program to convert hours to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2647]
### Description

Write a JavaScript program to convert hours to days

1 day = 24 hours

```
Input  : 120
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertHoursToDays.js` file
- Add `ConvertHoursToDays.js` file in `convert-hours-to-days` folder

</details>

**Comment by victoriacheng15** [comment]
!assign
