### ISSUE TITLE
Write a Julia program to convert hours to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2648]
### Description

Write a Julia program to convert hours to days

1 day = 24 hours

```
Input  : 120
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-hours-to-days.jl` file
- Add `convert-hours-to-days.jl` file in `convert-hours-to-days` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
