### ISSUE TITLE
Write a Kotlin program to convert hours to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2649]
### Description

Write a Kotlin program to convert hours to days

1 day = 24 hours

```
Input  : 120
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertHoursToDays.kt` file
- Add `ConvertHoursToDays.kt` file in `convert-hours-to-days` folder

</details>

**Comment by rahmat-st** [comment]
!assign

**Comment by rksp25** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @rksp25, this issue is already assigned to @rahmat-st !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by rksp25** [comment]
working on this
