### ISSUE TITLE
Write a PHP program to convert hours to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2651]
### Description

Write a PHP program to convert hours to days

1 day = 24 hours

```
Input  : 120
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_hours_to_days.php` file
- Add `convert_hours_to_days.php` file in `convert-hours-to-days` folder

</details>

**Comment by rahmat-st** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @rahmat-dev,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
