### ISSUE TITLE
Write a Python program to convert hours to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2652]
### Description

Write a Python program to convert hours to days

1 day = 24 hours

```
Input  : 120
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-hours-to-days.py` file
- Add `convert-hours-to-days.py` file in `convert-hours-to-days` folder

</details>

**Comment by Frey0-0** [comment]
I would like to do this issue as well. Can you please assign this as well?

**Comment by victoriacheng15** [comment]
@Frey0-0 Please type `!assign` on this issue and check out the [readme](https://github.com/codinasion/program/blob/master/README.md)

**Comment by kshitijv256** [comment]
!assign

**Comment by kshitijv256** [comment]
Completed the task #2852 Please review and merge it
