### ISSUE TITLE
Write a Ruby program to convert hours to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2654]
### Description

Write a Ruby program to convert hours to days

1 day = 24 hours

```
Input  : 120
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertHoursToDays.rb` file
- Add `ConvertHoursToDays.rb` file in `convert-hours-to-days` folder

</details>

**Comment by vjain98** [comment]
!assign
