### ISSUE TITLE
Write a Scala program to convert hours to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2656]
### Description

Write a Scala program to convert hours to days

1 day = 24 hours

```
Input  : 120
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convertHoursToDays.scala` file
- Add `convertHoursToDays.scala` file in `convert-hours-to-days` folder

</details>

**Comment by esivakumar18** [comment]
!assign
