### ISSUE TITLE
Write a TypeScript program to convert hours to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2658]
### Description

Write a TypeScript program to convert hours to days

1 day = 24 hours

```
Input  : 120
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertHoursToDays.ts` file
- Add `ConvertHoursToDays.ts` file in `convert-hours-to-days` folder

</details>

**Comment by Frey0-0** [comment]
I would like to work on this issue. Can you please assign to me?

**Comment by victoriacheng15** [comment]
@Frey0-0 

Please, type `!assign`

**Comment by Frey0-0** [comment]
!assign

**Comment by Frey0-0** [comment]
I also had a request could you please add the label "hacktoberfest" to this issue. @victoriacheng15 @harshraj8843

**Comment by victoriacheng15** [comment]
> I also had a request could you please add the label "hacktoberfest" to this issue. @victoriacheng15 @harshraj8843

The `hacktoberfest` will be added after your PR gets merge

**Comment by Frey0-0** [comment]
I have made a PR against this issue.
