### ISSUE TITLE
Write a Java program to calculate the combination of n objects taken r at a time

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2667]
### Description

Write a Java program to calculate the combination of n objects taken r at a time

Combination is a selection of objects from a group such that (unlike permutations) the order of selection does not matter. The number of combinations on n objects taken r at a time is given by the formula n!/(r!(n-r)!) = n(n-1)(n-2)...(n-r+1)/r!

```
Input  : 5, 2
Output : 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CalculateTheCombinationOfNObjectsTakenRAtATime.java` file
- Add `CalculateTheCombinationOfNObjectsTakenRAtATime.java` file in `calculate-the-combination-of-n-objects-taken-r-at-a-time` folder

</details>

**Comment by kshitijv256** [comment]
!assign

**Comment by kshitijv256** [comment]
Completed the task #2856 Please review and merge it
