### ISSUE TITLE
Write a JavaScript program to calculate the combination of n objects taken r at a time

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2668]
### Description

Write a JavaScript program to calculate the combination of n objects taken r at a time

Combination is a selection of objects from a group such that (unlike permutations) the order of selection does not matter. The number of combinations on n objects taken r at a time is given by the formula n!/(r!(n-r)!) = n(n-1)(n-2)...(n-r+1)/r!

```
Input  : 5, 2
Output : 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CalculateTheCombinationOfNObjectsTakenRAtATime.js` file
- Add `CalculateTheCombinationOfNObjectsTakenRAtATime.js` file in `calculate-the-combination-of-n-objects-taken-r-at-a-time` folder

</details>

**Comment by Larryking007** [comment]
!assign
