### ISSUE TITLE
Write a C program to convert string to lowercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2684]
### Description

Write a C program to convert string to lowercase

```
Input  : "Hello World"
Output : "hello world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToLowercase.c` file
- Add `ConvertStringToLowercase.c` file in `convert-string-to-lowercase` folder

</details>

**Comment by manyadua16** [comment]
!assign

**Comment by manyadua16** [comment]
I have added the program do review it and then merge it
