### ISSUE TITLE
Write a C++ program to convert string to lowercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2686]
### Description

Write a C++ program to convert string to lowercase

```
Input  : "Hello World"
Output : "hello world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToLowercase.cpp` file
- Add `ConvertStringToLowercase.cpp` file in `convert-string-to-lowercase` folder

</details>

**Comment by grraghav120** [comment]
!assign
