### ISSUE TITLE
Write a Dart program to convert string to lowercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2687]
### Description

Write a Dart program to convert string to lowercase

```
Input  : "Hello World"
Output : "hello world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_string_to_lowercase.dart` file
- Add `convert_string_to_lowercase.dart` file in `convert-string-to-lowercase` folder

</details>

**Comment by kshitijv256** [comment]
!assign

**Comment by kshitijv256** [comment]
Completed the task #2859 

Please review and merge it
