### ISSUE TITLE
Write a GO program to convert string to lowercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2689]
### Description

Write a GO program to convert string to lowercase

```
Input  : "Hello World"
Output : "hello world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_string_to_lowercase.go` file
- Add `convert_string_to_lowercase.go` file in `convert-string-to-lowercase` folder

</details>

**Comment by thiago5171** [comment]
!assigned

**Comment by thiago5171** [comment]
!assigned

**Comment by harshraj8843** [comment]
Hey @thiago5171, this issue is already assigned to @thiago5171 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Hey @thiago5171,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by sancoLgates** [comment]
!assign
