### ISSUE TITLE
Write a Java program to convert string to lowercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2691]
### Description

Write a Java program to convert string to lowercase

```
Input  : "Hello World"
Output : "hello world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToLowercase.java` file
- Add `ConvertStringToLowercase.java` file in `convert-string-to-lowercase` folder

</details>

**Comment by binayshaw7777** [comment]
I would like to work on this issue!

**Comment by Mikasa-Ackerman2074** [comment]
!assign

**Comment by ofirtzabari** [comment]
!assign
