### ISSUE TITLE
Write a Julia program to convert string to lowercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2693]
### Description

Write a Julia program to convert string to lowercase

```
Input  : "Hello World"
Output : "hello world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-string-to-lowercase.jl` file
- Add `convert-string-to-lowercase.jl` file in `convert-string-to-lowercase` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
