### ISSUE TITLE
Write a Kotlin program to convert string to lowercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2694]
### Description

Write a Kotlin program to convert string to lowercase

```
Input  : "Hello World"
Output : "hello world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToLowercase.kt` file
- Add `ConvertStringToLowercase.kt` file in `convert-string-to-lowercase` folder

</details>

**Comment by rahmat-st** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @rksp25, this issue is already assigned to @rahmat-st !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by rksp25** [comment]
working
