### ISSUE TITLE
Write a Python program to convert string to lowercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2697]
### Description

Write a Python program to convert string to lowercase

```
Input  : "Hello World"
Output : "hello world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-string-to-lowercase.py` file
- Add `convert-string-to-lowercase.py` file in `convert-string-to-lowercase` folder

</details>

**Comment by grraghav120** [comment]
!assign
