### ISSUE TITLE
Write a Swift program to convert string to lowercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2702]
### Description

Write a Swift program to convert string to lowercase

```
Input  : "Hello World"
Output : "hello world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToLowercase.swift` file
- Add `ConvertStringToLowercase.swift` file in `convert-string-to-lowercase` folder

</details>

**Comment by esivakumar18** [comment]
!assign
