### ISSUE TITLE
Write a TypeScript program to convert string to lowercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2703]
### Description

Write a TypeScript program to convert string to lowercase

```
Input  : "Hello World"
Output : "hello world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToLowercase.ts` file
- Add `ConvertStringToLowercase.ts` file in `convert-string-to-lowercase` folder

</details>

**Comment by victoriacheng15** [comment]
!assign
