### ISSUE TITLE
Write a Java program to print numbers from n to 1

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2718]
### Description

Write a Java program to print numbers from n to 1

```
Input  : 5
Output : 5 4 3 2 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintNumbersFromNTo1.java` file
- Add `PrintNumbersFromNTo1.java` file in `print-numbers-from-n-to-1` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign
