### ISSUE TITLE
Write a JavaScript program to print numbers from n to 1

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2719]
### Description

Write a JavaScript program to print numbers from n to 1

```
Input  : 5
Output : 5 4 3 2 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintNumbersFromNTo1.js` file
- Add `PrintNumbersFromNTo1.js` file in `print-numbers-from-n-to-1` folder

</details>

**Comment by PaxtonDevs** [comment]
Hello, I have sent a PR for this issue.

**Comment by TechnicalAmanjeet** [comment]
!assign
