### ISSUE TITLE
Write a Python program to print numbers from n to 1

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2724]
### Description

Write a Python program to print numbers from n to 1

```
Input  : 5
Output : 5 4 3 2 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/print-numbers-from-n-to-1.py` file
- Add `print-numbers-from-n-to-1.py` file in `print-numbers-from-n-to-1` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign

**Comment by QCind29** [comment]
I can do that, assign me, pls!
