### ISSUE TITLE
Write a R program to print numbers from n to 1

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2725]
### Description

Write a R program to print numbers from n to 1

```
Input  : 5
Output : 5 4 3 2 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/print_numbers_from_n_to_1.r` file
- Add `print_numbers_from_n_to_1.r` file in `print-numbers-from-n-to-1` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign
