### ISSUE TITLE
Write a Scala program to print numbers from n to 1

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2728]
### Description

Write a Scala program to print numbers from n to 1

```
Input  : 5
Output : 5 4 3 2 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/printNumbersFromNTo1.scala` file
- Add `printNumbersFromNTo1.scala` file in `print-numbers-from-n-to-1` folder

</details>

**Comment by TechnicalAmanjeet** [comment]
!assign
