### ISSUE TITLE
Write a C program to convert string to pathcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2745]
### Description

Write a C program to convert string to pathcase

Pathcase is a style of writing in which all letters are lowercase and spaces are replaced with forward slashes.

```
Input  : "hello world"
Output : "hello/world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToPathcase.c` file
- Add `ConvertStringToPathcase.c` file in `convert-string-to-pathcase` folder

</details>

**Comment by harshraj8843** [comment]
Hey @Nitya-Pasrija,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Osher160** [comment]
!assign
