### ISSUE TITLE
Write a Java program to convert string to pathcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2752]
### Description

Write a Java program to convert string to pathcase

Pathcase is a style of writing in which all letters are lowercase and spaces are replaced with forward slashes.

```
Input  : "hello world"
Output : "hello/world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToPathcase.java` file
- Add `ConvertStringToPathcase.java` file in `convert-string-to-pathcase` folder

</details>

**Comment by Nitya-Pasrija** [comment]
!assign
