### ISSUE TITLE
Write a JavaScript program to convert string to pathcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2753]
### Description

Write a JavaScript program to convert string to pathcase

Pathcase is a style of writing in which all letters are lowercase and spaces are replaced with forward slashes.

```
Input  : "hello world"
Output : "hello/world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToPathcase.js` file
- Add `ConvertStringToPathcase.js` file in `convert-string-to-pathcase` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
