### ISSUE TITLE
Write a Julia program to convert string to pathcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2754]
### Description

Write a Julia program to convert string to pathcase

Pathcase is a style of writing in which all letters are lowercase and spaces are replaced with forward slashes.

```
Input  : "hello world"
Output : "hello/world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-string-to-pathcase.jl` file
- Add `convert-string-to-pathcase.jl` file in `convert-string-to-pathcase` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
