### ISSUE TITLE
Write a C# program to find volume of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2791]
### Description

Write a C# program to find volume of a cube

Volume of cube = `Side`^3

```
Side : 2

Volume : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindVolumeOfACube.cs` file
- Add `FindVolumeOfACube.cs` file in `find-volume-of-a-cube` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign

**Comment by harshraj8843** [comment]
Duplicate of #63
