### ISSUE TITLE
Write a C++ program to find volume of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2793]
### Description

Write a C++ program to find volume of a cube

Volume of cube = `Side`^3

```
Side : 2

Volume : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindVolumeOfACube.cpp` file
- Add `FindVolumeOfACube.cpp` file in `find-volume-of-a-cube` folder

</details>

**Comment by Ayushkanodia11** [comment]
!assign

**Comment by manyadua16** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @manyadua16, this issue is already assigned to @Ayushkanodia11 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Duplicate of #63
