### ISSUE TITLE
Write a Java program to find volume of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2798]
### Description

Write a Java program to find volume of a cube

Volume of cube = `Side`^3

```
Side : 2

Volume : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindVolumeOfACube.java` file
- Add `FindVolumeOfACube.java` file in `find-volume-of-a-cube` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign

**Comment by manyadua16** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @manyadua16, this issue is already assigned to @CodingWithHardik !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by priya1011** [comment]
!assign
