### ISSUE TITLE
Write a C++ program to convert meters to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#280]
### Description

Write a C++ program to convert meters to miles

1 mile = 1609 meters

```
Input  : 8046.72
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMetersToMiles.cpp` file
- Add `ConvertMetersToMiles.cpp` file in `convert-meters-to-miles` folder

</details>

**Comment by akansharai2023** [comment]
!assign

**Comment by Osher160** [comment]
!assign
