### ISSUE TITLE
Write a Kotlin program to find volume of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2801]
### Description

Write a Kotlin program to find volume of a cube

Volume of cube = `Side`^3

```
Side : 2

Volume : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindVolumeOfACube.kt` file
- Add `FindVolumeOfACube.kt` file in `find-volume-of-a-cube` folder

</details>

**Comment by Tc2r1** [comment]
!assign I'd like to work on this one.
