### ISSUE TITLE
Write a PHP program to find volume of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2803]
### Description

Write a PHP program to find volume of a cube

Volume of cube = `Side`^3

```
Side : 2

Volume : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_volume_of_a_cube.php` file
- Add `find_volume_of_a_cube.php` file in `find-volume-of-a-cube` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign

**Comment by manyadua16** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @manyadua16, this issue is already assigned to @CodingWithHardik !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Duplicate of #63
