### ISSUE TITLE
Write a Ruby program to find volume of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2807]
### Description

Write a Ruby program to find volume of a cube

Volume of cube = `Side`^3

```
Side : 2

Volume : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindVolumeOfACube.rb` file
- Add `FindVolumeOfACube.rb` file in `find-volume-of-a-cube` folder

</details>

**Comment by horerick46** [comment]
please assign it to me

**Comment by horerick46** [comment]
is this under hacktober fest 2022 ????

**Comment by CodingWithHardik** [comment]
> is this under hacktober fest 2022 ????

yes and I am already assigned with this issue

**Comment by harshraj8843** [comment]
Hey @horerick46 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

**Comment by harshraj8843** [comment]
> is this under hacktober fest 2022 ????

Yes 🥳 

![Screenshot from 2022-10-10 17-27-53](https://user-images.githubusercontent.com/54644599/194861750-d2662fab-0c20-43c4-9947-2a51caed09f2.png)

**Comment by CodingWithHardik** [comment]
> ou can comment `!assign` on any `good first is`

WAITING [02:05:52:20] :-:

**Comment by harshraj8843** [comment]
Duplicate of #63
