### ISSUE TITLE
Write a Rust program to find volume of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2808]
### Description

Write a Rust program to find volume of a cube

Volume of cube = `Side`^3

```
Side : 2

Volume : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_volume_of_a_cube.rs` file
- Add `find_volume_of_a_cube.rs` file in `find-volume-of-a-cube` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign

**Comment by harshraj8843** [comment]
Duplicate of #63
