### ISSUE TITLE
Write a TypeScript program to find volume of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2811]
### Description

Write a TypeScript program to find volume of a cube

Volume of cube = `Side`^3

```
Side : 2

Volume : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindVolumeOfACube.ts` file
- Add `FindVolumeOfACube.ts` file in `find-volume-of-a-cube` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign

**Comment by tanishq-singh-2301** [comment]
!assign
