### ISSUE TITLE
Write a C program to find sum of n natural numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2823]
### Description

Write a C program to find sum of n natural numbers by recursion

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSumOfNNaturalNumbersByRecursion.c` file
- Add `FindSumOfNNaturalNumbersByRecursion.c` file in `find-sum-of-n-natural-numbers-by-recursion` folder

</details>

**Comment by PravunathSingh** [comment]
!assign
