### ISSUE TITLE
Write a GO program to find sum of n natural numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2828]
### Description

Write a GO program to find sum of n natural numbers by recursion

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_sum_of_n_natural_numbers_by_recursion.go` file
- Add `find_sum_of_n_natural_numbers_by_recursion.go` file in `find-sum-of-n-natural-numbers-by-recursion` folder

</details>

**Comment by gdguesser** [comment]
!assign
