### ISSUE TITLE
Write a GO program to convert meters to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#283]
### Description

Write a GO program to convert meters to miles

1 mile = 1609 meters

```
Input  : 8046.72
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_meters_to_miles.go` file
- Add `convert_meters_to_miles.go` file in `convert-meters-to-miles` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign
