### ISSUE TITLE
Write a Java program to find sum of n natural numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2830]
### Description

Write a Java program to find sum of n natural numbers by recursion

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSumOfNNaturalNumbersByRecursion.java` file
- Add `FindSumOfNNaturalNumbersByRecursion.java` file in `find-sum-of-n-natural-numbers-by-recursion` folder

</details>

**Comment by sksachin7z2** [comment]
!assign
