### ISSUE TITLE
Write a Kotlin program to find sum of n natural numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2833]
### Description

Write a Kotlin program to find sum of n natural numbers by recursion

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSumOfNNaturalNumbersByRecursion.kt` file
- Add `FindSumOfNNaturalNumbersByRecursion.kt` file in `find-sum-of-n-natural-numbers-by-recursion` folder

</details>

**Comment by aritra-tech** [comment]
!assign

**Comment by rksp25** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @rksp25, this issue is already assigned to @aritra-tech !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
