### ISSUE TITLE
Write a PHP program to find sum of n natural numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2835]
### Description

Write a PHP program to find sum of n natural numbers by recursion

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_sum_of_n_natural_numbers_by_recursion.php` file
- Add `find_sum_of_n_natural_numbers_by_recursion.php` file in `find-sum-of-n-natural-numbers-by-recursion` folder

</details>

**Comment by sksachin7z2** [comment]
!assign
