### ISSUE TITLE
Write a Python program to find sum of n natural numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2836]
### Description

Write a Python program to find sum of n natural numbers by recursion

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-sum-of-n-natural-numbers-by-recursion.py` file
- Add `find-sum-of-n-natural-numbers-by-recursion.py` file in `find-sum-of-n-natural-numbers-by-recursion` folder

</details>

**Comment by darkbits018** [comment]
@harshraj8843 can i contribute to it ??

**Comment by darkbits018** [comment]
!assign
