### ISSUE TITLE
Write a Java program to convert meters to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#284]
### Description

Write a Java program to convert meters to miles

1 mile = 1609 meters

```
Input  : 8046.72
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMetersToMiles.java` file
- Add `ConvertMetersToMiles.java` file in `convert-meters-to-miles` folder

</details>

**Comment by kangjung** [comment]
!assign
