### ISSUE TITLE
Write a TypeScript program to find sum of n natural numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2842]
### Description

Write a TypeScript program to find sum of n natural numbers by recursion

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSumOfNNaturalNumbersByRecursion.ts` file
- Add `FindSumOfNNaturalNumbersByRecursion.ts` file in `find-sum-of-n-natural-numbers-by-recursion` folder

</details>

**Comment by shailendrakanherkar18** [comment]
@harshraj8843 I am interested and started working on it.

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @shailendrakanherkar18 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```
