### ISSUE TITLE
Write a JavaScript program to convert meters to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#285]
### Description

Write a JavaScript program to convert meters to miles

1 mile = 1609 meters

```
Input  : 8046.72
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMetersToMiles.js` file
- Add `ConvertMetersToMiles.js` file in `convert-meters-to-miles` folder

</details>

**Comment by amitanshusahu** [comment]
i would like to contribute to that  @harshraj8843

**Comment by harshraj8843** [comment]
> i would like to contribute to that @harshraj8843

Hey @amitanshusahu 

Sorry, but @MusabMuhie already raise a PR for this. It will take some time to follow the workflow `get assigned` -> `raise PR`.

Please contribute to other `good first issue`

Thanks 🤗
