### ISSUE TITLE
Write a Julia program to convert meters to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#286]
### Description

Write a Julia program to convert meters to miles

1 mile = 1609 meters

```
Input  : 8046.72
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-meters-to-miles.jl` file
- Add `convert-meters-to-miles.jl` file in `convert-meters-to-miles` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
