### ISSUE TITLE
Write a JavaScript program to find gcd of two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2869]
### Description

Write a JavaScript program to find gcd of two numbers

GCD (Greatest Common Divisor) of two numbers is the largest number that divides both of them. A simple way to find GCD is to factorize both numbers and multiply common factors.

```
Input  : 12 18
Output : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindGcdOfTwoNumbers.js` file
- Add `FindGcdOfTwoNumbers.js` file in `find-gcd-of-two-numbers` folder

</details>

**Comment by sksachin7z2** [comment]
!assign
