### ISSUE TITLE
Write a Kotlin program to convert meters to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#287]
### Description

Write a Kotlin program to convert meters to miles

1 mile = 1609 meters

```
Input  : 8046.72
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMetersToMiles.kt` file
- Add `ConvertMetersToMiles.kt` file in `convert-meters-to-miles` folder

</details>

**Comment by ashankritwik07** [comment]
!assign

**Comment by rksp25** [comment]
!assign
