### ISSUE TITLE
Write a Ruby program to find gcd of two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2876]
### Description

Write a Ruby program to find gcd of two numbers

GCD (Greatest Common Divisor) of two numbers is the largest number that divides both of them. A simple way to find GCD is to factorize both numbers and multiply common factors.

```
Input  : 12 18
Output : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindGcdOfTwoNumbers.rb` file
- Add `FindGcdOfTwoNumbers.rb` file in `find-gcd-of-two-numbers` folder

</details>

**Comment by niranjan-patil** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @niranjan-patil,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by jfinley6** [comment]
!assign
