### ISSUE TITLE
Write a Rust program to find gcd of two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2877]
### Description

Write a Rust program to find gcd of two numbers

GCD (Greatest Common Divisor) of two numbers is the largest number that divides both of them. A simple way to find GCD is to factorize both numbers and multiply common factors.

```
Input  : 12 18
Output : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_gcd_of_two_numbers.rs` file
- Add `find_gcd_of_two_numbers.rs` file in `find-gcd-of-two-numbers` folder

</details>

**Comment by horerick46** [comment]
!assign

**Comment by horerick46** [comment]
@harshraj8843 please check the pull request just been updated and merge it under hacktober fest label sir.

**Comment by harshraj8843** [comment]
It will be merged soon, we are reviewing PRs on a Queue basis 

Thanks for contributing 👍🏻
