### ISSUE TITLE
Write a Scala program to find gcd of two numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2878]
### Description

Write a Scala program to find gcd of two numbers

GCD (Greatest Common Divisor) of two numbers is the largest number that divides both of them. A simple way to find GCD is to factorize both numbers and multiply common factors.

```
Input  : 12 18
Output : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/findGcdOfTwoNumbers.scala` file
- Add `findGcdOfTwoNumbers.scala` file in `find-gcd-of-two-numbers` folder

</details>

**Comment by esivakumar18** [comment]
!assign
