### ISSUE TITLE
Find smallest element in a matrix

### ISSUE THREAD

**Issue by ShubhraSuman** [codinasion/program#2882]
### Description

```
Input :
4 7 3
9 4 2
0 6 4

Output : 0
```

**Comment by ShubhraSuman** [comment]
can u assign it to me.

**Comment by harshraj8843** [comment]
Hey @ShubhraSuman 

you can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by harshraj8843** [comment]
> can u assign it to me.

This issue will be approved by a team member and the related issues will be auto created later

Thanks for contributing 👍🏻

**Comment by harshraj8843** [comment]
Program added successfully :tada:

Thanks for your contribution :hugs:
