### ISSUE TITLE
Write a PHP program to convert meters to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#289]
### Description

Write a PHP program to convert meters to miles

1 mile = 1609 meters

```
Input  : 8046.72
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_meters_to_miles.php` file
- Add `convert_meters_to_miles.php` file in `convert-meters-to-miles` folder

</details>

**Comment by Mahak008** [comment]
!assign
