### ISSUE TITLE
Write a Dart program to find largest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2898]
### Description

Write a Dart program to find largest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_largest_number_in_an_array.dart` file
- Add `find_largest_number_in_an_array.dart` file in `find-largest-number-in-an-array` folder

</details>

**Comment by Tushar12222** [comment]
!assign
