### ISSUE TITLE
Write a Java program to find largest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2902]
### Description

Write a Java program to find largest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindLargestNumberInAnArray.java` file
- Add `FindLargestNumberInAnArray.java` file in `find-largest-number-in-an-array` folder

</details>

**Comment by aritra-tech** [comment]
Can I work on this issue @harshraj8843

**Comment by Vignesh-dev07** [comment]
!assign

**Comment by aritra-tech** [comment]
@harshraj8843 I commented first so I will be assigned with the issue

**Comment by Vignesh-dev07** [comment]
Hey @aritra-tech when I checked it said no assignees so I assumed you unassigned yourslf. Sorry, i will unassign myslf

**Comment by aritra-tech** [comment]
> Hey @aritra-tech when I checked it said no assignees so I assumed you unassigned yourslf. Sorry, i will unassign myslf

@Vignesh-dev07 bro you are assigned so please you do it

**Comment by VIBER1** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @aritra-tech 

The auto-assignment is based on the comment `!assign` on `good first issue`

The github action automatically checks if a user has commented `!assign` and if that issue is assigned to no one, it auto-assigns the issue

---

### In your case 🤔 

You first commented

> Can I work on this issue @harshraj8843

Then you edited the same comment to 

> !assign

The github action doesn't' checks for the edited comments, that's why all this confusion happens

---

Sorry for the inconvenience caused 

Thanks for contributing to this project 👍🏻
