### ISSUE TITLE
Write a JavaScript program to find largest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2903]
### Description

Write a JavaScript program to find largest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindLargestNumberInAnArray.js` file
- Add `FindLargestNumberInAnArray.js` file in `find-largest-number-in-an-array` folder

</details>

**Comment by aldyadk** [comment]
!assign
