### ISSUE TITLE
Write a Python program to find largest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2908]
### Description

Write a Python program to find largest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-largest-number-in-an-array.py` file
- Add `find-largest-number-in-an-array.py` file in `find-largest-number-in-an-array` folder

</details>

**Comment by grraghav120** [comment]
!assign
