### ISSUE TITLE
Write a Ruby program to find largest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2910]
### Description

Write a Ruby program to find largest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindLargestNumberInAnArray.rb` file
- Add `FindLargestNumberInAnArray.rb` file in `find-largest-number-in-an-array` folder

</details>

**Comment by rafaover** [comment]
!assign
