### ISSUE TITLE
Write a TypeScript program to find largest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2914]
### Description

Write a TypeScript program to find largest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindLargestNumberInAnArray.ts` file
- Add `FindLargestNumberInAnArray.ts` file in `find-largest-number-in-an-array` folder

</details>

**Comment by victoriacheng15** [comment]
!assign
