### ISSUE TITLE
Write a Ruby program to convert meters to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#292]
### Description

Write a Ruby program to convert meters to miles

1 mile = 1609 meters

```
Input  : 8046.72
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMetersToMiles.rb` file
- Add `ConvertMetersToMiles.rb` file in `convert-meters-to-miles` folder

</details>

**Comment by sudiptog81** [comment]
!assign
