### ISSUE TITLE
Write a Rust program to convert meters to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#293]
### Description

Write a Rust program to convert meters to miles

1 mile = 1609 meters

```
Input  : 8046.72
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_meters_to_miles.rs` file
- Add `convert_meters_to_miles.rs` file in `convert-meters-to-miles` folder

</details>

**Comment by chinmaykumbhare** [comment]
hi @harshraj8843 , can you please assign this issue to me?

**Comment by harshraj8843** [comment]
Hey @chinmaykumbhare 

You can comment `!assign` on the issues you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by chinmaykumbhare** [comment]
!assign
