### ISSUE TITLE
Write a C program to check digit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2931]
### Description

Write a C program to check digit

Check wether given character is a digit (0-9).

```
Input  : 1
Output : Digit
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckDigit.c` file
- Add `CheckDigit.c` file in `check-digit` folder

</details>

**Comment by harshraj8843** [comment]
Hey @darkbits018,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Osher160** [comment]
!assign
