### ISSUE TITLE
Write a C# program to check digit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2932]
### Description

Write a C# program to check digit

Check wether given character is a digit (0-9).

```
Input  : 1
Output : Digit
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckDigit.cs` file
- Add `CheckDigit.cs` file in `check-digit` folder

</details>

**Comment by rsk2** [comment]
Hey @harshraj8843, can I work on this?

**Comment by rsk2** [comment]
!assign
