### ISSUE TITLE
Write a JavaScript program to check digit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2939]
### Description

Write a JavaScript program to check digit

Check wether given character is a digit (0-9).

```
Input  : 1
Output : Digit
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckDigit.js` file
- Add `CheckDigit.js` file in `check-digit` folder

</details>

**Comment by anastazir** [comment]
!assign

**Comment by Avicenne-b** [comment]
!assign

**Comment by sarahloher** [comment]
!assign
