### ISSUE TITLE
Write a Kotlin program to check digit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2941]
### Description

Write a Kotlin program to check digit

Check wether given character is a digit (0-9).

```
Input  : 1
Output : Digit
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckDigit.kt` file
- Add `CheckDigit.kt` file in `check-digit` folder

</details>

**Comment by rksp25** [comment]
!assign
