### ISSUE TITLE
Write a Python program to check digit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2944]
### Description

Write a Python program to check digit

Check wether given character is a digit (0-9).

```
Input  : 1
Output : Digit
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/check-digit.py` file
- Add `check-digit.py` file in `check-digit` folder

</details>

**Comment by marcleonschulz** [comment]
!assign

**Comment by joao-vitor-souza** [comment]
Already merged by #3140
