### ISSUE TITLE
Write a Ruby program to check digit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2946]
### Description

Write a Ruby program to check digit

Check wether given character is a digit (0-9).

```
Input  : 1
Output : Digit
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckDigit.rb` file
- Add `CheckDigit.rb` file in `check-digit` folder

</details>

**Comment by suryapoojary0** [comment]
I would like to contribute to this project!

**Comment by harshraj8843** [comment]
Hey @suryapoojary0 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```
