### ISSUE TITLE
Write a Swift program to convert meters to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#295]
### Description

Write a Swift program to convert meters to miles

1 mile = 1609 meters

```
Input  : 8046.72
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMetersToMiles.swift` file
- Add `ConvertMetersToMiles.swift` file in `convert-meters-to-miles` folder

</details>

**Comment by esivakumar18** [comment]
!assign
