### ISSUE TITLE
Write a TypeScript program to check digit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2950]
### Description

Write a TypeScript program to check digit

Check wether given character is a digit (0-9).

```
Input  : 1
Output : Digit
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckDigit.ts` file
- Add `CheckDigit.ts` file in `check-digit` folder

</details>

**Comment by Akhilbisht798** [comment]
Hey can i do this.

**Comment by CodingWithHardik** [comment]
!assign

**Comment by Akhilbisht798** [comment]
Hey, should i have to use !assign for issue I have been working.

**Comment by Akhilbisht798** [comment]
I will remember next time onward. Thank you for letting me know that.

**Comment by UrielOfir** [comment]
!assign
