### ISSUE TITLE
Write a TypeScript program to convert meters to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#296]
### Description

Write a TypeScript program to convert meters to miles

1 mile = 1609 meters

```
Input  : 8046.72
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMetersToMiles.ts` file
- Add `ConvertMetersToMiles.ts` file in `convert-meters-to-miles` folder

</details>

**Comment by madil89** [comment]
!assign
