### ISSUE TITLE
Write a C program to check special character

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2962]
### Description

Write a C program to check special character

Check if given character is a special character (not a letter or a number).

```
Input  : @
Output : Special Character
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckSpecialCharacter.c` file
- Add `CheckSpecialCharacter.c` file in `check-special-character` folder

</details>

**Comment by Suraj-Kumar-07** [comment]
!assign
