### ISSUE TITLE
Write a Java program to check special character

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2969]
### Description

Write a Java program to check special character

Check if given character is a special character (not a letter or a number).

```
Input  : @
Output : Special Character
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckSpecialCharacter.java` file
- Add `CheckSpecialCharacter.java` file in `check-special-character` folder

</details>

**Comment by suresh37** [comment]
!assign

**Comment by prajwalprogrammer** [comment]
Can I work on same issue

**Comment by prajwalprogrammer** [comment]
kindly check my PR:
https://github.com/codinasion/program/pull/3003
