### ISSUE TITLE
Write a JavaScript program to check special character

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2970]
### Description

Write a JavaScript program to check special character

Check if given character is a special character (not a letter or a number).

```
Input  : @
Output : Special Character
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckSpecialCharacter.js` file
- Add `CheckSpecialCharacter.js` file in `check-special-character` folder

</details>

**Comment by suresh37** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @suresh37,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by 0ME9A** [comment]
!assign

**Comment by 0ME9A** [comment]
Hey @harshraj8843 can I use regexp?

**Comment by harshraj8843** [comment]
Sure
