### ISSUE TITLE
Write a PHP program to check special character

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2974]
### Description

Write a PHP program to check special character

Check if given character is a special character (not a letter or a number).

```
Input  : @
Output : Special Character
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/check_special_character.php` file
- Add `check_special_character.php` file in `check-special-character` folder

</details>

**Comment by abrahamventura95** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @abrahamventura95,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
