### ISSUE TITLE
Write a Python program to check special character

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2975]
### Description

Write a Python program to check special character

Check if given character is a special character (not a letter or a number).

```
Input  : @
Output : Special Character
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/check-special-character.py` file
- Add `check-special-character.py` file in `check-special-character` folder

</details>

**Comment by Marsh-sudo** [comment]
Assign me this kindly

**Comment by ntoniocp** [comment]
@Marsh-sudo hey! you need to type exclamation assign so the bot can assign it to you. Check out the [CONTRIBUTING.MD](https://github.com/codinasion/program/blob/master/CONTRIBUTING.md)

**Comment by Marsh-sudo** [comment]
!assign
