### ISSUE TITLE
Write a Scala program to check special character

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2979]
### Description

Write a Scala program to check special character

Check if given character is a special character (not a letter or a number).

```
Input  : @
Output : Special Character
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/checkSpecialCharacter.scala` file
- Add `checkSpecialCharacter.scala` file in `check-special-character` folder

</details>

**Comment by esivakumar18** [comment]
!assign
