### ISSUE TITLE
Write a TypeScript program to check special character

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2981]
### Description

Write a TypeScript program to check special character

Check if given character is a special character (not a letter or a number).

```
Input  : @
Output : Special Character
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckSpecialCharacter.ts` file
- Add `CheckSpecialCharacter.ts` file in `check-special-character` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
