### ISSUE TITLE
Write a GO program to convert feet to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2992]
### Description

Write a GO program to convert feet to centimeters

1 foot = 30.48 centimeters

```
Input  : 5
Output : 152.4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_feet_to_centimeters.go` file
- Add `convert_feet_to_centimeters.go` file in `convert-feet-to-centimeters` folder

</details>

**Comment by ChiTr8or** [comment]
!assign
