### ISSUE TITLE
Write a JavaScript program to convert feet to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2995]
### Description

Write a JavaScript program to convert feet to centimeters

1 foot = 30.48 centimeters

```
Input  : 5
Output : 152.4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertFeetToCentimeters.js` file
- Add `ConvertFeetToCentimeters.js` file in `convert-feet-to-centimeters` folder

</details>

**Comment by DiamonndAde** [comment]
!assign
