### ISSUE TITLE
Write a Kotlin program to convert feet to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2997]
### Description

Write a Kotlin program to convert feet to centimeters

1 foot = 30.48 centimeters

```
Input  : 5
Output : 152.4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertFeetToCentimeters.kt` file
- Add `ConvertFeetToCentimeters.kt` file in `convert-feet-to-centimeters` folder

</details>

**Comment by rksp25** [comment]
!assign
