### ISSUE TITLE
Write a PHP program to convert feet to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#2999]
### Description

Write a PHP program to convert feet to centimeters

1 foot = 30.48 centimeters

```
Input  : 5
Output : 152.4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_feet_to_centimeters.php` file
- Add `convert_feet_to_centimeters.php` file in `convert-feet-to-centimeters` folder

</details>

**Comment by abrahamventura95** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @abrahamventura95,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
