### ISSUE TITLE
Write a Python program to convert feet to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3000]
### Description

Write a Python program to convert feet to centimeters

1 foot = 30.48 centimeters

```
Input  : 5
Output : 152.4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-feet-to-centimeters.py` file
- Add `convert-feet-to-centimeters.py` file in `convert-feet-to-centimeters` folder

</details>

**Comment by DiamonndAde** [comment]
!assign
