### ISSUE TITLE
Write a Scala program to convert feet to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3005]
### Description

Write a Scala program to convert feet to centimeters

1 foot = 30.48 centimeters

```
Input  : 5
Output : 152.4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convertFeetToCentimeters.scala` file
- Add `convertFeetToCentimeters.scala` file in `convert-feet-to-centimeters` folder

</details>

**Comment by esivakumar18** [comment]
!assign
