### ISSUE TITLE
Write a TypeScript program to convert feet to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3007]
### Description

Write a TypeScript program to convert feet to centimeters

1 foot = 30.48 centimeters

```
Input  : 5
Output : 152.4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertFeetToCentimeters.ts` file
- Add `ConvertFeetToCentimeters.ts` file in `convert-feet-to-centimeters` folder

</details>

**Comment by Larryking007** [comment]
!assign
