### ISSUE TITLE
Write a C program to find surface area of a sphere

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3009]
### Description

Write a C program to find surface area of a sphere

Surface area of sphere = 4 × π × `Radius`^2

```
Radius : 2

Surface area : 50.26548245743669
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSurfaceAreaOfASphere.c` file
- Add `FindSurfaceAreaOfASphere.c` file in `find-surface-area-of-a-sphere` folder

</details>

**Comment by william-monroy** [comment]
@harshraj8843 Could you assign me this issue?

**Comment by william-monroy** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @william-monroy,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by pokharel-nishan** [comment]
!assign
