### ISSUE TITLE
Write a JavaScript program to find surface area of a sphere

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3017]
### Description

Write a JavaScript program to find surface area of a sphere

Surface area of sphere = 4 × π × `Radius`^2

```
Radius : 2

Surface area : 50.26548245743669
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSurfaceAreaOfASphere.js` file
- Add `FindSurfaceAreaOfASphere.js` file in `find-surface-area-of-a-sphere` folder

</details>

**Comment by DiamonndAde** [comment]
!assign
