### ISSUE TITLE
Write a PHP program to find surface area of a sphere

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3021]
### Description

Write a PHP program to find surface area of a sphere

Surface area of sphere = 4 × π × `Radius`^2

```
Radius : 2

Surface area : 50.26548245743669
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_surface_area_of_a_sphere.php` file
- Add `find_surface_area_of_a_sphere.php` file in `find-surface-area-of-a-sphere` folder

</details>

**Comment by niteshbhaiya4224** [comment]
I want to work in this issue

**Comment by harshraj8843** [comment]
Hey @niteshbhaiya4224 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by esivakumar18** [comment]
!assign
