### ISSUE TITLE
Write a Swift program to find surface area of a sphere

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3027]
### Description

Write a Swift program to find surface area of a sphere

Surface area of sphere = 4 × π × `Radius`^2

```
Radius : 2

Surface area : 50.26548245743669
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSurfaceAreaOfASphere.swift` file
- Add `FindSurfaceAreaOfASphere.swift` file in `find-surface-area-of-a-sphere` folder

</details>

**Comment by esivakumar18** [comment]
!assign
