### ISSUE TITLE
Write a TypeScript program to find surface area of a sphere

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3028]
### Description

Write a TypeScript program to find surface area of a sphere

Surface area of sphere = 4 × π × `Radius`^2

```
Radius : 2

Surface area : 50.26548245743669
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSurfaceAreaOfASphere.ts` file
- Add `FindSurfaceAreaOfASphere.ts` file in `find-surface-area-of-a-sphere` folder

</details>

**Comment by Frey0-0** [comment]
!assign
