### ISSUE TITLE
Write a C++ program to convert weeks to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3038]
### Description

Write a C++ program to convert weeks to seconds

1 week = 7 days = 168 hours = 10080 minutes = 604800 seconds

```
Input  : 5
Output : 3024000
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertWeeksToSeconds.cpp` file
- Add `ConvertWeeksToSeconds.cpp` file in `convert-weeks-to-seconds` folder

</details>

**Comment by grraghav120** [comment]
!asign

**Comment by TechnicalAmanjeet** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @TechnicalAmanjeet,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by saintramon** [comment]
!assign
