### ISSUE TITLE
Write a JavaScript program to convert weeks to seconds

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3044]
### Description

Write a JavaScript program to convert weeks to seconds

1 week = 7 days = 168 hours = 10080 minutes = 604800 seconds

```
Input  : 5
Output : 3024000
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertWeeksToSeconds.js` file
- Add `ConvertWeeksToSeconds.js` file in `convert-weeks-to-seconds` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by TechnicalAmanjeet** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @TechnicalAmanjeet, this issue is already assigned to @Greeshma-frontier !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
