### ISSUE TITLE
Write a C program to find digital root of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3061]
### Description

Write a C program to find digital root of a number

Digital root of a number is the recursive sum of its digits until we get a single digit number.

```
Input  : 1234
Output : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindDigitalRootOfANumber.c` file
- Add `FindDigitalRootOfANumber.c` file in `find-digital-root-of-a-number` folder

</details>

**Comment by omprakashchhetri** [comment]
Can you assign me this issue!

**Comment by harshraj8843** [comment]
Hey @omprakashchhetri 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by omprakashchhetri** [comment]
!assign

**Comment by omprakashchhetri** [comment]
I have a question does this repo comes under hacktoberfest2022 ?

**Comment by harshraj8843** [comment]
Yes, it has been confirmed

![Screenshot from 2022-10-10 17-27-53](https://user-images.githubusercontent.com/54644599/195033161-3ffeb44f-5f48-45e2-ae2d-52d233e1ce34.png)

**Comment by suyash1397** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @suyash1397, this issue is already assigned to @omprakashchhetri !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
