### ISSUE TITLE
Write a C# program to find digital root of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3062]
### Description

Write a C# program to find digital root of a number

Digital root of a number is the recursive sum of its digits until we get a single digit number.

```
Input  : 1234
Output : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindDigitalRootOfANumber.cs` file
- Add `FindDigitalRootOfANumber.cs` file in `find-digital-root-of-a-number` folder

</details>

**Comment by LukasMikolaj** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @LukasMikolaj,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
