### ISSUE TITLE
Write a C++ program to find digital root of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3063]
### Description

Write a C++ program to find digital root of a number

Digital root of a number is the recursive sum of its digits until we get a single digit number.

```
Input  : 1234
Output : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindDigitalRootOfANumber.cpp` file
- Add `FindDigitalRootOfANumber.cpp` file in `find-digital-root-of-a-number` folder

</details>

**Comment by grraghav120** [comment]
!assign

**Comment by Osher160** [comment]
!assign
