### ISSUE TITLE
Write a Java program to find digital root of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3068]
### Description

Write a Java program to find digital root of a number

Digital root of a number is the recursive sum of its digits until we get a single digit number.

```
Input  : 1234
Output : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindDigitalRootOfANumber.java` file
- Add `FindDigitalRootOfANumber.java` file in `find-digital-root-of-a-number` folder

</details>

**Comment by Vishwamagdavan** [comment]
assign me!

**Comment by Vishwamagdavan** [comment]
!assign
