### ISSUE TITLE
Write a C++ program to convert miles to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3093]
### Description

Write a C++ program to convert miles to inches

1 mile = 63360 inches

```
Input  : 5
Output : 316800
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMilesToInches.cpp` file
- Add `ConvertMilesToInches.cpp` file in `convert-miles-to-inches` folder

</details>

**Comment by william-monroy** [comment]
!assign
