### ISSUE TITLE
Write a Haskell program to convert miles to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3097]
### Description

Write a Haskell program to convert miles to inches

1 mile = 63360 inches

```
Input  : 5
Output : 316800
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_miles_to_inches.hs` file
- Add `convert_miles_to_inches.hs` file in `convert-miles-to-inches` folder

</details>

**Comment by LukasMikolaj** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @LukasMikolaj,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
