### ISSUE TITLE
Write a JavaScript program to convert miles to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3099]
### Description

Write a JavaScript program to convert miles to inches

1 mile = 63360 inches

```
Input  : 5
Output : 316800
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMilesToInches.js` file
- Add `ConvertMilesToInches.js` file in `convert-miles-to-inches` folder

</details>

**Comment by aldyadk** [comment]
!assign
