### ISSUE TITLE
Write a Julia program to convert miles to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3100]
### Description

Write a Julia program to convert miles to inches

1 mile = 63360 inches

```
Input  : 5
Output : 316800
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-miles-to-inches.jl` file
- Add `convert-miles-to-inches.jl` file in `convert-miles-to-inches` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
