### ISSUE TITLE
Write a Kotlin program to convert miles to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3101]
### Description

Write a Kotlin program to convert miles to inches

1 mile = 63360 inches

```
Input  : 5
Output : 316800
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMilesToInches.kt` file
- Add `ConvertMilesToInches.kt` file in `convert-miles-to-inches` folder

</details>

**Comment by rksp25** [comment]
!assign
