### ISSUE TITLE
Write a Python program to convert miles to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3104]
### Description

Write a Python program to convert miles to inches

1 mile = 63360 inches

```
Input  : 5
Output : 316800
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-miles-to-inches.py` file
- Add `convert-miles-to-inches.py` file in `convert-miles-to-inches` folder

</details>

**Comment by sushmita2109** [comment]
hey can i get this assigned to me....

**Comment by harshraj8843** [comment]
Hey @sushmita2109 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by suyash1397** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @suyash1397, this issue is already assigned to @sushmita2109 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
