### ISSUE TITLE
Write a R program to convert miles to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3105]
### Description

Write a R program to convert miles to inches

1 mile = 63360 inches

```
Input  : 5
Output : 316800
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_miles_to_inches.r` file
- Add `convert_miles_to_inches.r` file in `convert-miles-to-inches` folder

</details>

**Comment by esivakumar18** [comment]
!assign
