### ISSUE TITLE
Write a Ruby program to convert miles to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3106]
### Description

Write a Ruby program to convert miles to inches

1 mile = 63360 inches

```
Input  : 5
Output : 316800
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMilesToInches.rb` file
- Add `ConvertMilesToInches.rb` file in `convert-miles-to-inches` folder

</details>

**Comment by lukastomcisak** [comment]
!asign

**Comment by lukastomcisak** [comment]
!assign
