### ISSUE TITLE
Write a Swift program to convert miles to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3109]
### Description

Write a Swift program to convert miles to inches

1 mile = 63360 inches

```
Input  : 5
Output : 316800
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMilesToInches.swift` file
- Add `ConvertMilesToInches.swift` file in `convert-miles-to-inches` folder

</details>

**Comment by esivakumar18** [comment]
!assign
