### ISSUE TITLE
Write a TypeScript program to convert miles to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3110]
### Description

Write a TypeScript program to convert miles to inches

1 mile = 63360 inches

```
Input  : 5
Output : 316800
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMilesToInches.ts` file
- Add `ConvertMilesToInches.ts` file in `convert-miles-to-inches` folder

</details>

**Comment by shailendrakanherkar18** [comment]
!assign
