### ISSUE TITLE
Write a JavaScript program to convert string to snakecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3128]
### Description

Write a JavaScript program to convert string to snakecase

Snakecase is a style of writing in which all letters are lowercase and spaces are replaced with underscores.

```
Input  : "hello world"
Output : "hello_world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToSnakecase.js` file
- Add `ConvertStringToSnakecase.js` file in `convert-string-to-snakecase` folder

</details>

**Comment by arsalan98m** [comment]
i can solve this issue assign it to me

**Comment by harshraj8843** [comment]
Hey @arsalan98m 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by CodingWithHardik** [comment]
!assign

**Comment by SyarifulMsth** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @SyarifulMsth, this issue is already assigned to @CodingWithHardik !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harmanbatheja15** [comment]
!assign

**Comment by harmanbatheja15** [comment]
Solved the issue and opened the pull request. Please review it.
