### ISSUE TITLE
Write a TypeScript program to convert string to snakecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3139]
### Description

Write a TypeScript program to convert string to snakecase

Snakecase is a style of writing in which all letters are lowercase and spaces are replaced with underscores.

```
Input  : "hello world"
Output : "hello_world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToSnakecase.ts` file
- Add `ConvertStringToSnakecase.ts` file in `convert-string-to-snakecase` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign
