### ISSUE TITLE
Write a C program to find the transpose of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3143]
### Description

Write a C program to find the transpose of a matrix

The transpose of a matrix is an operator which flips a matrix over its diagonal, that is it switches the row and column indices of the matrix by producing another matrix denoted as A<sup>T</sup>.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
1 4 7
2 5 8
3 6 9
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheTransposeOfAMatrix.c` file
- Add `FindTheTransposeOfAMatrix.c` file in `find-the-transpose-of-a-matrix` folder

</details>

**Comment by surajrane42** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @surajrane42,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Ishay1997** [comment]
!assign

**Comment by pandfun** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @pandfun, this issue is already assigned to @Ishay1997 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
