### ISSUE TITLE
Write a JavaScript program to find the eigenvectors of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3178]
### Description

Write a JavaScript program to find the eigenvectors of a matrix

The eigenvalues and eigenvectors of a linear transformation are the values and vectors that determine the transformation. The eigenvectors of a matrix A are the vectors v for which the matrix equation Av = λv has a non-trivial solution.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
[[-0.23197068724628608, -0.7858302387246789, 0.4082482904638631],
 [-0.5253220933012334, -0.08675134095039447, -0.8164965809277261],
 [-0.8186734993561807, 0.6123275568238899, 0.4082482904638631]]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheEigenvectorsOfAMatrix.js` file
- Add `FindTheEigenvectorsOfAMatrix.js` file in `find-the-eigenvectors-of-a-matrix` folder

</details>

**Comment by surajrane42** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @surajrane42,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by pritish1906** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @pritish1906, this issue is already assigned to @anandfresh !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by dsarussi** [comment]
!assign
