### ISSUE TITLE
Write a C program to find factorial of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3194]
### Description

Write a C program to find factorial of a number

Factorial of N = N *(N-1)* (N-2) *...* 1

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindFactorialOfANumber.c` file
- Add `FindFactorialOfANumber.c` file in `find-factorial-of-a-number` folder

</details>

**Comment by curious0207** [comment]
!assign
