### ISSUE TITLE
Write a JavaScript program to find factorial of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3202]
### Description

Write a JavaScript program to find factorial of a number

Factorial of N = N *(N-1)* (N-2) *...* 1

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindFactorialOfANumber.js` file
- Add `FindFactorialOfANumber.js` file in `find-factorial-of-a-number` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign

**Comment by K1118** [comment]
!assign

**Comment by anandfresh** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @anandfresh, this issue is already assigned to @K1118 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
