### ISSUE TITLE
Write a Python program to find factorial of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3207]
### Description

Write a Python program to find factorial of a number

Factorial of N = N *(N-1)* (N-2) *...* 1

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-factorial-of-a-number.py` file
- Add `find-factorial-of-a-number.py` file in `find-factorial-of-a-number` folder

</details>

**Comment by K1118** [comment]
!assign
