### ISSUE TITLE
Write a Ruby program to find factorial of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3209]
### Description

Write a Ruby program to find factorial of a number

Factorial of N = N *(N-1)* (N-2) *...* 1

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindFactorialOfANumber.rb` file
- Add `FindFactorialOfANumber.rb` file in `find-factorial-of-a-number` folder

</details>

**Comment by PraaneshSelvaraj** [comment]
!assign

**Comment by jfinley6** [comment]
!assign
