### ISSUE TITLE
Write a Scala program to find factorial of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3211]
### Description

Write a Scala program to find factorial of a number

Factorial of N = N *(N-1)* (N-2) *...* 1

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/findFactorialOfANumber.scala` file
- Add `findFactorialOfANumber.scala` file in `find-factorial-of-a-number` folder

</details>

**Comment by esivakumar18** [comment]
!assign
