### ISSUE TITLE
Write a Swift program to find factorial of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3212]
### Description

Write a Swift program to find factorial of a number

Factorial of N = N *(N-1)* (N-2) *...* 1

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindFactorialOfANumber.swift` file
- Add `FindFactorialOfANumber.swift` file in `find-factorial-of-a-number` folder

</details>

**Comment by esivakumar18** [comment]
!assign
