### ISSUE TITLE
Write a TypeScript program to find factorial of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3213]
### Description

Write a TypeScript program to find factorial of a number

Factorial of N = N *(N-1)* (N-2) *...* 1

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindFactorialOfANumber.ts` file
- Add `FindFactorialOfANumber.ts` file in `find-factorial-of-a-number` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign

**Comment by lukaszmielczarekdev** [comment]
!assign
