### ISSUE TITLE
Write a JavaScript program to convert string to camelcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3230]
### Description

Write a JavaScript program to convert string to camelcase

Camelcase is a style of writing in which the first letter of each word is capitalized except the first word.

```
Input  : "hello world"
Output : "helloWorld"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToCamelcase.js` file
- Add `ConvertStringToCamelcase.js` file in `convert-string-to-camelcase` folder

</details>

**Comment by curious0207** [comment]
!assign

**Comment by manishankardurai** [comment]
!assign
