### ISSUE TITLE
Write a Julia program to convert string to camelcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3231]
### Description

Write a Julia program to convert string to camelcase

Camelcase is a style of writing in which the first letter of each word is capitalized except the first word.

```
Input  : "hello world"
Output : "helloWorld"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-string-to-camelcase.jl` file
- Add `convert-string-to-camelcase.jl` file in `convert-string-to-camelcase` folder

</details>

**Comment by RiteshK-611** [comment]
!assign

**Comment by RiteshK-611** [comment]
This issue has been resolved with PR #7629
