### ISSUE TITLE
Write a Python program to convert string to camelcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3235]
### Description

Write a Python program to convert string to camelcase

Camelcase is a style of writing in which the first letter of each word is capitalized except the first word.

```
Input  : "hello world"
Output : "helloWorld"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-string-to-camelcase.py` file
- Add `convert-string-to-camelcase.py` file in `convert-string-to-camelcase` folder

</details>

**Comment by sanjeev0210** [comment]
!assign
