### ISSUE TITLE
Write a C program to find area of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3259]
### Description

Write a C program to find area of a cube

Area of cube = 6 × `Side`^2

```
Side : 2

Area : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAreaOfACube.c` file
- Add `FindAreaOfACube.c` file in `find-area-of-a-cube` folder

</details>

**Comment by curious0207** [comment]
!assign
