### ISSUE TITLE
Write a C++ program to find area of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3261]
### Description

Write a C++ program to find area of a cube

Area of cube = 6 × `Side`^2

```
Side : 2

Area : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAreaOfACube.cpp` file
- Add `FindAreaOfACube.cpp` file in `find-area-of-a-cube` folder

</details>

**Comment by curious0207** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @curious0207,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by hi-Kartik2004** [comment]
!assign
