### ISSUE TITLE
Write a JavaScript program to find area of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3267]
### Description

Write a JavaScript program to find area of a cube

Area of cube = 6 × `Side`^2

```
Side : 2

Area : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAreaOfACube.js` file
- Add `FindAreaOfACube.js` file in `find-area-of-a-cube` folder

</details>

**Comment by curious0207** [comment]
!assign

**Comment by harmanbatheja15** [comment]
I am interested in this. Please assign me this issue.

**Comment by harmanbatheja15** [comment]
Solved the issue and opened the pull request. Please review it.

**Comment by Sumsum1000** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Sumsum1000, this issue is already assigned to @harmanbatheja15 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by wheels63** [comment]
Is this still available to solve?

**Comment by harshraj8843** [comment]
Thanks for noticing this @wheels63
