### ISSUE TITLE
Write a Kotlin program to find area of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3269]
### Description

Write a Kotlin program to find area of a cube

Area of cube = 6 × `Side`^2

```
Side : 2

Area : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAreaOfACube.kt` file
- Add `FindAreaOfACube.kt` file in `find-area-of-a-cube` folder

</details>

**Comment by gvadam** [comment]
Hi, can I work on this?

**Comment by harshraj8843** [comment]
Hey @gvadam 

You can comment `!assign` on any good first issue you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by gvadam** [comment]
!assign
