### ISSUE TITLE
Write a Perl program to find area of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3270]
### Description

Write a Perl program to find area of a cube

Area of cube = 6 × `Side`^2

```
Side : 2

Area : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_area_of_a_cube.pl` file
- Add `find_area_of_a_cube.pl` file in `find-area-of-a-cube` folder

</details>

**Comment by esivakumar18** [comment]
!assign
