### ISSUE TITLE
Write a Ruby program to find area of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3274]
### Description

Write a Ruby program to find area of a cube

Area of cube = 6 × `Side`^2

```
Side : 2

Area : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAreaOfACube.rb` file
- Add `FindAreaOfACube.rb` file in `find-area-of-a-cube` folder

</details>

**Comment by esivakumar18** [comment]
!assign
