### ISSUE TITLE
Write a C program to find average of digits of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3294]
### Description

Write a C program to find average of digits of a number

Average of digits of a number is the sum of all digits divided by the number of digits.

```
Input  : 123
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAverageOfDigitsOfANumber.c` file
- Add `FindAverageOfDigitsOfANumber.c` file in `find-average-of-digits-of-a-number` folder

</details>

**Comment by astitva0011** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @astitva0011,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Coder-12-ux** [comment]
!assign

**Comment by Coder-12-ux** [comment]
Can Output be in decimal?

**Comment by harshraj8843** [comment]
It should be, thanks for noticing 👍🏻

**Comment by AdityaNarayanPradhan** [comment]
!assign
