### ISSUE TITLE
Write a C++ program to find average of digits of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3296]
### Description

Write a C++ program to find average of digits of a number

Average of digits of a number is the sum of all digits divided by the number of digits.

```
Input  : 123
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAverageOfDigitsOfANumber.cpp` file
- Add `FindAverageOfDigitsOfANumber.cpp` file in `find-average-of-digits-of-a-number` folder

</details>

**Comment by astitva0011** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @astitva0011,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by hi-Kartik2004** [comment]
!assign

**Comment by AbhinavPrabhat01** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @AbhinavPrabhat01, this issue is already assigned to @hi-Kartik2004 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
