### ISSUE TITLE
Write a JavaScript program to find average of digits of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3302]
### Description

Write a JavaScript program to find average of digits of a number

Average of digits of a number is the sum of all digits divided by the number of digits.

```
Input  : 123
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAverageOfDigitsOfANumber.js` file
- Add `FindAverageOfDigitsOfANumber.js` file in `find-average-of-digits-of-a-number` folder

</details>

**Comment by Frey0-0** [comment]
!assign
