### ISSUE TITLE
Write a Kotlin program to find average of digits of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3304]
### Description

Write a Kotlin program to find average of digits of a number

Average of digits of a number is the sum of all digits divided by the number of digits.

```
Input  : 123
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAverageOfDigitsOfANumber.kt` file
- Add `FindAverageOfDigitsOfANumber.kt` file in `find-average-of-digits-of-a-number` folder

</details>

**Comment by rksp25** [comment]
!assign
