### ISSUE TITLE
Write a Ruby program to find average of digits of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3309]
### Description

Write a Ruby program to find average of digits of a number

Average of digits of a number is the sum of all digits divided by the number of digits.

```
Input  : 123
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAverageOfDigitsOfANumber.rb` file
- Add `FindAverageOfDigitsOfANumber.rb` file in `find-average-of-digits-of-a-number` folder

</details>

**Comment by Fukurokudzu** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Fukurokudzu, this issue is already assigned to @anandfresh !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
