### ISSUE TITLE
Write a TypeScript program to find average of digits of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3313]
### Description

Write a TypeScript program to find average of digits of a number

Average of digits of a number is the sum of all digits divided by the number of digits.

```
Input  : 123
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAverageOfDigitsOfANumber.ts` file
- Add `FindAverageOfDigitsOfANumber.ts` file in `find-average-of-digits-of-a-number` folder

</details>

**Comment by ba-p** [comment]
Can I take this one?

**Comment by harshraj8843** [comment]
Hey @ba-p 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by ba-p** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @ba-p, this issue is already assigned to @ba-p !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by ba-p** [comment]
Sorry for unknown that. Thanks for showing me
