### ISSUE TITLE
Write a C program to convert miles to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#332]
### Description

Write a C program to convert miles to feet

1 mile = 5280 feet

```
Input  : 5
Output : 26400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMilesToFeet.c` file
- Add `ConvertMilesToFeet.c` file in `convert-miles-to-feet` folder

</details>

**Comment by anxkhn** [comment]
!assign
