### ISSUE TITLE
Write a C++ program to find sum of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3325]
### Description

Write a C++ program to find sum of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSumOfNumbersByRecursion.cpp` file
- Add `FindSumOfNumbersByRecursion.cpp` file in `find-sum-of-numbers-by-recursion` folder

</details>

**Comment by harshraj8843** [comment]
Hey @astitva0011,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by AbhinavPrabhat01** [comment]
!assign

**Comment by esivakumar18** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @esivakumar18, this issue is already assigned to @AbhinavPrabhat01 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by Shalevro2** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Shalevro2, this issue is already assigned to @AbhinavPrabhat01 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by pritish1906** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @pritish1906, this issue is already assigned to @AbhinavPrabhat01 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by AdityaNarayanPradhan** [comment]
!assign

**Comment by gitabysss** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @gitabysss, this issue is already assigned to @AdityaNarayanPradhan !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
