### ISSUE TITLE
Write a Java program to find sum of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3330]
### Description

Write a Java program to find sum of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSumOfNumbersByRecursion.java` file
- Add `FindSumOfNumbersByRecursion.java` file in `find-sum-of-numbers-by-recursion` folder

</details>

**Comment by curious0207** [comment]
!assign

**Comment by rksp25** [comment]
!assign
