### ISSUE TITLE
Write a JavaScript program to find sum of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3331]
### Description

Write a JavaScript program to find sum of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSumOfNumbersByRecursion.js` file
- Add `FindSumOfNumbersByRecursion.js` file in `find-sum-of-numbers-by-recursion` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
