### ISSUE TITLE
Write a Python program to find sum of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3336]
### Description

Write a Python program to find sum of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-sum-of-numbers-by-recursion.py` file
- Add `find-sum-of-numbers-by-recursion.py` file in `find-sum-of-numbers-by-recursion` folder

</details>

**Comment by bbhoom** [comment]
!assign me

**Comment by dankokonate** [comment]
!assign

**Comment by bbhoom** [comment]
!unassign me
