### ISSUE TITLE
Write a Scala program to find sum of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3340]
### Description

Write a Scala program to find sum of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/findSumOfNumbersByRecursion.scala` file
- Add `findSumOfNumbersByRecursion.scala` file in `find-sum-of-numbers-by-recursion` folder

</details>

**Comment by esivakumar18** [comment]
!assign
