### ISSUE TITLE
Write a TypeScript program to find sum of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3342]
### Description

Write a TypeScript program to find sum of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSumOfNumbersByRecursion.ts` file
- Add `FindSumOfNumbersByRecursion.ts` file in `find-sum-of-numbers-by-recursion` folder

</details>

**Comment by Medmly20208** [comment]
Hi I want to take this issue but I have a question ,  is the type of input an  Array?

**Comment by harshraj8843** [comment]
> Hi I want to take this issue but I have a question , is the type of input an Array?

The input can be `space saperated` like `1 2 3` or `multiline` like

```
n : 3
input : 1
input : 2
input : 3
```

---

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by YAbargil** [comment]
!assign
