### ISSUE TITLE
Write a Ruby program to check leap year

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3362]
### Description

Write a Ruby program to check leap year

Leap years are years that are divisible by 4, but not by 100, unless they are also divisible by 400. For example, 1996 is a leap year, but 1900 is not. Write a function that takes a year as a parameter and returns True if the year is a leap year, False otherwise.

```
Input  : 2016
Output : Leap Year
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckLeapYear.rb` file
- Add `CheckLeapYear.rb` file in `check-leap-year` folder

</details>

**Comment by ahasunos** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @ahasunos,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
