### ISSUE TITLE
Write a GO program to convert miles to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#337]
### Description

Write a GO program to convert miles to feet

1 mile = 5280 feet

```
Input  : 5
Output : 26400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_miles_to_feet.go` file
- Add `convert_miles_to_feet.go` file in `convert-miles-to-feet` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign
