### ISSUE TITLE
Write a C++ program to find the rank of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3375]
### Description

Write a C++ program to find the rank of a matrix

The rank of a matrix is the dimension of the vector space generated by its columns. The rank of a matrix is also equal to the dimension of the vector space generated by its rows. The rank of a matrix is also equal to the number of pivots in its reduced row echelon form.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheRankOfAMatrix.cpp` file
- Add `FindTheRankOfAMatrix.cpp` file in `find-the-rank-of-a-matrix` folder

</details>

**Comment by astitva0011** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @astitva0011,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by ddinh0411** [comment]
!assign
