### ISSUE TITLE
Write a Java program to find the rank of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3380]
### Description

Write a Java program to find the rank of a matrix

The rank of a matrix is the dimension of the vector space generated by its columns. The rank of a matrix is also equal to the dimension of the vector space generated by its rows. The rank of a matrix is also equal to the number of pivots in its reduced row echelon form.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheRankOfAMatrix.java` file
- Add `FindTheRankOfAMatrix.java` file in `find-the-rank-of-a-matrix` folder

</details>

**Comment by suryanshsoni120** [comment]
I would like to contribute to this issue.

**Comment by harshraj8843** [comment]
Hey @suryanshsoni120 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by suryanshsoni120** [comment]
Can it be counted for hacktober fest?

**Comment by harshraj8843** [comment]
> Can it be counted for hacktober fest?

Yes, it has been confirmed

![Screenshot from 2022-10-10 17-27-53](https://user-images.githubusercontent.com/54644599/195415177-866a4e7c-1668-4be9-8bc4-cad6e49f65f1.png)

**Comment by harshraj8843** [comment]
Please link this issue with the PR, by adding `Closes #3380` in the description of the PR 👍🏻

**Comment by harshraj8843** [comment]
Hey @suryanshsoni120,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by NoyHanan** [comment]
!assign

**Comment by crumbycupid** [comment]
is this issue still open?

**Comment by Athul0609** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Athul0609, this issue is already assigned to @NoyHanan !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Hey @brundabharadwaj, this issue is already assigned to @NoyHanan !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by vishalsingh2972** [comment]
@harshraj8843  could you assign this to me if it's still open?

**Comment by vishalsingh2972** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @vishalsingh2972, this issue is already assigned to @NoyHanan !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by vishalsingh2972** [comment]
@NoyHanan in case you have any problem with the issue let's connect and solve the issue! @harshraj8843

**Comment by vishalsingh2972** [comment]
thanks @harshraj8843

**Comment by PurandharAdigarla** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @PurandharAdigarla, this issue is already assigned to @vishalsingh2972 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by vishalsingh2972** [comment]
@harshraj8843 have submitted a PR for this, could you please check https://github.com/codinasion/program/issues/3380#issuecomment-1498010637
