### ISSUE TITLE
Write a JavaScript program to find the rank of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3381]
### Description

Write a JavaScript program to find the rank of a matrix

The rank of a matrix is the dimension of the vector space generated by its columns. The rank of a matrix is also equal to the dimension of the vector space generated by its rows. The rank of a matrix is also equal to the number of pivots in its reduced row echelon form.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheRankOfAMatrix.js` file
- Add `FindTheRankOfAMatrix.js` file in `find-the-rank-of-a-matrix` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by jaypavasiya** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @jaypavasiya, this issue is already assigned to @Greeshma-frontier !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
