### ISSUE TITLE
Write a JavaScript program to convert miles to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#339]
### Description

Write a JavaScript program to convert miles to feet

1 mile = 5280 feet

```
Input  : 5
Output : 26400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMilesToFeet.js` file
- Add `ConvertMilesToFeet.js` file in `convert-miles-to-feet` folder

</details>

**Comment by EniolaAdemola** [comment]
!assign issue #339
