### ISSUE TITLE
Write a TypeScript program to find the rank of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3392]
### Description

Write a TypeScript program to find the rank of a matrix

The rank of a matrix is the dimension of the vector space generated by its columns. The rank of a matrix is also equal to the dimension of the vector space generated by its rows. The rank of a matrix is also equal to the number of pivots in its reduced row echelon form.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheRankOfAMatrix.ts` file
- Add `FindTheRankOfAMatrix.ts` file in `find-the-rank-of-a-matrix` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by Ishay1997** [comment]
!assign

**Comment by RiteshK-611** [comment]
This issue has already been resolved with PR #7133
Here is the file [FindTheRankOfAMatrix.ts](https://github.com/codinasion/program/blob/master/program/find-the-rank-of-a-matrix/FindTheRankOfAMatrix.ts)
