### ISSUE TITLE
Write a C program to convert centimeters to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3399]
### Description

Write a C program to convert centimeters to inches

1 inch = 2.54 centimeters

```
Input  : 12.7
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCentimetersToInches.c` file
- Add `ConvertCentimetersToInches.c` file in `convert-centimeters-to-inches` folder

</details>

**Comment by HeYPoonam** [comment]
!assign

**Comment by Osher160** [comment]
!assign
