### ISSUE TITLE
Write a C++ program to convert centimeters to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3401]
### Description

Write a C++ program to convert centimeters to inches

1 inch = 2.54 centimeters

```
Input  : 12.7
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCentimetersToInches.cpp` file
- Add `ConvertCentimetersToInches.cpp` file in `convert-centimeters-to-inches` folder

</details>

**Comment by astitva0011** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @astitva0011,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Medmly20208** [comment]
!assign
