### ISSUE TITLE
Write a GO program to convert centimeters to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3404]
### Description

Write a GO program to convert centimeters to inches

1 inch = 2.54 centimeters

```
Input  : 12.7
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_centimeters_to_inches.go` file
- Add `convert_centimeters_to_inches.go` file in `convert-centimeters-to-inches` folder

</details>

**Comment by PoweredByCaffein** [comment]
!assign
