### ISSUE TITLE
Write a Julia program to convert centimeters to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3408]
### Description

Write a Julia program to convert centimeters to inches

1 inch = 2.54 centimeters

```
Input  : 12.7
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-centimeters-to-inches.jl` file
- Add `convert-centimeters-to-inches.jl` file in `convert-centimeters-to-inches` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
