### ISSUE TITLE
Write a Kotlin program to convert miles to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#341]
### Description

Write a Kotlin program to convert miles to feet

1 mile = 5280 feet

```
Input  : 5
Output : 26400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMilesToFeet.kt` file
- Add `ConvertMilesToFeet.kt` file in `convert-miles-to-feet` folder

</details>

**Comment by rksp25** [comment]
!assign
