### ISSUE TITLE
Write a Python program to convert centimeters to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3412]
### Description

Write a Python program to convert centimeters to inches

1 inch = 2.54 centimeters

```
Input  : 12.7
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-centimeters-to-inches.py` file
- Add `convert-centimeters-to-inches.py` file in `convert-centimeters-to-inches` folder

</details>

**Comment by Robert-Capra** [comment]
assign me

**Comment by grraghav120** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Robert-Capra 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```
