### ISSUE TITLE
Write a R program to convert centimeters to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3413]
### Description

Write a R program to convert centimeters to inches

1 inch = 2.54 centimeters

```
Input  : 12.7
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_centimeters_to_inches.r` file
- Add `convert_centimeters_to_inches.r` file in `convert-centimeters-to-inches` folder

</details>

**Comment by esivakumar18** [comment]
!assign
