### ISSUE TITLE
Write a Ruby program to convert centimeters to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3414]
### Description

Write a Ruby program to convert centimeters to inches

1 inch = 2.54 centimeters

```
Input  : 12.7
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCentimetersToInches.rb` file
- Add `ConvertCentimetersToInches.rb` file in `convert-centimeters-to-inches` folder

</details>

**Comment by ahasunos** [comment]
Hi @harshraj8843
Could you assign this to me?

**Comment by harshraj8843** [comment]
Hey @ahasunos 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by ahasunos** [comment]
!assign
