### ISSUE TITLE
Write a Scala program to convert centimeters to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3416]
### Description

Write a Scala program to convert centimeters to inches

1 inch = 2.54 centimeters

```
Input  : 12.7
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convertCentimetersToInches.scala` file
- Add `convertCentimetersToInches.scala` file in `convert-centimeters-to-inches` folder

</details>

**Comment by esivakumar18** [comment]
!assign
