### ISSUE TITLE
Write a TypeScript program to convert centimeters to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3418]
### Description

Write a TypeScript program to convert centimeters to inches

1 inch = 2.54 centimeters

```
Input  : 12.7
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCentimetersToInches.ts` file
- Add `ConvertCentimetersToInches.ts` file in `convert-centimeters-to-inches` folder

</details>

**Comment by viktiwari12** [comment]
!assign
