### ISSUE TITLE
Write a C++ program to find the determinant of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3425]
### Description

Write a C++ program to find the determinant of a matrix

The determinant of a square matrix is a scalar value that can be computed from the elements of the matrix. The determinant of a matrix A is denoted as det(A) or |A|.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
0
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheDeterminantOfAMatrix.cpp` file
- Add `FindTheDeterminantOfAMatrix.cpp` file in `find-the-determinant-of-a-matrix` folder

</details>

**Comment by viktiwari12** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @viktiwari12,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by PavanKumarCB** [comment]
does the matrix aways have to be 3x3?

**Comment by PavanKumarCB** [comment]
!assign
