### ISSUE TITLE
Write a PHP program to convert miles to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#343]
### Description

Write a PHP program to convert miles to feet

1 mile = 5280 feet

```
Input  : 5
Output : 26400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_miles_to_feet.php` file
- Add `convert_miles_to_feet.php` file in `convert-miles-to-feet` folder

</details>

**Comment by kashyapkumar-pdf** [comment]
!assign
