### ISSUE TITLE
Write a Java program to find the determinant of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3430]
### Description

Write a Java program to find the determinant of a matrix

The determinant of a square matrix is a scalar value that can be computed from the elements of the matrix. The determinant of a matrix A is denoted as det(A) or |A|.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
0
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheDeterminantOfAMatrix.java` file
- Add `FindTheDeterminantOfAMatrix.java` file in `find-the-determinant-of-a-matrix` folder

</details>

**Comment by gs16062021** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @gs16062021,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Sri01729** [comment]
!assign
