### ISSUE TITLE
Write a Ruby program to find the determinant of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3438]
### Description

Write a Ruby program to find the determinant of a matrix

The determinant of a square matrix is a scalar value that can be computed from the elements of the matrix. The determinant of a matrix A is denoted as det(A) or |A|.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
0
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheDeterminantOfAMatrix.rb` file
- Add `FindTheDeterminantOfAMatrix.rb` file in `find-the-determinant-of-a-matrix` folder

</details>

**Comment by ahasunos** [comment]
Hi @harshraj8843 ,
I am interested in this issue.
Could you assign this to me?

**Comment by harshraj8843** [comment]
Hey @ahasunos 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by ahasunos** [comment]
!assign
