### ISSUE TITLE
Write a Ruby program to convert miles to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#346]
### Description

Write a Ruby program to convert miles to feet

1 mile = 5280 feet

```
Input  : 5
Output : 26400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMilesToFeet.rb` file
- Add `ConvertMilesToFeet.rb` file in `convert-miles-to-feet` folder

</details>

**Comment by PraaneshSelvaraj** [comment]
!assign
