### ISSUE TITLE
Write a Rust program to convert miles to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#347]
### Description

Write a Rust program to convert miles to feet

1 mile = 5280 feet

```
Input  : 5
Output : 26400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_miles_to_feet.rs` file
- Add `convert_miles_to_feet.rs` file in `convert-miles-to-feet` folder

</details>

**Comment by Ishay1997** [comment]
!assign
