### ISSUE TITLE
Write a C++ program to print reverse of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3471]
### Description

Write a C++ program to print reverse of a number

Reverse of a number is the number obtained by reversing the digits of the original number. For example, the reverse of 123 is 321. The reverse of 100 is 1. The reverse of 1000 is 1.

```
Input  : 123
Output : 321
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintReverseOfANumber.cpp` file
- Add `PrintReverseOfANumber.cpp` file in `print-reverse-of-a-number` folder

</details>

**Comment by sidharthbh8** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @sidharthbh8,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by roshan798** [comment]
!assign
