### ISSUE TITLE
Write a Kotlin program to print reverse of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3479]
### Description

Write a Kotlin program to print reverse of a number

Reverse of a number is the number obtained by reversing the digits of the original number. For example, the reverse of 123 is 321. The reverse of 100 is 1. The reverse of 1000 is 1.

```
Input  : 123
Output : 321
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintReverseOfANumber.kt` file
- Add `PrintReverseOfANumber.kt` file in `print-reverse-of-a-number` folder

</details>

**Comment by rksp25** [comment]
!assign
