### ISSUE TITLE
Write a TypeScript program to print reverse of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3489]
### Description

Write a TypeScript program to print reverse of a number

Reverse of a number is the number obtained by reversing the digits of the original number. For example, the reverse of 123 is 321. The reverse of 100 is 1. The reverse of 1000 is 1.

```
Input  : 123
Output : 321
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintReverseOfANumber.ts` file
- Add `PrintReverseOfANumber.ts` file in `print-reverse-of-a-number` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign

**Comment by gs16062021** [comment]
I would like to do this. Can you assign it to me?

**Comment by harshraj8843** [comment]
Hey @gs16062021 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by gs16062021** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @gs16062021, this issue is already assigned to @CodingWithHardik !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by lukaszmielczarekdev** [comment]
!assign
