### ISSUE TITLE
Write a Swift program to convert miles to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#349]
### Description

Write a Swift program to convert miles to feet

1 mile = 5280 feet

```
Input  : 5
Output : 26400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMilesToFeet.swift` file
- Add `ConvertMilesToFeet.swift` file in `convert-miles-to-feet` folder

</details>

**Comment by esivakumar18** [comment]
!assign
