### ISSUE TITLE
Write a TypeScript program to convert miles to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#350]
### Description

Write a TypeScript program to convert miles to feet

1 mile = 5280 feet

```
Input  : 5
Output : 26400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMilesToFeet.ts` file
- Add `ConvertMilesToFeet.ts` file in `convert-miles-to-feet` folder

</details>

**Comment by RShalman** [comment]
!assign
