### ISSUE TITLE
Write a GO program to convert minutes to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3508]
### Description

Write a GO program to convert minutes to hours

1 hour = 60 minutes

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_minutes_to_hours.go` file
- Add `convert_minutes_to_hours.go` file in `convert-minutes-to-hours` folder

</details>

**Comment by ba-p** [comment]
!assign
