### ISSUE TITLE
Write a Java program to convert minutes to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3510]
### Description

Write a Java program to convert minutes to hours

1 hour = 60 minutes

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMinutesToHours.java` file
- Add `ConvertMinutesToHours.java` file in `convert-minutes-to-hours` folder

</details>

**Comment by Harsh3341** [comment]
!assign
