### ISSUE TITLE
Write a JavaScript program to convert minutes to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3511]
### Description

Write a JavaScript program to convert minutes to hours

1 hour = 60 minutes

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMinutesToHours.js` file
- Add `ConvertMinutesToHours.js` file in `convert-minutes-to-hours` folder

</details>

**Comment by sidharthbh8** [comment]
!assign

**Comment by samilieberman** [comment]
I put a PR for this issue: https://github.com/codinasion/program/pull/4797
