### ISSUE TITLE
Write a Julia program to convert minutes to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3512]
### Description

Write a Julia program to convert minutes to hours

1 hour = 60 minutes

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-minutes-to-hours.jl` file
- Add `convert-minutes-to-hours.jl` file in `convert-minutes-to-hours` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
