### ISSUE TITLE
Write a Kotlin program to convert minutes to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3513]
### Description

Write a Kotlin program to convert minutes to hours

1 hour = 60 minutes

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMinutesToHours.kt` file
- Add `ConvertMinutesToHours.kt` file in `convert-minutes-to-hours` folder

</details>

**Comment by rksp25** [comment]
!assign
