### ISSUE TITLE
Write a Perl program to convert minutes to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3514]
### Description

Write a Perl program to convert minutes to hours

1 hour = 60 minutes

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_minutes_to_hours.pl` file
- Add `convert_minutes_to_hours.pl` file in `convert-minutes-to-hours` folder

</details>

**Comment by esivakumar18** [comment]
!assign
