### ISSUE TITLE
Write a Python program to convert minutes to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3516]
### Description

Write a Python program to convert minutes to hours

1 hour = 60 minutes

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-minutes-to-hours.py` file
- Add `convert-minutes-to-hours.py` file in `convert-minutes-to-hours` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign

**Comment by Avinash-rvv** [comment]
!assign
