### ISSUE TITLE
Write a Swift program to convert minutes to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3521]
### Description

Write a Swift program to convert minutes to hours

1 hour = 60 minutes

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMinutesToHours.swift` file
- Add `ConvertMinutesToHours.swift` file in `convert-minutes-to-hours` folder

</details>

**Comment by esivakumar18** [comment]
!assign
