### ISSUE TITLE
Write a C++ program to convert string to uppercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3529]
### Description

Write a C++ program to convert string to uppercase

```
Input  : "Hello World"
Output : "HELLO WORLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToUppercase.cpp` file
- Add `ConvertStringToUppercase.cpp` file in `convert-string-to-uppercase` folder

</details>

**Comment by darkbits018** [comment]
!assign

**Comment by astitva0011** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @astitva0011, this issue is already assigned to @darkbits018 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Hey @darkbits018,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by cacti23** [comment]
!assign
