### ISSUE TITLE
Write a GO program to convert string to uppercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3532]
### Description

Write a GO program to convert string to uppercase

```
Input  : "Hello World"
Output : "HELLO WORLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_string_to_uppercase.go` file
- Add `convert_string_to_uppercase.go` file in `convert-string-to-uppercase` folder

</details>

**Comment by HeYPoonam** [comment]
!assign
