### ISSUE TITLE
Write a Java program to convert string to uppercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3534]
### Description

Write a Java program to convert string to uppercase

```
Input  : "Hello World"
Output : "HELLO WORLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToUppercase.java` file
- Add `ConvertStringToUppercase.java` file in `convert-string-to-uppercase` folder

</details>

**Comment by vishalpattnaik** [comment]
!assign
