### ISSUE TITLE
Write a Julia program to convert string to uppercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3536]
### Description

Write a Julia program to convert string to uppercase

```
Input  : "Hello World"
Output : "HELLO WORLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-string-to-uppercase.jl` file
- Add `convert-string-to-uppercase.jl` file in `convert-string-to-uppercase` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
