### ISSUE TITLE
Write a Kotlin program to convert string to uppercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3537]
### Description

Write a Kotlin program to convert string to uppercase

```
Input  : "Hello World"
Output : "HELLO WORLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToUppercase.kt` file
- Add `ConvertStringToUppercase.kt` file in `convert-string-to-uppercase` folder

</details>

**Comment by rksp25** [comment]
!assign
