### ISSUE TITLE
Write a Perl program to convert string to uppercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3538]
### Description

Write a Perl program to convert string to uppercase

```
Input  : "Hello World"
Output : "HELLO WORLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_string_to_uppercase.pl` file
- Add `convert_string_to_uppercase.pl` file in `convert-string-to-uppercase` folder

</details>

**Comment by esivakumar18** [comment]
!assign
