### ISSUE TITLE
Write a PHP program to convert string to uppercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3539]
### Description

Write a PHP program to convert string to uppercase

```
Input  : "Hello World"
Output : "HELLO WORLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_string_to_uppercase.php` file
- Add `convert_string_to_uppercase.php` file in `convert-string-to-uppercase` folder

</details>

**Comment by Robert-Capra** [comment]
!assign

**Comment by sureshr3git** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @sureshr3git, this issue is already assigned to @Robert-Capra !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
