### ISSUE TITLE
Write a Python program to convert string to uppercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3540]
### Description

Write a Python program to convert string to uppercase

```
Input  : "Hello World"
Output : "HELLO WORLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-string-to-uppercase.py` file
- Add `convert-string-to-uppercase.py` file in `convert-string-to-uppercase` folder

</details>

**Comment by Mudi-Igbinoba** [comment]
!assign
