### ISSUE TITLE
Write a Swift program to convert string to uppercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3545]
### Description

Write a Swift program to convert string to uppercase

```
Input  : "Hello World"
Output : "HELLO WORLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToUppercase.swift` file
- Add `ConvertStringToUppercase.swift` file in `convert-string-to-uppercase` folder

</details>

**Comment by esivakumar18** [comment]
!assign
