### ISSUE TITLE
Write a C++ program to convert seconds to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#356]
### Description

Write a C++ program to convert seconds to minutes

1 minute = 60 seconds

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertSecondsToMinutes.cpp` file
- Add `ConvertSecondsToMinutes.cpp` file in `convert-seconds-to-minutes` folder

</details>

**Comment by anxkhn** [comment]
!assign

**Comment by destroyer5067** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @destroyer5067, this issue is already assigned to @anxkhn !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
