### ISSUE TITLE
Write a Java program to find second largest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3565]
### Description

Write a Java program to find second largest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSecondLargestNumberInAnArray.java` file
- Add `FindSecondLargestNumberInAnArray.java` file in `find-second-largest-number-in-an-array` folder

</details>

**Comment by AutoCoderrr** [comment]
!assign

**Comment by saiprakash255** [comment]
hello sir, can you assign this issue to me?

**Comment by harshraj8843** [comment]
Hey @saiprakash255 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by saiprakash255** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @saiprakash255, this issue is already assigned to @AutoCoderrr !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Hey @AutoCoderrr,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by saintramon** [comment]
!assign

**Comment by AutoCoderrr** [comment]
assign!
