### ISSUE TITLE
Write a Kotlin program to find second largest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3568]
### Description

Write a Kotlin program to find second largest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSecondLargestNumberInAnArray.kt` file
- Add `FindSecondLargestNumberInAnArray.kt` file in `find-second-largest-number-in-an-array` folder

</details>

**Comment by mrajen27** [comment]
!assign
