### ISSUE TITLE
Write a Swift program to find second largest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3576]
### Description

Write a Swift program to find second largest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSecondLargestNumberInAnArray.swift` file
- Add `FindSecondLargestNumberInAnArray.swift` file in `find-second-largest-number-in-an-array` folder

</details>

**Comment by esivakumar18** [comment]
!assign
