### ISSUE TITLE
Write a TypeScript program to find second largest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3577]
### Description

Write a TypeScript program to find second largest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSecondLargestNumberInAnArray.ts` file
- Add `FindSecondLargestNumberInAnArray.ts` file in `find-second-largest-number-in-an-array` folder

</details>

**Comment by shailendrakanherkar18** [comment]
!assign
