### ISSUE TITLE
Write a GO program to convert seconds to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#359]
### Description

Write a GO program to convert seconds to minutes

1 minute = 60 seconds

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_seconds_to_minutes.go` file
- Add `convert_seconds_to_minutes.go` file in `convert-seconds-to-minutes` folder

</details>

**Comment by renanlmiranda** [comment]
!assign
