### ISSUE TITLE
Write a Java program to convert seconds to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#360]
### Description

Write a Java program to convert seconds to minutes

1 minute = 60 seconds

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertSecondsToMinutes.java` file
- Add `ConvertSecondsToMinutes.java` file in `convert-seconds-to-minutes` folder

</details>

**Comment by Mahak008** [comment]
!assign
