### ISSUE TITLE
Write a Ruby program to find square root of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3607]
### Description

Write a Ruby program to find square root of a number

Square root of a number is the number that when multiplied by itself gives the original number. For example, square root of 4 is 2 because 2 * 2 = 4. Similarly, square root of 9 is 3 because 3 * 3 = 9.

```
Input  : 4
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSquareRootOfANumber.rb` file
- Add `FindSquareRootOfANumber.rb` file in `find-square-root-of-a-number` folder

</details>

**Comment by saiprakash255** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @saiprakash255,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by rafaover** [comment]
!assign
