### ISSUE TITLE
Write a JavaScript program to convert seconds to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#361]
### Description

Write a JavaScript program to convert seconds to minutes

1 minute = 60 seconds

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertSecondsToMinutes.js` file
- Add `ConvertSecondsToMinutes.js` file in `convert-seconds-to-minutes` folder

</details>

**Comment by jyotik09** [comment]
Hi, I'm happy to work on this. Can you assign to me ?

**Comment by jyotik09** [comment]
!assign

**Comment by DiamonndAde** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @DiamonndAde, this issue is already assigned to @jyotik09 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
