### ISSUE TITLE
Write a Julia program to convert seconds to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#362]
### Description

Write a Julia program to convert seconds to minutes

1 minute = 60 seconds

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-seconds-to-minutes.jl` file
- Add `convert-seconds-to-minutes.jl` file in `convert-seconds-to-minutes` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
