### ISSUE TITLE
Write a C program to convert seconds to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3621]
### Description

Write a C program to convert seconds to weeks

1 week = 7 days = 168 hours = 10080 minutes = 604800 seconds

```
Input  : 3024000
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertSecondsToWeeks.c` file
- Add `ConvertSecondsToWeeks.c` file in `convert-seconds-to-weeks` folder

</details>

**Comment by astitva0011** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @astitva0011,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Osher160** [comment]
!assign
