### ISSUE TITLE
Write a Haskell program to convert seconds to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3627]
### Description

Write a Haskell program to convert seconds to weeks

1 week = 7 days = 168 hours = 10080 minutes = 604800 seconds

```
Input  : 3024000
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_seconds_to_weeks.hs` file
- Add `convert_seconds_to_weeks.hs` file in `convert-seconds-to-weeks` folder

</details>

**Comment by esivakumar18** [comment]
!assign
