### ISSUE TITLE
Write a Kotlin program to convert seconds to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#363]
### Description

Write a Kotlin program to convert seconds to minutes

1 minute = 60 seconds

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertSecondsToMinutes.kt` file
- Add `ConvertSecondsToMinutes.kt` file in `convert-seconds-to-minutes` folder

</details>

**Comment by sourav9599** [comment]
Hi, @harshraj8843 ,  Can i work on this?

**Comment by harshraj8843** [comment]
Hey @sourav9599 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto assigned

```
!assign
```

**Comment by sourav9599** [comment]
!assign
