### ISSUE TITLE
Write a Julia program to convert seconds to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3630]
### Description

Write a Julia program to convert seconds to weeks

1 week = 7 days = 168 hours = 10080 minutes = 604800 seconds

```
Input  : 3024000
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-seconds-to-weeks.jl` file
- Add `convert-seconds-to-weeks.jl` file in `convert-seconds-to-weeks` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
