### ISSUE TITLE
Write a JavaScript program to convert seconds to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3653]
### Description

Write a JavaScript program to convert seconds to days

1 day = 24 hours = 1440 minutes = 86400 seconds

```
Input  : 432000
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertSecondsToDays.js` file
- Add `ConvertSecondsToDays.js` file in `convert-seconds-to-days` folder

</details>

**Comment by SyarifulMsth** [comment]
!assign
