### ISSUE TITLE
Write a Julia program to convert seconds to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3654]
### Description

Write a Julia program to convert seconds to days

1 day = 24 hours = 1440 minutes = 86400 seconds

```
Input  : 432000
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-seconds-to-days.jl` file
- Add `convert-seconds-to-days.jl` file in `convert-seconds-to-days` folder

</details>

**Comment by RiteshK-611** [comment]
!assign

**Comment by RiteshK-611** [comment]
Hey @harshraj8843 
Please close this issue as it's been solved
Here is the file link for this issue [Seconds to Days in Julia](https://github.com/codinasion/program/blob/master/program/convert-seconds-to-days/convert-seconds-to-days.jl)

Also there is one more such issue: [Write a Julia program to convert minutes to weeks #1013
](https://github.com/codinasion/program/issues/1013)

**Comment by harshraj8843** [comment]
Hey @RiteshK-611 

Thanks for noticing this 👍🏻
