### ISSUE TITLE
Write a Kotlin program to convert seconds to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3655]
### Description

Write a Kotlin program to convert seconds to days

1 day = 24 hours = 1440 minutes = 86400 seconds

```
Input  : 432000
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertSecondsToDays.kt` file
- Add `ConvertSecondsToDays.kt` file in `convert-seconds-to-days` folder

</details>

**Comment by rksp25** [comment]
!assign
