### ISSUE TITLE
Write a Python program to convert seconds to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3658]
### Description

Write a Python program to convert seconds to days

1 day = 24 hours = 1440 minutes = 86400 seconds

```
Input  : 432000
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-seconds-to-days.py` file
- Add `convert-seconds-to-days.py` file in `convert-seconds-to-days` folder

</details>

**Comment by BiscuitCandy** [comment]
!assign

**Comment by BiscuitCandy** [comment]
completed in PR #3691
