### ISSUE TITLE
Write a Python program to convert seconds to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#366]
### Description

Write a Python program to convert seconds to minutes

1 minute = 60 seconds

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-seconds-to-minutes.py` file
- Add `convert-seconds-to-minutes.py` file in `convert-seconds-to-minutes` folder

</details>

**Comment by c0d3-br3ak9r** [comment]
!assign
