### ISSUE TITLE
Write a Scala program to convert seconds to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#370]
### Description

Write a Scala program to convert seconds to minutes

1 minute = 60 seconds

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convertSecondsToMinutes.scala` file
- Add `convertSecondsToMinutes.scala` file in `convert-seconds-to-minutes` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
