### ISSUE TITLE
Write a Java program to check valid date

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3702]
### Description

Write a Java program to check valid date

Check if a given date is valid or not.

```
Input  : 2019-02-29
Output : False
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckValidDate.java` file
- Add `CheckValidDate.java` file in `check-valid-date` folder

</details>

**Comment by Shivay10th** [comment]
!assign

**Comment by Cherifzeraguine** [comment]
Hi, I would like to contribute to this issus.
Can you assign it to me please?

**Comment by Cherifzeraguine** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Cherifzeraguine, this issue is already assigned to @Shivay10th !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Hey @Shivay10th,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by mitrofmep** [comment]
!assign
