### ISSUE TITLE
Write a JavaScript program to check valid date

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3703]
### Description

Write a JavaScript program to check valid date

Check if a given date is valid or not.

```
Input  : 2019-02-29
Output : False
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckValidDate.js` file
- Add `CheckValidDate.js` file in `check-valid-date` folder

</details>

**Comment by musadiqpeerzada** [comment]
Can you assign this to me please?

**Comment by harshraj8843** [comment]
Hey @musadiqpeerzada 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by musadiqpeerzada** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @musadiqpeerzada,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by harmanbatheja15** [comment]
!assign

**Comment by harmanbatheja15** [comment]
Solved the issue and opened the pull request. Please review it.
