### ISSUE TITLE
Write a Kotlin program to check valid date

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3705]
### Description

Write a Kotlin program to check valid date

Check if a given date is valid or not.

```
Input  : 2019-02-29
Output : False
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckValidDate.kt` file
- Add `CheckValidDate.kt` file in `check-valid-date` folder

</details>

**Comment by rksp25** [comment]
!assign
