### ISSUE TITLE
Write a Swift program to convert seconds to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#371]
### Description

Write a Swift program to convert seconds to minutes

1 minute = 60 seconds

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertSecondsToMinutes.swift` file
- Add `ConvertSecondsToMinutes.swift` file in `convert-seconds-to-minutes` folder

</details>

**Comment by esivakumar18** [comment]
!assign
