### ISSUE TITLE
Write a Ruby program to check valid date

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3710]
### Description

Write a Ruby program to check valid date

Check if a given date is valid or not.

```
Input  : 2019-02-29
Output : False
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckValidDate.rb` file
- Add `CheckValidDate.rb` file in `check-valid-date` folder

</details>

**Comment by ahasunos** [comment]
!assign
