### ISSUE TITLE
Write a TypeScript program to check valid date

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3714]
### Description

Write a TypeScript program to check valid date

Check if a given date is valid or not.

```
Input  : 2019-02-29
Output : False
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckValidDate.ts` file
- Add `CheckValidDate.ts` file in `check-valid-date` folder

</details>

**Comment by jaypavasiya** [comment]
!assign
