### ISSUE TITLE
Write a TypeScript program to convert seconds to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#372]
### Description

Write a TypeScript program to convert seconds to minutes

1 minute = 60 seconds

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertSecondsToMinutes.ts` file
- Add `ConvertSecondsToMinutes.ts` file in `convert-seconds-to-minutes` folder

</details>

**Comment by YasiOnFire** [comment]
Hi, I'm happy to work on this
!assign

**Comment by YasiOnFire** [comment]
!assign
