### ISSUE TITLE
Write a Java program to convert seconds to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3729]
### Description

Write a Java program to convert seconds to hours

1 hour = 60 minutes = 3600 seconds

```
Input  : 18000
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertSecondsToHours.java` file
- Add `ConvertSecondsToHours.java` file in `convert-seconds-to-hours` folder

</details>

**Comment by grraghav120** [comment]
!commit

**Comment by grraghav120** [comment]
!assign
