### ISSUE TITLE
Write a JavaScript program to convert seconds to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3730]
### Description

Write a JavaScript program to convert seconds to hours

1 hour = 60 minutes = 3600 seconds

```
Input  : 18000
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertSecondsToHours.js` file
- Add `ConvertSecondsToHours.js` file in `convert-seconds-to-hours` folder

</details>

**Comment by jaypavasiya** [comment]
!assign
