### ISSUE TITLE
Write a Julia program to convert seconds to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3731]
### Description

Write a Julia program to convert seconds to hours

1 hour = 60 minutes = 3600 seconds

```
Input  : 18000
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-seconds-to-hours.jl` file
- Add `convert-seconds-to-hours.jl` file in `convert-seconds-to-hours` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
