### ISSUE TITLE
Write a Perl program to convert seconds to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3733]
### Description

Write a Perl program to convert seconds to hours

1 hour = 60 minutes = 3600 seconds

```
Input  : 18000
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_seconds_to_hours.pl` file
- Add `convert_seconds_to_hours.pl` file in `convert-seconds-to-hours` folder

</details>

**Comment by esivakumar18** [comment]
!assign
