### ISSUE TITLE
Write a PHP program to convert seconds to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3734]
### Description

Write a PHP program to convert seconds to hours

1 hour = 60 minutes = 3600 seconds

```
Input  : 18000
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_seconds_to_hours.php` file
- Add `convert_seconds_to_hours.php` file in `convert-seconds-to-hours` folder

</details>

**Comment by sancoLgates** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @sancoLgates, this issue is already assigned to @anandfresh !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by esivakumar18** [comment]
!assign
