### ISSUE TITLE
Write a Python program to convert seconds to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3735]
### Description

Write a Python program to convert seconds to hours

1 hour = 60 minutes = 3600 seconds

```
Input  : 18000
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-seconds-to-hours.py` file
- Add `convert-seconds-to-hours.py` file in `convert-seconds-to-hours` folder

</details>

**Comment by Robert-Capra** [comment]
!assign

**Comment by Emilia-mazari** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Emilia-mazari, this issue is already assigned to @Robert-Capra !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
