### ISSUE TITLE
Write a Swift program to convert seconds to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3740]
### Description

Write a Swift program to convert seconds to hours

1 hour = 60 minutes = 3600 seconds

```
Input  : 18000
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertSecondsToHours.swift` file
- Add `ConvertSecondsToHours.swift` file in `convert-seconds-to-hours` folder

</details>

**Comment by esivakumar18** [comment]
!assign
