### ISSUE TITLE
Write a GO program to find minimum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3756]
### Description

Write a GO program to find minimum of n numbers

```
Input  : 10 20 30 40 50
Output : 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_minimum_of_n_numbers.go` file
- Add `find_minimum_of_n_numbers.go` file in `find-minimum-of-n-numbers` folder

</details>

**Comment by ba-p** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @ba-p,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by sancoLgates** [comment]
!assign
