### ISSUE TITLE
Write a Java program to find minimum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3758]
### Description

Write a Java program to find minimum of n numbers

```
Input  : 10 20 30 40 50
Output : 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindMinimumOfNNumbers.java` file
- Add `FindMinimumOfNNumbers.java` file in `find-minimum-of-n-numbers` folder

</details>

**Comment by grraghav120** [comment]
!assign
