### ISSUE TITLE
Write a JavaScript program to find minimum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3759]
### Description

Write a JavaScript program to find minimum of n numbers

```
Input  : 10 20 30 40 50
Output : 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindMinimumOfNNumbers.js` file
- Add `FindMinimumOfNNumbers.js` file in `find-minimum-of-n-numbers` folder

</details>

**Comment by vfon98** [comment]
!assign
