### ISSUE TITLE
Write a Python program to find minimum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3764]
### Description

Write a Python program to find minimum of n numbers

```
Input  : 10 20 30 40 50
Output : 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-minimum-of-n-numbers.py` file
- Add `find-minimum-of-n-numbers.py` file in `find-minimum-of-n-numbers` folder

</details>

**Comment by ba-p** [comment]
!assign
