### ISSUE TITLE
Write a Ruby program to find minimum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3766]
### Description

Write a Ruby program to find minimum of n numbers

```
Input  : 10 20 30 40 50
Output : 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindMinimumOfNNumbers.rb` file
- Add `FindMinimumOfNNumbers.rb` file in `find-minimum-of-n-numbers` folder

</details>

**Comment by rafaover** [comment]
!assign
