### ISSUE TITLE
Write a Rust program to find minimum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3767]
### Description

Write a Rust program to find minimum of n numbers

```
Input  : 10 20 30 40 50
Output : 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_minimum_of_n_numbers.rs` file
- Add `find_minimum_of_n_numbers.rs` file in `find-minimum-of-n-numbers` folder

</details>

**Comment by ba-p** [comment]
!assign
