### ISSUE TITLE
Write a Swift program to find minimum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3769]
### Description

Write a Swift program to find minimum of n numbers

```
Input  : 10 20 30 40 50
Output : 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindMinimumOfNNumbers.swift` file
- Add `FindMinimumOfNNumbers.swift` file in `find-minimum-of-n-numbers` folder

</details>

**Comment by esivakumar18** [comment]
!assign
