### ISSUE TITLE
Write a TypeScript program to find minimum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3770]
### Description

Write a TypeScript program to find minimum of n numbers

```
Input  : 10 20 30 40 50
Output : 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindMinimumOfNNumbers.ts` file
- Add `FindMinimumOfNNumbers.ts` file in `find-minimum-of-n-numbers` folder

</details>

**Comment by ba-p** [comment]
!assign
