### ISSUE TITLE
Write a C program to convert feet to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#378]
### Description

Write a C program to convert feet to miles

1 mile = 5280 feet

```
Input  : 26400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToMiles.c` file
- Add `ConvertFeetToMiles.c` file in `convert-feet-to-miles` folder

</details>

**Comment by anxkhn** [comment]
!assign
