### ISSUE TITLE
Write a C program to convert miles to meters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3782]
### Description

Write a C program to convert miles to meters

1 mile = 1609 meters

```
Input  : 5
Output : 8046.72
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMilesToMeters.c` file
- Add `ConvertMilesToMeters.c` file in `convert-miles-to-meters` folder

</details>

**Comment by kituuu** [comment]
!assogn

**Comment by kituuu** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @kituuu,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by pokharel-nishan** [comment]
!assign
