### ISSUE TITLE
Write a C++ program to convert miles to meters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3784]
### Description

Write a C++ program to convert miles to meters

1 mile = 1609 meters

```
Input  : 5
Output : 8046.72
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMilesToMeters.cpp` file
- Add `ConvertMilesToMeters.cpp` file in `convert-miles-to-meters` folder

</details>

**Comment by sidharthbh8** [comment]
!assign
