### ISSUE TITLE
Write a GO program to convert miles to meters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3787]
### Description

Write a GO program to convert miles to meters

1 mile = 1609 meters

```
Input  : 5
Output : 8046.72
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_miles_to_meters.go` file
- Add `convert_miles_to_meters.go` file in `convert-miles-to-meters` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign

**Comment by vedantpople4** [comment]
!assign
