### ISSUE TITLE
Write a Haskell program to convert miles to meters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3788]
### Description

Write a Haskell program to convert miles to meters

1 mile = 1609 meters

```
Input  : 5
Output : 8046.72
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_miles_to_meters.hs` file
- Add `convert_miles_to_meters.hs` file in `convert-miles-to-meters` folder

</details>

**Comment by esivakumar18** [comment]
!assign
