### ISSUE TITLE
Write a Java program to convert miles to meters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3789]
### Description

Write a Java program to convert miles to meters

1 mile = 1609 meters

```
Input  : 5
Output : 8046.72
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMilesToMeters.java` file
- Add `ConvertMilesToMeters.java` file in `convert-miles-to-meters` folder

</details>

**Comment by grraghav120** [comment]
!assign

**Comment by grraghav120** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @grraghav120, this issue is already assigned to @grraghav120 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
