### ISSUE TITLE
Write a JavaScript program to convert miles to meters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3790]
### Description

Write a JavaScript program to convert miles to meters

1 mile = 1609 meters

```
Input  : 5
Output : 8046.72
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMilesToMeters.js` file
- Add `ConvertMilesToMeters.js` file in `convert-miles-to-meters` folder

</details>

**Comment by Mudi-Igbinoba** [comment]
!assign
