### ISSUE TITLE
Write a Julia program to convert miles to meters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3791]
### Description

Write a Julia program to convert miles to meters

1 mile = 1609 meters

```
Input  : 5
Output : 8046.72
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-miles-to-meters.jl` file
- Add `convert-miles-to-meters.jl` file in `convert-miles-to-meters` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
