### ISSUE TITLE
Write a Kotlin program to convert miles to meters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3792]
### Description

Write a Kotlin program to convert miles to meters

1 mile = 1609 meters

```
Input  : 5
Output : 8046.72
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMilesToMeters.kt` file
- Add `ConvertMilesToMeters.kt` file in `convert-miles-to-meters` folder

</details>

**Comment by rksp25** [comment]
!assign
