### ISSUE TITLE
Write a Python program to convert miles to meters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3795]
### Description

Write a Python program to convert miles to meters

1 mile = 1609 meters

```
Input  : 5
Output : 8046.72
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-miles-to-meters.py` file
- Add `convert-miles-to-meters.py` file in `convert-miles-to-meters` folder

</details>

**Comment by Mudi-Igbinoba** [comment]
!assign
