### ISSUE TITLE
Write a TypeScript program to convert miles to meters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3801]
### Description

Write a TypeScript program to convert miles to meters

1 mile = 1609 meters

```
Input  : 5
Output : 8046.72
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMilesToMeters.ts` file
- Add `ConvertMilesToMeters.ts` file in `convert-miles-to-meters` folder

</details>

**Comment by jaypavasiya** [comment]
!assign
