### ISSUE TITLE
Write a C++ program to convert time from 12-hour to 24-hour format

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3812]
### Description

Write a C++ program to convert time from 12-hour to 24-hour format

```
Input  : 12:05:45PM
Output : 12:05:45
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertTimeFrom12-hourTo24-hourFormat.cpp` file
- Add `ConvertTimeFrom12-hourTo24-hourFormat.cpp` file in `convert-time-from-12-hour-to-24-hour-format` folder

</details>

**Comment by grraghav120** [comment]
!assign

**Comment by its-kundan** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @its-kundan, this issue is already assigned to @grraghav120 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by its-kundan** [comment]
Okay..

**Comment by bhavesh20-mb** [comment]
!assign
