### ISSUE TITLE
Write a Java program to convert time from 12-hour to 24-hour format

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3817]
### Description

Write a Java program to convert time from 12-hour to 24-hour format

```
Input  : 12:05:45PM
Output : 12:05:45
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertTimeFrom12-hourTo24-hourFormat.java` file
- Add `ConvertTimeFrom12-hourTo24-hourFormat.java` file in `convert-time-from-12-hour-to-24-hour-format` folder

</details>

**Comment by Mux199** [comment]
!assign

**Comment by rksp25** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @rksp25, this issue is already assigned to @Mux199 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
