### ISSUE TITLE
Write a JavaScript program to convert time from 12-hour to 24-hour format

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3818]
### Description

Write a JavaScript program to convert time from 12-hour to 24-hour format

```
Input  : 12:05:45PM
Output : 12:05:45
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertTimeFrom12-hourTo24-hourFormat.js` file
- Add `ConvertTimeFrom12-hourTo24-hourFormat.js` file in `convert-time-from-12-hour-to-24-hour-format` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
