### ISSUE TITLE
Write a Python program to convert time from 12-hour to 24-hour format

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3823]
### Description

Write a Python program to convert time from 12-hour to 24-hour format

```
Input  : 12:05:45PM
Output : 12:05:45
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-time-from-12-hour-to-24-hour-format.py` file
- Add `convert-time-from-12-hour-to-24-hour-format.py` file in `convert-time-from-12-hour-to-24-hour-format` folder

</details>

**Comment by bhoopesh369** [comment]
!assign
