### ISSUE TITLE
Write a Ruby program to convert time from 12-hour to 24-hour format

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3825]
### Description

Write a Ruby program to convert time from 12-hour to 24-hour format

```
Input  : 12:05:45PM
Output : 12:05:45
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertTimeFrom12-hourTo24-hourFormat.rb` file
- Add `ConvertTimeFrom12-hourTo24-hourFormat.rb` file in `convert-time-from-12-hour-to-24-hour-format` folder

</details>

**Comment by its-kundan** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @its-kundan,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by jfinley6** [comment]
!assign
