### ISSUE TITLE
Write a TypeScript program to convert time from 12-hour to 24-hour format

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3829]
### Description

Write a TypeScript program to convert time from 12-hour to 24-hour format

```
Input  : 12:05:45PM
Output : 12:05:45
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertTimeFrom12-hourTo24-hourFormat.ts` file
- Add `ConvertTimeFrom12-hourTo24-hourFormat.ts` file in `convert-time-from-12-hour-to-24-hour-format` folder

</details>

**Comment by bhoopesh369** [comment]
Can i work on this issue ?

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @bhoopesh369 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```
