### ISSUE TITLE
Write a Java program to convert feet to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#384]
### Description

Write a Java program to convert feet to miles

1 mile = 5280 feet

```
Input  : 26400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToMiles.java` file
- Add `ConvertFeetToMiles.java` file in `convert-feet-to-miles` folder

</details>

**Comment by Mahak008** [comment]
!assign

**Comment by parachaz** [comment]
I’d like to work on this issue.  Please assign it to me.

**Comment by harshraj8843** [comment]
Hey @Mahak008,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by NEOCLOUD0** [comment]
!assign
