### ISSUE TITLE
Write a JavaScript program to convert feet to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#385]
### Description

Write a JavaScript program to convert feet to miles

1 mile = 5280 feet

```
Input  : 26400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToMiles.js` file
- Add `ConvertFeetToMiles.js` file in `convert-feet-to-miles` folder

</details>

**Comment by jyotik09** [comment]
Hi, I'm happy to work on this. Can you assign to me ?

**Comment by harshraj8843** [comment]
Hey @jyotik09 

You ca comment `!assign` on the issue you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by jyotik09** [comment]
!assign

**Comment by GustavoGomesRibeiro** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @GustavoGomesRibeiro, this issue is already assigned to @jyotik09 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
