### ISSUE TITLE
Write a Julia program to convert feet to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#386]
### Description

Write a Julia program to convert feet to miles

1 mile = 5280 feet

```
Input  : 26400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-feet-to-miles.jl` file
- Add `convert-feet-to-miles.jl` file in `convert-feet-to-miles` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
