### ISSUE TITLE
Write a Kotlin program to convert feet to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#387]
### Description

Write a Kotlin program to convert feet to miles

1 mile = 5280 feet

```
Input  : 26400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToMiles.kt` file
- Add `ConvertFeetToMiles.kt` file in `convert-feet-to-miles` folder

</details>

**Comment by rksp25** [comment]
!assign
