### ISSUE TITLE
Write a C program to find volume of a cone

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3872]
### Description

Write a C program to find volume of a cone

Volume of cone = 1/3 × π × `Radius`^2 × `Height`

```
Radius : 2
Height : 3

Volume : 12.566370614359
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindVolumeOfACone.c` file
- Add `FindVolumeOfACone.c` file in `find-volume-of-a-cone` folder

</details>

**Comment by harshraj8843** [comment]
Hey @Krunal-Karena 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by kituuu** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @kituuu,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by kituuu** [comment]
I am a bit busy with college activities, i can do it after the 8th of February.

**Comment by harshraj8843** [comment]
No worries 🤗 

Feel free to contribute anytime

**Comment by esivakumar18** [comment]
!assign
