### ISSUE TITLE
Write a GO program to find volume of a cone

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3877]
### Description

Write a GO program to find volume of a cone

Volume of cone = 1/3 × π × `Radius`^2 × `Height`

```
Radius : 2
Height : 3

Volume : 12.566370614359
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_volume_of_a_cone.go` file
- Add `find_volume_of_a_cone.go` file in `find-volume-of-a-cone` folder

</details>

**Comment by yabhinavy** [comment]
Do assign. Willing to resolve.

**Comment by harshraj8843** [comment]
Hey @yabhinavy 

You can comment `!assign` on any `good first issue` you want to contribute to, o be auto-assigned

```
!assign
```

**Comment by MadhuS-1605** [comment]
!assign

**Comment by yabhinavy** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @MadhuS-1605,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
