### ISSUE TITLE
Write a Java program to find volume of a cone

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3879]
### Description

Write a Java program to find volume of a cone

Volume of cone = 1/3 × π × `Radius`^2 × `Height`

```
Radius : 2
Height : 3

Volume : 25.132741228718345
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindVolumeOfACone.java` file
- Add `FindVolumeOfACone.java` file in `find-volume-of-a-cone` folder

</details>

**Comment by castanedadev-edu** [comment]
!assign
