### ISSUE TITLE
Write a Python program to find volume of a cone

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3885]
### Description

Write a Python program to find volume of a cone

Volume of cone = 1/3 × π × `Radius`^2 × `Height`

```
Radius : 2
Height : 3

Volume : 12.566370614359
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-volume-of-a-cone.py` file
- Add `find-volume-of-a-cone.py` file in `find-volume-of-a-cone` folder

</details>

**Comment by Medmly20208** [comment]
!assign

**Comment by Medmly20208** [comment]
@harshraj8843 you have a fault in the readme file the volume of cone based on input is 12.57 not  25.132741228718345

**Comment by harshraj8843** [comment]
Thanks @Medmly20208 for noticing it
