### ISSUE TITLE
Write a Rust program to find volume of a cone

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3888]
### Description

Write a Rust program to find volume of a cone

Volume of cone = 1/3 × π × `Radius`^2 × `Height`

```
Radius : 2
Height : 3

Volume : 12.566370614359
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_volume_of_a_cone.rs` file
- Add `find_volume_of_a_cone.rs` file in `find-volume-of-a-cone` folder

</details>

**Comment by esivakumar18** [comment]
!assign
