### ISSUE TITLE
Write a PHP program to convert feet to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#389]
### Description

Write a PHP program to convert feet to miles

1 mile = 5280 feet

```
Input  : 26400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_feet_to_miles.php` file
- Add `convert_feet_to_miles.php` file in `convert-feet-to-miles` folder

</details>

**Comment by praveenscience** [comment]
!assign
