### ISSUE TITLE
Write a TypeScript program to find volume of a cone

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3891]
### Description

Write a TypeScript program to find volume of a cone

Volume of cone = 1/3 × π × `Radius`^2 × `Height`

```
Radius : 2
Height : 3

Volume : 12.566370614359
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindVolumeOfACone.ts` file
- Add `FindVolumeOfACone.ts` file in `find-volume-of-a-cone` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Greeshma-frontier,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
