### ISSUE TITLE
Write a Python program to convert feet to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#390]
### Description

Write a Python program to convert feet to miles

1 mile = 5280 feet

```
Input  : 26400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-feet-to-miles.py` file
- Add `convert-feet-to-miles.py` file in `convert-feet-to-miles` folder

</details>

**Comment by EniolaAdemola** [comment]
I assign issue #390 ,
