### ISSUE TITLE
Write a Ruby program to convert feet to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#392]
### Description

Write a Ruby program to convert feet to miles

1 mile = 5280 feet

```
Input  : 26400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToMiles.rb` file
- Add `ConvertFeetToMiles.rb` file in `convert-feet-to-miles` folder

</details>

**Comment by rafaover** [comment]
!assign
