### ISSUE TITLE
Write a GO program to find the maximum sum of a contiguous subarray (kadane's algorithm)

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3924]
### Description

Write a GO program to find the maximum sum of a contiguous subarray (kadane's algorithm)

Kadane's algorithm is used to find the maximum sum of a contiguous subarray within a one-dimensional array of numbers. For example, for the sequence of values `−2, 1, −3, 4, −1, 2, 1, −5, 4;` the contiguous subarray with the largest sum is `4, −1, 2, 1,` with sum `6`.

```
Input  : [1, 2, 3, -2, 5]
Output : 9
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_the_maximum_sum_of_a_contiguous_subarray_(kadane's_algorithm).go` file
- Add `find_the_maximum_sum_of_a_contiguous_subarray_(kadane's_algorithm).go` file in `find-the-maximum-sum-of-a-contiguous-subarray-(kadane's-algorithm)` folder

</details>

**Comment by nikzayn** [comment]
!assign
