### ISSUE TITLE
Write a Rust program to convert feet to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#393]
### Description

Write a Rust program to convert feet to miles

1 mile = 5280 feet

```
Input  : 26400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_feet_to_miles.rs` file
- Add `convert_feet_to_miles.rs` file in `convert-feet-to-miles` folder

</details>

**Comment by melko** [comment]
!assign
