### ISSUE TITLE
Write a C++ program to find smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3945]
### Description

Write a C++ program to find smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSmallestNumberInAnArray.cpp` file
- Add `FindSmallestNumberInAnArray.cpp` file in `find-smallest-number-in-an-array` folder

</details>

**Comment by SiriuswhiteIND** [comment]
Please assign this to me

**Comment by hi-Kartik2004** [comment]
!assign
