### ISSUE TITLE
Write a GO program to find smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3948]
### Description

Write a GO program to find smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_smallest_number_in_an_array.go` file
- Add `find_smallest_number_in_an_array.go` file in `find-smallest-number-in-an-array` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @MadhuS-1605,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by vedantpople4** [comment]
!assign
