### ISSUE TITLE
Write a Swift program to convert feet to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#395]
### Description

Write a Swift program to convert feet to miles

1 mile = 5280 feet

```
Input  : 26400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToMiles.swift` file
- Add `ConvertFeetToMiles.swift` file in `convert-feet-to-miles` folder

</details>

**Comment by esivakumar18** [comment]
!assign
