### ISSUE TITLE
Write a Java program to find smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3950]
### Description

Write a Java program to find smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSmallestNumberInAnArray.java` file
- Add `FindSmallestNumberInAnArray.java` file in `find-smallest-number-in-an-array` folder

</details>

**Comment by castanedadev-edu** [comment]
!assign
