### ISSUE TITLE
Write a JavaScript program to find smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3951]
### Description

Write a JavaScript program to find smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSmallestNumberInAnArray.js` file
- Add `FindSmallestNumberInAnArray.js` file in `find-smallest-number-in-an-array` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
