### ISSUE TITLE
Write a Kotlin program to find smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3953]
### Description

Write a Kotlin program to find smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSmallestNumberInAnArray.kt` file
- Add `FindSmallestNumberInAnArray.kt` file in `find-smallest-number-in-an-array` folder

</details>

**Comment by gsquareg2** [comment]
!assign

**Comment by esivakumar18** [comment]
!assign
