### ISSUE TITLE
Write a Ruby program to find smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3958]
### Description

Write a Ruby program to find smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSmallestNumberInAnArray.rb` file
- Add `FindSmallestNumberInAnArray.rb` file in `find-smallest-number-in-an-array` folder

</details>

**Comment by jfinley6** [comment]
!assign
