### ISSUE TITLE
Write a Rust program to find smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3959]
### Description

Write a Rust program to find smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_smallest_number_in_an_array.rs` file
- Add `find_smallest_number_in_an_array.rs` file in `find-smallest-number-in-an-array` folder

</details>

**Comment by hugosmoreira** [comment]
!assign
