### ISSUE TITLE
Write a TypeScript program to convert feet to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#396]
### Description

Write a TypeScript program to convert feet to miles

1 mile = 5280 feet

```
Input  : 26400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToMiles.ts` file
- Add `ConvertFeetToMiles.ts` file in `convert-feet-to-miles` folder

</details>

**Comment by lotfijb** [comment]
!assign
