### ISSUE TITLE
Write a Swift program to find smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3961]
### Description

Write a Swift program to find smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSmallestNumberInAnArray.swift` file
- Add `FindSmallestNumberInAnArray.swift` file in `find-smallest-number-in-an-array` folder

</details>

**Comment by esivakumar18** [comment]
!assign
