### ISSUE TITLE
Write a TypeScript program to find smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3962]
### Description

Write a TypeScript program to find smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSmallestNumberInAnArray.ts` file
- Add `FindSmallestNumberInAnArray.ts` file in `find-smallest-number-in-an-array` folder

</details>

**Comment by thongncvn** [comment]
!assign

**Comment by dmosc** [comment]
!assign
