### ISSUE TITLE
Write a Java program to convert string to constantcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3974]
### Description

Write a Java program to convert string to constantcase

Constantcase is a style of writing in which all letters are uppercase and spaces are replaced with underscores.

```
Input  : "hello world"
Output : "HELLO_WORLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToConstantcase.java` file
- Add `ConvertStringToConstantcase.java` file in `convert-string-to-constantcase` folder

</details>

**Comment by castanedadev-edu** [comment]
!assign

**Comment by Cherifzeraguine** [comment]
Hi, I would like to contribute to this issus. 
Can you assign it to me please ?

**Comment by Cherifzeraguine** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Cherifzeraguine, this issue is already assigned to @castanedadev-edu !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by Cherifzeraguine** [comment]
okay
