### ISSUE TITLE
Write a Julia program to convert string to constantcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3976]
### Description

Write a Julia program to convert string to constantcase

Constantcase is a style of writing in which all letters are uppercase and spaces are replaced with underscores.

```
Input  : "hello world"
Output : "HELLO_WORLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-string-to-constantcase.jl` file
- Add `convert-string-to-constantcase.jl` file in `convert-string-to-constantcase` folder

</details>

**Comment by RiteshK-611** [comment]
!assign

**Comment by RiteshK-611** [comment]
This issue has been resolved with PR #7629
