### ISSUE TITLE
Write a Python program to convert string to constantcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#3980]
### Description

Write a Python program to convert string to constantcase

Constantcase is a style of writing in which all letters are uppercase and spaces are replaced with underscores.

```
Input  : "hello world"
Output : "HELLO_WORLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-string-to-constantcase.py` file
- Add `convert-string-to-constantcase.py` file in `convert-string-to-constantcase` folder

</details>

**Comment by Marsh-sudo** [comment]
!assign
