### ISSUE TITLE
Write a PHP program to print pascal's triangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4001]
### Description

Write a PHP program to print pascal's triangle

Pascal's triangle is a triangular array of the binomial coefficients. Write a function that takes an integer value `n` as input and prints first `n` lines of the Pascal's triangle.

```
Input  : 5

Output : 
        1
       1 1
      1 2 1
     1 3 3 1
    1 4 6 4 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/print_pascal's_triangle.php` file
- Add `print_pascal's_triangle.php` file in `print-pascal's-triangle` folder

</details>

**Comment by anonimak** [comment]
I would like to work on this issue

**Comment by harshraj8843** [comment]
Hey @anonimak 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by anonimak** [comment]
!assign

**Comment by anonimak** [comment]
can u add hacktoberfest & hacktoberfest-accepted ? @harshraj8843

**Comment by harshraj8843** [comment]
Hey @anonimak 

This repo has been `excluded` from Hacktoberfest 2022

**Comment by harshraj8843** [comment]
Hey @anonimak,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Roybas2001** [comment]
!assign
