### ISSUE TITLE
Write a C program to convert kilometers to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4012]
### Description

Write a C program to convert kilometers to miles

1 mile = 1.609 kilometers

```
Input  : 8.04672
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertKilometersToMiles.c` file
- Add `ConvertKilometersToMiles.c` file in `convert-kilometers-to-miles` folder

</details>

**Comment by marcleonschulz** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @marcleonschulz,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by marcleonschulz** [comment]
!assign

**Comment by pokharel-nishan** [comment]
!assign
