### ISSUE TITLE
Write a Java program to convert kilometers to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4019]
### Description

Write a Java program to convert kilometers to miles

1 mile = 1.609 kilometers

```
Input  : 8.04672
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertKilometersToMiles.java` file
- Add `ConvertKilometersToMiles.java` file in `convert-kilometers-to-miles` folder

</details>

**Comment by Avicenne-b** [comment]
Greetings from France ! Can you assign me this issue ?

**Comment by aghiles-medane** [comment]
Hi, I am looking for my first contribution, can I take this issue?

**Comment by VasireddyGanesh** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Avicenne-b @aghiles-medane 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```
