### ISSUE TITLE
Write a JavaScript program to convert kilometers to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4020]
### Description

Write a JavaScript program to convert kilometers to miles

1 mile = 1.609 kilometers

```
Input  : 8.04672
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertKilometersToMiles.js` file
- Add `ConvertKilometersToMiles.js` file in `convert-kilometers-to-miles` folder

</details>

**Comment by Medmly20208** [comment]
!assign
