### ISSUE TITLE
Write a Python program to convert kilometers to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4025]
### Description

Write a Python program to convert kilometers to miles

1 mile = 1.609 kilometers

```
Input  : 8.04672
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-kilometers-to-miles.py` file
- Add `convert-kilometers-to-miles.py` file in `convert-kilometers-to-miles` folder

</details>

**Comment by WillLowrie** [comment]
!assign
