### ISSUE TITLE
Write a TypeScript program to convert kilometers to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4031]
### Description

Write a TypeScript program to convert kilometers to miles

1 mile = 1.609 kilometers

```
Input  : 8.04672
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertKilometersToMiles.ts` file
- Add `ConvertKilometersToMiles.ts` file in `convert-kilometers-to-miles` folder

</details>

**Comment by tanishq-singh-2301** [comment]
!assign
