### ISSUE TITLE
Write a JavaScript program to find the adjoint of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4046]
### Description

Write a JavaScript program to find the adjoint of a matrix

The adjoint of a square matrix A is the transpose of the matrix of cofactors of A. The adjoint of a matrix A is denoted as A<sup>\*</sup>.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
[[-3, 6, -3], [6, -12, 6], [-3, 6, -3]]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheAdjointOfAMatrix.js` file
- Add `FindTheAdjointOfAMatrix.js` file in `find-the-adjoint-of-a-matrix` folder

</details>

**Comment by avireni** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @avireni,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by SarthakSanjay** [comment]
!assign
