### ISSUE TITLE
Write a GO program to swap two numbers without using third variable

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4066]
### Description

Write a GO program to swap two numbers without using third variable

```
Input  : 10 20
Output : 20 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/swap_two_numbers_without_using_third_variable.go` file
- Add `swap_two_numbers_without_using_third_variable.go` file in `swap-two-numbers-without-using-third-variable` folder

</details>

**Comment by harshraj8843** [comment]
Hey @MadhuS-1605,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by vedantpople4** [comment]
!assign
