### ISSUE TITLE
Write a Java program to swap two numbers without using third variable

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4068]
### Description

Write a Java program to swap two numbers without using third variable

```
Input  : 10 20
Output : 20 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/SwapTwoNumbersWithoutUsingThirdVariable.java` file
- Add `SwapTwoNumbersWithoutUsingThirdVariable.java` file in `swap-two-numbers-without-using-third-variable` folder

</details>

**Comment by mounaj5** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @rksp25, this issue is already assigned to @mounaj5 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
