### ISSUE TITLE
Write a JavaScript program to swap two numbers without using third variable

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4069]
### Description

Write a JavaScript program to swap two numbers without using third variable

```
Input  : 10 20
Output : 20 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/SwapTwoNumbersWithoutUsingThirdVariable.js` file
- Add `SwapTwoNumbersWithoutUsingThirdVariable.js` file in `swap-two-numbers-without-using-third-variable` folder

</details>

**Comment by Dheeraj0014** [comment]
!assign
