### ISSUE TITLE
Write a Python program to swap two numbers without using third variable

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4074]
### Description

Write a Python program to swap two numbers without using third variable

```
Input  : 10 20
Output : 20 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/swap-two-numbers-without-using-third-variable.py` file
- Add `swap-two-numbers-without-using-third-variable.py` file in `swap-two-numbers-without-using-third-variable` folder

</details>

**Comment by Medmly20208** [comment]
!assign
