### ISSUE TITLE
Write a Scala program to swap two numbers without using third variable

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4078]
### Description

Write a Scala program to swap two numbers without using third variable

```
Input  : 10 20
Output : 20 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/swapTwoNumbersWithoutUsingThirdVariable.scala` file
- Add `swapTwoNumbersWithoutUsingThirdVariable.scala` file in `swap-two-numbers-without-using-third-variable` folder

</details>

**Comment by dht7** [comment]
!assign
