### ISSUE TITLE
Write a TypeScript program to swap two numbers without using third variable

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4080]
### Description

Write a TypeScript program to swap two numbers without using third variable

```
Input  : 10 20
Output : 20 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/SwapTwoNumbersWithoutUsingThirdVariable.ts` file
- Add `SwapTwoNumbersWithoutUsingThirdVariable.ts` file in `swap-two-numbers-without-using-third-variable` folder

</details>

**Comment by Avicenne-b** [comment]
!assign
