### ISSUE TITLE
Write a C program to convert string to pascalcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4086]
### Description

Write a C program to convert string to pascalcase

Pascalcase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "HelloWorld"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToPascalcase.c` file
- Add `ConvertStringToPascalcase.c` file in `convert-string-to-pascalcase` folder

</details>

**Comment by kituuu** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @kituuu,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by roshan798** [comment]
!assign
