### ISSUE TITLE
Write a C++ program to convert string to pascalcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4088]
### Description

Write a C++ program to convert string to pascalcase

Pascalcase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "HelloWorld"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToPascalcase.cpp` file
- Add `ConvertStringToPascalcase.cpp` file in `convert-string-to-pascalcase` folder

</details>

**Comment by SoumyadiptoPal** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @SoumyadiptoPal, this issue is already assigned to @cacti23 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by Bogumil-Sapinski-Mobica** [comment]
!assign
