### ISSUE TITLE
Write a Java program to convert string to pascalcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4093]
### Description

Write a Java program to convert string to pascalcase

Pascalcase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "HelloWorld"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToPascalcase.java` file
- Add `ConvertStringToPascalcase.java` file in `convert-string-to-pascalcase` folder

</details>

**Comment by Arbaz23** [comment]
hello, can i take this issue ?

**Comment by Arbaz23** [comment]
!asign

**Comment by Arbaz23** [comment]
!assign

**Comment by Arbaz23** [comment]
#4731
