### ISSUE TITLE
Write a JavaScript program to convert string to pascalcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4094]
### Description

Write a JavaScript program to convert string to pascalcase

Pascalcase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "HelloWorld"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToPascalcase.js` file
- Add `ConvertStringToPascalcase.js` file in `convert-string-to-pascalcase` folder

</details>

**Comment by Dheeraj0014** [comment]
!assign
