### ISSUE TITLE
Write a Kotlin program to convert string to pascalcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4096]
### Description

Write a Kotlin program to convert string to pascalcase

Pascalcase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "HelloWorld"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToPascalcase.kt` file
- Add `ConvertStringToPascalcase.kt` file in `convert-string-to-pascalcase` folder

</details>

**Comment by rksp25** [comment]
!assign
