### ISSUE TITLE
Write a Ruby program to convert string to pascalcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4101]
### Description

Write a Ruby program to convert string to pascalcase

Pascalcase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "HelloWorld"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToPascalcase.rb` file
- Add `ConvertStringToPascalcase.rb` file in `convert-string-to-pascalcase` folder

</details>

**Comment by rafaover** [comment]
!assign
