### ISSUE TITLE
Write a TypeScript program to convert string to pascalcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4105]
### Description

Write a TypeScript program to convert string to pascalcase

Pascalcase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "HelloWorld"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToPascalcase.ts` file
- Add `ConvertStringToPascalcase.ts` file in `convert-string-to-pascalcase` folder

</details>

**Comment by Arbaz23** [comment]
hello, can i take this issue ?

**Comment by Avicenne-b** [comment]
!assign

**Comment by Avicenne-b** [comment]
!assign
