### ISSUE TITLE
Write a C program to print pattern 1

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4114]
### Description

Write a C program to print pattern 1

```
Input  : 5

Output :
1
1 2 
1 2 3
1 2 3 4
1 2 3 4 5
```

<sub>Contributed by - @PraaneshSelvaraj</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintPattern1.c` file
- Add `PrintPattern1.c` file in `print-pattern-1` folder

</details>

**Comment by kituuu** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @kituuu,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by roshan798** [comment]
!assign

**Comment by AdityaNarayanPradhan** [comment]
!assign

**Comment by PavanKumarCB** [comment]
!assign

**Comment by PavanKumarCB** [comment]
hey i think there already exists a file for this issue in the folder. Can u please confirm...?
