### ISSUE TITLE
Write a C# program to print pattern 1

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4115]
### Description

Write a C# program to print pattern 1

```
Input  : 5

Output :
1
1 2 
1 2 3
1 2 3 4
1 2 3 4 5
```

<sub>Contributed by - @PraaneshSelvaraj</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintPattern1.cs` file
- Add `PrintPattern1.cs` file in `print-pattern-1` folder

</details>

**Comment by roberanegussie** [comment]
!assign

**Comment by roberanegussie** [comment]
I have created a PR #7155 kindly review.
