### ISSUE TITLE
Write a C++ program to print pattern 1

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4116]
### Description

Write a C++ program to print pattern 1

```
Input  : 5

Output :
1
1 2 
1 2 3
1 2 3 4
1 2 3 4 5
```

<sub>Contributed by - @PraaneshSelvaraj</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintPattern1.cpp` file
- Add `PrintPattern1.cpp` file in `print-pattern-1` folder

</details>

**Comment by pramaai** [comment]
!assign

**Comment by pramaai** [comment]
@harshraj8843  Please review fed1828d9cdc3c186eaaf600b82e15af679439d9
