### ISSUE TITLE
Write a GO program to print pattern 1

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4119]
### Description

Write a GO program to print pattern 1

```
Input  : 5

Output :
1
1 2 
1 2 3
1 2 3 4
1 2 3 4 5
```

<sub>Contributed by - @PraaneshSelvaraj</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `program/print_pattern_1.go` file
- Add `print_pattern_1.go` file in `print-pattern-1` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @MadhuS-1605,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by MadhuS-1605** [comment]
Sorry was occupied with other work. Will restart to contribute. Apologies for the issue.

**Comment by harshraj8843** [comment]
Hey @MadhuS-1605 

We are testing our new script #5709, no worries 🤗

**Comment by vedantpople4** [comment]
!assign
