### ISSUE TITLE
Write a Java program to print pattern 1

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4121]
### Description

Write a Java program to print pattern 1

```
Input  : 5

Output :
1
1 2 
1 2 3
1 2 3 4
1 2 3 4 5
```

<sub>Contributed by - @PraaneshSelvaraj</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintPattern1.java` file
- Add `PrintPattern1.java` file in `print-pattern-1` folder

</details>

**Comment by 123shuklaayush** [comment]
Please could you assign this to me

**Comment by harshraj8843** [comment]
Hey @123shuklaayush 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by 123shuklaayush** [comment]
!assign
