### ISSUE TITLE
Write a JavaScript program to print pattern 1

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4122]
### Description

Write a JavaScript program to print pattern 1

```
Input  : 5

Output :
1
1 2 
1 2 3
1 2 3 4
1 2 3 4 5
```

<sub>Contributed by - @PraaneshSelvaraj</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintPattern1.js` file
- Add `PrintPattern1.js` file in `print-pattern-1` folder

</details>

**Comment by manishgupta416** [comment]
Can you assign to me?

**Comment by PraaneshSelvaraj** [comment]
type !assign in the comment, You will be assigned to this issue

**Comment by vedha-vikash-pixel** [comment]
!assign
