### ISSUE TITLE
Write a GO program to print ascii value of a character

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4143]
### Description

Write a GO program to print ascii value of a character

ASCII value is the numeric representation of a character. For example, the ASCII value of the character 'A' is 65. The ASCII value of the character 'a' is 97. The ASCII value of the character '0' is 48. The ASCII value of the character ' ' is 32.

```
Input  : A
Output : 65
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/print_ascii_value_of_a_character.go` file
- Add `print_ascii_value_of_a_character.go` file in `print-ascii-value-of-a-character` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @MadhuS-1605,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by vedantpople4** [comment]
!assign
