### ISSUE TITLE
Write a Python program to print ascii value of a character

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4151]
### Description

Write a Python program to print ascii value of a character

ASCII value is the numeric representation of a character. For example, the ASCII value of the character 'A' is 65. The ASCII value of the character 'a' is 97. The ASCII value of the character '0' is 48. The ASCII value of the character ' ' is 32.

```
Input  : A
Output : 65
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/print-ascii-value-of-a-character.py` file
- Add `print-ascii-value-of-a-character.py` file in `print-ascii-value-of-a-character` folder

</details>

**Comment by amitbatra31** [comment]
please assign this to me

**Comment by harshraj8843** [comment]
Hey @amitbatra31 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by amitbatra31** [comment]
ok

> Hey @amitbatra31
> 
> You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned
> 
> ```
> !assign
> ```

okay

**Comment by amitbatra31** [comment]
!assign
