### ISSUE TITLE
Write a C++ program to find the maximum sum of a contiguous subarray

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4170]
### Description

Write a C++ program to find the maximum sum of a contiguous subarray

Maximum subarray problem is the task of finding the contiguous subarray within a one-dimensional array of numbers which has the largest sum. For example, for the sequence of values `−2, 1, −3, 4, −1, 2, 1, −5, 4;` the contiguous subarray with the largest sum is `4, −1, 2, 1,` with sum `6`.

```
Input  : [-2, -3, 4, -1, -2, 1, 5, -3]
Output : 7
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheMaximumSumOfAContiguousSubarray.cpp` file
- Add `FindTheMaximumSumOfAContiguousSubarray.cpp` file in `find-the-maximum-sum-of-a-contiguous-subarray` folder

</details>

**Comment by Dheeraj0014** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Dheeraj0014,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by cacti23** [comment]
!assign
