### ISSUE TITLE
Write a C program to calculate the permutation of n objects taken r at a time

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4195]
### Description

Write a C program to calculate the permutation of n objects taken r at a time

Permutation is an arrangement of objects in a particular order. The number of permutations on n objects taken r at a time is given by the formula n!/(n-r)!

```
Input  : 5, 2
Output : 20
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CalculateThePermutationOfNObjectsTakenRAtATime.c` file
- Add `CalculateThePermutationOfNObjectsTakenRAtATime.c` file in `calculate-the-permutation-of-n-objects-taken-r-at-a-time` folder

</details>

**Comment by kituuu** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @kituuu,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Osher160** [comment]
!assign
