### ISSUE TITLE
Write a JavaScript program to calculate the permutation of n objects taken r at a time

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4203]
### Description

Write a JavaScript program to calculate the permutation of n objects taken r at a time

Permutation is an arrangement of objects in a particular order. The number of permutations on n objects taken r at a time is given by the formula n!/(n-r)!

```
Input  : 5, 2
Output : 20
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CalculateThePermutationOfNObjectsTakenRAtATime.js` file
- Add `CalculateThePermutationOfNObjectsTakenRAtATime.js` file in `calculate-the-permutation-of-n-objects-taken-r-at-a-time` folder

</details>

**Comment by BrokenDesign** [comment]
!assign
