### ISSUE TITLE
Write a Python program to calculate the permutation of n objects taken r at a time

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4208]
### Description

Write a Python program to calculate the permutation of n objects taken r at a time

Permutation is an arrangement of objects in a particular order. The number of permutations on n objects taken r at a time is given by the formula n!/(n-r)!

```
Input  : 5, 2
Output : 20
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/calculate-the-permutation-of-n-objects-taken-r-at-a-time.py` file
- Add `calculate-the-permutation-of-n-objects-taken-r-at-a-time.py` file in `calculate-the-permutation-of-n-objects-taken-r-at-a-time` folder

</details>

**Comment by BrokenDesign** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @BrokenDesign, this issue is already assigned to @Mulayam13986 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
