### ISSUE TITLE
Write a TypeScript program to calculate the permutation of n objects taken r at a time

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4214]
### Description

Write a TypeScript program to calculate the permutation of n objects taken r at a time

Permutation is an arrangement of objects in a particular order. The number of permutations on n objects taken r at a time is given by the formula n!/(n-r)!

```
Input  : 5, 2
Output : 20
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CalculateThePermutationOfNObjectsTakenRAtATime.ts` file
- Add `CalculateThePermutationOfNObjectsTakenRAtATime.ts` file in `calculate-the-permutation-of-n-objects-taken-r-at-a-time` folder

</details>

**Comment by Mulayam13986** [comment]
!assign

**Comment by BrokenDesign** [comment]
!assign

**Comment by BrokenDesign** [comment]
Don't know where you want it committed to. Noticed you have this open for a bunch of languages, wondered why? Reason I ask is I can could write for a bunch of them if you're doing it for some benchmarking or something. 
```js
function factorial(num: number) : number {
    if (num == 0) return 1
    return num * factorial(num - 1)
}

function permutations(total: number, sample:number) : number {
  if(total>sample){
    return factorial(total)/factorial(total-sample)!
  } else {
    throw new Error(`ERROR: supplied total > sample; permutations(total=${total}, sample=${sample}, total`)
  }
}

console.log(permutations(5, 2))
```
