### ISSUE TITLE
Write a C program to find cube root of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4216]
### Description

Write a C program to find cube root of a number

```
Input  : 27
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindCubeRootOfANumber.c` file
- Add `FindCubeRootOfANumber.c` file in `find-cube-root-of-a-number` folder

</details>

**Comment by kituuu** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @kituuu,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by harshraj8843** [comment]
Hey @pokharel-nishan 

I am unable to find any PR for this issue

Could you please provide the link to the PR?

**Comment by harshraj8843** [comment]
Hey @pokharel-nishan 

Sorry for the confusion,

You have committed `3 files` in #6617, but linked only one issue `Closes #4404`

We may have missed it while reviewing.

---

To prevent this kind of situation, please link all the issues in the PR (if contributing to more than `1 file`)

`Closes #4404`
`Closes #4216`
`Closes #4314`
