### ISSUE TITLE
Write a C++ program to find cube root of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4218]
### Description

Write a C++ program to find cube root of a number

```
Input  : 27
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindCubeRootOfANumber.cpp` file
- Add `FindCubeRootOfANumber.cpp` file in `find-cube-root-of-a-number` folder

</details>

**Comment by Medmly20208** [comment]
!assign
