### ISSUE TITLE
Write a Haskell program to find cube root of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4222]
### Description

Write a Haskell program to find cube root of a number

```
Input  : 27
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_cube_root_of_a_number.hs` file
- Add `find_cube_root_of_a_number.hs` file in `find-cube-root-of-a-number` folder

</details>

**Comment by esivakumar18** [comment]
!assign
