### ISSUE TITLE
Write a Java program to find cube root of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4223]
### Description

Write a Java program to find cube root of a number

```
Input  : 27
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindCubeRootOfANumber.java` file
- Add `FindCubeRootOfANumber.java` file in `find-cube-root-of-a-number` folder

</details>

**Comment by rksp25** [comment]
!assign
