### ISSUE TITLE
Write a JavaScript program to find cube root of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4224]
### Description

Write a JavaScript program to find cube root of a number

```
Input  : 27
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindCubeRootOfANumber.js` file
- Add `FindCubeRootOfANumber.js` file in `find-cube-root-of-a-number` folder

</details>

**Comment by ZZirbel** [comment]
!assign
