### ISSUE TITLE
Write a PHP program to find cube root of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4228]
### Description

Write a PHP program to find cube root of a number

```
Input  : 27
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_cube_root_of_a_number.php` file
- Add `find_cube_root_of_a_number.php` file in `find-cube-root-of-a-number` folder

</details>

**Comment by esivakumar18** [comment]
!assign
