### ISSUE TITLE
Write a Python program to find cube root of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4229]
### Description

Write a Python program to find cube root of a number

```
Input  : 27
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-cube-root-of-a-number.py` file
- Add `find-cube-root-of-a-number.py` file in `find-cube-root-of-a-number` folder

</details>

**Comment by dalilabesseghir** [comment]
!assign
