### ISSUE TITLE
Write a TypeScript program to find cube root of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4235]
### Description

Write a TypeScript program to find cube root of a number

```
Input  : 27
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindCubeRootOfANumber.ts` file
- Add `FindCubeRootOfANumber.ts` file in `find-cube-root-of-a-number` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
