### ISSUE TITLE
Write a C program to convert days to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4266]
### Description

Write a C program to convert days to hours

1 day = 24 hours

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertDaysToHours.c` file
- Add `ConvertDaysToHours.c` file in `convert-days-to-hours` folder

</details>

**Comment by Osher160** [comment]
!assign
