### ISSUE TITLE
Write a JavaScript program to convert days to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4274]
### Description

Write a JavaScript program to convert days to hours

1 day = 24 hours

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertDaysToHours.js` file
- Add `ConvertDaysToHours.js` file in `convert-days-to-hours` folder

</details>

**Comment by chaitanya-24** [comment]
Assign me

**Comment by Dheeraj0014** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Dheeraj0014,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by 0ME9A** [comment]
!assign
