### ISSUE TITLE
Write a Julia program to convert days to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4275]
### Description

Write a Julia program to convert days to hours

1 day = 24 hours

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-days-to-hours.jl` file
- Add `convert-days-to-hours.jl` file in `convert-days-to-hours` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
