### ISSUE TITLE
Write a Kotlin program to convert days to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4276]
### Description

Write a Kotlin program to convert days to hours

1 day = 24 hours

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertDaysToHours.kt` file
- Add `ConvertDaysToHours.kt` file in `convert-days-to-hours` folder

</details>

**Comment by rksp25** [comment]
!assign
