### ISSUE TITLE
Write a Python program to convert days to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4279]
### Description

Write a Python program to convert days to hours

1 day = 24 hours

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-days-to-hours.py` file
- Add `convert-days-to-hours.py` file in `convert-days-to-hours` folder

</details>

**Comment by PraaneshSelvaraj** [comment]
!assign
