### ISSUE TITLE
Write a R program to convert days to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4280]
### Description

Write a R program to convert days to hours

1 day = 24 hours

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_days_to_hours.r` file
- Add `convert_days_to_hours.r` file in `convert-days-to-hours` folder

</details>

**Comment by esivakumar18** [comment]
!assign
