### ISSUE TITLE
Write a Scala program to convert days to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4283]
### Description

Write a Scala program to convert days to hours

1 day = 24 hours

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convertDaysToHours.scala` file
- Add `convertDaysToHours.scala` file in `convert-days-to-hours` folder

</details>

**Comment by ritikal167** [comment]
!assign

**Comment by ritikal167** [comment]
@harshraj8843  Can you please add the label hacktoberfest also in this issue ?

**Comment by harshraj8843** [comment]
Sorry, but this repo has been `excluded` from Hacktoberfest 2022

**Comment by ritikal167** [comment]
Can you suggest any repo which is included in Hacktoberfest 2022

**Comment by harshraj8843** [comment]
Not sure, but maybe you can try this 👉🏻 https://github.com/codinasion/program/discussions/4032

**Comment by ritikal167** [comment]
Sure Thanks :)
