### ISSUE TITLE
Write a TypeScript program to convert days to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4285]
### Description

Write a TypeScript program to convert days to hours

1 day = 24 hours

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertDaysToHours.ts` file
- Add `ConvertDaysToHours.ts` file in `convert-days-to-hours` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
