### ISSUE TITLE
Write a Java program to convert time from 24-hour to 12-hour format

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4294]
### Description

Write a Java program to convert time from 24-hour to 12-hour format

```
Input  : 12:05:45
Output : 12:05:45PM
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertTimeFrom24-hourTo12-hourFormat.java` file
- Add `ConvertTimeFrom24-hourTo12-hourFormat.java` file in `convert-time-from-24-hour-to-12-hour-format` folder

</details>

**Comment by reinem** [comment]
!assign
