### ISSUE TITLE
Write a Perl program to convert time from 24-hour to 12-hour format

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4298]
### Description

Write a Perl program to convert time from 24-hour to 12-hour format

```
Input  : 12:05:45
Output : 12:05:45PM
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_time_from_24-hour_to_12-hour_format.pl` file
- Add `convert_time_from_24-hour_to_12-hour_format.pl` file in `convert-time-from-24-hour-to-12-hour-format` folder

</details>

**Comment by ddinh0411** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @ddinh0411, this issue is already assigned to @ddinh0411 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
