### ISSUE TITLE
Write a C program to find square of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#43]
### Description

Write a C program to find square of a number

```
Input  : 5
Output : 25
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSquareOfANumber.c` file
- Add `FindSquareOfANumber.c` file in `find-square-of-a-number` folder

</details>

**Comment by KaptainCS3** [comment]
assign me

**Comment by SidharthSarangi** [comment]
!assign

**Comment by Osher160** [comment]
!assign
