### ISSUE TITLE
Write a Python program to convert time from 24-hour to 12-hour format

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4300]
### Description

Write a Python program to convert time from 24-hour to 12-hour format

```
Input  : 12:05:45
Output : 12:05:45PM
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-time-from-24-hour-to-12-hour-format.py` file
- Add `convert-time-from-24-hour-to-12-hour-format.py` file in `convert-time-from-24-hour-to-12-hour-format` folder

</details>

**Comment by dalilabesseghir** [comment]
!assign
