### ISSUE TITLE
Write a C program to convert minutes to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4314]
### Description

Write a C program to convert minutes to days

1 day = 24 hours = 1440 minutes

```
Input  : 7200
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMinutesToDays.c` file
- Add `ConvertMinutesToDays.c` file in `convert-minutes-to-days` folder

</details>

**Comment by pokharel-nishan** [comment]
!assign

**Comment by pokharel-nishan** [comment]
@harshraj8843  I already submitted the solution to this problem. And, the solution is merged into the main repository. But, this issue isn't closed yet. Can you please explain the reason.

**Comment by harshraj8843** [comment]
https://github.com/codinasion/program/issues/4216#issuecomment-1464740706
