### ISSUE TITLE
Write a C++ program to convert minutes to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4316]
### Description

Write a C++ program to convert minutes to days

1 day = 24 hours = 1440 minutes

```
Input  : 7200
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMinutesToDays.cpp` file
- Add `ConvertMinutesToDays.cpp` file in `convert-minutes-to-days` folder

</details>

**Comment by akash-1107** [comment]
Please assign this to me

**Comment by akash-1107** [comment]
Can u please add hacktoberfest tag in it .

**Comment by harshraj8843** [comment]
Hey @akash-1107 

You can comment `!assign` on any `good first issue` you want to contribute to , to be auto-assigned

```
!assign
```

**Comment by harshraj8843** [comment]
> Can u please add hacktoberfest tag in it .

This repo has been `excluded` from Hacktoberfest 2022

**Comment by akash-1107** [comment]
Thanks for the information

**Comment by Osher160** [comment]
!assign
