### ISSUE TITLE
Write a JavaScript program to convert minutes to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4322]
### Description

Write a JavaScript program to convert minutes to days

1 day = 24 hours = 1440 minutes

```
Input  : 7200
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMinutesToDays.js` file
- Add `ConvertMinutesToDays.js` file in `convert-minutes-to-days` folder

</details>

**Comment by samilieberman** [comment]
!assign

**Comment by samilieberman** [comment]
I put a PR for this issue: https://github.com/codinasion/program/pull/4798
