### ISSUE TITLE
Write a Kotlin program to convert minutes to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4324]
### Description

Write a Kotlin program to convert minutes to days

1 day = 24 hours = 1440 minutes

```
Input  : 7200
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMinutesToDays.kt` file
- Add `ConvertMinutesToDays.kt` file in `convert-minutes-to-days` folder

</details>

**Comment by mrajen27** [comment]
!assign

**Comment by mrajen27** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @mrajen27, this issue is already assigned to @mrajen27 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
