### ISSUE TITLE
Write a Python program to convert minutes to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4327]
### Description

Write a Python program to convert minutes to days

1 day = 24 hours = 1440 minutes

```
Input  : 7200
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-minutes-to-days.py` file
- Add `convert-minutes-to-days.py` file in `convert-minutes-to-days` folder

</details>

**Comment by dalilabesseghir** [comment]
hi, it's my first contribution, 
can you assigne it to me, please ?

**Comment by akansharai2023** [comment]
!assign
