### ISSUE TITLE
Write a Swift program to convert minutes to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4332]
### Description

Write a Swift program to convert minutes to days

1 day = 24 hours = 1440 minutes

```
Input  : 7200
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMinutesToDays.swift` file
- Add `ConvertMinutesToDays.swift` file in `convert-minutes-to-days` folder

</details>

**Comment by esivakumar18** [comment]
!assign
