### ISSUE TITLE
Write a C++ program to check lower case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4337]
### Description

Write a C++ program to check lower case

Check if given character is lower case (a-z).

```
Input  : a
Output : Lower Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckLowerCase.cpp` file
- Add `CheckLowerCase.cpp` file in `check-lower-case` folder

</details>

**Comment by yashasvini121** [comment]
!assign
