### ISSUE TITLE
Write a Dart program to check lower case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4338]
### Description

Write a Dart program to check lower case

Check if given character is lower case (a-z).

```
Input  : a
Output : Lower Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/check_lower_case.dart` file
- Add `check_lower_case.dart` file in `check-lower-case` folder

</details>

**Comment by Tushar12222** [comment]
!assign
