### ISSUE TITLE
Write a Java program to check lower case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4342]
### Description

Write a Java program to check lower case

Check if given character is lower case (a-z).

```
Input  : a
Output : Lower Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckLowerCase.java` file
- Add `CheckLowerCase.java` file in `check-lower-case` folder

</details>

**Comment by rksp25** [comment]
!assign
