### ISSUE TITLE
Write a JavaScript program to check lower case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4343]
### Description

Write a JavaScript program to check lower case

Check if given character is lower case (a-z).

```
Input  : a
Output : Lower Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckLowerCase.js` file
- Add `CheckLowerCase.js` file in `check-lower-case` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
