### ISSUE TITLE
Write a Perl program to check lower case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4346]
### Description

Write a Perl program to check lower case

Check if given character is lower case (a-z).

```
Input  : a
Output : Lower Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/check_lower_case.pl` file
- Add `check_lower_case.pl` file in `check-lower-case` folder

</details>

**Comment by esivakumar18** [comment]
!assign
