### ISSUE TITLE
Write a Ruby program to check lower case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4350]
### Description

Write a Ruby program to check lower case

Check if given character is lower case (a-z).

```
Input  : a
Output : Lower Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckLowerCase.rb` file
- Add `CheckLowerCase.rb` file in `check-lower-case` folder

</details>

**Comment by PraaneshSelvaraj** [comment]
!assign

**Comment by jfinley6** [comment]
!assign
