### ISSUE TITLE
Write a TypeScript program to check lower case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4354]
### Description

Write a TypeScript program to check lower case

Check if given character is lower case (a-z).

```
Input  : a
Output : Lower Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckLowerCase.ts` file
- Add `CheckLowerCase.ts` file in `check-lower-case` folder

</details>

**Comment by tahakocabuga** [comment]
!assign
