### ISSUE TITLE
Write a C++ program to find area of a square

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#436]
### Description

Write a C++ program to find area of a square

Area of square = `Side`^2

```
Side : 2

Area : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAreaOfASquare.cpp` file
- Add `FindAreaOfASquare.cpp` file in `find-area-of-a-square` folder

</details>

**Comment by destroyer5067** [comment]
Hey, can you assign this issue to me?

**Comment by destroyer5067** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @destroyer5067 

Please comment `!assign` on the issue you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by AbhinavPrabhat01** [comment]
!assign
