### ISSUE TITLE
Write a C# program to find sum of ap series

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4362]
### Description

Write a C# program to find sum of ap series

An arithmetic progression (AP) is a sequence of numbers such that the difference of any two consecutive terms is a constant. The nth term of an AP is given by the formula a<sub>n</sub> = a<sub>1</sub> + (n-1)d where a<sub>1</sub> is the first term and d is the common difference.

```
a = 2
n = 5
d = 3

Output : 40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSumOfApSeries.cs` file
- Add `FindSumOfApSeries.cs` file in `find-sum-of-ap-series` folder

</details>

**Comment by neswatch** [comment]
!assign
