### ISSUE TITLE
Write a C++ program to find sum of ap series

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4363]
### Description

Write a C++ program to find sum of ap series

An arithmetic progression (AP) is a sequence of numbers such that the difference of any two consecutive terms is a constant. The nth term of an AP is given by the formula a<sub>n</sub> = a<sub>1</sub> + (n-1)d where a<sub>1</sub> is the first term and d is the common difference.

```
Input  : 2, 5, 3
Output : 40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSumOfApSeries.cpp` file
- Add `FindSumOfApSeries.cpp` file in `find-sum-of-ap-series` folder

</details>

**Comment by RohithBoppey** [comment]
But how should the input be? That I am not clear about. By the way I would like to work on the issue.

**Comment by harshraj8843** [comment]
> But how should the input be? That I am not clear about.

You can simply use a static array and run the program 👍🏻 

---

You can comment `!assign` on any `god first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by RohithBoppey** [comment]
!assign
