### ISSUE TITLE
Write a Java program to find sum of ap series

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4368]
### Description

Write a Java program to find sum of ap series

An arithmetic progression (AP) is a sequence of numbers such that the difference of any two consecutive terms is a constant. The nth term of an AP is given by the formula a<sub>n</sub> = a<sub>1</sub> + (n-1)d where a<sub>1</sub> is the first term and d is the common difference.

```
a = 2
n = 5
d = 3

Output : 40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSumOfApSeries.java` file
- Add `FindSumOfApSeries.java` file in `find-sum-of-ap-series` folder

</details>

**Comment by brundabharadwaj** [comment]
!assign

**Comment by brundabharadwaj** [comment]
Hi @harshraj8843 , This output mentioned here appears to be wrong,
Please refer this image, and let me know if my understanding is not correct.
![image](https://user-images.githubusercontent.com/49773125/198036789-5b89dcec-199b-4ce0-8520-0df89722b04c.png)

**Comment by harshraj8843** [comment]
Hey @brundabharadwaj 

The second one is the right answer i.e. 40
a = 2
n = 5
d = 3

Thanks for letting me know 👍🏻

**Comment by harshraj8843** [comment]
Hey @brundabharadwaj,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
