### ISSUE TITLE
Write a JavaScript program to find sum of ap series

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4369]
### Description

Write a JavaScript program to find sum of ap series

An arithmetic progression (AP) is a sequence of numbers such that the difference of any two consecutive terms is a constant. The nth term of an AP is given by the formula a<sub>n</sub> = a<sub>1</sub> + (n-1)d where a<sub>1</sub> is the first term and d is the common difference.

```
a = 2
n = 5
d = 3

Output : 40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSumOfApSeries.js` file
- Add `FindSumOfApSeries.js` file in `find-sum-of-ap-series` folder

</details>

**Comment by avireni** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @avireni,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Coder-12-ux** [comment]
!assign
