### ISSUE TITLE
Write a Python program to find sum of ap series

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4374]
### Description

Write a Python program to find sum of ap series

An arithmetic progression (AP) is a sequence of numbers such that the difference of any two consecutive terms is a constant. The nth term of an AP is given by the formula a<sub>n</sub> = a<sub>1</sub> + (n-1)d where a<sub>1</sub> is the first term and d is the common difference.

```
a = 2
n = 5
d = 3

Output : 40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-sum-of-ap-series.py` file
- Add `find-sum-of-ap-series.py` file in `find-sum-of-ap-series` folder

</details>

**Comment by akansharai2023** [comment]
!assign

**Comment by joao-vitor-souza** [comment]
@harshraj8843, could you explain what `2, 5, 3` means respectively?

**Comment by harshraj8843** [comment]
Hey @joao-vitor-souza 

Sorry for the late reply

This issue was raised in #4368 and I forgot to update the issues

Thanks for letting me know.

**Comment by harsha-desaraju** [comment]
!assign
