### ISSUE TITLE
Write a Java program to convert days to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4389]
### Description

Write a Java program to convert days to weeks

1 week = 7 days

```
Input  : 35
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertDaysToWeeks.java` file
- Add `ConvertDaysToWeeks.java` file in `convert-days-to-weeks` folder

</details>

**Comment by SpirosArk** [comment]
!assign
