### ISSUE TITLE
Write a JavaScript program to convert days to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4390]
### Description

Write a JavaScript program to convert days to weeks

1 week = 7 days

```
Input  : 35
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertDaysToWeeks.js` file
- Add `ConvertDaysToWeeks.js` file in `convert-days-to-weeks` folder

</details>

**Comment by K1118** [comment]
!assign

**Comment by manishankardurai** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @manishankardurai, this issue is already assigned to @K1118 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
