### ISSUE TITLE
Write a Julia program to convert days to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4391]
### Description

Write a Julia program to convert days to weeks

1 week = 7 days

```
Input  : 35
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-days-to-weeks.jl` file
- Add `convert-days-to-weeks.jl` file in `convert-days-to-weeks` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
