### ISSUE TITLE
Write a Kotlin program to convert days to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4392]
### Description

Write a Kotlin program to convert days to weeks

1 week = 7 days

```
Input  : 35
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertDaysToWeeks.kt` file
- Add `ConvertDaysToWeeks.kt` file in `convert-days-to-weeks` folder

</details>

**Comment by mrajen27** [comment]
!assign
