### ISSUE TITLE
Write a PHP program to convert days to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4394]
### Description

Write a PHP program to convert days to weeks

1 week = 7 days

```
Input  : 35
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_days_to_weeks.php` file
- Add `convert_days_to_weeks.php` file in `convert-days-to-weeks` folder

</details>

**Comment by tom-laplace** [comment]
!assign
