### ISSUE TITLE
Write a Python program to convert days to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4395]
### Description

Write a Python program to convert days to weeks

1 week = 7 days

```
Input  : 35
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-days-to-weeks.py` file
- Add `convert-days-to-weeks.py` file in `convert-days-to-weeks` folder

</details>

**Comment by dalilabesseghir** [comment]
!assign
