### ISSUE TITLE
Write a Rust program to convert days to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4398]
### Description

Write a Rust program to convert days to weeks

1 week = 7 days

```
Input  : 35
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_days_to_weeks.rs` file
- Add `convert_days_to_weeks.rs` file in `convert-days-to-weeks` folder

</details>

**Comment by hugosmoreira** [comment]
!assign
