### ISSUE TITLE
Write a Java program to find area of a square

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#440]
### Description

Write a Java program to find area of a square

Area of square = `Side`^2

```
Side : 2

Area : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAreaOfASquare.java` file
- Add `FindAreaOfASquare.java` file in `find-area-of-a-square` folder

</details>

**Comment by Mahak008** [comment]
!assign

**Comment by sharvil1205** [comment]
!assign
