### ISSUE TITLE
Write a Swift program to convert days to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4400]
### Description

Write a Swift program to convert days to weeks

1 week = 7 days

```
Input  : 35
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertDaysToWeeks.swift` file
- Add `ConvertDaysToWeeks.swift` file in `convert-days-to-weeks` folder

</details>

**Comment by esivakumar18** [comment]
!assign
