### ISSUE TITLE
Write a TypeScript program to convert days to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4401]
### Description

Write a TypeScript program to convert days to weeks

1 week = 7 days

```
Input  : 35
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertDaysToWeeks.ts` file
- Add `ConvertDaysToWeeks.ts` file in `convert-days-to-weeks` folder

</details>

**Comment by tanishq-singh-2301** [comment]
!assign
