### ISSUE TITLE
Write a C program to convert a string to an integer

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4404]
### Description

Write a C program to convert a string to an integer

```
Input  : "123"
Output : 123
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertAStringToAnInteger.c` file
- Add `ConvertAStringToAnInteger.c` file in `convert-a-string-to-an-integer` folder

</details>

**Comment by pokharel-nishan** [comment]
!assign
