### ISSUE TITLE
Write a C# program to convert a string to an integer

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4405]
### Description

Write a C# program to convert a string to an integer

```
Input  : "123"
Output : 123
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertAStringToAnInteger.cs` file
- Add `ConvertAStringToAnInteger.cs` file in `convert-a-string-to-an-integer` folder

</details>

**Comment by roberanegussie** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @roberanegussie, this issue is already assigned to @anandfresh !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
