### ISSUE TITLE
Write a C++ program to convert a string to an integer

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4406]
### Description

Write a C++ program to convert a string to an integer

```
Input  : "123"
Output : 123
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertAStringToAnInteger.cpp` file
- Add `ConvertAStringToAnInteger.cpp` file in `convert-a-string-to-an-integer` folder

</details>

**Comment by Deep-Chandra-Mathpal** [comment]
!assign
