### ISSUE TITLE
Write a GO program to convert a string to an integer

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4409]
### Description

Write a GO program to convert a string to an integer

```
Input  : "123"
Output : 123
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_a_string_to_an_integer.go` file
- Add `convert_a_string_to_an_integer.go` file in `convert-a-string-to-an-integer` folder

</details>

**Comment by sureshr3git** [comment]
!assign
