### ISSUE TITLE
Write a JavaScript program to find area of a square

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#441]
### Description

Write a JavaScript program to find area of a square

Area of square = `Side`^2

```
Side : 2

Area : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAreaOfASquare.js` file
- Add `FindAreaOfASquare.js` file in `find-area-of-a-square` folder

</details>

**Comment by praveenscience** [comment]
!assign
