### ISSUE TITLE
Write a JavaScript program to convert a string to an integer

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4412]
### Description

Write a JavaScript program to convert a string to an integer

```
Input  : "123"
Output : 123
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertAStringToAnInteger.js` file
- Add `ConvertAStringToAnInteger.js` file in `convert-a-string-to-an-integer` folder

</details>

**Comment by avireni** [comment]
!assign
