### ISSUE TITLE
Write a Julia program to convert a string to an integer

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4413]
### Description

Write a Julia program to convert a string to an integer

```
Input  : "123"
Output : 123
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-a-string-to-an-integer.jl` file
- Add `convert-a-string-to-an-integer.jl` file in `convert-a-string-to-an-integer` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
