### ISSUE TITLE
Write a Python program to convert a string to an integer

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4417]
### Description

Write a Python program to convert a string to an integer

```
Input  : "123"
Output : 123
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-a-string-to-an-integer.py` file
- Add `convert-a-string-to-an-integer.py` file in `convert-a-string-to-an-integer` folder

</details>

**Comment by AryanKansagara** [comment]
hello there I just created a pull request for the same

**Comment by harshraj8843** [comment]
Hey @AryanKansagara 

Please be auto-assigned to the issue by commenting `!assign`, before raising a PR (to prevent any conflict) 🤗 

```
!assign
```

**Comment by dankokonate** [comment]
!assign
