### ISSUE TITLE
Write a Scala program to convert a string to an integer

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4421]
### Description

Write a Scala program to convert a string to an integer

```
Input  : "123"
Output : 123
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convertAStringToAnInteger.scala` file
- Add `convertAStringToAnInteger.scala` file in `convert-a-string-to-an-integer` folder

</details>

**Comment by ani2108** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @ani2108,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
