### ISSUE TITLE
Write a C program to print numbers from n to 1 without using a loop

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4428]
### Description

Write a C program to print numbers from n to 1 without using a loop

```
Input  : 5
Output : 5 4 3 2 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintNumbersFromNTo1WithoutUsingALoop.c` file
- Add `PrintNumbersFromNTo1WithoutUsingALoop.c` file in `print-numbers-from-n-to-1-without-using-a-loop` folder

</details>

**Comment by mdArshad10** [comment]
i can solve it 
plz assign it to me

**Comment by harshraj8843** [comment]
Hey @mdArshad10,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Osher160** [comment]
!assign
