### ISSUE TITLE
Write a Kotlin program to find area of a square

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#443]
### Description

Write a Kotlin program to find area of a square

Area of square = `Side`^2

```
Side : 2

Area : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAreaOfASquare.kt` file
- Add `FindAreaOfASquare.kt` file in `find-area-of-a-square` folder

</details>

**Comment by UsmanFani** [comment]
!assign
