### ISSUE TITLE
Write a C++ program to print numbers from n to 1 without using a loop

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4430]
### Description

Write a C++ program to print numbers from n to 1 without using a loop

```
Input  : 5
Output : 5 4 3 2 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintNumbersFromNTo1WithoutUsingALoop.cpp` file
- Add `PrintNumbersFromNTo1WithoutUsingALoop.cpp` file in `print-numbers-from-n-to-1-without-using-a-loop` folder

</details>

**Comment by KacperTKI** [comment]
!assign
