### ISSUE TITLE
Write a Dart program to print numbers from n to 1 without using a loop

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4431]
### Description

Write a Dart program to print numbers from n to 1 without using a loop

```
Input  : 5
Output : 5 4 3 2 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/print_numbers_from_n_to_1_without_using_a_loop.dart` file
- Add `print_numbers_from_n_to_1_without_using_a_loop.dart` file in `print-numbers-from-n-to-1-without-using-a-loop` folder

</details>

**Comment by Tushar12222** [comment]
!assign
