### ISSUE TITLE
Write a Java program to print numbers from n to 1 without using a loop

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4435]
### Description

Write a Java program to print numbers from n to 1 without using a loop

```
Input  : 5
Output : 5 4 3 2 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintNumbersFromNTo1WithoutUsingALoop.java` file
- Add `PrintNumbersFromNTo1WithoutUsingALoop.java` file in `print-numbers-from-n-to-1-without-using-a-loop` folder

</details>

**Comment by abhiyadav2345** [comment]
Please assign this issue to me with the label hacktoberfest

!assign

**Comment by harshraj8843** [comment]
Hey @abhiyadav2345 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by abhiyadav2345** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @abhiyadav2345,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by sharvil1205** [comment]
!assign

**Comment by sharvil1205** [comment]
hi @harshraj8843 
Looks like this issue has been solved already

**Comment by harshraj8843** [comment]
Thanks for letting us know 👍🏻

**Comment by itsarraj** [comment]
Hello sir ,
I am new to open source contribution.
I already know java , my tech stacks & tools includes C, C++ , Python , Java, JavaScript , HTML , CSS , SQL , Bootstrap, ReactJS, ExpressJS, NodeJS & Git . I need a little help from your side to contribute to these amazing projects.
