### ISSUE TITLE
Write a PHP program to print numbers from n to 1 without using a loop

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4440]
### Description

Write a PHP program to print numbers from n to 1 without using a loop

```
Input  : 5
Output : 5 4 3 2 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/print_numbers_from_n_to_1_without_using_a_loop.php` file
- Add `print_numbers_from_n_to_1_without_using_a_loop.php` file in `print-numbers-from-n-to-1-without-using-a-loop` folder

</details>

**Comment by anandfresh** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @anandfresh,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
