### ISSUE TITLE
Write a Python program to print numbers from n to 1 without using a loop

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4441]
### Description

Write a Python program to print numbers from n to 1 without using a loop

```
Input  : 5
Output : 5 4 3 2 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/print-numbers-from-n-to-1-without-using-a-loop.py` file
- Add `print-numbers-from-n-to-1-without-using-a-loop.py` file in `print-numbers-from-n-to-1-without-using-a-loop` folder

</details>

**Comment by Medmly20208** [comment]
!assign
