### ISSUE TITLE
Write a C program to find surface area of a cuboid

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4454]
### Description

Write a C program to find surface area of a cuboid

Surface area of cuboid = 2 × (`Length` × `Width` + `Length` × `Height` + `Width` × `Height`)

```
Length : 2
Width  : 3
Height : 4

Surface area : 52
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSurfaceAreaOfACuboid.c` file
- Add `FindSurfaceAreaOfACuboid.c` file in `find-surface-area-of-a-cuboid` folder

</details>

**Comment by mdArshad10** [comment]
i can do it 
plz assign it to me

**Comment by harshraj8843** [comment]
Hey @mdArshad10,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign

**Comment by Sri01729** [comment]
!assign
