### ISSUE TITLE
Write a C++ program to find surface area of a cuboid

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4456]
### Description

Write a C++ program to find surface area of a cuboid

Surface area of cuboid = 2 × (`Length` × `Width` + `Length` × `Height` + `Width` × `Height`)

```
Length : 2
Width  : 3
Height : 4

Surface area : 52
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSurfaceAreaOfACuboid.cpp` file
- Add `FindSurfaceAreaOfACuboid.cpp` file in `find-surface-area-of-a-cuboid` folder

</details>

**Comment by Aditya-9919** [comment]
can you assign me with it

**Comment by harshraj8843** [comment]
Hey @Aditya-9919 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by tanishq-singh-2301** [comment]
!assign
