### ISSUE TITLE
Write a JavaScript program to find surface area of a cuboid

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4462]
### Description

Write a JavaScript program to find surface area of a cuboid

Surface area of cuboid = 2 × (`Length` × `Width` + `Length` × `Height` + `Width` × `Height`)

```
Length : 2
Width  : 3
Height : 4

Surface area : 52
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSurfaceAreaOfACuboid.js` file
- Add `FindSurfaceAreaOfACuboid.js` file in `find-surface-area-of-a-cuboid` folder

</details>

**Comment by danveb** [comment]
!assign

**Comment by danveb** [comment]
requesting review of pull request. Thanks!

**Comment by harshraj8843** [comment]
Hey @danveb,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by SarthakSanjay** [comment]
!assign
