### ISSUE TITLE
Write a Kotlin program to find surface area of a cuboid

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4464]
### Description

Write a Kotlin program to find surface area of a cuboid

Surface area of cuboid = 2 × (`Length` × `Width` + `Length` × `Height` + `Width` × `Height`)

```
Length : 2
Width  : 3
Height : 4

Surface area : 52
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSurfaceAreaOfACuboid.kt` file
- Add `FindSurfaceAreaOfACuboid.kt` file in `find-surface-area-of-a-cuboid` folder

</details>

**Comment by mrajen27** [comment]
!assign
