### ISSUE TITLE
Write a Python program to find surface area of a cuboid

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4467]
### Description

Write a Python program to find surface area of a cuboid

Surface area of cuboid = 2 × (`Length` × `Width` + `Length` × `Height` + `Width` × `Height`)

```
Length : 2
Width  : 3
Height : 4

Surface area : 52
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-surface-area-of-a-cuboid.py` file
- Add `find-surface-area-of-a-cuboid.py` file in `find-surface-area-of-a-cuboid` folder

</details>

**Comment by Danuragtiwari** [comment]
@harshraj8843 Assign it to me

**Comment by dalilabesseghir** [comment]
!assign

**Comment by manny-uncharted** [comment]
Assign this to me
