### ISSUE TITLE
Write a Ruby program to find surface area of a cuboid

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4469]
### Description

Write a Ruby program to find surface area of a cuboid

Surface area of cuboid = 2 × (`Length` × `Width` + `Length` × `Height` + `Width` × `Height`)

```
Length : 2
Width  : 3
Height : 4

Surface area : 52
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSurfaceAreaOfACuboid.rb` file
- Add `FindSurfaceAreaOfACuboid.rb` file in `find-surface-area-of-a-cuboid` folder

</details>

**Comment by helloshiv01** [comment]
please assign me this issue

**Comment by harshraj8843** [comment]
Hey @helloshiv01 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by helloshiv01** [comment]
!assign
