### ISSUE TITLE
Write a Rust program to find surface area of a cuboid

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4470]
### Description

Write a Rust program to find surface area of a cuboid

Surface area of cuboid = 2 × (`Length` × `Width` + `Length` × `Height` + `Width` × `Height`)

```
Length : 2
Width  : 3
Height : 4

Surface area : 52
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_surface_area_of_a_cuboid.rs` file
- Add `find_surface_area_of_a_cuboid.rs` file in `find-surface-area-of-a-cuboid` folder

</details>

**Comment by esivakumar18** [comment]
!assign

**Comment by esivakumar18** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @esivakumar18, this issue is already assigned to @esivakumar18 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
