### ISSUE TITLE
Write a Scala program to find surface area of a cuboid

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4471]
### Description

Write a Scala program to find surface area of a cuboid

Surface area of cuboid = 2 × (`Length` × `Width` + `Length` × `Height` + `Width` × `Height`)

```
Length : 2
Width  : 3
Height : 4

Surface area : 52
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/findSurfaceAreaOfACuboid.scala` file
- Add `findSurfaceAreaOfACuboid.scala` file in `find-surface-area-of-a-cuboid` folder

</details>

**Comment by plopez26DPU** [comment]
Can you assign me this task? I will work on it

**Comment by plopez26DPU** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @plopez26DPU 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by harshraj8843** [comment]
Hey @plopez26DPU,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
