### ISSUE TITLE
Write a C++ program to find second smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4479]
### Description

Write a C++ program to find second smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSecondSmallestNumberInAnArray.cpp` file
- Add `FindSecondSmallestNumberInAnArray.cpp` file in `find-second-smallest-number-in-an-array` folder

</details>

**Comment by codingkush** [comment]
!assign
