### ISSUE TITLE
Write a Ruby program to find area of a square

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#448]
### Description

Write a Ruby program to find area of a square

Area of square = `Side`^2

```
Side : 2

Area : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAreaOfASquare.rb` file
- Add `FindAreaOfASquare.rb` file in `find-area-of-a-square` folder

</details>

**Comment by PraaneshSelvaraj** [comment]
!assign
