### ISSUE TITLE
Write a GO program to find second smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4482]
### Description

Write a GO program to find second smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_second_smallest_number_in_an_array.go` file
- Add `find_second_smallest_number_in_an_array.go` file in `find-second-smallest-number-in-an-array` folder

</details>

**Comment by vedantpople4** [comment]
!assign
