### ISSUE TITLE
Write a Java program to find second smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4484]
### Description

Write a Java program to find second smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSecondSmallestNumberInAnArray.java` file
- Add `FindSecondSmallestNumberInAnArray.java` file in `find-second-smallest-number-in-an-array` folder

</details>

**Comment by harshraj8843** [comment]
Hey @SpirosArk, this issue is already assigned to @brundabharadwaj !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by SpirosArk** [comment]
Sorry never saw it!

**Comment by harshraj8843** [comment]
Hey @brundabharadwaj,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by sharvil1205** [comment]
!assign
