### ISSUE TITLE
Write a JavaScript program to find second smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4485]
### Description

Write a JavaScript program to find second smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSecondSmallestNumberInAnArray.js` file
- Add `FindSecondSmallestNumberInAnArray.js` file in `find-second-smallest-number-in-an-array` folder

</details>

**Comment by danveb** [comment]
Hey @harshraj8843, I'll work on this program. Let me know, thanks.
