### ISSUE TITLE
Write a Rust program to find area of a square

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#449]
### Description

Write a Rust program to find area of a square

Area of square = `Side`^2

```
Side : 2

Area : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_area_of_a_square.rs` file
- Add `find_area_of_a_square.rs` file in `find-area-of-a-square` folder

</details>

**Comment by esivakumar18** [comment]
!assign
