### ISSUE TITLE
Write a Python program to find second smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4490]
### Description

Write a Python program to find second smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-second-smallest-number-in-an-array.py` file
- Add `find-second-smallest-number-in-an-array.py` file in `find-second-smallest-number-in-an-array` folder

</details>

**Comment by sureshr3git** [comment]
!assign

**Comment by victoriacheng15** [comment]
Someone was assigned to the issue. Please find other issues to contribute. And make sure you type `!assign` to grab them!

Thank you
