### ISSUE TITLE
Write a Ruby program to find second smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4492]
### Description

Write a Ruby program to find second smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSecondSmallestNumberInAnArray.rb` file
- Add `FindSecondSmallestNumberInAnArray.rb` file in `find-second-smallest-number-in-an-array` folder

</details>

**Comment by PraaneshSelvaraj** [comment]
!assign
