### ISSUE TITLE
Write a C++ program to find square of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#45]
### Description

Write a C++ program to find square of a number

```
Input  : 5
Output : 25
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSquareOfANumber.cpp` file
- Add `FindSquareOfANumber.cpp` file in `find-square-of-a-number` folder

</details>

**Comment by KaptainCS3** [comment]
assign me

**Comment by KaptainCS3** [comment]
assign me

**Comment by SidharthSarangi** [comment]
!assign

**Comment by destroyer5067** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @destroyer5067, this issue is already assigned to @SidharthSarangi !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
