### ISSUE TITLE
Write a Scala program to find area of a square

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#450]
### Description

Write a Scala program to find area of a square

Area of square = `Side`^2

```
Side : 2

Area : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `findAreaOfASquare.scala` file
- Add `findAreaOfASquare.scala` file in `find-area-of-a-square` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @esivakumar18, this issue is already assigned to @anandfresh !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
