### ISSUE TITLE
Write a Java program to convert octal to binary

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4507]
### Description

Write a Java program to convert octal to binary

Octal is a base-8 number system. It uses only eight digits: 0, 1, 2, 3, 4, 5, 6, and 7. The digits are called octits. An octit is the smallest unit of information in a computer. An octit can be used to represent a single value, such as 0, 1, 2, 3, 4, 5, 6, or 7, or it can be used to represent a single state, such as on or off.

Binary is a base-2 number system. It uses only two digits: 0 and 1. The digits are called bits. A bit is the smallest unit of information in a computer. A bit can be either 0 or 1. A bit can be used to represent a single value, such as 0 or 1, or it can be used to represent a single state, such as on or off.

To convert an octal number to binary, we can use the following algorithm:

1. Convert the octal number to decimal.
2. Convert the decimal number to binary.

```
Input  : 12
Output : 1010
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertOctalToBinary.java` file
- Add `ConvertOctalToBinary.java` file in `convert-octal-to-binary` folder

</details>

**Comment by brundabharadwaj** [comment]
@harshraj8843 I would like to work on this!

**Comment by harshraj8843** [comment]
Hey @brundabharadwaj 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by brundabharadwaj** [comment]
!assign

**Comment by brundabharadwaj** [comment]
!assign

**Comment by brundabharadwaj** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @brundabharadwaj, this issue is already assigned to @brundabharadwaj !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by notpx** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @notpx, this issue is already assigned to @brundabharadwaj !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Hey @notpx,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Coder-12-ux** [comment]
!assign

**Comment by saintramon** [comment]
!assign
