### ISSUE TITLE
Write a Swift program to find area of a square

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#451]
### Description

Write a Swift program to find area of a square

Area of square = `Side`^2

```
Side : 2

Area : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAreaOfASquare.swift` file
- Add `FindAreaOfASquare.swift` file in `find-area-of-a-square` folder

</details>

**Comment by esivakumar18** [comment]
!assign
