### ISSUE TITLE
Write a TypeScript program to find area of a square

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#452]
### Description

Write a TypeScript program to find area of a square

Area of square = `Side`^2

```
Side : 2

Area : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAreaOfASquare.ts` file
- Add `FindAreaOfASquare.ts` file in `find-area-of-a-square` folder

</details>

**Comment by RShalman** [comment]
Can grab this one)

**Comment by harshraj8843** [comment]
Hey @RShalman 

Please comment `!assign` on any `good first issue` you want to contribute to, to be auto assigned

```
!assign
```

**Comment by RShalman** [comment]
!assign
