### ISSUE TITLE
Write a Kotlin program to check integer or float

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4532]
### Description

Write a Kotlin program to check integer or float

```
Input  : 1
Output : Integer
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckIntegerOrFloat.kt` file
- Add `CheckIntegerOrFloat.kt` file in `check-integer-or-float` folder

</details>

**Comment by mrajen27** [comment]
!assign
