### ISSUE TITLE
Write a PHP program to check integer or float

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4534]
### Description

Write a PHP program to check integer or float

```
Input  : 1
Output : Integer
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/check_integer_or_float.php` file
- Add `check_integer_or_float.php` file in `check-integer-or-float` folder

</details>

**Comment by savi001** [comment]
I am interested in this work
Please assign it to me
