### ISSUE TITLE
Write a Python program to check integer or float

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4535]
### Description

Write a Python program to check integer or float

```
Input  : 1
Output : Integer
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/check-integer-or-float.py` file
- Add `check-integer-or-float.py` file in `check-integer-or-float` folder

</details>

**Comment by savi001** [comment]
I am interested in this work
Please assign it to me

**Comment by Forsigg** [comment]
!assign
