### ISSUE TITLE
Write a TypeScript program to check integer or float

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4541]
### Description

Write a TypeScript program to check integer or float

```
Input  : 1
Output : Integer
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckIntegerOrFloat.ts` file
- Add `CheckIntegerOrFloat.ts` file in `check-integer-or-float` folder

</details>

**Comment by savi001** [comment]
I am interested in this work
Please assign it to me

**Comment by tanishq-singh-2301** [comment]
!assign
