### ISSUE TITLE
Write a Java program to add two matrices

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4552]
### Description

Write a Java program to add two matrices

Matrix addition is the process of adding two matrices by adding the corresponding elements of the two matrices. Two matrices must have an equal number of rows and columns to be added.

```
Input  :
1 2 3
4 5 6
7 8 9

1 2 3
4 5 6
7 8 9

Output :
2 4 6
8 10 12
14 16 18
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/AddTwoMatrices.java` file
- Add `AddTwoMatrices.java` file in `add-two-matrices` folder

</details>

**Comment by BrokenDesign** [comment]
!assign

**Comment by savi001** [comment]
i am new to open source , can u assign this to me

**Comment by BrokenDesign** [comment]
@savi001 they have it automated so if you see an open issue just type !assign and it will assign the issue to you. I've already written a solution for this... 
```java
import org.apache.commons.math3.linear.RealMatrix;
import org.apache.commons.math3.linear.RealMatrixFormat;
import org.apache.commons.math3.linear.MatrixUtils;
import org.apache.commons.math3.linear.MatrixDimensionMismatchException;

public class AddTwoMatrices {
    
    public static void print(RealMatrix m){
        RealMatrixFormat matrixFormat = new RealMatrixFormat("", "", "", "\n", "", ", ");
        System.out.println(matrixFormat.format(m));
    }
    
    public static void main(String args[]) 
        throws MatrixDimensionMismatchException {
            
        double[][] data = {{1d,2d,3d}, {4d,5d,6d}, {7d,8d,9d}};
        RealMatrix a = MatrixUtils.createRealMatrix(data);
        RealMatrix b = MatrixUtils.createRealMatrix(data);
        
        try {
            MatrixUtils.checkAdditionCompatible(a, b); 
            print(a.add(b));
        }
        catch(MatrixDimensionMismatchException error){
            System.out.println("ERROR: Incompatible for addition.\n" + error.getMessage());
        }
    }
}
```
But let me know if you have any suggestions - I was in two minds of whether to use the commons library or write it from scratch so if you want to write it yourself just using arrays then we could show both solutions? Let me know and will link you the branch.

**Comment by harshraj8843** [comment]
Hey @BrokenDesign,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
