### ISSUE TITLE
Write a PHP program to add two matrices

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4557]
### Description

Write a PHP program to add two matrices

Matrix addition is the process of adding two matrices by adding the corresponding elements of the two matrices. Two matrices must have an equal number of rows and columns to be added.

```
Input  :
1 2 3
4 5 6
7 8 9

1 2 3
4 5 6
7 8 9

Output :
2 4 6
8 10 12
14 16 18
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/add_two_matrices.php` file
- Add `add_two_matrices.php` file in `add-two-matrices` folder

</details>

**Comment by savi001** [comment]
i am new to open source , can u assign this to me

**Comment by harshraj8843** [comment]
Hey @savi001 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by K1118** [comment]
!assign
