### ISSUE TITLE
Write a Python program to add two matrices

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4558]
### Description

Write a Python program to add two matrices

Matrix addition is the process of adding two matrices by adding the corresponding elements of the two matrices. Two matrices must have an equal number of rows and columns to be added.

```
Input  :
1 2 3
4 5 6
7 8 9

1 2 3
4 5 6
7 8 9

Output :
2 4 6
8 10 12
14 16 18
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/add-two-matrices.py` file
- Add `add-two-matrices.py` file in `add-two-matrices` folder

</details>

**Comment by BrokenDesign** [comment]
!assign

**Comment by savi001** [comment]
i am new to open source , can u assign this to me

**Comment by BrokenDesign** [comment]
@savi001 same comment on this one, I would have but already written solution to this: 
```python
import numpy as np
a = np.arange(1, 10).reshape((3, 3))
b = np.arange(1, 10).reshape((3, 3))
c = np.add(a, b)
print(c)
```
But if you want to write a version that only uses pure-python then we could include both?
