### ISSUE TITLE
Write a TypeScript program to add two matrices

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4564]
### Description

Write a TypeScript program to add two matrices

Matrix addition is the process of adding two matrices by adding the corresponding elements of the two matrices. Two matrices must have an equal number of rows and columns to be added.

```
Input  :
1 2 3
4 5 6
7 8 9

1 2 3
4 5 6
7 8 9

Output :
2 4 6
8 10 12
14 16 18
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/AddTwoMatrices.ts` file
- Add `AddTwoMatrices.ts` file in `add-two-matrices` folder

</details>

**Comment by BrokenDesign** [comment]
!assign

**Comment by avireni** [comment]
!assign
