### ISSUE TITLE
Write a JavaScript program to find surface area of a cone

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4575]
### Description

Write a JavaScript program to find surface area of a cone

Surface area of cone = π × `Radius` × (`Radius` + `Slant Height`)

```
Radius       : 2
Slant Height : 3

Surface area : 31.4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSurfaceAreaOfACone.js` file
- Add `FindSurfaceAreaOfACone.js` file in `find-surface-area-of-a-cone` folder

</details>

**Comment by tanishq-singh-2301** [comment]
!assign
