### ISSUE TITLE
Write a Python program to find surface area of a cone

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4580]
### Description

Write a Python program to find surface area of a cone

Surface area of cone = π × `Radius` × (`Radius` + `Slant Height`)

```
Radius       : 2
Slant Height : 3

Surface area : 31.4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-surface-area-of-a-cone.py` file
- Add `find-surface-area-of-a-cone.py` file in `find-surface-area-of-a-cone` folder

</details>

**Comment by Medmly20208** [comment]
!assign

**Comment by Medmly20208** [comment]
@harshraj8843 your formula is wrong this is the right one :      

Surface area of cone = π*  radius * ( radius + sqrt( radius^2 + slantHeight^2 ))

**Comment by joao-vitor-souza** [comment]
> @harshraj8843 your formula is wrong this is the right one :
> 
> Surface area of cone = π* radius * ( radius + sqrt( radius^2 + slantHeight^2 ))

[No, it's not.](https://www.varsitytutors.com/hotmath/hotmath_help/topics/surface-area-of-a-cone)
