### ISSUE TITLE
Write a R program to find surface area of a cone

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4581]
### Description

Write a R program to find surface area of a cone

Surface area of cone = π × `Radius` × (`Radius` + `Slant Height`)

```
Radius       : 2
Slant Height : 3

Surface area : 31.4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_surface_area_of_a_cone.r` file
- Add `find_surface_area_of_a_cone.r` file in `find-surface-area-of-a-cone` folder

</details>

**Comment by esivakumar18** [comment]
!assign
