### ISSUE TITLE
Write a Swift program to find surface area of a cone

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4585]
### Description

Write a Swift program to find surface area of a cone

Surface area of cone = π × `Radius` × (`Radius` + `Slant Height`)

```
Radius       : 2
Slant Height : 3

Surface area : 31.4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSurfaceAreaOfACone.swift` file
- Add `FindSurfaceAreaOfACone.swift` file in `find-surface-area-of-a-cone` folder

</details>

**Comment by esivakumar18** [comment]
!assign
