### ISSUE TITLE
Write a C program to find the trace of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4590]
### Description

Write a C program to find the trace of a matrix

The trace of a square matrix is the sum of the elements on the main diagonal (from the upper left to the lower right).

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheTraceOfAMatrix.c` file
- Add `FindTheTraceOfAMatrix.c` file in `find-the-trace-of-a-matrix` folder

</details>

**Comment by codingkush** [comment]
!assign
