### ISSUE TITLE
Write a GO program to find the trace of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4595]
### Description

Write a GO program to find the trace of a matrix

The trace of a square matrix is the sum of the elements on the main diagonal (from the upper left to the lower right).

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_the_trace_of_a_matrix.go` file
- Add `find_the_trace_of_a_matrix.go` file in `find-the-trace-of-a-matrix` folder

</details>

**Comment by vedantpople4** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @vedantpople4,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by vedantpople4** [comment]
!assign
