### ISSUE TITLE
Write a TypeScript program to find average of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4631]
### Description

Write a TypeScript program to find average of numbers by recursion

Average of numbers is the sum of all numbers divided by the number of numbers. For example, the average of 1, 2, 3, 4, 5 is 3. The average of 1, 2, 3, 4, 5, 6 is 3.5.

Average of numbers can be calculated by recursion. The average of numbers is the sum of the first number and the average of the rest of the numbers. The average of the rest of the numbers is the sum of the second number and the average of the rest of the numbers. The average of the rest of the numbers is the sum of the third number and the average of the rest of the numbers. And so on.

```
Input  : 1 2 3 4 5
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAverageOfNumbersByRecursion.ts` file
- Add `FindAverageOfNumbersByRecursion.ts` file in `find-average-of-numbers-by-recursion` folder

</details>

**Comment by tanishq-singh-2301** [comment]
!assign

**Comment by tirumalarakesh** [comment]
!assign
