### ISSUE TITLE
Write a C++ program to convert hours to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4638]
### Description

Write a C++ program to convert hours to minutes

1 hour = 60 minutes

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertHoursToMinutes.cpp` file
- Add `ConvertHoursToMinutes.cpp` file in `convert-hours-to-minutes` folder

</details>

**Comment by tanishq-singh-2301** [comment]
!assign
