### ISSUE TITLE
Write a GO program to convert hours to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4641]
### Description

Write a GO program to convert hours to minutes

1 hour = 60 minutes

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_hours_to_minutes.go` file
- Add `convert_hours_to_minutes.go` file in `convert-hours-to-minutes` folder

</details>

**Comment by sureshr3git** [comment]
!assign
