### ISSUE TITLE
Write a Java program to convert hours to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4643]
### Description

Write a Java program to convert hours to minutes

1 hour = 60 minutes

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertHoursToMinutes.java` file
- Add `ConvertHoursToMinutes.java` file in `convert-hours-to-minutes` folder

</details>

**Comment by Cherifzeraguine** [comment]
!assign
