### ISSUE TITLE
Write a JavaScript program to convert hours to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4644]
### Description

Write a JavaScript program to convert hours to minutes

1 hour = 60 minutes

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertHoursToMinutes.js` file
- Add `ConvertHoursToMinutes.js` file in `convert-hours-to-minutes` folder

</details>

**Comment by watacodes** [comment]
Hello, Harsh! I hope your day is going well. This is my first time contributing to the open source. Could you kindly assign this case to me, please? I am looking forward to working on this issue!

**Comment by harshraj8843** [comment]
Hey @watacodes 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by watacodes** [comment]
@harshraj8843 Thank you so much for your reply and advice! I didn't know that.
!assign

**Comment by watacodes** [comment]
!assign

**Comment by watacodes** [comment]
@harshraj8843 Thank you so much for your advice! I sent my PR to this issue. I appreciate your support, have a wonderful day!
