### ISSUE TITLE
Write a Julia program to convert hours to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4645]
### Description

Write a Julia program to convert hours to minutes

1 hour = 60 minutes

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-hours-to-minutes.jl` file
- Add `convert-hours-to-minutes.jl` file in `convert-hours-to-minutes` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
