### ISSUE TITLE
Write a Kotlin program to convert hours to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4646]
### Description

Write a Kotlin program to convert hours to minutes

1 hour = 60 minutes

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertHoursToMinutes.kt` file
- Add `ConvertHoursToMinutes.kt` file in `convert-hours-to-minutes` folder

</details>

**Comment by mrajen27** [comment]
!assign
