### ISSUE TITLE
Write a Python program to convert hours to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4649]
### Description

Write a Python program to convert hours to minutes

1 hour = 60 minutes

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-hours-to-minutes.py` file
- Add `convert-hours-to-minutes.py` file in `convert-hours-to-minutes` folder

</details>

**Comment by Medmly20208** [comment]
!assign
