### ISSUE TITLE
Write a Ruby program to convert hours to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4651]
### Description

Write a Ruby program to convert hours to minutes

1 hour = 60 minutes

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertHoursToMinutes.rb` file
- Add `ConvertHoursToMinutes.rb` file in `convert-hours-to-minutes` folder

</details>

**Comment by PraaneshSelvaraj** [comment]
!assign
