### ISSUE TITLE
Write a Rust program to convert hours to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4652]
### Description

Write a Rust program to convert hours to minutes

1 hour = 60 minutes

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_hours_to_minutes.rs` file
- Add `convert_hours_to_minutes.rs` file in `convert-hours-to-minutes` folder

</details>

**Comment by esivakumar18** [comment]
!assign

**Comment by RiteshK-611** [comment]
!assign
