### ISSUE TITLE
Write a Swift program to convert hours to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4654]
### Description

Write a Swift program to convert hours to minutes

1 hour = 60 minutes

```
Input  : 5
Output : 300
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertHoursToMinutes.swift` file
- Add `ConvertHoursToMinutes.swift` file in `convert-hours-to-minutes` folder

</details>

**Comment by esivakumar18** [comment]
!assign
