### ISSUE TITLE
Write a C program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4666]
### Description

Write a C program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintDiamondPattern.c` file
- Add `PrintDiamondPattern.c` file in `print-diamond-pattern` folder

</details>

**Comment by das-amit** [comment]
!assign

**Comment by KrunalGupta02** [comment]
Hey @harshraj8843 can u assign me this

**Comment by harshraj8843** [comment]
Hey @KrunalGupta02 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by KrunalGupta02** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @KrunalGupta02, this issue is already assigned to @das-amit !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by KrunalGupta02** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @KrunalGupta02, this issue is already assigned to @das-amit !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by das-amit** [comment]
hey @harshraj8843 ,I've made the PR
Check #4704

**Comment by Aditya449930** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Aditya449930, this issue is already assigned to @das-amit !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
