### ISSUE TITLE
Write a C# program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4667]
### Description

Write a C# program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintDiamondPattern.cs` file
- Add `PrintDiamondPattern.cs` file in `print-diamond-pattern` folder

</details>

**Comment by Premjeet1804** [comment]
can i do this one

**Comment by harshraj8843** [comment]
Hey @Premjeet1804 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by Premjeet1804** [comment]
!assign please sir

**Comment by Mrunmayi28** [comment]
!assign

**Comment by Mrunmayi28** [comment]
[https://github.com/codinasion/program/pull/4784](C# program to print diamond pattern)

**Comment by Mrunmayi28** [comment]
[C# program to print diamond pattern](https://github.com/codinasion/program/pull/4784)
