### ISSUE TITLE
Write a C++ program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4668]
### Description

Write a C++ program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintDiamondPattern.cpp` file
- Add `PrintDiamondPattern.cpp` file in `print-diamond-pattern` folder

</details>

**Comment by das-amit** [comment]
Hey @harshraj8843 , I would like to contribute to this

**Comment by harshraj8843** [comment]
Hey @das-amit 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by das-amit** [comment]
!assign
