### ISSUE TITLE
Write a Dart program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4669]
### Description

Write a Dart program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/print_diamond_pattern.dart` file
- Add `print_diamond_pattern.dart` file in `print-diamond-pattern` folder

</details>

**Comment by divyasakre** [comment]
hey @harshraj8843 i want to contribute to this issue. Please assign this issue to me.


!assign

**Comment by divyasakre** [comment]
Code added. Do check. [https://github.com/codinasion/program/pull/4758](https://github.com/codinasion/program/pull/4758)

**Comment by divyasakre** [comment]
#4758

**Comment by divyasakre** [comment]
Changes made. Do check. #4787
