### ISSUE TITLE
Write a GO program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4671]
### Description

Write a GO program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/print_diamond_pattern.go` file
- Add `print_diamond_pattern.go` file in `print-diamond-pattern` folder

</details>

**Comment by vedantpople4** [comment]
!assign
