### ISSUE TITLE
Write a Java program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4673]
### Description

Write a Java program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintDiamondPattern.java` file
- Add `PrintDiamondPattern.java` file in `print-diamond-pattern` folder

</details>

**Comment by singhayush20** [comment]
!assign

**Comment by sam-mugo** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @sam-mugo, this issue is already assigned to @singhayush20 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Hey @sam-mugo 

You can contribute to this 😃

**Comment by sam-mugo** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @sam-mugo, this issue is already assigned to @sam-mugo !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
