### ISSUE TITLE
Write a JavaScript program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4674]
### Description

Write a JavaScript program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintDiamondPattern.js` file
- Add `PrintDiamondPattern.js` file in `print-diamond-pattern` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by simranrangari** [comment]
!assign
