### ISSUE TITLE
Write a Kotlin program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4676]
### Description

Write a Kotlin program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintDiamondPattern.kt` file
- Add `PrintDiamondPattern.kt` file in `print-diamond-pattern` folder

</details>

**Comment by Oudeinguene** [comment]
!asssign
