### ISSUE TITLE
Write a Python program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4679]
### Description

Write a Python program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/print-diamond-pattern.py` file
- Add `print-diamond-pattern.py` file in `print-diamond-pattern` folder

</details>

**Comment by Medmly20208** [comment]
!assign
