### ISSUE TITLE
Write a R program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4680]
### Description

Write a R program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/print_diamond_pattern.r` file
- Add `print_diamond_pattern.r` file in `print-diamond-pattern` folder

</details>

**Comment by simranrangari** [comment]
!assign

**Comment by simranrangari** [comment]
do check #4785
