### ISSUE TITLE
Write a Ruby program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4681]
### Description

Write a Ruby program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintDiamondPattern.rb` file
- Add `PrintDiamondPattern.rb` file in `print-diamond-pattern` folder

</details>

**Comment by Fukurokudzu** [comment]
!assign
