### ISSUE TITLE
Write a Scala program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4683]
### Description

Write a Scala program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/printDiamondPattern.scala` file
- Add `printDiamondPattern.scala` file in `print-diamond-pattern` folder

</details>

**Comment by sam-mugo** [comment]
!assign
