### ISSUE TITLE
Write a TypeScript program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4685]
### Description

Write a TypeScript program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintDiamondPattern.ts` file
- Add `PrintDiamondPattern.ts` file in `print-diamond-pattern` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Greeshma-frontier,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by BarBronshtein** [comment]
!assign
