### ISSUE TITLE
Auto assign is not working as expected 

### ISSUE THREAD

**Issue by brundabharadwaj** [codinasion/program#4699]
### What would you like to share?

Hi Team,

as I have observed, till yesterday auto assign was working as expected on comment of !assign… but it’s failing today
![B6241CFB-DA84-42DF-ABE2-598CEC959F5D](https://user-images.githubusercontent.com/49773125/196324843-1805d015-6192-492b-a334-5e91a7f6bb33.png)

added image for reference.
 @harshraj8843 FYI

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)

**Comment by harshraj8843** [comment]
Thanks @brundabharadwaj for reporting this 👍🏻

**Comment by harshraj8843** [comment]
!assign `test`

**Comment by harshraj8843** [comment]
!assign `test`

**Comment by harshraj8843** [comment]
Hey @harshraj8843, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Fixed 🎉 

There was an issue with Node Js version
