### ISSUE TITLE
Write a C program to find sum of squares of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#482]
### Description

Write a C program to find sum of squares of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 55
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfSquaresOfNumbersByRecursion.c` file
- Add `FindSumOfSquaresOfNumbersByRecursion.c` file in `find-sum-of-squares-of-numbers-by-recursion` folder

</details>

**Comment by Ritesh-Dabral** [comment]
@harshraj8843 
Can u assign this to me ?
Thanks

**Comment by harshraj8843** [comment]
Hey @Ritesh-Dabral 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

Thanks for contributing 👍🏻

**Comment by Ritesh-Dabral** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Ritesh-Dabral, this issue is already assigned to @Ritesh-Dabral !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
