### ISSUE TITLE
Write a C++ program to find sum of squares of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#484]
### Description

Write a C++ program to find sum of squares of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 55
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfSquaresOfNumbersByRecursion.cpp` file
- Add `FindSumOfSquaresOfNumbersByRecursion.cpp` file in `find-sum-of-squares-of-numbers-by-recursion` folder

</details>

**Comment by destroyer5067** [comment]
!assign

**Comment by Osher160** [comment]
!assign
