### ISSUE TITLE
Write a GO program to find sum of squares of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#487]
### Description

Write a GO program to find sum of squares of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 55
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_sum_of_squares_of_numbers_by_recursion.go` file
- Add `find_sum_of_squares_of_numbers_by_recursion.go` file in `find-sum-of-squares-of-numbers-by-recursion` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign

**Comment by sancoLgates** [comment]
!assign
