### ISSUE TITLE
Write a Java program to find sum of squares of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#488]
### Description

Write a Java program to find sum of squares of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 55
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfSquaresOfNumbersByRecursion.java` file
- Add `FindSumOfSquaresOfNumbersByRecursion.java` file in `find-sum-of-squares-of-numbers-by-recursion` folder

</details>

**Comment by sumeetk10** [comment]
I want to work on this issue, can you assign this to me.

**Comment by Ipankaj07** [comment]
!assign
