### ISSUE TITLE
Write a JavaScript program to find sum of squares of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#489]
### Description

Write a JavaScript program to find sum of squares of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 55
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfSquaresOfNumbersByRecursion.js` file
- Add `FindSumOfSquaresOfNumbersByRecursion.js` file in `find-sum-of-squares-of-numbers-by-recursion` folder

</details>

**Comment by kangjung** [comment]
!assign
