### ISSUE TITLE
Write a C++ program to find the average of all numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4911]
### Description

Write a C++ program to find the average of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheAverageOfAllNumbersInAnArray.cpp` file
- Add `FindTheAverageOfAllNumbersInAnArray.cpp` file in `find-the-average-of-all-numbers-in-an-array` folder

</details>

**Comment by hi-Kartik2004** [comment]
Hi @harshraj8843, this issue is already solved - reference [PR #2004](https://github.com/codinasion/program/pull/2004)

**Comment by harshraj8843** [comment]
Hey @hi-Kartik2004 

PR #2004 is linked to issue #1858

This issue is similar to #1858 but for different purpose

**Comment by AbhinavPrabhat01** [comment]
Hey can I solve this issue

**Comment by hi-Kartik2004** [comment]
> Hey can I solve this issue
Hi @AbhinavPrabhat01, thanks for showing your interest in contributing, you can type `!assign` on any good first issues which are not already assigned to someone else, in this case, this issue is open and not assigned to anyone, and if you wish to contribute just type `!assign`.
