### ISSUE TITLE
Write a Java program to find the average of all numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4916]
### Description

Write a Java program to find the average of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheAverageOfAllNumbersInAnArray.java` file
- Add `FindTheAverageOfAllNumbersInAnArray.java` file in `find-the-average-of-all-numbers-in-an-array` folder

</details>

**Comment by dineshlalam15** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @dineshlalam15,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
