### ISSUE TITLE
Write a Kotlin program to find the average of all numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4919]
### Description

Write a Kotlin program to find the average of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheAverageOfAllNumbersInAnArray.kt` file
- Add `FindTheAverageOfAllNumbersInAnArray.kt` file in `find-the-average-of-all-numbers-in-an-array` folder

</details>

**Comment by Coder-12-ux** [comment]
!assign

**Comment by gsquareg2** [comment]
!assign

**Comment by D-I-J** [comment]
!assign
