### ISSUE TITLE
Write a Python program to find the average of all numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4922]
### Description

Write a Python program to find the average of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-the-average-of-all-numbers-in-an-array.py` file
- Add `find-the-average-of-all-numbers-in-an-array.py` file in `find-the-average-of-all-numbers-in-an-array` folder

</details>

**Comment by EniolaAdemola** [comment]
!assign

**Comment by harsha-desaraju** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @harsha-desaraju, this issue is already assigned to @EniolaAdemola !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
