### ISSUE TITLE
Write a Ruby program to find the average of all numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4924]
### Description

Write a Ruby program to find the average of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheAverageOfAllNumbersInAnArray.rb` file
- Add `FindTheAverageOfAllNumbersInAnArray.rb` file in `find-the-average-of-all-numbers-in-an-array` folder

</details>

**Comment by jfinley6** [comment]
!assign
