### ISSUE TITLE
Write a C program to convert string to vowelcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4930]
### Description

Write a C program to convert string to vowelcase

Vowelcase is a style of writing in which all vowels are converted to uppercase and all consonants are converted to lowercase.

```
Input  : "hello world"
Output : "hEllO wOrld"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToVowelcase.c` file
- Add `ConvertStringToVowelcase.c` file in `convert-string-to-vowelcase` folder

</details>

**Comment by ob-codes** [comment]
!assign
