### ISSUE TITLE
Write a Java program to convert string to vowelcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4937]
### Description

Write a Java program to convert string to vowelcase

Vowelcase is a style of writing in which all vowels are converted to uppercase and all consonants are converted to lowercase.

```
Input  : "hello world"
Output : "hEllO wOrld"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToVowelcase.java` file
- Add `ConvertStringToVowelcase.java` file in `convert-string-to-vowelcase` folder

</details>

**Comment by mail2poonam89** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @mail2poonam89,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Coder-12-ux** [comment]
!assign
