### ISSUE TITLE
Write a Python program to find sum of squares of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#494]
### Description

Write a Python program to find sum of squares of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 55
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-sum-of-squares-of-numbers-by-recursion.py` file
- Add `find-sum-of-squares-of-numbers-by-recursion.py` file in `find-sum-of-squares-of-numbers-by-recursion` folder

</details>

**Comment by AyushSrivastava27** [comment]
! assign
