### ISSUE TITLE
Write a Python program to convert string to vowelcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4943]
### Description

Write a Python program to convert string to vowelcase

Vowelcase is a style of writing in which all vowels are converted to uppercase and all consonants are converted to lowercase.

```
Input  : "hello world"
Output : "hEllO wOrld"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-string-to-vowelcase.py` file
- Add `convert-string-to-vowelcase.py` file in `convert-string-to-vowelcase` folder

</details>

**Comment by EsakkiMuthu-dev** [comment]
Is this still active ?  I like to contirbute to this issue

**Comment by HadasBrave** [comment]
assign

**Comment by HadasBrave** [comment]
Closes #9151

What's being changed:
Added PY file with the function of vowelCasePy

**Comment by HadasBrave** [comment]
Closed:
#9151
What being changed:
Added a py file with vowelCasePy function
