### ISSUE TITLE
Write a C++ program to reverse an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4953]
### Description

Write a C++ program to reverse an array

```
Input  : [1, 2, 3, 4, 5]
Output : [5, 4, 3, 2, 1]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ReverseAnArray.cpp` file
- Add `ReverseAnArray.cpp` file in `program/reverse-an-array` folder

</details>

**Comment by hi-Kartik2004** [comment]
!assign
