### ISSUE TITLE
Write a GO program to reverse an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4956]
### Description

Write a GO program to reverse an array

```
Input  : [1, 2, 3, 4, 5]
Output : [5, 4, 3, 2, 1]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `reverse_an_array.go` file
- Add `reverse_an_array.go` file in `program/reverse-an-array` folder

</details>

**Comment by vedantpople4** [comment]
!assign
