### ISSUE TITLE
Write a Java program to reverse an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4958]
### Description

Write a Java program to reverse an array

```
Input  : [1, 2, 3, 4, 5]
Output : [5, 4, 3, 2, 1]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ReverseAnArray.java` file
- Add `ReverseAnArray.java` file in `program/reverse-an-array` folder

</details>

**Comment by mail2poonam89** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @dineshlalam15, this issue is already assigned to @mail2poonam89 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
