### ISSUE TITLE
Write a Ruby program to find sum of squares of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#496]
### Description

Write a Ruby program to find sum of squares of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 55
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfSquaresOfNumbersByRecursion.rb` file
- Add `FindSumOfSquaresOfNumbersByRecursion.rb` file in `find-sum-of-squares-of-numbers-by-recursion` folder

</details>

**Comment by AthiraKadampatta** [comment]
Hi @harshraj8843 I would like to work on this too!! !assign

**Comment by AthiraKadampatta** [comment]
!assign
