### ISSUE TITLE
Write a Kotlin program to reverse an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4961]
### Description

Write a Kotlin program to reverse an array

```
Input  : [1, 2, 3, 4, 5]
Output : [5, 4, 3, 2, 1]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ReverseAnArray.kt` file
- Add `ReverseAnArray.kt` file in `program/reverse-an-array` folder

</details>

**Comment by gsquareg2** [comment]
!assign
