### ISSUE TITLE
Write a Python program to reverse an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4964]
### Description

Write a Python program to reverse an array

```
Input  : [1, 2, 3, 4, 5]
Output : [5, 4, 3, 2, 1]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `reverse-an-array.py` file
- Add `reverse-an-array.py` file in `program/reverse-an-array` folder

</details>

**Comment by loesking** [comment]
!assign
