### ISSUE TITLE
Write a Rust program to reverse an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4967]
### Description

Write a Rust program to reverse an array

```
Input  : [1, 2, 3, 4, 5]
Output : [5, 4, 3, 2, 1]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `reverse_an_array.rs` file
- Add `reverse_an_array.rs` file in `program/reverse-an-array` folder

</details>

**Comment by hugosmoreira** [comment]
!assign
