### ISSUE TITLE
Write a Java program to find sum of gp series

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4980]
### Description

Write a Java program to find sum of gp series

A geometric progression (GP) is a sequence of numbers where each term after the first is found by multiplying the previous one by a fixed, non-zero number called the common ratio. The nth term of a GP is given by the formula a<sub>n</sub> = a<sub>1</sub>r<sup>n-1</sup> where a<sub>1</sub> is the first term and r is the common ratio.

```
Input  : 2, 3, 3
Output : 26
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfGpSeries.java` file
- Add `FindSumOfGpSeries.java` file in `program/find-sum-of-gp-series` folder

</details>

**Comment by brundabharadwaj** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @brundabharadwaj, this issue is already assigned to @brundabharadwaj !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by txsnxm** [comment]
!assign

**Comment by txsnxm** [comment]
import java.util.Scanner;
public class FindSumOfGpSeries {
    public static void main(String[] args) {
        Scanner sc=new Scanner(System.in);
        //a is the first term of series
        double a=sc.nextDouble();
        //n is the number of terms
        int n=sc.nextInt();
        //r is common ratio
        double r=sc.nextDouble();
        double sum=0;
        // initialize temp as a
        double temp=a;
        for(int i=0;i<n;i++){
            sum=sum+temp;
            // increase temp every time by r
            temp=temp*r;
        }
        System.out.println(sum);
        
    }
}
