### ISSUE TITLE
Write a JavaScript program to find sum of gp series

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#4981]
### Description

Write a JavaScript program to find sum of gp series

A geometric progression (GP) is a sequence of numbers where each term after the first is found by multiplying the previous one by a fixed, non-zero number called the common ratio. The nth term of a GP is given by the formula a<sub>n</sub> = a<sub>1</sub>r<sup>n-1</sup> where a<sub>1</sub> is the first term and r is the common ratio.

`Input: a r n`

```
Input  : 2, 3, 3
Output : 26
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfGpSeries.js` file
- Add `FindSumOfGpSeries.js` file in `program/find-sum-of-gp-series` folder

</details>

**Comment by sujalcodes3** [comment]
Hey, I want to work on this issue, can you please assign me this issue. But i would first like to ask that what is the format of the input like what are **2,3,3** in the example input respectively.

**Comment by harshraj8843** [comment]
@sujalcodes3 Sorry for the confusion

`Input: a r n`

**Comment by sujalcodes3** [comment]
!assign

**Comment by SarthakSanjay** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @SarthakSanjay, this issue is already assigned to @sujalcodes3 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by ShivamK2002** [comment]
!assign

**Comment by sagi403** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @sagi403, this issue is already assigned to @ShivamK2002 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by pritish1906** [comment]
Please assign this to me
