### ISSUE TITLE
Write a JavaScript program to find square of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#50]
### Description

Write a JavaScript program to find square of a number

```
Input  : 5
Output : 25
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSquareOfANumber.js` file
- Add `FindSquareOfANumber.js` file in `find-square-of-a-number` folder

</details>

**Comment by KaptainCS3** [comment]
Assign me

**Comment by harshraj8843** [comment]
> Assign me

Hey @KaptainCS3 

Thanks for showing your interest in this project 😃 

You can also comment `!assign` on any `good first issue` to be auto-assigned

```
!assign
```

**Comment by amitanshusahu** [comment]
ok i am taking the task !assign

**Comment by amitanshusahu** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @amitanshusahu, this issue is already assigned to @KaptainCS3 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
