### ISSUE TITLE
Write a Haskell program to convert fahrenheit to celsius

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5020]
### Description

Write a Haskell program to convert fahrenheit to celsius

celcius = (fahrenheit - 32) * 5/9

```
Input ( F )  : -40
Output ( C ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_fahrenheit_to_celsius.hs` file
- Add `convert_fahrenheit_to_celsius.hs` file in `program/convert-fahrenheit-to-celsius` folder

</details>

**Comment by esivakumar18** [comment]
!assign

**Comment by RiteshK-611** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @RiteshK-611, this issue is already assigned to @esivakumar18 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by RiteshK-611** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @RiteshK-611, this issue is already assigned to @esivakumar18 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
