### ISSUE TITLE
Write a Java program to convert fahrenheit to celsius

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5021]
### Description

Write a Java program to convert fahrenheit to celsius

celcius = (fahrenheit - 32) * 5/9

```
Input ( F )  : -40
Output ( C ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFahrenheitToCelsius.java` file
- Add `ConvertFahrenheitToCelsius.java` file in `program/convert-fahrenheit-to-celsius` folder

</details>

**Comment by mail2poonam89** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @mail2poonam89,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by txsnxm** [comment]
please assign this issue to me.

**Comment by harshraj8843** [comment]
Hey @txsnxm 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by GaganD777** [comment]
!assign

**Comment by txsnxm** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @txsnxm, this issue is already assigned to @GaganD777 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
