### ISSUE TITLE
Write a JavaScript program to convert fahrenheit to celsius

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5022]
### Description

Write a JavaScript program to convert fahrenheit to celsius

celcius = (fahrenheit - 32) * 5/9

```
Input ( F )  : -40
Output ( C ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFahrenheitToCelsius.js` file
- Add `ConvertFahrenheitToCelsius.js` file in `program/convert-fahrenheit-to-celsius` folder

</details>

**Comment by Michal-eng** [comment]
!assign

**Comment by yesayajones** [comment]
Can I work on this?

**Comment by harshraj8843** [comment]
Hey @yesayajones 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by yesayajones** [comment]
!assign
