### ISSUE TITLE
Write a Julia program to convert fahrenheit to celsius

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5023]
### Description

Write a Julia program to convert fahrenheit to celsius

celcius = (fahrenheit - 32) * 5/9

```
Input ( F )  : -40
Output ( C ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-fahrenheit-to-celsius.jl` file
- Add `convert-fahrenheit-to-celsius.jl` file in `program/convert-fahrenheit-to-celsius` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
