### ISSUE TITLE
Write a Python program to convert fahrenheit to celsius

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5027]
### Description

Write a Python program to convert fahrenheit to celsius

celcius = (fahrenheit - 32) * 5/9

```
Input ( F )  : -40
Output ( C ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-fahrenheit-to-celsius.py` file
- Add `convert-fahrenheit-to-celsius.py` file in `program/convert-fahrenheit-to-celsius` folder

</details>

**Comment by Medmly20208** [comment]
!assign
