### ISSUE TITLE
Write a R program to convert fahrenheit to celsius

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5028]
### Description

Write a R program to convert fahrenheit to celsius

celcius = (fahrenheit - 32) * 5/9

```
Input ( F )  : -40
Output ( C ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_fahrenheit_to_celsius.r` file
- Add `convert_fahrenheit_to_celsius.r` file in `program/convert-fahrenheit-to-celsius` folder

</details>

**Comment by esivakumar18** [comment]
!assign
