### ISSUE TITLE
Write a Ruby program to convert fahrenheit to celsius

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5029]
### Description

Write a Ruby program to convert fahrenheit to celsius

celcius = (fahrenheit - 32) * 5/9

```
Input ( F )  : -40
Output ( C ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFahrenheitToCelsius.rb` file
- Add `ConvertFahrenheitToCelsius.rb` file in `program/convert-fahrenheit-to-celsius` folder

</details>

**Comment by jfinley6** [comment]
!assign
