### ISSUE TITLE
Write a Swift program to convert fahrenheit to celsius

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5032]
### Description

Write a Swift program to convert fahrenheit to celsius

celcius = (fahrenheit - 32) * 5/9

```
Input ( F )  : -40
Output ( C ) : -40
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFahrenheitToCelsius.swift` file
- Add `ConvertFahrenheitToCelsius.swift` file in `program/convert-fahrenheit-to-celsius` folder

</details>

**Comment by esivakumar18** [comment]
!assign
