### ISSUE TITLE
Write a Haskell program to find surface area of a cylinder

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5041]
### Description

Write a Haskell program to find surface area of a cylinder

Surface area of cylinder = 2 × π × `Radius`  × ( `Radius` + `Height` )

```
Radius : 2
Height : 3

Surface area : 62.83185307179586
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_surface_area_of_a_cylinder.hs` file
- Add `find_surface_area_of_a_cylinder.hs` file in `program/find-surface-area-of-a-cylinder` folder

</details>

**Comment by esivakumar18** [comment]
!assign
