### ISSUE TITLE
Write a Java program to find surface area of a cylinder

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5042]
### Description

Write a Java program to find surface area of a cylinder

Surface area of cylinder = 2 × π × `Radius`  × ( `Radius` + `Height` )

```
Radius : 2
Height : 3

Surface area : 62.83185307179586
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSurfaceAreaOfACylinder.java` file
- Add `FindSurfaceAreaOfACylinder.java` file in `program/find-surface-area-of-a-cylinder` folder

</details>

**Comment by mail2poonam89** [comment]
!assign
