### ISSUE TITLE
Write a JavaScript program to find surface area of a cylinder

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5043]
### Description

Write a JavaScript program to find surface area of a cylinder

Surface area of cylinder = 2 × π × `Radius`  × ( `Radius` + `Height` )

```
Radius : 2
Height : 3

Surface area : 62.83185307179586
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSurfaceAreaOfACylinder.js` file
- Add `FindSurfaceAreaOfACylinder.js` file in `program/find-surface-area-of-a-cylinder` folder

</details>

**Comment by yesayajones** [comment]
!assign

**Comment by yesayajones** [comment]
Can I work on this? The automatic assigning, "!assign", is not working again.

**Comment by harshraj8843** [comment]
!assign test

**Comment by harshraj8843** [comment]
Hey @harshraj8843, this issue is already assigned to @yesayajones !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
@yesayajones Thanks for reporting this incident 👍🏻 

The workflow was ignored 👉🏻 https://github.com/codinasion/program/actions/runs/3797187150

Don't know why (as issue body contains `!assign`), but I will try to fix it ASAP

https://github.com/codinasion/program/blob/ad631886f3a8a59df7e10e0a2edb3b5493669a0d/.github/workflows/auto-assign-issue.yml#L8

**Comment by sujalcodes3** [comment]
!assign
