### ISSUE TITLE
Write a Python program to find surface area of a cylinder

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5048]
### Description

Write a Python program to find surface area of a cylinder

Surface area of cylinder = 2 × π × `Radius`  × ( `Radius` + `Height` )

```
Radius : 2
Height : 3

Surface area : 62.83185307179586
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-surface-area-of-a-cylinder.py` file
- Add `find-surface-area-of-a-cylinder.py` file in `program/find-surface-area-of-a-cylinder` folder

</details>

**Comment by SarthakSanjay** [comment]
!assign

**Comment by SarthakSanjay** [comment]
Formula for surface area of cylinder is wrong.
It should be surfaceAreaOfCylinder =2 × π × Radius ×(Radius+ Height)

**Comment by harshraj8843** [comment]
Hey @SarthakSanjay 

Thanks for noticing this issue and letting us know 👍🏻
