### ISSUE TITLE
Write a C++ program to convert string to sentencecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5058]
### Description

Write a C++ program to convert string to sentencecase

Sentencecase is a style of writing in which the first letter of the first word is capitalized.

```
Input  : "hello world"
Output : "Hello world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertStringToSentencecase.cpp` file
- Add `ConvertStringToSentencecase.cpp` file in `program/convert-string-to-sentencecase` folder

</details>

**Comment by Osher160** [comment]
!assign
