### ISSUE TITLE
Write a Kotlin program to convert string to sentencecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5066]
### Description

Write a Kotlin program to convert string to sentencecase

Sentencecase is a style of writing in which the first letter of the first word is capitalized.

```
Input  : "hello world"
Output : "Hello world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertStringToSentencecase.kt` file
- Add `ConvertStringToSentencecase.kt` file in `program/convert-string-to-sentencecase` folder

</details>

**Comment by rksp25** [comment]
!assign
