### ISSUE TITLE
Write a C++ program to print numbers from 1 to n without using a loop

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5079]
### Description

Write a C++ program to print numbers from 1 to n without using a loop

```
Input  : 5
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintNumbersFrom1ToNWithoutUsingALoop.cpp` file
- Add `PrintNumbersFrom1ToNWithoutUsingALoop.cpp` file in `program/print-numbers-from-1-to-n-without-using-a-loop` folder

</details>

**Comment by hi-Kartik2004** [comment]
!assign

**Comment by hi-Kartik2004** [comment]
Issue solved in Pull request number #5811

**Comment by hi-Kartik2004** [comment]
Issue solved in Pull request number https://github.com/codinasion/program/pull/5811
