### ISSUE TITLE
Write a Java program to print numbers from 1 to n without using a loop

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5084]
### Description

Write a Java program to print numbers from 1 to n without using a loop

```
Input  : 5
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintNumbersFrom1ToNWithoutUsingALoop.java` file
- Add `PrintNumbersFrom1ToNWithoutUsingALoop.java` file in `program/print-numbers-from-1-to-n-without-using-a-loop` folder

</details>

**Comment by mail2poonam89** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @dineshlalam15, this issue is already assigned to @mail2poonam89 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
