### ISSUE TITLE
Write a JavaScript program to print numbers from 1 to n without using a loop

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5085]
### Description

Write a JavaScript program to print numbers from 1 to n without using a loop

```
Input  : 5
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintNumbersFrom1ToNWithoutUsingALoop.js` file
- Add `PrintNumbersFrom1ToNWithoutUsingALoop.js` file in `program/print-numbers-from-1-to-n-without-using-a-loop` folder

</details>

**Comment by SarthakSanjay** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @SarthakSanjay,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by SarthakSanjay** [comment]
!assign
