### ISSUE TITLE
Write a Ruby program to print numbers from 1 to n without using a loop

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5092]
### Description

Write a Ruby program to print numbers from 1 to n without using a loop

```
Input  : 5
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintNumbersFrom1ToNWithoutUsingALoop.rb` file
- Add `PrintNumbersFrom1ToNWithoutUsingALoop.rb` file in `program/print-numbers-from-1-to-n-without-using-a-loop` folder

</details>

**Comment by jfinley6** [comment]
!assign
