### ISSUE TITLE
Write a R program to find power of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5113]
### Description

Write a R program to find power of a number

Power of a number is the result of multiplying a number by itself a certain number of times. For example, 2^3 = 2 * 2 * 2 = 8. The number 2 is the base and 3 is the exponent.

```
Input  : 2 3
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_power_of_a_number.r` file
- Add `find_power_of_a_number.r` file in `program/find-power-of-a-number` folder

</details>

**Comment by 1movemate** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @1movemate, this issue is already assigned to @anandfresh !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
