### ISSUE TITLE
Write a C++ program to find smallest element in a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5124]
### Description

Write a C++ program to find smallest element in a matrix

```
Input :
4 7 3
9 4 2
0 6 4

Output : 0
```

<sub>Contributed by - @ShubhraSuman</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSmallestElementInAMatrix.cpp` file
- Add `FindSmallestElementInAMatrix.cpp` file in `program/find-smallest-element-in-a-matrix` folder

</details>

**Comment by hi-Kartik2004** [comment]
!assign
