### ISSUE TITLE
Write a Python program to find smallest element in a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5135]
### Description

Write a Python program to find smallest element in a matrix

```
Input :
4 7 3
9 4 2
0 6 4

Output : 0
```

<sub>Contributed by - @ShubhraSuman</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `find-smallest-element-in-a-matrix.py` file
- Add `find-smallest-element-in-a-matrix.py` file in `program/find-smallest-element-in-a-matrix` folder

</details>

**Comment by Medmly20208** [comment]
!assign
