### ISSUE TITLE
Write a C program to convert string to consonantcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5143]
### Description

Write a C program to convert string to consonantcase

Consonantcase is a style of writing in which all consonants are converted to uppercase and all vowels are converted to lowercase.

```
Input  : "hello world"
Output : "HeLLo WoRLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertStringToConsonantcase.c` file
- Add `ConvertStringToConsonantcase.c` file in `program/convert-string-to-consonantcase` folder

</details>

**Comment by pokharel-nishan** [comment]
!assign
