### ISSUE TITLE
Write a Dart program to convert string to consonantcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5146]
### Description

Write a Dart program to convert string to consonantcase

Consonantcase is a style of writing in which all consonants are converted to uppercase and all vowels are converted to lowercase.

```
Input  : "hello world"
Output : "HeLLo WoRLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_string_to_consonantcase.dart` file
- Add `convert_string_to_consonantcase.dart` file in `program/convert-string-to-consonantcase` folder

</details>

**Comment by james-tharit** [comment]
!assign
