### ISSUE TITLE
Write a Java program to convert string to consonantcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5150]
### Description

Write a Java program to convert string to consonantcase

Consonantcase is a style of writing in which all consonants are converted to uppercase and all vowels are converted to lowercase.

```
Input  : "hello world"
Output : "HeLLo WoRLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertStringToConsonantcase.java` file
- Add `ConvertStringToConsonantcase.java` file in `program/convert-string-to-consonantcase` folder

</details>

**Comment by NoyHanan** [comment]
Hi!
May I work on it?

**Comment by harshraj8843** [comment]
Hey @NoyHanan 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by NoyHanan** [comment]
@harshraj8843 
Thanks!

**Comment by NoyHanan** [comment]
@harshraj8843 
Hi. I saw that there already is a solution for this problem in the specified folder, so please close this issue.
Thank you! :)

**Comment by harshraj8843** [comment]
Hey @NoyHanan 

#5142 and #3966 are different issues ( `consonantcase` & `constantcase` )

**Comment by ritika4554244** [comment]
assign!!

**Comment by ritika4554244** [comment]
!assign 
@harshraj8843

**Comment by harshraj8843** [comment]
Hey @ritika4554244, this issue is already assigned to @NoyHanan !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by Shadow-Mo** [comment]
Hi, may I work on this?

**Comment by harshraj8843** [comment]
Sure @Shadow-Mo
