### ISSUE TITLE
Write a Julia program to convert string to consonantcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5152]
### Description

Write a Julia program to convert string to consonantcase

Consonantcase is a style of writing in which all consonants are converted to uppercase and all vowels are converted to lowercase.

```
Input  : "hello world"
Output : "HeLLo WoRLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-string-to-consonantcase.jl` file
- Add `convert-string-to-consonantcase.jl` file in `program/convert-string-to-consonantcase` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
