### ISSUE TITLE
Write a GO program to convert string to reversecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5169]
### Description

Write a GO program to convert string to reversecase

Reversecase is a style of writing in which all lowercase letters are converted to uppercase and all uppercase letters are converted to lowercase.

```
Input  : "hello world"
Output : "HELLO WORLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_string_to_reversecase.go` file
- Add `convert_string_to_reversecase.go` file in `program/convert-string-to-reversecase` folder

</details>

**Comment by vedantpople4** [comment]
!assign
