### ISSUE TITLE
Write a Julia program to convert string to reversecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5173]
### Description

Write a Julia program to convert string to reversecase

Reversecase is a style of writing in which all lowercase letters are converted to uppercase and all uppercase letters are converted to lowercase.

```
Input  : "hello world"
Output : "HELLO WORLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-string-to-reversecase.jl` file
- Add `convert-string-to-reversecase.jl` file in `program/convert-string-to-reversecase` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
