### ISSUE TITLE
Write a JavaScript program to find gcd of two numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5195]
### Description

Write a JavaScript program to find gcd of two numbers by recursion

GCD (Greatest Common Divisor) of two numbers is the largest number that divides both of them. A simple way to find GCD is to factorize both numbers and multiply common factors.

```
Input  : 12 18
Output : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindGcdOfTwoNumbersByRecursion.js` file
- Add `FindGcdOfTwoNumbersByRecursion.js` file in `program/find-gcd-of-two-numbers-by-recursion` folder

</details>

**Comment by yesayajones** [comment]
!assign
