### ISSUE TITLE
Write a Kotlin program to find square of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#52]
### Description

Write a Kotlin program to find square of a number

```
Input  : 5
Output : 25
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSquareOfANumber.kt` file
- Add `FindSquareOfANumber.kt` file in `find-square-of-a-number` folder

</details>

**Comment by saiprakash255** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @saiprakash255, this issue is already assigned to @darkbits018 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
