### ISSUE TITLE
Write a C program to print numbers from 1 to n

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5208]
### Description

Write a C program to print numbers from 1 to n

```
Input  : 5
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintNumbersFrom1ToN.c` file
- Add `PrintNumbersFrom1ToN.c` file in `program/print-numbers-from-1-to-n` folder

</details>

**Comment by Medmly20208** [comment]
!assign
