### ISSUE TITLE
Write a JavaScript program to print numbers from 1 to n

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5216]
### Description

Write a JavaScript program to print numbers from 1 to n

```
Input  : 5
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintNumbersFrom1ToN.js` file
- Add `PrintNumbersFrom1ToN.js` file in `program/print-numbers-from-1-to-n` folder

</details>

**Comment by harshraj8843** [comment]
Hey @shauryag2002 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by Michal-eng** [comment]
!assign
