### ISSUE TITLE
Write a Python program to print numbers from 1 to n

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5221]
### Description

Write a Python program to print numbers from 1 to n

```
Input  : 5
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `print-numbers-from-1-to-n.py` file
- Add `print-numbers-from-1-to-n.py` file in `program/print-numbers-from-1-to-n` folder

</details>

**Comment by cushonz** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @cushonz, this issue is already assigned to @anandfresh !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
