### ISSUE TITLE
Write a Ruby program to print numbers from 1 to n

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5223]
### Description

Write a Ruby program to print numbers from 1 to n

```
Input  : 5
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintNumbersFrom1ToN.rb` file
- Add `PrintNumbersFrom1ToN.rb` file in `program/print-numbers-from-1-to-n` folder

</details>

**Comment by rafaover** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @rafaover, this issue is already assigned to @anandfresh !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
