### ISSUE TITLE
Write a GO program to convert rupees to paise

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5234]
### Description

Write a GO program to convert rupees to paise

```
Input  ( Rs ) : 1
Output ( Ps ) : 100
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_rupees_to_paise.go` file
- Add `convert_rupees_to_paise.go` file in `program/convert-rupees-to-paise` folder

</details>

**Comment by vedantpople4** [comment]
!assign
