### ISSUE TITLE
Write a Haskell program to convert rupees to paise

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5235]
### Description

Write a Haskell program to convert rupees to paise

```
Input  ( Rs ) : 1
Output ( Ps ) : 100
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_rupees_to_paise.hs` file
- Add `convert_rupees_to_paise.hs` file in `program/convert-rupees-to-paise` folder

</details>

**Comment by esivakumar18** [comment]
!assign
