### ISSUE TITLE
Write a Java program to convert rupees to paise

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5236]
### Description

Write a Java program to convert rupees to paise

```
Input  ( Rs ) : 1
Output ( Ps ) : 100
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertRupeesToPaise.java` file
- Add `ConvertRupeesToPaise.java` file in `program/convert-rupees-to-paise` folder

</details>

**Comment by rhinoxD** [comment]
!assign
