### ISSUE TITLE
Write a PHP program to convert rupees to paise

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5241]
### Description

Write a PHP program to convert rupees to paise

```
Input  ( Rs ) : 1
Output ( Ps ) : 100
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_rupees_to_paise.php` file
- Add `convert_rupees_to_paise.php` file in `program/convert-rupees-to-paise` folder

</details>

**Comment by rhinoxD** [comment]
!assign
