### ISSUE TITLE
Write a Python program to convert rupees to paise

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5242]
### Description

Write a Python program to convert rupees to paise

```
Input  ( Rs ) : 1
Output ( Ps ) : 100
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-rupees-to-paise.py` file
- Add `convert-rupees-to-paise.py` file in `program/convert-rupees-to-paise` folder

</details>

**Comment by rhinoxD** [comment]
!assign
