### ISSUE TITLE
Write a Swift program to convert rupees to paise

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5247]
### Description

Write a Swift program to convert rupees to paise

```
Input  ( Rs ) : 1
Output ( Ps ) : 100
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertRupeesToPaise.swift` file
- Add `ConvertRupeesToPaise.swift` file in `program/convert-rupees-to-paise` folder

</details>

**Comment by esivakumar18** [comment]
!assign
