### ISSUE TITLE
Write a C++ program to find sum of squares of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5253]
### Description

Write a C++ program to find sum of squares of numbers

Suppose you have a list of numbers, and you want to find the sum of the squares of those numbers. For example, if you have the list `[1, 2, 3]`, you want to find the sum of the squares of those numbers, which is `1^2 + 2^2 + 3^2 = 14`.

```
Input  : 1 2 3 4 5
Output : 55
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfSquaresOfNumbers.cpp` file
- Add `FindSumOfSquaresOfNumbers.cpp` file in `program/find-sum-of-squares-of-numbers` folder

</details>

**Comment by hi-Kartik2004** [comment]
!assign

**Comment by hi-Kartik2004** [comment]
Issue solved in Pull request number #5811

**Comment by hi-Kartik2004** [comment]
Can we ask the user for the count of the numbers he will be entering?
Or Can you ask the user to enter the number without space and hit enter whenever they are done entering!?

**Comment by harshraj8843** [comment]
Sure we can modify the program in a way that will be good for everyone 👍🏻

**Comment by hi-Kartik2004** [comment]
Issue solved in Pull request number https://github.com/codinasion/program/pull/5811
