### ISSUE TITLE
Write a Swift program to find sum of squares of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5269]
### Description

Write a Swift program to find sum of squares of numbers

Suppose you have a list of numbers, and you want to find the sum of the squares of those numbers. For example, if you have the list `[1, 2, 3]`, you want to find the sum of the squares of those numbers, which is `1^2 + 2^2 + 3^2 = 14`.

```
Input  : 1 2 3 4 5
Output : 55
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfSquaresOfNumbers.swift` file
- Add `FindSumOfSquaresOfNumbers.swift` file in `program/find-sum-of-squares-of-numbers` folder

</details>

**Comment by esivakumar18** [comment]
!assign
