### ISSUE TITLE
Write a C program to find the inverse of a

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5272]
### Description

Write a C program to find the inverse of a

The inverse of a square matrix A is another square matrix B such that the product of A and B is the identity matrix I. The inverse of A is denoted as A<sup>-1</sup>.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
-0.16666666666666666 0.3333333333333333 -0.16666666666666666
0.3333333333333333 -0.6666666666666666 0.3333333333333333
-0.16666666666666666 0.3333333333333333 -0.16666666666666666
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindTheInverseOfA.c` file
- Add `FindTheInverseOfA.c` file in `program/find-the-inverse-of-a` folder

</details>

**Comment by roshan798** [comment]
!assign

**Comment by AdityaNarayanPradhan** [comment]
!assign
