### ISSUE TITLE
Write a C++ program to calculate simple interest

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5296]
### Description

Write a C++ program to calculate simple interest

Simple interest = (principal amount * rate of interest * time) / 100

```
Principal : 1000
Rate      : 10
Time      : 5

Simple interest : 500
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CalculateSimpleInterest.cpp` file
- Add `CalculateSimpleInterest.cpp` file in `program/calculate-simple-interest` folder

</details>

**Comment by yashasvini121** [comment]
!assign

**Comment by Coder-12-ux** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Coder-12-ux, this issue is already assigned to @yashasvini121 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
