### ISSUE TITLE
Write a JavaScript program to calculate simple interest

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5302]
### Description

Write a JavaScript program to calculate simple interest

Simple interest = (principal amount * rate of interest * time) / 100

```
Principal : 1000
Rate      : 10
Time      : 5

Simple interest : 500
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CalculateSimpleInterest.js` file
- Add `CalculateSimpleInterest.js` file in `program/calculate-simple-interest` folder

</details>

**Comment by yesayajones** [comment]
Can I work on this?

**Comment by harshraj8843** [comment]
Sorry a PR has already been raised for this issue

**Comment by harshraj8843** [comment]
You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```
