### ISSUE TITLE
Write a Julia program to calculate simple interest

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5303]
### Description

Write a Julia program to calculate simple interest

Simple interest = (principal amount * rate of interest * time) / 100

```
Principal : 1000
Rate      : 10
Time      : 5

Simple interest : 500
```
<details>
<summary>How to contribute</summary>

- Save the solution in `calculate-simple-interest.jl` file
- Add `calculate-simple-interest.jl` file in `program/calculate-simple-interest` folder

</details>

**Comment by Ishay1997** [comment]
!assign
