### ISSUE TITLE
Write a C program to convert string to alternatingcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5317]
### Description

Write a C program to convert string to alternatingcase

Alternatingcase is a style of writing in which each letter is converted to its opposite case.

```
Input  : "hello world"
Output : "hElLo WoRlD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertStringToAlternatingcase.c` file
- Add `ConvertStringToAlternatingcase.c` file in `program/convert-string-to-alternatingcase` folder

</details>

**Comment by cacti23** [comment]
!assign

**Comment by pokharel-nishan** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @pokharel-nishan, this issue is already assigned to @cacti23 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by pokharel-nishan** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @pokharel-nishan, this issue is already assigned to @cacti23 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by Siripujitha01** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Siripujitha01, this issue is already assigned to @cacti23 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by AdityaNarayanPradhan** [comment]
!assign
