### ISSUE TITLE
Write a Python program to convert string to alternatingcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5330]
### Description

Write a Python program to convert string to alternatingcase

Alternatingcase is a style of writing in which each letter is converted to its opposite case.

```
Input  : "hello world"
Output : "hElLo WoRlD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-string-to-alternatingcase.py` file
- Add `convert-string-to-alternatingcase.py` file in `program/convert-string-to-alternatingcase` folder

</details>

**Comment by Pal-Sandeep** [comment]
@harshraj8843 I want to contribute to this issue.

**Comment by harshraj8843** [comment]
Hey @Pal-Sandeep 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned 🤗 

```
!assign
```
