### ISSUE TITLE
Write a Ruby program to convert string to alternatingcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5332]
### Description

Write a Ruby program to convert string to alternatingcase

Alternatingcase is a style of writing in which each letter is converted to its opposite case.

```
Input  : "hello world"
Output : "hElLo WoRlD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertStringToAlternatingcase.rb` file
- Add `ConvertStringToAlternatingcase.rb` file in `program/convert-string-to-alternatingcase` folder

</details>

**Comment by jfinley6** [comment]
!assign
