### ISSUE TITLE
Write a C program to find sum of n natural numbers using formula

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5338]
### Description

Write a C program to find sum of n natural numbers using formula

formula: n(n+1)/2

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNNaturalNumbersUsingFormula.c` file
- Add `FindSumOfNNaturalNumbersUsingFormula.c` file in `program/find-sum-of-n-natural-numbers-using-formula` folder

</details>

**Comment by cacti23** [comment]
!assign

**Comment by Sri01729** [comment]
!assign

**Comment by roshan798** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @roshan798, this issue is already assigned to @cacti23 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by pritish1906** [comment]
!assign

**Comment by AdityaNarayanPradhan** [comment]
!assign
