### ISSUE TITLE
Write a C++ program to find sum of n natural numbers using formula

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5340]
### Description

Write a C++ program to find sum of n natural numbers using formula

formula: n(n+1)/2

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNNaturalNumbersUsingFormula.cpp` file
- Add `FindSumOfNNaturalNumbersUsingFormula.cpp` file in `program/find-sum-of-n-natural-numbers-using-formula` folder

</details>

**Comment by hi-Kartik2004** [comment]
!assign

**Comment by hi-Kartik2004** [comment]
Issue solved in Pull request number #5811

**Comment by harshraj8843** [comment]
Will be reviewed and merged shortly 🤗 

Thanks for contributing 👍🏻

**Comment by hi-Kartik2004** [comment]
Issue solved in Pull request number https://github.com/codinasion/program/pull/5811
