### ISSUE TITLE
Write a Java program to find sum of n natural numbers using formula

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5345]
### Description

Write a Java program to find sum of n natural numbers using formula

formula: n(n+1)/2

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNNaturalNumbersUsingFormula.java` file
- Add `FindSumOfNNaturalNumbersUsingFormula.java` file in `program/find-sum-of-n-natural-numbers-using-formula` folder

</details>

**Comment by dineshlalam15** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @dineshlalam15,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
