### ISSUE TITLE
Write a JavaScript program to find sum of n natural numbers using formula

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5346]
### Description

Write a JavaScript program to find sum of n natural numbers using formula

formula: n(n+1)/2

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNNaturalNumbersUsingFormula.js` file
- Add `FindSumOfNNaturalNumbersUsingFormula.js` file in `program/find-sum-of-n-natural-numbers-using-formula` folder

</details>

**Comment by yesayajones** [comment]
!assign

**Comment by yesayajones** [comment]
Can I work on this?

I try assigning myself using "!assign" but it's not working.

**Comment by harshraj8843** [comment]
Hey @yesayajones 

Thanks for noticing the assignment issue, it has been fixed :)
