### ISSUE TITLE
Write a Julia program to find sum of n natural numbers using formula

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5347]
### Description

Write a Julia program to find sum of n natural numbers using formula

formula: n(n+1)/2

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-sum-of-n-natural-numbers-using-formula.jl` file
- Add `find-sum-of-n-natural-numbers-using-formula.jl` file in `program/find-sum-of-n-natural-numbers-using-formula` folder

</details>

**Comment by champati-v** [comment]
!assign
