### ISSUE TITLE
Write a Kotlin program to find sum of n natural numbers using formula

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5348]
### Description

Write a Kotlin program to find sum of n natural numbers using formula

formula: n(n+1)/2

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNNaturalNumbersUsingFormula.kt` file
- Add `FindSumOfNNaturalNumbersUsingFormula.kt` file in `program/find-sum-of-n-natural-numbers-using-formula` folder

</details>

**Comment by gsquareg2** [comment]
!assign
