### ISSUE TITLE
Write a Python program to find sum of n natural numbers using formula

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5351]
### Description

Write a Python program to find sum of n natural numbers using formula

formula: n(n+1)/2

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-sum-of-n-natural-numbers-using-formula.py` file
- Add `find-sum-of-n-natural-numbers-using-formula.py` file in `program/find-sum-of-n-natural-numbers-using-formula` folder

</details>

**Comment by SarthakSanjay** [comment]
!assign
