### ISSUE TITLE
Write a Swift program to find sum of n natural numbers using formula

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5356]
### Description

Write a Swift program to find sum of n natural numbers using formula

formula: n(n+1)/2

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNNaturalNumbersUsingFormula.swift` file
- Add `FindSumOfNNaturalNumbersUsingFormula.swift` file in `program/find-sum-of-n-natural-numbers-using-formula` folder

</details>

**Comment by esivakumar18** [comment]
!assign
