### ISSUE TITLE
Write a GO program to find power of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#537]
### Description

Write a GO program to find power of a number by recursion

Power of a number is calculated by multiplying the number by itself for the given number of times. For example, 2^3 = 2 * 2 * 2 = 8.

Power of a number can be calculated by recursion. The formula is:

```math
x^n = x * x^{n-1}
```

```
Input  : 2 3
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_power_of_a_number_by_recursion.go` file
- Add `find_power_of_a_number_by_recursion.go` file in `find-power-of-a-number-by-recursion` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign

**Comment by sancoLgates** [comment]
!assign
