### ISSUE TITLE
Write a Java program to find power of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#538]
### Description

Write a Java program to find power of a number by recursion

Power of a number is calculated by multiplying the number by itself for the given number of times. For example, 2^3 = 2 * 2 * 2 = 8.

Power of a number can be calculated by recursion. The formula is:

```math
x^n = x * x^{n-1}
```

```
Input  : 2 3
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindPowerOfANumberByRecursion.java` file
- Add `FindPowerOfANumberByRecursion.java` file in `find-power-of-a-number-by-recursion` folder

</details>

**Comment by Mahak008** [comment]
I would like to contribute to this. Please assign this issue to me

**Comment by sumeetk10** [comment]
I want to work on this issue, can you assign this to me.

**Comment by Ipankaj07** [comment]
!assign
