### ISSUE TITLE
Write a Java program to find volume of a cylinder

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5389]
### Description

Write a Java program to find volume of a cylinder

Volume of cylinder = π × `Radius`^2 × `Height`

```
Radius : 2
Height : 3

Volume : 37.69911184307752
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfACylinder.java` file
- Add `FindVolumeOfACylinder.java` file in `program/find-volume-of-a-cylinder` folder

</details>

**Comment by Edward-Regalado** [comment]
!assign
