### ISSUE TITLE
Write a JavaScript program to find power of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#539]
### Description

Write a JavaScript program to find power of a number by recursion

Power of a number is calculated by multiplying the number by itself for the given number of times. For example, 2^3 = 2 * 2 * 2 = 8.

Power of a number can be calculated by recursion. The formula is:

```math
x^n = x * x^{n-1}
```

```
Input  : 2 3
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindPowerOfANumberByRecursion.js` file
- Add `FindPowerOfANumberByRecursion.js` file in `find-power-of-a-number-by-recursion` folder

</details>

**Comment by 9389lalit** [comment]
I would like to contribute in this

**Comment by RShalman** [comment]
!assign
