### ISSUE TITLE
Write a JavaScript program to find volume of a cylinder

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5390]
### Description

Write a JavaScript program to find volume of a cylinder

Volume of cylinder = π × `Radius`^2 × `Height`

```
Radius : 2
Height : 3

Volume : 37.69911184307752
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfACylinder.js` file
- Add `FindVolumeOfACylinder.js` file in `program/find-volume-of-a-cylinder` folder

</details>

**Comment by Edward-Regalado** [comment]
!assign

**Comment by Edward-Regalado** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Edward-Regalado, this issue is already assigned to @Edward-Regalado !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
