### ISSUE TITLE
Write a Scala program to find volume of a cylinder

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5399]
### Description

Write a Scala program to find volume of a cylinder

Volume of cylinder = π × `Radius`^2 × `Height`

```
Radius : 2
Height : 3

Volume : 37.69911184307752
```
<details>
<summary>How to contribute</summary>

- Save the solution in `findVolumeOfACylinder.scala` file
- Add `findVolumeOfACylinder.scala` file in `program/find-volume-of-a-cylinder` folder

</details>

**Comment by Edward-Regalado** [comment]
!assign
