### ISSUE TITLE
Write a Swift program to find volume of a cylinder

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5400]
### Description

Write a Swift program to find volume of a cylinder

Volume of cylinder = π × `Radius`^2 × `Height`

```
Radius : 2
Height : 3

Volume : 37.69911184307752
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfACylinder.swift` file
- Add `FindVolumeOfACylinder.swift` file in `program/find-volume-of-a-cylinder` folder

</details>

**Comment by esivakumar18** [comment]
!assign
