### ISSUE TITLE
Write a C program to find sum of digits of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5403]
### Description

Write a C program to find sum of digits of a number

Suppose you have a number `n` and you want to find the sum of its digits. For example, if `n = 123`, then the sum of its digits is `1 + 2 + 3 = 6`.

```
Input  : 123
Output : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfDigitsOfANumber.c` file
- Add `FindSumOfDigitsOfANumber.c` file in `program/find-sum-of-digits-of-a-number` folder

</details>

**Comment by Coder-12-ux** [comment]
!assign
