### ISSUE TITLE
Write a C++ program to find sum of digits of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5405]
### Description

Write a C++ program to find sum of digits of a number

Suppose you have a number `n` and you want to find the sum of its digits. For example, if `n = 123`, then the sum of its digits is `1 + 2 + 3 = 6`.

```
Input  : 123
Output : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfDigitsOfANumber.cpp` file
- Add `FindSumOfDigitsOfANumber.cpp` file in `program/find-sum-of-digits-of-a-number` folder

</details>

**Comment by hi-Kartik2004** [comment]
!assign

**Comment by hi-Kartik2004** [comment]
Issue solved in Pull request number #5811

**Comment by hi-Kartik2004** [comment]
Issue solved in Pull request number https://github.com/codinasion/program/pull/5811
