### ISSUE TITLE
Write a GO program to find sum of digits of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5408]
### Description

Write a GO program to find sum of digits of a number

Suppose you have a number `n` and you want to find the sum of its digits. For example, if `n = 123`, then the sum of its digits is `1 + 2 + 3 = 6`.

```
Input  : 123
Output : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_sum_of_digits_of_a_number.go` file
- Add `find_sum_of_digits_of_a_number.go` file in `program/find-sum-of-digits-of-a-number` folder

</details>

**Comment by iamtejasmane** [comment]
!assign

**Comment by vedantpople4** [comment]
!assign
