### ISSUE TITLE
Write a Java program to find sum of digits of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5410]
### Description

Write a Java program to find sum of digits of a number

Suppose you have a number `n` and you want to find the sum of its digits. For example, if `n = 123`, then the sum of its digits is `1 + 2 + 3 = 6`.

```
Input  : 123
Output : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfDigitsOfANumber.java` file
- Add `FindSumOfDigitsOfANumber.java` file in `program/find-sum-of-digits-of-a-number` folder

</details>

**Comment by dineshlalam15** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @dineshlalam15,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
