### ISSUE TITLE
Write a Python program to find sum of digits of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5416]
### Description

Write a Python program to find sum of digits of a number

Suppose you have a number `n` and you want to find the sum of its digits. For example, if `n = 123`, then the sum of its digits is `1 + 2 + 3 = 6`.

```
Input  : 123
Output : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-sum-of-digits-of-a-number.py` file
- Add `find-sum-of-digits-of-a-number.py` file in `program/find-sum-of-digits-of-a-number` folder

</details>

**Comment by Pinklemonade33** [comment]
!assign

**Comment by Pinklemonade33** [comment]
It seems that the "find-sum-of-digits-of-a-number.py" file is already in the "program/find-sum-of-digits-of-a-number" folder containing the requested solution.

**Comment by harshraj8843** [comment]
Thanks, @Pinklemonade33  for noticing this issue 🤗 

We may have missed it in #5707
