### ISSUE TITLE
Write a Swift program to find sum of digits of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5421]
### Description

Write a Swift program to find sum of digits of a number

Suppose you have a number `n` and you want to find the sum of its digits. For example, if `n = 123`, then the sum of its digits is `1 + 2 + 3 = 6`.

```
Input  : 123
Output : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfDigitsOfANumber.swift` file
- Add `FindSumOfDigitsOfANumber.swift` file in `program/find-sum-of-digits-of-a-number` folder

</details>

**Comment by champati-v** [comment]
!assign

**Comment by champati-v** [comment]
Thank you so much for the approval!
