### ISSUE TITLE
Write a C++ program to merge two strings

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5426]
### Description

Write a C++ program to merge two strings

```
Input  : ABC DEF
Output : ABCDEF
```
<details>
<summary>How to contribute</summary>

- Save the solution in `MergeTwoStrings.cpp` file
- Add `MergeTwoStrings.cpp` file in `program/merge-two-strings` folder

</details>

**Comment by hi-Kartik2004** [comment]
!assign

**Comment by hi-Kartik2004** [comment]
Issue solved in Pull request number #5811
