### ISSUE TITLE
Write a F# program to merge two strings

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5428]
### Description

Write a F# program to merge two strings

```
Input  : ABC DEF
Output : ABCDEF
```
<details>
<summary>How to contribute</summary>

- Save the solution in `MergeTwoStrings.fs` file
- Add `MergeTwoStrings.fs` file in `program/merge-two-strings` folder

</details>

**Comment by Preetiraj3697** [comment]
! assign

**Comment by Preetiraj3697** [comment]
!assign
