### ISSUE TITLE
Write a GO program to merge two strings

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5429]
### Description

Write a GO program to merge two strings

```
Input  : ABC DEF
Output : ABCDEF
```
<details>
<summary>How to contribute</summary>

- Save the solution in `merge_two_strings.go` file
- Add `merge_two_strings.go` file in `program/merge-two-strings` folder

</details>

**Comment by iamtejasmane** [comment]
Hi @harshraj8843, I would like to contribute, could you assign this to me?

**Comment by harshraj8843** [comment]
Hey @iamtejasmane 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned 🤗 

```
!assign
```

**Comment by iamtejasmane** [comment]
Okay, got it. Thank you.
