### ISSUE TITLE
Write a JavaScript program to merge two strings

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5432]
### Description

Write a JavaScript program to merge two strings

```
Input  : ABC DEF
Output : ABCDEF
```
<details>
<summary>How to contribute</summary>

- Save the solution in `MergeTwoStrings.js` file
- Add `MergeTwoStrings.js` file in `program/merge-two-strings` folder

</details>

**Comment by Dcastro99** [comment]
Hello, I would like to contribute to this code.

**Comment by harshraj8843** [comment]
Hey @Dcastro99 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

Thanks for showing your interest 🤗

**Comment by Dcastro99** [comment]
!assign
