### ISSUE TITLE
Write a Kotlin program to merge two strings

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5434]
### Description

Write a Kotlin program to merge two strings

```
Input  : ABC DEF
Output : ABCDEF
```
<details>
<summary>How to contribute</summary>

- Save the solution in `MergeTwoStrings.kt` file
- Add `MergeTwoStrings.kt` file in `program/merge-two-strings` folder

</details>

**Comment by Sandhya2902** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Sandhya2902,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
