### ISSUE TITLE
Write a Swift program to merge two strings

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5442]
### Description

Write a Swift program to merge two strings

```
Input  : ABC DEF
Output : ABCDEF
```
<details>
<summary>How to contribute</summary>

- Save the solution in `MergeTwoStrings.swift` file
- Add `MergeTwoStrings.swift` file in `program/merge-two-strings` folder

</details>

**Comment by esivakumar18** [comment]
!assign
