### ISSUE TITLE
Write a TypeScript program to merge two strings

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5443]
### Description

Write a TypeScript program to merge two strings

```
Input  : ABC DEF
Output : ABCDEF
```
<details>
<summary>How to contribute</summary>

- Save the solution in `MergeTwoStrings.ts` file
- Add `MergeTwoStrings.ts` file in `program/merge-two-strings` folder

</details>

**Comment by Varun-Dhruv** [comment]
!assign
