### ISSUE TITLE
Write a C program to cylindrically rotate a matrix by 90 degrees

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5445]
### Description

Write a C program to cylindrically rotate a matrix by 90 degrees

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
7 4 1
8 5 2
9 6 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `CylindricallyRotateAMatrixBy90Degrees.c` file
- Add `CylindricallyRotateAMatrixBy90Degrees.c` file in `program/cylindrically-rotate-a-matrix-by-90-degrees` folder

</details>

**Comment by cacti23** [comment]
!assign
