### ISSUE TITLE
Write a Julia program to cylindrically rotate a matrix by 90 degrees

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5454]
### Description

Write a Julia program to cylindrically rotate a matrix by 90 degrees

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
7 4 1
8 5 2
9 6 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `cylindrically-rotate-a-matrix-by-90-degrees.jl` file
- Add `cylindrically-rotate-a-matrix-by-90-degrees.jl` file in `program/cylindrically-rotate-a-matrix-by-90-degrees` folder

</details>

**Comment by abhisek-1221** [comment]
!assign

**Comment by abhisek-1221** [comment]
Issue linked to PR #7389
