### ISSUE TITLE
Write a C program to print elements of an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5466]
### Description

Write a C program to print elements of an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintElementsOfAnArray.c` file
- Add `PrintElementsOfAnArray.c` file in `program/print-elements-of-an-array` folder

</details>

**Comment by Pinklemonade33** [comment]
!assign
