### ISSUE TITLE
Write a C++ program to print elements of an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5468]
### Description

Write a C++ program to print elements of an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintElementsOfAnArray.cpp` file
- Add `PrintElementsOfAnArray.cpp` file in `program/print-elements-of-an-array` folder

</details>

**Comment by grraghav120** [comment]
!assign

**Comment by Km103** [comment]
is issue still open

**Comment by harshraj8843** [comment]
Sorry, a PR has already been raised for this. You can try other issues 🤗
