### ISSUE TITLE
Write a GO program to print elements of an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5471]
### Description

Write a GO program to print elements of an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `print_elements_of_an_array.go` file
- Add `print_elements_of_an_array.go` file in `program/print-elements-of-an-array` folder

</details>

**Comment by sahdev77** [comment]
!assign

**Comment by vedantpople4** [comment]
!assign
