### ISSUE TITLE
Write a Haskell program to print elements of an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5472]
### Description

Write a Haskell program to print elements of an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `print_elements_of_an_array.hs` file
- Add `print_elements_of_an_array.hs` file in `program/print-elements-of-an-array` folder

</details>

**Comment by Amirth24** [comment]
!assign

**Comment by Amirth24** [comment]
I've already given the solution in #7101. Please close the issue
