### ISSUE TITLE
Write a Java program to print elements of an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5473]
### Description

Write a Java program to print elements of an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintElementsOfAnArray.java` file
- Add `PrintElementsOfAnArray.java` file in `program/print-elements-of-an-array` folder

</details>

**Comment by dineshlalam15** [comment]
!assign
