### ISSUE TITLE
Write a Kotlin program to print elements of an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5476]
### Description

Write a Kotlin program to print elements of an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintElementsOfAnArray.kt` file
- Add `PrintElementsOfAnArray.kt` file in `program/print-elements-of-an-array` folder

</details>

**Comment by gsquareg2** [comment]
!assign
