### ISSUE TITLE
Write a Ruby program to print elements of an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5481]
### Description

Write a Ruby program to print elements of an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintElementsOfAnArray.rb` file
- Add `PrintElementsOfAnArray.rb` file in `program/print-elements-of-an-array` folder

</details>

**Comment by jfinley6** [comment]
!assign
