### ISSUE TITLE
Write a Rust program to print elements of an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5482]
### Description

Write a Rust program to print elements of an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `print_elements_of_an_array.rs` file
- Add `print_elements_of_an_array.rs` file in `program/print-elements-of-an-array` folder

</details>

**Comment by hugosmoreira** [comment]
!assign
