### ISSUE TITLE
Write a Swift program to print elements of an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5484]
### Description

Write a Swift program to print elements of an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintElementsOfAnArray.swift` file
- Add `PrintElementsOfAnArray.swift` file in `program/print-elements-of-an-array` folder

</details>

**Comment by esivakumar18** [comment]
!assign
