### ISSUE TITLE
Write a TypeScript program to print elements of an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5485]
### Description

Write a TypeScript program to print elements of an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintElementsOfAnArray.ts` file
- Add `PrintElementsOfAnArray.ts` file in `program/print-elements-of-an-array` folder

</details>

**Comment by AleksiUu** [comment]
!assign
