### ISSUE TITLE
Write a C++ program to convert weeks to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5513]
### Description

Write a C++ program to convert weeks to days

1 week = 7 days

```
Input  : 5
Output : 35
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToDays.cpp` file
- Add `ConvertWeeksToDays.cpp` file in `program/convert-weeks-to-days` folder

</details>

**Comment by hi-Kartik2004** [comment]
!assign

**Comment by hi-Kartik2004** [comment]
Issue solved in Pull request number #5811
