### ISSUE TITLE
Write a F# program to convert weeks to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5515]
### Description

Write a F# program to convert weeks to days

1 week = 7 days

```
Input  : 5
Output : 35
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToDays.fs` file
- Add `ConvertWeeksToDays.fs` file in `program/convert-weeks-to-days` folder

</details>

**Comment by Preetiraj3697** [comment]
Assign me.
