### ISSUE TITLE
Write a Haskell program to convert weeks to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5517]
### Description

Write a Haskell program to convert weeks to days

1 week = 7 days

```
Input  : 5
Output : 35
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_weeks_to_days.hs` file
- Add `convert_weeks_to_days.hs` file in `program/convert-weeks-to-days` folder

</details>

**Comment by akaliacius** [comment]
!assign
