### ISSUE TITLE
Write a JavaScript program to convert weeks to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5519]
### Description

Write a JavaScript program to convert weeks to days

1 week = 7 days

```
Input  : 5
Output : 35
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToDays.js` file
- Add `ConvertWeeksToDays.js` file in `program/convert-weeks-to-days` folder

</details>

**Comment by SarthakSanjay** [comment]
!assign
