### ISSUE TITLE
Write a Julia program to convert weeks to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5520]
### Description

Write a Julia program to convert weeks to days

1 week = 7 days

```
Input  : 5
Output : 35
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-weeks-to-days.jl` file
- Add `convert-weeks-to-days.jl` file in `program/convert-weeks-to-days` folder

</details>

**Comment by nicoleSosa** [comment]
!assign
