### ISSUE TITLE
Write a Python program to convert weeks to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5524]
### Description

Write a Python program to convert weeks to days

1 week = 7 days

```
Input  : 5
Output : 35
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-weeks-to-days.py` file
- Add `convert-weeks-to-days.py` file in `program/convert-weeks-to-days` folder

</details>

**Comment by loesking** [comment]
!assign
