### ISSUE TITLE
Write a Ruby program to convert weeks to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5526]
### Description

Write a Ruby program to convert weeks to days

1 week = 7 days

```
Input  : 5
Output : 35
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToDays.rb` file
- Add `ConvertWeeksToDays.rb` file in `program/convert-weeks-to-days` folder

</details>

**Comment by jfinley6** [comment]
!assign
