### ISSUE TITLE
Write a Rust program to convert weeks to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5527]
### Description

Write a Rust program to convert weeks to days

1 week = 7 days

```
Input  : 5
Output : 35
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_weeks_to_days.rs` file
- Add `convert_weeks_to_days.rs` file in `program/convert-weeks-to-days` folder

</details>

**Comment by hugosmoreira** [comment]
!assign
