### ISSUE TITLE
Write a Swift program to convert weeks to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5529]
### Description

Write a Swift program to convert weeks to days

1 week = 7 days

```
Input  : 5
Output : 35
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToDays.swift` file
- Add `ConvertWeeksToDays.swift` file in `program/convert-weeks-to-days` folder

</details>

**Comment by esivakumar18** [comment]
!assign
