### ISSUE TITLE
Write a TypeScript program to convert weeks to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5530]
### Description

Write a TypeScript program to convert weeks to days

1 week = 7 days

```
Input  : 5
Output : 35
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToDays.ts` file
- Add `ConvertWeeksToDays.ts` file in `program/convert-weeks-to-days` folder

</details>

**Comment by AleksiUu** [comment]
!assign
