### ISSUE TITLE
Find length of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5533]
### Description

Write a program to find length of a string

```
Input  : abcd
Output : 4
```

### Tracking Issues

- [x] #5534
- [x] #5535
- [x] #5536
- [x] #5537
- [x] #5538
- [x] #5539
- [x] #5540
- [x] #5541
- [x] #5542
- [x] #5543
- [x] #5544
- [x] #5545
- [x] #5546
- [x] #5547
- [x] #5548
- [x] #5549
- [x] #5550
- [x] #5551
- [x] #5552
- [x] #5553

**Comment by Anujsharma002** [comment]
please assign to me
