### ISSUE TITLE
Write a C program to find length of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5534]
### Description

Write a C program to find length of a string

```
Input  : abcd
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindLengthOfAString.c` file
- Add `FindLengthOfAString.c` file in `program/find-length-of-a-string` folder

</details>

**Comment by Pinklemonade33** [comment]
!assign

**Comment by kashif0313** [comment]
hi i want to contribute to this can u assign me

**Comment by kashif0313** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @kashif0313, this issue is already assigned to @Pinklemonade33 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Sure @Osher160 

Thank for noticing the issue 👍🏻
