### ISSUE TITLE
Write a C++ program to find length of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5536]
### Description

Write a C++ program to find length of a string

```
Input  : abcd
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindLengthOfAString.cpp` file
- Add `FindLengthOfAString.cpp` file in `program/find-length-of-a-string` folder

</details>

**Comment by hi-Kartik2004** [comment]
Can you assign this task to me!?

**Comment by harshraj8843** [comment]
Hey @hi-Kartik2004 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```
