### ISSUE TITLE
Write a Haskell program to find length of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5540]
### Description

Write a Haskell program to find length of a string

```
Input  : abcd
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_length_of_a_string.hs` file
- Add `find_length_of_a_string.hs` file in `program/find-length-of-a-string` folder

</details>

**Comment by cacti23** [comment]
!assign

**Comment by esivakumar18** [comment]
!assign
