### ISSUE TITLE
Write a JavaScript program to find length of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5542]
### Description

Write a JavaScript program to find length of a string

```
Input  : abcd
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindLengthOfAString.js` file
- Add `FindLengthOfAString.js` file in `program/find-length-of-a-string` folder

</details>

**Comment by SarthakSanjay** [comment]
!assign
