### ISSUE TITLE
Write a Julia program to find length of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5543]
### Description

Write a Julia program to find length of a string

```
Input  : abcd
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-length-of-a-string.jl` file
- Add `find-length-of-a-string.jl` file in `program/find-length-of-a-string` folder

</details>

**Comment by SoumyadiptoPal** [comment]
!assign
