### ISSUE TITLE
Write a Kotlin program to find length of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5544]
### Description

Write a Kotlin program to find length of a string

```
Input  : abcd
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindLengthOfAString.kt` file
- Add `FindLengthOfAString.kt` file in `program/find-length-of-a-string` folder

</details>

**Comment by Oudeinguene** [comment]
!assign
