### ISSUE TITLE
Write a Ruby program to find length of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5549]
### Description

Write a Ruby program to find length of a string

```
Input  : abcd
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindLengthOfAString.rb` file
- Add `FindLengthOfAString.rb` file in `program/find-length-of-a-string` folder

</details>

**Comment by jfinley6** [comment]
For stuff like this are you looking for an answer without a built in method? For instance string.length

**Comment by harshraj8843** [comment]
Hey @jfinley6 

Any method will be acceptable, if not explicitly addressed (like, write a program *** `without using in-built function`)

**Comment by jfinley6** [comment]
Ok perfect

**Comment by jfinley6** [comment]
!assign
