### ISSUE TITLE
Write a TypeScript program to find length of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5553]
### Description

Write a TypeScript program to find length of a string

```
Input  : abcd
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindLengthOfAString.ts` file
- Add `FindLengthOfAString.ts` file in `program/find-length-of-a-string` folder

</details>

**Comment by AleksiUu** [comment]
!assign
