### ISSUE TITLE
Write a GO program to print reverse of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5560]
### Description

Write a GO program to print reverse of a number by recursion

Reverse of a number is the number obtained by reversing the digits of the original number. For example, reverse of 123 is 321. The recursive solution is to print the last digit of the number and then call the function recursively to print the remaining digits.

```
Input  : 123
Output : 321
```
<details>
<summary>How to contribute</summary>

- Save the solution in `print_reverse_of_a_number_by_recursion.go` file
- Add `print_reverse_of_a_number_by_recursion.go` file in `program/print-reverse-of-a-number-by-recursion` folder

</details>

**Comment by sahdev77** [comment]
!assign

**Comment by cacti23** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @cacti23, this issue is already assigned to @sahdev77 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by sancoLgates** [comment]
!assign
