### ISSUE TITLE
Write a Kotlin program to print reverse of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5565]
### Description

Write a Kotlin program to print reverse of a number by recursion

Reverse of a number is the number obtained by reversing the digits of the original number. For example, reverse of 123 is 321. The recursive solution is to print the last digit of the number and then call the function recursively to print the remaining digits.

```
Input  : 123
Output : 321
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintReverseOfANumberByRecursion.kt` file
- Add `PrintReverseOfANumberByRecursion.kt` file in `program/print-reverse-of-a-number-by-recursion` folder

</details>

**Comment by ANUSHRAV01** [comment]
Hello @harshraj8843 I like to contribute
fun reverseNumber(num: Int): Int {
    return if (num < 10) {
        num
    } else {
        val lastDigit = num % 10
        val remainingNum = num / 10
        val reversedRemainingNum = reverseNumber(remainingNum)
        (lastDigit * Math.pow(10.0, (remainingNum.toString().length).toDouble()).toInt()) + reversedRemainingNum
    }
}

fun main() {
    val number = 12345
    val reversedNumber = reverseNumber(number)
    println("The reverse of $number is $reversedNumber")
}
Can u review it once and assign this issue to me.

**Comment by harshraj8843** [comment]
> Can u review it 

It works well 👍🏻 

---

> assign this issue to me

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by SoumyadiptoPal** [comment]
!assign
