### ISSUE TITLE
Write a TypeScript program to print reverse of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5574]
### Description

Write a TypeScript program to print reverse of a number by recursion

Reverse of a number is the number obtained by reversing the digits of the original number. For example, reverse of 123 is 321. The recursive solution is to print the last digit of the number and then call the function recursively to print the remaining digits.

```
Input  : 123
Output : 321
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintReverseOfANumberByRecursion.ts` file
- Add `PrintReverseOfANumberByRecursion.ts` file in `program/print-reverse-of-a-number-by-recursion` folder

</details>

**Comment by UrielOfir** [comment]
Hello, can I be assigned to this project?

**Comment by harshraj8843** [comment]
Hey @UrielOfir 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by UrielOfir** [comment]
!assign
