### ISSUE TITLE
Write a C++ program to find the eigenvalues of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5578]
### Description

Write a C++ program to find the eigenvalues of a matrix

The eigenvalues and eigenvectors of a linear transformation are the values and vectors that determine the transformation. The eigenvalues of a matrix A are the values λ for which the matrix equation Av = λv has a non-trivial solution.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
16.116843969807043
-1.1168439698070427
0.9999999999999998
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindTheEigenvaluesOfAMatrix.cpp` file
- Add `FindTheEigenvaluesOfAMatrix.cpp` file in `program/find-the-eigenvalues-of-a-matrix` folder

</details>

**Comment by maneesh756** [comment]
!assign
