### ISSUE TITLE
Write a C program to convert feet to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5597]
### Description

Write a C program to convert feet to inches

1 foot = 12 inches

```
Input  : 5
Output : 60
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToInches.c` file
- Add `ConvertFeetToInches.c` file in `program/convert-feet-to-inches` folder

</details>

**Comment by block2045** [comment]
!assign
