### ISSUE TITLE
Write a C++ program to convert feet to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5599]
### Description

Write a C++ program to convert feet to inches

1 foot = 12 inches

```
Input  : 5
Output : 60
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToInches.cpp` file
- Add `ConvertFeetToInches.cpp` file in `program/convert-feet-to-inches` folder

</details>

**Comment by hi-Kartik2004** [comment]
Can you assign this task to me!

**Comment by harshraj8843** [comment]
Hey @hi-Kartik2004 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by hi-Kartik2004** [comment]
!assign
