### ISSUE TITLE
Write a F# program to convert feet to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5601]
### Description

Write a F# program to convert feet to inches

1 foot = 12 inches

```
Input  : 5
Output : 60
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToInches.fs` file
- Add `ConvertFeetToInches.fs` file in `program/convert-feet-to-inches` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
