### ISSUE TITLE
Write a Haskell program to convert feet to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5603]
### Description

Write a Haskell program to convert feet to inches

1 foot = 12 inches

```
Input  : 5
Output : 60
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_feet_to_inches.hs` file
- Add `convert_feet_to_inches.hs` file in `program/convert-feet-to-inches` folder

</details>

**Comment by anafvana** [comment]
!assign
