### ISSUE TITLE
Write a JavaScript program to convert feet to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5605]
### Description

Write a JavaScript program to convert feet to inches

1 foot = 12 inches

```
Input  : 5
Output : 60
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToInches.js` file
- Add `ConvertFeetToInches.js` file in `program/convert-feet-to-inches` folder

</details>

**Comment by grraghav120** [comment]
!assign

**Comment by Sumsum1000** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Sumsum1000, this issue is already assigned to @grraghav120 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
