### ISSUE TITLE
Write a Julia program to convert feet to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5606]
### Description

Write a Julia program to convert feet to inches

1 foot = 12 inches

```
Input  : 5
Output : 60
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-feet-to-inches.jl` file
- Add `convert-feet-to-inches.jl` file in `program/convert-feet-to-inches` folder

</details>

**Comment by SoumyadiptoPal** [comment]
!assign

**Comment by RiteshK-611** [comment]
!assign
