### ISSUE TITLE
Write a Kotlin program to convert feet to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5607]
### Description

Write a Kotlin program to convert feet to inches

1 foot = 12 inches

```
Input  : 5
Output : 60
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToInches.kt` file
- Add `ConvertFeetToInches.kt` file in `program/convert-feet-to-inches` folder

</details>

**Comment by jayendra541** [comment]
!assign
