### ISSUE TITLE
Write a Python program to convert feet to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5610]
### Description

Write a Python program to convert feet to inches

1 foot = 12 inches

```
Input  : 5
Output : 60
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-feet-to-inches.py` file
- Add `convert-feet-to-inches.py` file in `program/convert-feet-to-inches` folder

</details>

**Comment by arunkumarkota** [comment]
!assign
