### ISSUE TITLE
Write a R program to convert feet to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5611]
### Description

Write a R program to convert feet to inches

1 foot = 12 inches

```
Input  : 5
Output : 60
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_feet_to_inches.r` file
- Add `convert_feet_to_inches.r` file in `program/convert-feet-to-inches` folder

</details>

**Comment by Sumsum1000** [comment]
!assign

**Comment by esivakumar18** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @esivakumar18, this issue is already assigned to @Sumsum1000 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by KyleWynne** [comment]
!assign

**Comment by harshraj8843** [comment]
!assign Test

**Comment by jacksonmcafee** [comment]
!assign
