### ISSUE TITLE
Write a Ruby program to convert feet to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5612]
### Description

Write a Ruby program to convert feet to inches

1 foot = 12 inches

```
Input  : 5
Output : 60
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToInches.rb` file
- Add `ConvertFeetToInches.rb` file in `program/convert-feet-to-inches` folder

</details>

**Comment by jfinley6** [comment]
!assign
