### ISSUE TITLE
Write a Rust program to convert feet to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5613]
### Description

Write a Rust program to convert feet to inches

1 foot = 12 inches

```
Input  : 5
Output : 60
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_feet_to_inches.rs` file
- Add `convert_feet_to_inches.rs` file in `program/convert-feet-to-inches` folder

</details>

**Comment by hugosmoreira** [comment]
!assign
