### ISSUE TITLE
Write a Swift program to convert feet to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5615]
### Description

Write a Swift program to convert feet to inches

1 foot = 12 inches

```
Input  : 5
Output : 60
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToInches.swift` file
- Add `ConvertFeetToInches.swift` file in `program/convert-feet-to-inches` folder

</details>

**Comment by jayendra541** [comment]
!assign

**Comment by patel-aum** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @patel-aum, this issue is already assigned to @jayendra541 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by patel-aum** [comment]
heyy @jayendra541 are you still working on this issue?

**Comment by esivakumar18** [comment]
!assign

**Comment by esivakumar18** [comment]
!assign

**Comment by champati-v** [comment]
!assign

**Comment by champati-v** [comment]
Hi @harshraj8843 , I've created a pull request for the above issue #5615 . You may check.
