### ISSUE TITLE
Write a TypeScript program to convert feet to inches

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5616]
### Description

Write a TypeScript program to convert feet to inches

1 foot = 12 inches

```
Input  : 5
Output : 60
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToInches.ts` file
- Add `ConvertFeetToInches.ts` file in `program/convert-feet-to-inches` folder

</details>

**Comment by Varun-Dhruv** [comment]
!assign
