### ISSUE TITLE
Convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5617]
### Description

Write a program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```

### Tracking Issues

- [x] #5618
- [x] #5619
- [x] #5620
- [x] #5621
- [x] #5622
- [x] #5623
- [x] #5624
- [x] #5625
- [x] #5626
- [ ] #5627
- [x] #5628
- [x] #5629
- [x] #5630
- [x] #5631
- [x] #5632
- [x] #5633
- [x] #5634
- [x] #5635
- [x] #5636
- [x] #5637

**Comment by we-kash** [comment]
#include <stdio.h>
         int main()
         {
               long double inches,feet;//to store fractional part
               printf("Enter inches: ");
               scanf("%Lf",&inches);//To take take the input from the user
               feet=inches/12;
               printf("%Lf ",feet);
               return 0;
        }

**Comment by harisdev-netizen** [comment]
Can you assign me this issue?

**Comment by harshraj8843** [comment]
Hey @harisdev-netizen 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by harisdev-netizen** [comment]
!assign
