### ISSUE TITLE
Write a C program to convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5618]
### Description

Write a C program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToFeet.c` file
- Add `ConvertInchesToFeet.c` file in `program/convert-inches-to-feet` folder

</details>

**Comment by ob-codes** [comment]
!assign

**Comment by kashif0313** [comment]
hey i want to contribute to this can u assign me this
