### ISSUE TITLE
Write a C++ program to convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5620]
### Description

Write a C++ program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToFeet.cpp` file
- Add `ConvertInchesToFeet.cpp` file in `program/convert-inches-to-feet` folder

</details>

**Comment by grraghav120** [comment]
!assign
