### ISSUE TITLE
Write a GO program to convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5623]
### Description

Write a GO program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_inches_to_feet.go` file
- Add `convert_inches_to_feet.go` file in `program/convert-inches-to-feet` folder

</details>

**Comment by vedantpople4** [comment]
!assign
