### ISSUE TITLE
Write a Java program to convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5625]
### Description

Write a Java program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToFeet.java` file
- Add `ConvertInchesToFeet.java` file in `program/convert-inches-to-feet` folder

</details>

**Comment by notpx** [comment]
!assign

**Comment by anandfresh** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @anandfresh, this issue is already assigned to @notpx !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
