### ISSUE TITLE
Write a JavaScript program to convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5626]
### Description

Write a JavaScript program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToFeet.js` file
- Add `ConvertInchesToFeet.js` file in `program/convert-inches-to-feet` folder

</details>

**Comment by Sumsum1000** [comment]
!assign

**Comment by anandfresh** [comment]
> !assign

@Sumsum1000  this issue has been closed already
