### ISSUE TITLE
Write a Kotlin program to convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5628]
### Description

Write a Kotlin program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToFeet.kt` file
- Add `ConvertInchesToFeet.kt` file in `program/convert-inches-to-feet` folder

</details>

**Comment by rksp25** [comment]
!assign
