### ISSUE TITLE
Write a Python program to convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5631]
### Description

Write a Python program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-inches-to-feet.py` file
- Add `convert-inches-to-feet.py` file in `program/convert-inches-to-feet` folder

</details>

**Comment by gtierrezandres** [comment]
!assign
