### ISSUE TITLE
Write a R program to convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5632]
### Description

Write a R program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_inches_to_feet.r` file
- Add `convert_inches_to_feet.r` file in `program/convert-inches-to-feet` folder

</details>

**Comment by rksp25** [comment]
!assign

**Comment by aarishmkhan** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @aarishmkhan, this issue is already assigned to @rksp25 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by ANUSHRAV01** [comment]
Hello @harshraj8843 ,I feel maybe this issue is not completed and can u assign this

**Comment by ANUSHRAV01** [comment]
# function to convert inches to feet
inches_to_feet <- function(inches) {
  feet <- inches / 12
  return(feet)
}

can u review this code

**Comment by harshraj8843** [comment]
Hey @ANUSHRAV01 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned 🤗 

```
!assign
```
