### ISSUE TITLE
Write a Rust program to convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5634]
### Description

Write a Rust program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_inches_to_feet.rs` file
- Add `convert_inches_to_feet.rs` file in `program/convert-inches-to-feet` folder

</details>

**Comment by hugosmoreira** [comment]
Hello again, can I try this one too?

**Comment by harshraj8843** [comment]
Hey @hugosmoreira 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned 😃 

```
!assign
```

**Comment by hugosmoreira** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @hugosmoreira,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
