### ISSUE TITLE
Write a Scala program to convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5635]
### Description

Write a Scala program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convertInchesToFeet.scala` file
- Add `convertInchesToFeet.scala` file in `program/convert-inches-to-feet` folder

</details>

**Comment by ANUSHRAV01** [comment]
can u assign me this task . I understand code but recently i know about the open-source and i find it very interesting and like to be     of a good community

**Comment by harshraj8843** [comment]
Hey @ANUSHRAV01 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned 🤗 

```
!assign
```
