### ISSUE TITLE
Write a Swift program to convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5636]
### Description

Write a Swift program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToFeet.swift` file
- Add `ConvertInchesToFeet.swift` file in `program/convert-inches-to-feet` folder

</details>

**Comment by patel-aum** [comment]
!assign

**Comment by patel-aum** [comment]
Check this i have used int as required but could convert it to float to get precise values after conversions
