### ISSUE TITLE
Write a TypeScript program to convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5637]
### Description

Write a TypeScript program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToFeet.ts` file
- Add `ConvertInchesToFeet.ts` file in `program/convert-inches-to-feet` folder

</details>

**Comment by Varun-Dhruv** [comment]
!assign
