### ISSUE TITLE
Write a C program to split string into array of words

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5639]
### Description

Write a C program to split string into array of words

```
Input  : "hello world"
Output : ["hello", "world"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `SplitStringIntoArrayOfWords.c` file
- Add `SplitStringIntoArrayOfWords.c` file in `program/split-string-into-array-of-words` folder

</details>

**Comment by Pinklemonade33** [comment]
!assign

**Comment by kashif0313** [comment]
hey i want to contribute to this can u assign me this task ( c program to split string into array )

**Comment by harshraj8843** [comment]
Hey @kashif0313 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by kashif0313** [comment]
!assign

**Comment by aarishmkhan** [comment]
The issue has not been resolved yet, so can you assign me this task

**Comment by aarishmkhan** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @aarishmkhan, this issue is already assigned to @kashif0313 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by ashish07-07** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @ashish07-07, this issue is already assigned to @kashif0313 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by anshuman0123** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @anshuman0123, this issue is already assigned to @kashif0313 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by rishivyas24** [comment]
Hey I want to work on this issue, Is any one working on this project?

**Comment by iligeoili** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @iligeoili, this issue is already assigned to @rishivyas24 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by ANUSHRAV01** [comment]
hello @harshraj8843 , i really like to contribute to git and i find it very interesting to contribute to this issue. i am so ,interested that i have done the written the code
can u !assign me this task too

**Comment by ANUSHRAV01** [comment]
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {
  char input[] = "hello world";
  char **words = malloc(sizeof(char*) * strlen(input));
  int word_count = 0;
  char *token = strtok(input, " ");
  while (token != NULL) {
    words[word_count] = malloc(sizeof(char) * strlen(token));
    strcpy(words[word_count], token);
    word_count++;
    token = strtok(NULL, " ");
  }
  for (int i = 0; i < word_count; i++) {
    printf("%s\n", words[i]);
    free(words[i]);
  }
  free(words);
  return 0;
}
 here is the code that i am thinking .can u say whether it is correct or not

**Comment by harshraj8843** [comment]
> can u say whether it is correct or not

Now, its correct @anshuman0123 

You can raise a Pull Request for this 🤗

**Comment by mohamedmehdigara** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @mohamedmehdigara, this issue is already assigned to @ANUSHRAV01 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
