### ISSUE TITLE
Write a C++ program to split string into array of words

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5641]
### Description

Write a C++ program to split string into array of words

```
Input  : "hello world"
Output : ["hello", "world"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `SplitStringIntoArrayOfWords.cpp` file
- Add `SplitStringIntoArrayOfWords.cpp` file in `program/split-string-into-array-of-words` folder

</details>

**Comment by grraghav120** [comment]
!assign
