### ISSUE TITLE
Write a Dart program to split string into array of words

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5642]
### Description

Write a Dart program to split string into array of words

```
Input  : "hello world"
Output : ["hello", "world"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `split_string_into_array_of_words.dart` file
- Add `split_string_into_array_of_words.dart` file in `program/split-string-into-array-of-words` folder

</details>

**Comment by loesking** [comment]
!assign
