### ISSUE TITLE
Write a F# program to split string into array of words

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5643]
### Description

Write a F# program to split string into array of words

```
Input  : "hello world"
Output : ["hello", "world"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `SplitStringIntoArrayOfWords.fs` file
- Add `SplitStringIntoArrayOfWords.fs` file in `program/split-string-into-array-of-words` folder

</details>

**Comment by ashish07-07** [comment]
!assign
