### ISSUE TITLE
Write a Haskell program to split string into array of words

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5645]
### Description

Write a Haskell program to split string into array of words

```
Input  : "hello world"
Output : ["hello", "world"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `split_string_into_array_of_words.hs` file
- Add `split_string_into_array_of_words.hs` file in `program/split-string-into-array-of-words` folder

</details>

**Comment by cacti23** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @iligeoili, this issue is already assigned to @cacti23 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by Sumsum1000** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Sumsum1000, this issue is already assigned to @iligeoili !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by ritika4554244** [comment]
assign!!

**Comment by abhisek-1221** [comment]
!assign
