### ISSUE TITLE
Write a JavaScript program to split string into array of words

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5647]
### Description

Write a JavaScript program to split string into array of words

```
Input  : "hello world"
Output : ["hello", "world"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `SplitStringIntoArrayOfWords.js` file
- Add `SplitStringIntoArrayOfWords.js` file in `program/split-string-into-array-of-words` folder

</details>

**Comment by sparsh-30** [comment]
I want to work on this. Please assign me to this issue.

**Comment by anandfresh** [comment]
!assign

**Comment by harshraj8843** [comment]
> I want to work on this. Please assign me to this issue.

Hey @sparsh-30 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by Sumsum1000** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Sumsum1000, this issue is already assigned to @anandfresh !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
