### ISSUE TITLE
Write a Julia program to split string into array of words

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5648]
### Description

Write a Julia program to split string into array of words

```
Input  : "hello world"
Output : ["hello", "world"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `split-string-into-array-of-words.jl` file
- Add `split-string-into-array-of-words.jl` file in `program/split-string-into-array-of-words` folder

</details>

**Comment by ashish07-07** [comment]
!assign
