### ISSUE TITLE
Write a Kotlin program to split string into array of words

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5649]
### Description

Write a Kotlin program to split string into array of words

```
Input  : "hello world"
Output : ["hello", "world"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `SplitStringIntoArrayOfWords.kt` file
- Add `SplitStringIntoArrayOfWords.kt` file in `program/split-string-into-array-of-words` folder

</details>

**Comment by james-tharit** [comment]
If this is still on going, can you assign it to me?

**Comment by harshraj8843** [comment]
Hey @james-tharit 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by james-tharit** [comment]
!assign
