### ISSUE TITLE
Write a Python program to split string into array of words

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5652]
### Description

Write a Python program to split string into array of words

```
Input  : "hello world"
Output : ["hello", "world"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `split-string-into-array-of-words.py` file
- Add `split-string-into-array-of-words.py` file in `program/split-string-into-array-of-words` folder

</details>

**Comment by loesking** [comment]
!assign
