### ISSUE TITLE
Write a R program to split string into array of words

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5653]
### Description

Write a R program to split string into array of words

```
Input  : "hello world"
Output : ["hello", "world"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `split_string_into_array_of_words.r` file
- Add `split_string_into_array_of_words.r` file in `program/split-string-into-array-of-words` folder

</details>

**Comment by WHJang-0421** [comment]
!assign
