### ISSUE TITLE
Write a Rust program to split string into array of words

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5655]
### Description

Write a Rust program to split string into array of words

```
Input  : "hello world"
Output : ["hello", "world"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `split_string_into_array_of_words.rs` file
- Add `split_string_into_array_of_words.rs` file in `program/split-string-into-array-of-words` folder

</details>

**Comment by hugosmoreira** [comment]
fn split_string(s: &str) -> Vec<&str> {
    s.split_whitespace().collect()
}

fn main() {
    let s = "hello world";
    let words = split_string(s);
    println!("{:?}", words);
}

**Comment by harshraj8843** [comment]
Hey @hugosmoreira 

Could you please raise a PR for this 😃

**Comment by hugosmoreira** [comment]
@harshraj8843 I'm trying, I don't experience doing PR and it's making me frustrated but I will get there

**Comment by harshraj8843** [comment]
Hey @hugosmoreira 

You can add code from the GitHub website like this

On the repo home page -> Add a new file

![Screenshot from 2022-12-12 00-36-17](https://user-images.githubusercontent.com/54644599/206923727-250a1d1f-5b08-4474-83d9-6f1211799e19.png)

Then create a new branch

![Screenshot from 2022-12-12 00-36-40](https://user-images.githubusercontent.com/54644599/206923725-e964f0c8-3a1c-4475-84b6-39b7d20dca23.png)

Then you will be able to create a PR

---

Hope this will help 🤗

**Comment by hugosmoreira** [comment]
@harshraj8843 I just did thank you for the help, I was trying to use vscode but I failed I will try to practice more
