### ISSUE TITLE
Write a Scala program to split string into array of words

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5656]
### Description

Write a Scala program to split string into array of words

```
Input  : "hello world"
Output : ["hello", "world"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `splitStringIntoArrayOfWords.scala` file
- Add `splitStringIntoArrayOfWords.scala` file in `program/split-string-into-array-of-words` folder

</details>

**Comment by Sdfeagt** [comment]
!assign

**Comment by patel-aum** [comment]
ok i can do this
