### ISSUE TITLE
Write a TypeScript program to split string into array of words

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5658]
### Description

Write a TypeScript program to split string into array of words

```
Input  : "hello world"
Output : ["hello", "world"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `SplitStringIntoArrayOfWords.ts` file
- Add `SplitStringIntoArrayOfWords.ts` file in `program/split-string-into-array-of-words` folder

</details>

**Comment by Varun-Dhruv** [comment]
Hey I would like to contribute to this issue can you please assign me the task

**Comment by Varun-Dhruv** [comment]
!assign
