### ISSUE TITLE
Write a PHP program to print reverse of a string by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#566]
### Description

Write a PHP program to print reverse of a string by recursion

Reverse of a string is the string with characters in reverse order. For example, reverse of "GeeksQuiz" is "ziuQskeeG".

```
Input  : abcd
Output : dcba
```
<details>
<summary>How to contribute</summary>

- Save the solution in `print_reverse_of_a_string_by_recursion.php` file
- Add `print_reverse_of_a_string_by_recursion.php` file in `print-reverse-of-a-string-by-recursion` folder

</details>

**Comment by sksachin7z2** [comment]
!assign
