### ISSUE TITLE
Unassign Issues

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5709]
Write a script to unassign users from `good first issue` whose assignment is older than a month.

### Why

Hundreds of `good first issue` were assigned to different contributors during `Hacktoberfest 2022` but were never completed.

### How to contribute

- Add a python script inside the `scripts` folder
- create a PR

---

The way I am thinking of the solution is as follows:- 

1. `GET` all `good-first-issues` from the Github API

	`GET` https://api.github.com/repos/codinasion/program/issues?labels=good%20first%20issue

3. Check for the length of `assignees`. If length > 0

5. `Get` issue events from the Github API

	`GET` https://api.github.com/repos/codinasion/program/issues/5657/events

7. Find the latest assignment event

	```json
	"event": "assigned",
	```

9. Check event time and compare from time. now

	```json
	"created_at": "2022-12-31T14:57:00Z",
	```

11. If the assignment is older than a specific time period unassign the user

	https://docs.github.com/en/rest/issues/assignees?apiVersion=2022-11-28#remove-assignees-from-an-issue

**Comment by patel-aum** [comment]
I am ready to contribute , can u assign me this ... so that i can unasssign users  lol  :^)

**Comment by hi-Kartik2004** [comment]
Sure @patel-aum :)

**Comment by sharvil1205** [comment]
Someone, please work on this. Many users assigned issues to themselves months ago, but haven't solved them.

**Comment by harshraj8843** [comment]
Hey @sharvil1205 

Sorry for the issue, it will be solved ASAP

**Comment by harshraj8843** [comment]
Hey @patel-aum 

Are you still working on this issue? Otherwise I would like to solve it

**Comment by patel-aum** [comment]
> Hey @patel-aum
> 
> Are you still working on this issue? Otherwise I would like to solve it

yess i will try again!!
