### ISSUE TITLE
Filter programs by languages

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5735]
### What to do

Update the website code to filter programs based on the programming language

![Screenshot from 2022-12-17 23-41-29](https://user-images.githubusercontent.com/54644599/208255727-db1e73ad-728b-4db2-8fbe-459e809e97c0.png)

For example, check out [`good1stissue.codinasion.org`](https://good1stissue.codinasion.org/)

![Screenshot from 2022-12-17 23-45-40](https://user-images.githubusercontent.com/54644599/208255771-0db35ceb-074e-45e9-83f8-37c0452c2313.png)

### What to Update

Update the[`pages/index.tsx`](https://github.com/codinasion/program/blob/master/website/pages/index.tsx) with similar logic to :point_right: https://github.com/codinasion/good-1st-issue/blob/master/pages/index.js

**Comment by 0ME9A** [comment]
Bro allows me to complete this project.🧑‍💻

**Comment by harshraj8843** [comment]
Sure 👍🏻

**Comment by harshraj8843** [comment]
Please let me know if you need any help 🤗

**Comment by 0ME9A** [comment]
Just confirm.
[

https://user-images.githubusercontent.com/83957658/208308898-caea5210-1d01-4736-b92c-c9a1ecf7c267.mp4

](url)

**Comment by harshraj8843** [comment]
Awesome 🤩

**Comment by harshraj8843** [comment]
Can you please suggest, how can we improve this website?

Saw your [website](https://ome9a.com/), it's so cool 😃

**Comment by 0ME9A** [comment]
Thank you, 🙏

And It's an honor to me If I help something to improve this site. 😃

**Comment by 0ME9A** [comment]
Task completed Filter program by lang feature added. 🎉🎉🎉

**Comment by harshraj8843** [comment]
This issue was fixed in the `fork`, not in the `base` repo

**Comment by 0ME9A** [comment]
Sorry, I'll fix it very soon.🧐

**Comment by harshraj8843** [comment]
No need to `fix`

The changes will automatically be merged in #5737

**Comment by 0ME9A** [comment]
Ok

**Comment by 0ME9A** [comment]
now you can merge it.
