### ISSUE TITLE
Readme.md file Images 404: Not Found

### ISSUE THREAD

**Issue by 0ME9A** [codinasion/program#5747]
## Hi there

We can see that readme.md file contains the image URL but the readme.md file can not able to find that images url.

Example first image URL is:- _https://raw.githubusercontent.com/codinasion/.github/master/assets/rainbow-hr.png_

But there is no any images file in dir `codinasion/.github/master/assets/`

So add image files to fix this problem. 🖼️

@har

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)

**Comment by harshraj8843** [comment]
Hey @0ME9A 

That will be added asap https://github.com/orgs/codinasion/teams/team/discussions/5

**Comment by 0ME9A** [comment]
Great 👍
