### ISSUE TITLE
Write a C program to print ascii value of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#579]
### Description

Write a C program to print ascii value of a string

ASCII value is the numeric representation of a character. For example, the ASCII value of the character 'A' is 65. The ASCII value of the character 'a' is 97. The ASCII value of the character '0' is 48. The ASCII value of the character ' ' is 32.

```
Input  : ABC
Output : 65 66 67
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintAsciiValueOfAString.c` file
- Add `PrintAsciiValueOfAString.c` file in `print-ascii-value-of-a-string` folder

</details>

**Comment by Chirag8023** [comment]
!assign
