### ISSUE TITLE
`BUG` Rename File Script

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#5809]
### Description

The [`rename file script`](https://github.com/codinasion/program/blob/master/scripts/rename_files.py) is creating new files instead of renaming them

https://github.com/codinasion/program/blob/ad631886f3a8a59df7e10e0a2edb3b5493669a0d/scripts/rename_files.py#L72-L80

### Additional information

See 👉🏻 https://github.com/codinasion/program/commit/ad631886f3a8a59df7e10e0a2edb3b5493669a0d

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)

**Comment by hi-Kartik2004** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @hi-Kartik2004, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Hey @hi-Kartik2004 

Any idea why it is happening 🤔

**Comment by hi-Kartik2004** [comment]
Hey @harshraj8843, 
I've tested the script out, and according to my testing, **the script ran well and has no bugs**, According to me, two different branches being merged that have the same file might have caused the issue as the file that is to be renamed already exists.

**Note: this happens only when Someone adds an additional "<any_name>.extension" file to the folder.**

**For example:**
If a contributor **contributes a file to the folder find-string-length in cpp language with file name "calculate_string_len.cpp" The rename.py script will rename it to FindStringLength** (i.e The folder name as per the naming convention specified in data/languages.json),
But if another contributor **tries to contribute another .cpp file to solve the same problem it will not do anything as the FindStringLength.cpp file already exists** and two files cannot have the exactly same names with the same extensions.
hence the file added later will not be renamed.

PS: The script doesn't delete the additional file that exists in the folder.
Do you want me to add that functionality?
