### ISSUE TITLE
Write a Python program to print ascii value of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#591]
### Description

Write a Python program to print ascii value of a string

ASCII value is the numeric representation of a character. For example, the ASCII value of the character 'A' is 65. The ASCII value of the character 'a' is 97. The ASCII value of the character '0' is 48. The ASCII value of the character ' ' is 32.

```
Input  : ABC
Output : 65 66 67
```
<details>
<summary>How to contribute</summary>

- Save the solution in `print-ascii-value-of-a-string.py` file
- Add `print-ascii-value-of-a-string.py` file in `print-ascii-value-of-a-string` folder

</details>

**Comment by Arnab-K-S** [comment]
Hey there! I would like to contribute for this issue. Please Assign me this issue.

**Comment by harshraj8843** [comment]
Hey @Arnab-K-S 

You can comment `!assign` on any issue you want to contribute to, to be auto-assigned

```
!assign
```
