### ISSUE TITLE
Write a Scala program to print ascii value of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#595]
### Description

Write a Scala program to print ascii value of a string

ASCII value is the numeric representation of a character. For example, the ASCII value of the character 'A' is 65. The ASCII value of the character 'a' is 97. The ASCII value of the character '0' is 48. The ASCII value of the character ' ' is 32.

```
Input  : ABC
Output : 65 66 67
```
<details>
<summary>How to contribute</summary>

- Save the solution in `printAsciiValueOfAString.scala` file
- Add `printAsciiValueOfAString.scala` file in `print-ascii-value-of-a-string` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
