### ISSUE TITLE
Write a TypeScript program to print ascii value of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#597]
### Description

Write a TypeScript program to print ascii value of a string

ASCII value is the numeric representation of a character. For example, the ASCII value of the character 'A' is 65. The ASCII value of the character 'a' is 97. The ASCII value of the character '0' is 48. The ASCII value of the character ' ' is 32.

```
Input  : ABC
Output : 65 66 67
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintAsciiValueOfAString.ts` file
- Add `PrintAsciiValueOfAString.ts` file in `print-ascii-value-of-a-string` folder

</details>

**Comment by krishan-here** [comment]
hey assign it to me!

**Comment by krishan-here** [comment]
hey I have created a PR for this #627 please review and merge.

**Comment by krishan-here** [comment]
!assign
