### ISSUE TITLE
Script/rename_files.py fails when file_name is typographically same, but Uppercase-lower case mismatch

### ISSUE THREAD

**Issue by hi-Kartik2004** [codinasion/program#5971]
### Description

# Example
#### Ideally the file name must be AddTwoMatrices.c
![image](https://user-images.githubusercontent.com/111000515/211150753-e911c360-0a37-47b1-b3ee-c6cf9bbe8ac7.png)
#### script/rename_files.py runs....
![image](https://user-images.githubusercontent.com/111000515/211150834-d8403f3c-e24a-45a7-8f41-da0db1a27f26.png)
We get an error saying a file named exactly there exists and there are duplicate files, asking you to delete the wrong one.
But we can see that there is only one C file.
And the wrong file has not been corrected.

### Additional information

You may refer https://answers.microsoft.com/en-us/windows/forum/all/unable-to-name-files-with-a-capital-and-lower-case/5a50d483-ce64-46a3-9105-4e7468a5322e

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)

**Comment by hi-Kartik2004** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @hi-Kartik2004, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by hi-Kartik2004** [comment]
Hi @harshraj8843, can you please test the script out and let's see if it clears all the edge cases!! Thanks :)
