### ISSUE TITLE
Write a program to check anagram string

### ISSUE THREAD

**Issue by sahdev77** [codinasion/program#5987]
### Description

Two strings are said to be anagrams if they make a meaningful word by rearranging or shuffling the letters of the string. In other words, we can say that two strings are anagrams if they contain the same characters but in different order.

```
Input:  listen
Output: silent
```

**Comment by ShadyResurrected** [comment]
Can i be assigned this issue?

**Comment by ShadyResurrected** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @ShadyResurrected, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by ShadyResurrected** [comment]
ok

**Comment by Coder-12-ux** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Coder-12-ux, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by sohamsahare123** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @sohamsahare123, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by iligeoili** [comment]
i would like to work on this project if its still open

**Comment by Sumsum1000** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Sumsum1000, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by allan-anilson** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @allan-anilson, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Program added successfully :tada:

Thanks for your contribution :hugs:
