### ISSUE TITLE
Main branch ReadMe.md file images are not loading in the main branch

### ISSUE THREAD

**Issue by brundabharadwaj** [codinasion/program#5996]
### Description

![image](https://user-images.githubusercontent.com/49773125/211511733-185e247e-b688-4727-8007-abc83124d8d1.png)
 Please find above image for more details! 

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)

**Comment by hi-Kartik2004** [comment]
Hi @brundabharadwaj, what I see now is that the images are back, can you confirm the same?

###Reference image below:
![image](https://user-images.githubusercontent.com/111000515/211541685-e748038e-2813-49d8-ad33-82cec0c2ac30.png)

**Comment by brundabharadwaj** [comment]
Hi @hi-Kartik2004  , issue still persist -1/10/23 5:32PM IST
![image](https://user-images.githubusercontent.com/49773125/211546730-072a1958-762c-434a-804d-af6600a7108f.png)

**Comment by brundabharadwaj** [comment]
> Hi @brundabharadwaj, what I see now is that the images are back, can you confirm the same?
> 
> ### Reference image below:
> ![image](https://user-images.githubusercontent.com/111000515/211541685-e748038e-2813-49d8-ad33-82cec0c2ac30.png)

Did you try verifying from the master branch?

**Comment by hi-Kartik2004** [comment]
Hi @brundabharadwaj, all the branches except the data branch have the readme file and everything looks good at all branches with the readme.md file for me, I am not sure why you are not able to see the images.

As you said I have rechecked, I'm on the default branch as seen in the image below.
### Reference image

![image](https://user-images.githubusercontent.com/111000515/211549738-ac8f36b6-fdf5-4f77-8f08-e2f4d45eddb2.png)

**Comment by brundabharadwaj** [comment]
Okay could be as issue with my Google chrome version/ update, I tried opening the same repo from the edge browser and things look perfect! Closing this issue on the same note 👍🏻  Thanks @hi-Kartik2004

**Comment by hi-Kartik2004** [comment]
Glad :)

**Comment by harshraj8843** [comment]
This issue is very common depending on the browser we use and in some cases due to Internet Service Providers.

Some ISPs don't allow some specific URLs to access.

For example, (In India) if you are using `JIO` ISP then you won't be able to access `https://raw.githubusercontent.com` unless you use a `VPN`.

> **Note** The most image links we are using in the READMEs are accessed directly through `https://raw.githubusercontent.com/`
