### ISSUE TITLE
User can unassign  themselves when they are unable to contribute

### ISSUE THREAD

**Issue by brundabharadwaj** [codinasion/program#6000]
### Description

Solution:
Because of time constraints or any other reasons if user wants to step back they can do it be commenting something like 
 !unassign .
This feature provides other contributors an opportunity to contribute .

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)

**Comment by harshraj8843** [comment]
Users can unassign themselves from the side menu (I guess 🤔 ) 

I don't think this command will be useful

**Comment by brundabharadwaj** [comment]
Agreed!!
