### ISSUE TITLE
FindAreaOfASquare.c

### ISSUE THREAD

**Issue by Idanos99** [codinasion/program#6150]
### Description

```
#include <stdio.h>

float edge;

int main(void){
    printf("Enter the square edge:\n");
    scanf("%f", &edge);

    printf("The area of the square is: %f\n", edge*edge);

    return 0;
}
```

**Comment by ShivamK2002** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @ShivamK2002, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Hey @Idanos99 

Please create a pull request for #434

You can comment `!assign` on #434, to be auto-assigned

Thanks for contributing 🤗
