### ISSUE TITLE
FindLargestAndSmallestNumbersInAnArray.js the first function is not relevant to the task

### ISSUE THREAD

**Issue by pelegsch666** [codinasion/program#6304]
### Description

there is too much code in this file

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)

**Comment by pelegsch666** [comment]
!assgin

**Comment by harshraj8843** [comment]
Hey @pelegsch666 

Could you please explain the purpose of this issue 🤔 

File https://github.com/codinasion/program/blob/master/program/find-largest-and-smallest-numbers-in-an-array/FindLargestAndSmallestNumbersInAnArray.js seems right

https://github.com/codinasion/program/blob/5b511ced7045bc757222fa7eb9482b2bfbdb8289/program/find-largest-and-smallest-numbers-in-an-array/FindLargestAndSmallestNumbersInAnArray.js#L1-L10

**Comment by pelegsch666** [comment]
the function largesmall only sorting the array and doesnt return the values only the console log itself

**Comment by patel-aum** [comment]
function largeSmall(numbers) {
    let sorted = numbers.slice().sort(function (a, b) {
        return a - b;
    });
    let smallest = sorted[0];
    let largest = sorted[sorted.length - 1];
    return console.log(` ${largest} ${smallest}`);

}

let numbers = [1, 2, 3, 4, 5];
largeSmall(numbers);

> the function largesmall only sorting the array and doesnt return the values only the console log itself

**@pelegsch666 you are suggesting something like thiss right?**

**Comment by pelegsch666** [comment]
i have a better solution 
function findingSmallestLargest(numArr) {
    return [Math.max(...numArr), Math.min(...numArr)];
  
}
  //those are for testing purpose
  const numberArrTest = [1, 2, 3, 4, 5];
  findingSmallLarge(numberArrTest);

**Comment by patel-aum** [comment]
> 

Okay your approach is more direct and doesn't require creating a sorted copy of the array, so it may be faster and more efficient for large arrays. Good 🔥

**Comment by patel-aum** [comment]
@harshraj8843 can we update this code with this approach?

**Comment by harshraj8843** [comment]
Yes, this approach is much better 😃
