### ISSUE TITLE
Write a C program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#64]
### Description

Write a C program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfCube.c` file
- Add `FindVolumeOfCube.c` file in `find-volume-of-cube` folder

</details>

**Comment by KaptainCS3** [comment]
assign me

**Comment by SidharthSarangi** [comment]
!assign

**Comment by esivakumar18** [comment]
!assign
