### ISSUE TITLE
Write a C program to whether two given input Strings are anagram or not

### ISSUE THREAD

**Issue by deepakkhanna18** [codinasion/program#6414]
### Description

Write a C program to whether two given input Strings are anagram or not

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)

**Comment by genedafnkid** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @genedafnkid, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.
