### ISSUE TITLE
Write a C program to convert inches to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#649]
### Description

Write a C program to convert inches to centimeters

1 inch = 2.54 centimeters

```
Input  : 5
Output : 12.7
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToCentimeters.c` file
- Add `ConvertInchesToCentimeters.c` file in `convert-inches-to-centimeters` folder

</details>

**Comment by PraaneshSelvaraj** [comment]
!assign
