### ISSUE TITLE
Write a C# program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#65]
### Description

Write a C# program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfCube.cs` file
- Add `FindVolumeOfCube.cs` file in `find-volume-of-cube` folder

</details>

**Comment by Khushi260** [comment]
!assign
