### ISSUE TITLE
Write a C++ program to convert inches to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#651]
### Description

Write a C++ program to convert inches to centimeters

1 inch = 2.54 centimeters

```
Input  : 5
Output : 12.7
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToCentimeters.cpp` file
- Add `ConvertInchesToCentimeters.cpp` file in `convert-inches-to-centimeters` folder

</details>

**Comment by destroyer5067** [comment]
!assign

**Comment by Osher160** [comment]
!assign
