### ISSUE TITLE
Write a GO program to convert inches to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#654]
### Description

Write a GO program to convert inches to centimeters

1 inch = 2.54 centimeters

```
Input  : 5
Output : 12.7
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_inches_to_centimeters.go` file
- Add `convert_inches_to_centimeters.go` file in `convert-inches-to-centimeters` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign
