### ISSUE TITLE
Write a Java program to convert inches to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#655]
### Description

Write a Java program to convert inches to centimeters

1 inch = 2.54 centimeters

```
Input  : 5
Output : 12.7
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToCentimeters.java` file
- Add `ConvertInchesToCentimeters.java` file in `convert-inches-to-centimeters` folder

</details>

**Comment by sahooankeeta** [comment]
!assign
