### ISSUE TITLE
Write a JavaScript program to convert inches to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#656]
### Description

Write a JavaScript program to convert inches to centimeters

1 inch = 2.54 centimeters

```
Input  : 5
Output : 12.7
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToCentimeters.js` file
- Add `ConvertInchesToCentimeters.js` file in `convert-inches-to-centimeters` folder

</details>

**Comment by rwlc** [comment]
!assign
