### ISSUE TITLE
Write a Kotlin program to convert inches to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#658]
### Description

Write a Kotlin program to convert inches to centimeters

1 inch = 2.54 centimeters

```
Input  : 5
Output : 12.7
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToCentimeters.kt` file
- Add `ConvertInchesToCentimeters.kt` file in `convert-inches-to-centimeters` folder

</details>

**Comment by rksp25** [comment]
!assign
