### ISSUE TITLE
Write a C++ program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#66]
### Description

Write a C++ program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfCube.cpp` file
- Add `FindVolumeOfCube.cpp` file in `find-volume-of-cube` folder

</details>

**Comment by KaptainCS3** [comment]
assign me

**Comment by SidharthSarangi** [comment]
!assign

**Comment by SidharthSarangi** [comment]
@harshraj8843
