### ISSUE TITLE
Write a Python program to convert inches to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#661]
### Description

Write a Python program to convert inches to centimeters

1 inch = 2.54 centimeters

```
Input  : 5
Output : 12.7
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-inches-to-centimeters.py` file
- Add `convert-inches-to-centimeters.py` file in `convert-inches-to-centimeters` folder

</details>

**Comment by rakibul-islam-raju** [comment]
!assign
