### ISSUE TITLE
Write a Dart program to check anagram string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#6646]
### Description

Write a Dart program to check anagram string

Two strings are said to be anagrams if they make a meaningful word by rearranging or shuffling the letters of the string. In other words, we can say that two strings are anagrams if they contain the same characters but in different order.

```txt
Input  : pan, nap
Output : Anagram Strings
```

<sub>Contributed by - @sahdev77</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `write_a_program_to_check_anagram_string.dart` file
- Add `write_a_program_to_check_anagram_string.dart` file in `program/write-a-program-to-check-anagram-string` folder

</details>

**Comment by Hkashifa** [comment]
I would like to work on this

**Comment by harshraj8843** [comment]
Hey @Hkashifa 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by Hkashifa** [comment]
!assign

**Comment by Otamendiethio** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Otamendiethio, this issue is already assigned to @Hkashifa !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by pksX01** [comment]
!assign

**Comment by micies** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @micies, this issue is already assigned to @pksX01 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
