### ISSUE TITLE
Write a Rust program to check anagram string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#6659]
### Description

Write a Rust program to check anagram string

Two strings are said to be anagrams if they make a meaningful word by rearranging or shuffling the letters of the string. In other words, we can say that two strings are anagrams if they contain the same characters but in different order.

```txt
Input  : pan, nap
Output : Anagram Strings
```

<sub>Contributed by - @sahdev77</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `write_a_program_to_check_anagram_string.rs` file
- Add `write_a_program_to_check_anagram_string.rs` file in `program/write-a-program-to-check-anagram-string` folder

</details>

**Comment by Amirth24** [comment]
!assign
