### ISSUE TITLE
Write a Swift program to convert inches to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#666]
### Description

Write a Swift program to convert inches to centimeters

1 inch = 2.54 centimeters

```
Input  : 5
Output : 12.7
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToCentimeters.swift` file
- Add `ConvertInchesToCentimeters.swift` file in `convert-inches-to-centimeters` folder

</details>

**Comment by urlunaticguy** [comment]
!assign
