### ISSUE TITLE
Write a TypeScript program to check anagram string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#6662]
### Description

Write a TypeScript program to check anagram string

Two strings are said to be anagrams if they make a meaningful word by rearranging or shuffling the letters of the string. In other words, we can say that two strings are anagrams if they contain the same characters but in different order.

```txt
Input  : pan, nap
Output : Anagram Strings
```

<sub>Contributed by - @sahdev77</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `WriteAProgramToCheckAnagramString.ts` file
- Add `WriteAProgramToCheckAnagramString.ts` file in `program/write-a-program-to-check-anagram-string` folder

</details>

**Comment by 786-aquib** [comment]
Hello ,
i do it ..

**Comment by harshraj8843** [comment]
Hey @786-aquib 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by 786-aquib** [comment]
It is done na??
Or i have to do something??

**Comment by harshraj8843** [comment]
Hey @786-aquib 

If you want to contribute to an issue, simply comment `!assign` and the issue will be auto-assigned to you 🤗 

You can try this on any other issue

**Comment by 786-aquib** [comment]
This program is label as contributed by me na??
PR done by me na??

**Comment by crumbycupid** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @crumbycupid, this issue is already assigned to @786-aquib !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
