### ISSUE TITLE
Write a TypeScript program to convert inches to centimeters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#667]
### Description

Write a TypeScript program to convert inches to centimeters

1 inch = 2.54 centimeters

```
Input  : 5
Output : 12.7
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToCentimeters.ts` file
- Add `ConvertInchesToCentimeters.ts` file in `convert-inches-to-centimeters` folder

</details>

**Comment by MaestroDagan** [comment]
!assign

**Comment by Ishay1997** [comment]
!assign
