### ISSUE TITLE
Rainbow hr image not loading

### ISSUE THREAD

**Issue by roshan798** [codinasion/program#6703]
### Description

Rainbow hr image in the readme.md file is note showing 

### Additional information

![image](https://user-images.githubusercontent.com/107319136/226166899-7e44a0a2-8f29-4808-8d37-56ab9a59a1b9.png)

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)

**Comment by harshraj8843** [comment]
https://github.com/codinasion/program/issues/5996#issuecomment-1377222631
