### ISSUE TITLE
Write a C program to find maximum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#674]
### Description

Write a C program to find maximum of n numbers

```
Input  : 10 20 30 40 50
Output : 50
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindMaximumOfNNumbers.c` file
- Add `FindMaximumOfNNumbers.c` file in `find-maximum-of-n-numbers` folder

</details>

**Comment by Zeuhz-Droid** [comment]
!assign
