### ISSUE TITLE
Write a C++ program to find maximum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#676]
### Description

Write a C++ program to find maximum of n numbers

```
Input  : 10 20 30 40 50
Output : 50
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindMaximumOfNNumbers.cpp` file
- Add `FindMaximumOfNNumbers.cpp` file in `find-maximum-of-n-numbers` folder

</details>

**Comment by destroyer5067** [comment]
!assign

**Comment by grraghav120** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @grraghav120, this issue is already assigned to @destroyer5067 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Hey @destroyer5067,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by grraghav120** [comment]
!assign

**Comment by AbhinavPrabhat01** [comment]
!assign

**Comment by KarmakarRahul** [comment]
!assign
