### ISSUE TITLE
Write a GO program to find maximum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#679]
### Description

Write a GO program to find maximum of n numbers

```
Input  : 10 20 30 40 50
Output : 50
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_maximum_of_n_numbers.go` file
- Add `find_maximum_of_n_numbers.go` file in `find-maximum-of-n-numbers` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign

**Comment by vedantpople4** [comment]
!assign
