### ISSUE TITLE
Write a F# program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#68]
### Description

Write a F# program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfCube.fs` file
- Add `FindVolumeOfCube.fs` file in `find-volume-of-cube` folder

</details>

**Comment by AmanjeetCogoport** [comment]
!assign
