### ISSUE TITLE
Write a Java program to find maximum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#680]
### Description

Write a Java program to find maximum of n numbers

```
Input  : 10 20 30 40 50
Output : 50
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindMaximumOfNNumbers.java` file
- Add `FindMaximumOfNNumbers.java` file in `find-maximum-of-n-numbers` folder

</details>

**Comment by smilewithkhushi** [comment]
Hi, Can you assign this to me?
Also, does the PR pertaining to this issue stands valid for HacktoberFest 2022?

**Comment by RachitGarg-12** [comment]
!assign

**Comment by niteshbhaiya4224** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @niteshbhaiya4224, this issue is already assigned to @RachitGarg-12 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
