### ISSUE TITLE
Write a JavaScript program to find maximum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#681]
### Description

Write a JavaScript program to find maximum of n numbers

```
Input  : 10 20 30 40 50
Output : 50
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindMaximumOfNNumbers.js` file
- Add `FindMaximumOfNNumbers.js` file in `find-maximum-of-n-numbers` folder

</details>

**Comment by Zeuhz-Droid** [comment]
I would like to take on this issue harsharaj

**Comment by harshraj8843** [comment]
Hey @Zeuhz-Droid 

Please comment `!assign` on the issue you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by Zeuhz-Droid** [comment]
!assign
