### ISSUE TITLE
Write a Kotlin program to find maximum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#683]
### Description

Write a Kotlin program to find maximum of n numbers

```
Input  : 10 20 30 40 50
Output : 50
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindMaximumOfNNumbers.kt` file
- Add `FindMaximumOfNNumbers.kt` file in `find-maximum-of-n-numbers` folder

</details>

**Comment by RachitGarg-12** [comment]
!assign

**Comment by gsquareg2** [comment]
!assign

**Comment by esivakumar18** [comment]
!assign
