### ISSUE TITLE
Write a PHP program to find maximum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#685]
### Description

Write a PHP program to find maximum of n numbers

```
Input  : 10 20 30 40 50
Output : 50
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_maximum_of_n_numbers.php` file
- Add `find_maximum_of_n_numbers.php` file in `find-maximum-of-n-numbers` folder

</details>

**Comment by RachitGarg-12** [comment]
!assign
