### ISSUE TITLE
Write a Ruby program to find maximum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#688]
### Description

Write a Ruby program to find maximum of n numbers

```
Input  : 10 20 30 40 50
Output : 50
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindMaximumOfNNumbers.rb` file
- Add `FindMaximumOfNNumbers.rb` file in `find-maximum-of-n-numbers` folder

</details>

**Comment by jfinley6** [comment]
!assign
