### ISSUE TITLE
convert pound to kilogram

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#6887]
### Description

Write a program to convert pound to kilogram

1 pound = 0.453592 kg

```
Input  : 1
Output : 0.453592
```

<sub>Contributed by - @Aranarora</sub>
    

### Tracking Issues

- [x] #6888
- [x] #6889
- [x] #6890
- [x] #6891
- [x] #6892
- [x] #6893
- [x] #6894
- [x] #6895
- [x] #6896
- [x] #6897
- [x] #6898
- [x] #6899
- [x] #6900
- [x] #6901
- [x] #6902
- [x] #6903
- [x] #6904
- [x] #6905
- [x] #6906
- [x] #6907

**Comment by harisdev-netizen** [comment]
Assign me this issue

**Comment by harshraj8843** [comment]
Hey @harisdev-netizen 

All issues have already been closed

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```
