### ISSUE TITLE
Write a C program to convert pound to kilogram

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#6888]
### Description

Write a C program to convert pound to kilogram

1 pound = 0.453592 kg

```
Input  : 1
Output : 0.453592
```

<sub>Contributed by - @Aranarora</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertPoundToKilogram.c` file
- Add `ConvertPoundToKilogram.c` file in `program/convert-pound-to-kilogram` folder

</details>

**Comment by 1movemate** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @1movemate, this issue is already assigned to @anandfresh !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
