### ISSUE TITLE
Write a C++ program to convert pound to kilogram

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#6890]
### Description

Write a C++ program to convert pound to kilogram

1 pound = 0.453592 kg

```
Input  : 1
Output : 0.453592
```

<sub>Contributed by - @Aranarora</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertPoundToKilogram.cpp` file
- Add `ConvertPoundToKilogram.cpp` file in `program/convert-pound-to-kilogram` folder

</details>

**Comment by Shalevro2** [comment]
!assign

**Comment by 1movemate** [comment]
!assign
