### ISSUE TITLE
Write a F# program to convert pound to kilogram

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#6892]
### Description

Write a F# program to convert pound to kilogram

1 pound = 0.453592 kg

```
Input  : 1
Output : 0.453592
```

<sub>Contributed by - @Aranarora</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertPoundToKilogram.fs` file
- Add `ConvertPoundToKilogram.fs` file in `program/convert-pound-to-kilogram` folder

</details>

**Comment by Preetiraj3697** [comment]
!assign
