### ISSUE TITLE
Write a Haskell program to convert pound to kilogram

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#6894]
### Description

Write a Haskell program to convert pound to kilogram

1 pound = 0.453592 kg

```
Input  : 1
Output : 0.453592
```

<sub>Contributed by - @Aranarora</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_pound_to_kilogram.hs` file
- Add `convert_pound_to_kilogram.hs` file in `program/convert-pound-to-kilogram` folder

</details>

**Comment by akaliacius** [comment]
!assign
