### ISSUE TITLE
Write a Java program to convert pound to kilogram

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#6895]
### Description

Write a Java program to convert pound to kilogram

1 pound = 0.453592 kg

```
Input  : 1
Output : 0.453592
```

<sub>Contributed by - @Aranarora</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertPoundToKilogram.java` file
- Add `ConvertPoundToKilogram.java` file in `program/convert-pound-to-kilogram` folder

</details>

**Comment by pokharel-nishan** [comment]
!assign

**Comment by gitabysss** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @gitabysss, this issue is already assigned to @pokharel-nishan !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
