### ISSUE TITLE
Write a Kotlin program to convert pound to kilogram

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#6898]
### Description

Write a Kotlin program to convert pound to kilogram

1 pound = 0.453592 kg

```
Input  : 1
Output : 0.453592
```

<sub>Contributed by - @Aranarora</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertPoundToKilogram.kt` file
- Add `ConvertPoundToKilogram.kt` file in `program/convert-pound-to-kilogram` folder

</details>

**Comment by pksX01** [comment]
!assign

**Comment by pksX01** [comment]
@harshraj8843 Could you please review the PR.
