### ISSUE TITLE
Write a Python program to convert pound to kilogram

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#6901]
### Description

Write a Python program to convert pound to kilogram

1 pound = 0.453592 kg

```
Input  : 1
Output : 0.453592
```

<sub>Contributed by - @Aranarora</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-pound-to-kilogram.py` file
- Add `convert-pound-to-kilogram.py` file in `program/convert-pound-to-kilogram` folder

</details>

**Comment by hyperion912** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Dimarond, this issue is already assigned to @hyperion912 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
