### ISSUE TITLE
Write a Swift program to convert pound to kilogram

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#6906]
### Description

Write a Swift program to convert pound to kilogram

1 pound = 0.453592 kg

```
Input  : 1
Output : 0.453592
```

<sub>Contributed by - @Aranarora</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertPoundToKilogram.swift` file
- Add `ConvertPoundToKilogram.swift` file in `program/convert-pound-to-kilogram` folder

</details>

**Comment by queenkatherinecodes** [comment]
I would like to contribute and solve this issue! (:
