### ISSUE TITLE
Write a Swift program to find maximum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#691]
### Description

Write a Swift program to find maximum of n numbers

```
Input  : 10 20 30 40 50
Output : 50
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindMaximumOfNNumbers.swift` file
- Add `FindMaximumOfNNumbers.swift` file in `find-maximum-of-n-numbers` folder

</details>

**Comment by esivakumar18** [comment]
!assign
