### ISSUE TITLE
Write a Java program to find weekend days from number of years

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#6916]
### Description

Write a Java program to find weekend days from number of years

Weekend means Saturday & Sunday together. In total, we have 52 weeks in a year. So there are 52 weekends in a year. So, in normal we have 104 Weekend Days.

```
Input  : 1 
Output : 104
```

<sub>Contributed by - @Aranarora</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `FindWeekendDaysFromNumberOfYears.java` file
- Add `FindWeekendDaysFromNumberOfYears.java` file in `program/find-weekend-days-from-number-of-years` folder

</details>

**Comment by harshraj8843** [comment]
Hey @hyperion912, this issue is already assigned to @FINUSAM !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by jaswanthg76** [comment]
'm new to open-sourcing and I have no clue about what I should be doing. Can anyone guide me? I have basic knowledge of java
let me know in which way I can help you.

**Comment by harshraj8843** [comment]
Hey @jaswanthg76 

As a starting point, you can follow:

1. Find the issue you want to contribute to

	> **Note** You can use labels to narrow down your search, like `java` `c` `python`

3. Get auto-assigned to the issue by commenting `!assign` on the issue, you want to contribute to

	```
	!assign
	```

4. Raise a PR for the respective issue

Hope this will help 🤗

**Comment by jaswanthg76** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @jaswanthg76, this issue is already assigned to @FINUSAM !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
