### ISSUE TITLE
Write a Julia program to find weekend days from number of years

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#6918]
### Description

Write a Julia program to find weekend days from number of years

Weekend means Saturday & Sunday together. In total, we have 52 weeks in a year. So there are 52 weekends in a year. So, in normal we have 104 Weekend Days.

```
Input  : 1 
Output : 104
```

<sub>Contributed by - @Aranarora</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `find-weekend-days-from-number-of-years.jl` file
- Add `find-weekend-days-from-number-of-years.jl` file in `program/find-weekend-days-from-number-of-years` folder

</details>

**Comment by abhisek-1221** [comment]
!assign

**Comment by abhisek-1221** [comment]
I've added the julia code and sent the PR
