### ISSUE TITLE
Write a TypeScript program to find maximum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#692]
### Description

Write a TypeScript program to find maximum of n numbers

```
Input  : 10 20 30 40 50
Output : 50
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindMaximumOfNNumbers.ts` file
- Add `FindMaximumOfNNumbers.ts` file in `find-maximum-of-n-numbers` folder

</details>

**Comment by rwlc** [comment]
!assign
