### ISSUE TITLE
Write a Python program to find weekend days from number of years

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#6922]
### Description

Write a Python program to find weekend days from number of years

Weekend means Saturday & Sunday together. In total, we have 52 weeks in a year. So there are 52 weekends in a year. So, in normal we have 104 Weekend Days.

```
Input  : 1 
Output : 104
```

<sub>Contributed by - @Aranarora</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `find-weekend-days-from-number-of-years.py` file
- Add `find-weekend-days-from-number-of-years.py` file in `program/find-weekend-days-from-number-of-years` folder

</details>

**Comment by FINUSAM** [comment]
Hi, i am new to contribution and my guess is this is also a newbie task. So how do I publish my work? Should I directly PR or should I be assigned to this ? Or should I comment the code ? Totally confused.

**Comment by harshraj8843** [comment]
Hey @FINUSAM 

Please get auto-assigned to the issue by commenting `!assign` on any issue you want to contribute to.

Then raise a PR 🤗 

```
!assign
```

**Comment by FINUSAM** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @FINUSAM, this issue is already assigned to @abdurafeyf !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by Ishay1997** [comment]
!assign
