### ISSUE TITLE
Seconds input can be dynamic

### ISSUE THREAD

**Issue by brundabharadwaj** [codinasion/program#6942]
Update https://github.com/codinasion/program/blob/master/program/convert-seconds-to-hours/convert-seconds-to-hours.r to accept dynamic input

> Seconds input can be dynamic
>
> _Originally posted by @brundabharadwaj in https://github.com/codinasion/program/pull/6937#pullrequestreview-1357826150_

**Comment by JahnabDutta** [comment]
!assign
