### ISSUE TITLE
Improvement : Input value Can we made Dynamic

### ISSUE THREAD

**Issue by brundabharadwaj** [codinasion/program#6955]
Update https://github.com/codinasion/program/blob/master/program/convert-pound-to-kilogram/ConvertPoundToKilogram.ts to accept input from user

> Improvement: Input value Can be made dynamic
>
> _Originally posted by @brundabharadwaj in https://github.com/codinasion/program/pull/6951#pullrequestreview-1357980286_

**Comment by patel-aum** [comment]
!assign
