### ISSUE TITLE
Code Improvement : To allow user input than hardcoding

### ISSUE THREAD

**Issue by brundabharadwaj** [codinasion/program#6978]
Update https://github.com/codinasion/program/blob/master/program/find-square-root-of-a-number/FindSquareRootOfANumber.cs to accept user input

> Code Improvement : To allow user input than hardcoding
>
> _Originally posted by @brundabharadwaj in https://github.com/codinasion/program/pull/6845#pullrequestreview-1358007985_

**Comment by roberanegussie** [comment]
!assign
