### ISSUE TITLE
Write a F# program to print hello world

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#7]
### Description

Write a F# program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.fs` file
- Add `PrintHelloWorld.fs` file in `print-hello-world` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
