### ISSUE TITLE
Write a Java program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#70]
### Description

Write a Java program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfCube.java` file
- Add `FindVolumeOfCube.java` file in `find-volume-of-cube` folder

</details>

**Comment by ashankritwik07** [comment]
Hi , sir I have gone through the problem you mentioned and also match my interest  ,so please assign this project to me.
Yours Faithfully,
Ashank Ritwik
