### ISSUE TITLE
Hacktoberfest 2022

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#702]
### Hacktoberfest 2022

If you face any error for your Hacktoberfest PR, such as:

- Issue while submitting PRs
- PR not labeled as `hacktoberfest-accepted`
- etc.

Please comment on this issue.

The Codinasion Team will try to fix it ASAP.

Thanks, everyone for contributing to this project 👍🏻

**Comment by error707-persona** [comment]
My PR was not labeled as hacktoberfest-accepted for Issue #81

**Comment by harshraj8843** [comment]
> My PR was not labeled as hacktoberfest-accepted for Issue #81

PR #1024 is not reviewed and merged.

It will be reviewed and merged soon, then only it will be labeled as `hacktoberfest-accepted`

**Comment by Mudi-Igbinoba** [comment]
My PRs are being excluded from the hacktoberfest platform
![Screenshot_20221013-112937_Chrome](https://user-images.githubusercontent.com/65790714/195573571-cf8d033f-3756-423e-9af8-cf96438c058b.jpg)

**Comment by harshraj8843** [comment]
## Update `13/10/2022`

This repo has been `excluded` from Hacktoberfest 2022

**Comment by krishan-here** [comment]
hey @harshraj8843  my 2 PR is excluded from hacktoberfest #1976 and #1973. what should i do here?
