### ISSUE TITLE
Improvement :modify the program to take user input

### ISSUE THREAD

**Issue by brundabharadwaj** [codinasion/program#7022]
Update https://github.com/codinasion/program/blob/master/program/convert-decimal-to-octal/ConvertDecimalToOctal.cs for accepting user input

> Improvement :modify the program to take user input
> 
> _Originally posted by @brundabharadwaj in https://github.com/codinasion/program/pull/7021#discussion_r1148599477_

**Comment by FINUSAM** [comment]
I am seeing multiple issues with this same theme. Was it intentional? Also is there any specific files I need to fix or should I look through all the programs?

**Comment by brundabharadwaj** [comment]
> I am seeing multiple issues with this same theme. Was it intentional? Also is there any specific files I need to fix or should I look through all the programs?

Yes , It was intentional so that anyone can utilize as tagged with good-first-issue.
You can find the file details by looking into the closed issue. (specifically in this case it's https://github.com/codinasion/program/pull/7021#discussion_r1148599477)

**Comment by harshraj8843** [comment]
Hey @brundabharadwaj, it will be better if we can specify the file to edit in the issue itself and also add the `language label` with the `good first issue` label while creating an issue like this

👉🏻 Update https://github.com/codinasion/program/blob/master/program/convert-decimal-to-octal/ConvertDecimalToOctal.cs
👉🏻 Label: `C#`
