### ISSUE TITLE
Write a C++ program to find area of a circle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#703]
### Description

Write a C++ program to find area of a circle

Area of circle = π × `Radius`^2

```
Radius : 2

Area : 12.566370614359172
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAreaOfACircle.cpp` file
- Add `FindAreaOfACircle.cpp` file in `find-area-of-a-circle` folder

</details>

**Comment by destroyer5067** [comment]
!assign
