### ISSUE TITLE
Write a Dart program to find area of a circle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#704]
### Description

Write a Dart program to find area of a circle

Area of circle = π × `Radius`^2

```
Radius : 2

Area : 12.566370614359172
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_area_of_a_circle.dart` file
- Add `find_area_of_a_circle.dart` file in `find-area-of-a-circle` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
