### ISSUE TITLE
Input values could be  from the user instead of hard coding

### ISSUE THREAD

**Issue by brundabharadwaj** [codinasion/program#7057]
Update : https://github.com/codinasion/program/blob/master/program/convert-hours-to-seconds/convert-hours-to-seconds.r
            
              Input values could be  from the user instead of hard coding

_Originally posted by @brundabharadwaj in https://github.com/codinasion/program/pull/7056#pullrequestreview-1360171295_

**Comment by aayushxrj** [comment]
!assign
