### ISSUE TITLE
Write a GO program to find area of a circle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#706]
### Description

Write a GO program to find area of a circle

Area of circle = π × `Radius`^2

```
Radius : 2

Area : 12.566370614359172
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_area_of_a_circle.go` file
- Add `find_area_of_a_circle.go` file in `find-area-of-a-circle` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign
