### ISSUE TITLE
Write a JavaScript program to find area of a circle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#708]
### Description

Write a JavaScript program to find area of a circle

Area of circle = π × `Radius`^2

```
Radius : 2

Area : 12.566370614359172
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAreaOfACircle.js` file
- Add `FindAreaOfACircle.js` file in `find-area-of-a-circle` folder

</details>

**Comment by RShalman** [comment]
I'll grab this one)

**Comment by RShalman** [comment]
!assign

**Comment by victoriacheng15** [comment]
The PR merged a while ago.
