### ISSUE TITLE
Write a JavaScript program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#71]
### Description

Write a JavaScript program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfCube.js` file
- Add `FindVolumeOfCube.js` file in `find-volume-of-cube` folder

</details>

**Comment by amitanshusahu** [comment]
### yep easy let me do this , please assign me the task ... 😄

**Comment by amitanshusahu** [comment]
!assign

**Comment by CodingWithHardik** [comment]
!assign

**Comment by Khushi260** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Khushi260, this issue is already assigned to @CodingWithHardik !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
