### ISSUE TITLE
Write a Python program to find area of a circle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#713]
### Description

Write a Python program to find area of a circle

Area of circle = π × `Radius`^2

```
Radius : 2

Area : 12.566370614359172
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-area-of-a-circle.py` file
- Add `find-area-of-a-circle.py` file in `find-area-of-a-circle` folder

</details>

**Comment by destroyer5067** [comment]
!assign
