### ISSUE TITLE
Write a R program to find area of a circle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#714]
### Description

Write a R program to find area of a circle

Area of circle = π × `Radius`^2

```
Radius : 2

Area : 12.566370614359172
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_area_of_a_circle.r` file
- Add `find_area_of_a_circle.r` file in `find-area-of-a-circle` folder

</details>

**Comment by esivakumar18** [comment]
!assign

**Comment by esivakumar18** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @esivakumar18, this issue is already assigned to @esivakumar18 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
