### ISSUE TITLE
I want to write a Java program that creates a simple form to input a name, age, email, phone number, and message, and then displays the input on a dialog box

### ISSUE THREAD

**Issue by minhaj-313** [codinasion/program#7145]

**Comment by harshraj8843** [comment]
Hey @roberanegussie, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by vishalsingh2972** [comment]
@minhaj-313 could you assign this to me if it's still open?

**Comment by minhaj-313** [comment]
> Java swing or fx?

Swing

**Comment by gitabysss** [comment]
swing

**Comment by gitabysss** [comment]
Can you review it?

**Comment by harshraj8843** [comment]
Hey @minhaj-313 & @gitabysss 

This repo contains programs that are easy and can be contributed in my different languages.

As for this program, it can't be contributed in all languages. See full language list 👉🏻 https://github.com/codinasion/program/blob/master/data/languages.json

Sorry, for the confusion and late response, but this program can't be accepted in this repo as it will cause additional issues for the website too

Thank you for giving your valuable time 🙏🏻
