### ISSUE TITLE
Write a Java program to implement NullPointerException Handling.

### ISSUE THREAD

**Issue by adityalearnsgit** [codinasion/program#7181]
### Description

NullPointerException is a RuntimeException. In Java, a special null value can be assigned to an object reference. NullPointerException is thrown when program attempts to use an object reference that has the null value.

**Comment by abhisek-1221** [comment]
How can I contribute to this issue as the !assign feature is for good first issues and not this

**Comment by adityalearnsgit** [comment]
@abhisek-1221 same goes for this one! You can create an issue of whatever program you like and after the owner of the repository respond, you can pull a request.
