### ISSUE TITLE
Write a Java program to implement user defined exception if number is greater than 10.

### ISSUE THREAD

**Issue by adityalearnsgit** [codinasion/program#7190]
### Description

I want to code a user defined exception which will display the message "The number is less than 10" when the user enters a number less than 10, "The number is 10" when the user enters the number 10, and last but not least, a user defined exception with a message "The number is greater than 10", when the user enters a number greater than 10.

**Comment by harshraj8843** [comment]
Hey @adityalearnsgit 

Is it something like

```
Input  : 9
Output : The number is less than 10

Input  : 10
Output : The number is 10

Input  : 11
Output : The number is greater than 10
```

**Comment by abhisek-1221** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @abhisek-1221, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by abhisek-1221** [comment]
Then how can I contribute to this code?

**Comment by Abdi-Tiruneh** [comment]
hey bro!
### **I think what you are looking for is the following one:**
class GreaterThanTenException extends Exception {
    public GreaterThanTenException(String message) {
        super(message);
    }
}

public class Main {
    public static void main(String[] args) {
        int number = 11;

        try {
            if (number < 10) {
                throw new GreaterThanTenException ("The number is less than 10.");
            } else if (number == 10) {
                throw new GreaterThanTenException ("The number is 10.");
            } else if (number > 10) {
                throw new GreaterThanTenException ("The number is greater than 10.");
            }
        } catch (NumberException e) {
            System.out.println("Caught exception: " + e.getMessage());
        }
    }
}

**Comment by Abdi-Tiruneh** [comment]
hey bro!
### **I think what you are looking for is the following one:**
class GreaterThanTenException extends Exception {
    public GreaterThanTenException(String message) {
        super(message);
    }
}

public class Main {
    public static void main(String[] args) {
        int number = 11;

        try {
            if (number < 10) {
                throw new GreaterThanTenException ("The number is less than 10.");
            } else if (number == 10) {
                throw new GreaterThanTenException ("The number is 10.");
            } else if (number > 10) {
                throw new GreaterThanTenException ("The number is greater than 10.");
            }
        } catch (NumberException e) {
            System.out.println("Caught exception: " + e.getMessage());
        }
    }
}

**Comment by abhisek-1221** [comment]
Nope, I've the code but I'm looking for the directory path where I can raise my PR and also to be assigned by the owners

**Comment by abhisek-1221** [comment]
@harshraj8843 Can you assign me this issue

**Comment by adityalearnsgit** [comment]
@abhisek-1221 I really appreciate your enthusiasm and your participation but I have raised this issue to solve it for myself as there was not any Java issues left. You can either checkout other issues or you can create an issue for yourself and wait for the owner to assign it to you.
