### ISSUE TITLE
Write a Julia program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#72]
### Description

Write a Julia program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-volume-of-cube.jl` file
- Add `find-volume-of-cube.jl` file in `find-volume-of-cube` folder

</details>

**Comment by AmanjeetCogoport** [comment]
!assign
