### ISSUE TITLE
This program can have Dynamic input

### ISSUE THREAD

**Issue by brundabharadwaj** [codinasion/program#7260]
This program can have Dynamic input
File to be updated : https://github.com/anandfresh/program/blob/35fe14503d0f23832fb92ccfc61c126f7ae966f7/program/find-surface-area-of-a-cylinder/FindSurfaceAreaOfACylinder.fs

_Originally posted by @brundabharadwaj in https://github.com/codinasion/program/pull/7242#pullrequestreview-1381292390_

**Comment by RiteshK-611** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @RiteshK-611, this issue is already assigned to @anandfresh !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
