### ISSUE TITLE
Write a Kotlin program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#73]
### Description

Write a Kotlin program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfCube.kt` file
- Add `FindVolumeOfCube.kt` file in `find-volume-of-cube` folder

</details>

**Comment by AmanjeetCogoport** [comment]
!assign
