### ISSUE TITLE
Write a F# program to convert feet to centimeters

### ISSUE THREAD

**Issue by RiteshK-611** [codinasion/program#7325]
### Description

Write a F# program to convert feet to centimeters

1 feet = 30.48 centimeters

```
Input  : 5 
Output : 152.4
```

<details>
<summary>How to contribute ?</summary>

-   Save the solution in `ConvertFeetToCentimeters.fs` file
-   Add `ConvertFeetToCentimeters.swift` file in `program/convert-feet-to-centimeters` folder
</details>

**Comment by harshraj8843** [comment]
Hey @RiteshK-611 

Issue #2991 already exists and has been contributed
