### ISSUE TITLE
Write a C++ program to convert fahrenheit to kelvin

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#7366]
### Description

Write a C++ program to convert fahrenheit to kelvin

(1°F − 32) × 5/9 + 273.15 = 255.928K

```
Input  : 1
Output : 255.928
```

<sub>Contributed by - @KyleMcIndoe</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFahrenheitToKelvin.cpp` file
- Add `ConvertFahrenheitToKelvin.cpp` file in `program/convert-fahrenheit-to-kelvin` folder

</details>

**Comment by RoniRan542** [comment]
!assign

**Comment by PavanKumarCB** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @PavanKumarCB, this issue is already assigned to @RoniRan542 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by PavanKumarCB** [comment]
This issue has not been addressed since a week. Would you be willing if i assign this to myself?

**Comment by PavanKumarCB** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @PavanKumarCB, this issue is already assigned to @RoniRan542 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by PavanKumarCB** [comment]
alright
