### ISSUE TITLE
Write a Dart program to convert fahrenheit to kelvin

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#7367]
### Description

Write a Dart program to convert fahrenheit to kelvin

(1°F − 32) × 5/9 + 273.15 = 255.928K

```
Input  : 1
Output : 255.928
```

<sub>Contributed by - @KyleMcIndoe</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_fahrenheit_to_kelvin.dart` file
- Add `convert_fahrenheit_to_kelvin.dart` file in `program/convert-fahrenheit-to-kelvin` folder

</details>

**Comment by gantanikhilraj** [comment]
I would like to work on this @harshraj8843, assign it to me.

**Comment by harshraj8843** [comment]
Hey @gantanikhilraj 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by gantanikhilraj** [comment]
!assign
