### ISSUE TITLE
Write a Julia program to convert fahrenheit to kelvin

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#7373]
### Description

Write a Julia program to convert fahrenheit to kelvin

(1°F − 32) × 5/9 + 273.15 = 255.928K

```
Input  : 1
Output : 255.928
```

<sub>Contributed by - @KyleMcIndoe</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-fahrenheit-to-kelvin.jl` file
- Add `convert-fahrenheit-to-kelvin.jl` file in `program/convert-fahrenheit-to-kelvin` folder

</details>

**Comment by Subham5401** [comment]
Hello, I'd take this further.
