### ISSUE TITLE
Write a Perl program to convert fahrenheit to kelvin

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#7375]
### Description

Write a Perl program to convert fahrenheit to kelvin

(1°F − 32) × 5/9 + 273.15 = 255.928K

```
Input  : 1
Output : 255.928
```

<sub>Contributed by - @KyleMcIndoe</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_fahrenheit_to_kelvin.pl` file
- Add `convert_fahrenheit_to_kelvin.pl` file in `program/convert-fahrenheit-to-kelvin` folder

</details>

**Comment by champati-v** [comment]
Hi! 
Can you assign me for this task if its not assigned yet. 
Thanks and regards
Vibekananda Champati

**Comment by harshraj8843** [comment]
Hey @champati-v 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by champati-v** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @champati-v, this issue is already assigned to @anandfresh !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by champati-v** [comment]
> Hey @champati-v, this issue is already assigned to @anandfresh !!!
> 
> Please choose another issue.
> 
> Thanks for your interest in contributing to this project.

Sure. Thanks
