### ISSUE TITLE
Write a Python program to convert fahrenheit to kelvin

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#7377]
### Description

Write a Python program to convert fahrenheit to kelvin

(1°F − 32) × 5/9 + 273.15 = 255.928K

```
Input  : 1
Output : 255.928
```

<sub>Contributed by - @KyleMcIndoe</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-fahrenheit-to-kelvin.py` file
- Add `convert-fahrenheit-to-kelvin.py` file in `program/convert-fahrenheit-to-kelvin` folder

</details>

**Comment by ammarfitwalla** [comment]
Can I work on this issue?

**Comment by harshraj8843** [comment]
Hey @ammarfitwalla 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by ammarfitwalla** [comment]
!assign
