### ISSUE TITLE
Write a R program to convert fahrenheit to kelvin

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#7378]
### Description

Write a R program to convert fahrenheit to kelvin

(1°F − 32) × 5/9 + 273.15 = 255.928K

```
Input  : 1
Output : 255.928
```

<sub>Contributed by - @KyleMcIndoe</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_fahrenheit_to_kelvin.r` file
- Add `convert_fahrenheit_to_kelvin.r` file in `program/convert-fahrenheit-to-kelvin` folder

</details>

**Comment by Subham5401** [comment]
Hi,
I'd take this further.

**Comment by ShantanuBadmanji** [comment]
Hi, I see there is no one assigned to this issue. I'd love to work on it.
