### ISSUE TITLE
Write a Swift program to convert fahrenheit to kelvin

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#7382]
### Description

Write a Swift program to convert fahrenheit to kelvin

(1°F − 32) × 5/9 + 273.15 = 255.928K

```
Input  : 1
Output : 255.928
```

<sub>Contributed by - @KyleMcIndoe</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFahrenheitToKelvin.swift` file
- Add `ConvertFahrenheitToKelvin.swift` file in `program/convert-fahrenheit-to-kelvin` folder

</details>

**Comment by Subham5401** [comment]
Hello, 
I'd like to take this further.

**Comment by harshraj8843** [comment]
Hey @Subham5401 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by laurenszlosek** [comment]
!assign

**Comment by laurenszlosek** [comment]
!assign
