### ISSUE TITLE
Write a TypeScript program to convert fahrenheit to kelvin

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#7383]
### Description

Write a TypeScript program to convert fahrenheit to kelvin

(1°F − 32) × 5/9 + 273.15 = 255.928K

```
Input  : 1
Output : 255.928
```

<sub>Contributed by - @KyleMcIndoe</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFahrenheitToKelvin.ts` file
- Add `ConvertFahrenheitToKelvin.ts` file in `program/convert-fahrenheit-to-kelvin` folder

</details>

**Comment by ReprogramAkash** [comment]
I would like to work on this.

**Comment by harshraj8843** [comment]
Hey @ReprogramAkash 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by dipankr** [comment]
!assign
