### ISSUE TITLE
Write a GO program to find sum of digits of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#739]
### Description

Write a GO program to find sum of digits of a number by recursion

Suppose we have a number `n` and we want to find the sum of its digits. For example, if `n = 123`, then the sum of its digits is `1 + 2 + 3 = 6`.

Recursion is a method of solving a problem where the solution depends on solutions to smaller instances of the same problem. In this case, we can use recursion to find the sum of digits of a number.

```
Input  : 123
Output : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_sum_of_digits_of_a_number_by_recursion.go` file
- Add `find_sum_of_digits_of_a_number_by_recursion.go` file in `find-sum-of-digits-of-a-number-by-recursion` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign

**Comment by sancoLgates** [comment]
!assign
