### ISSUE TITLE
Write a C program to print reverse of a number

### ISSUE THREAD

**Issue by PavanKumarCB** [codinasion/program#7394]
# Description
Write a C program to print reverse of a number

Reverse of a number is the number obtained by reversing the digits of the original number. For example, the reverse of 123 is 321. The reverse of 100 is 1. The reverse of 1000 is 1.
```
Input  : 123
Output : 321
```
<details>
<summary>How to Contribute</summary>

- Save the solution in ```program/PrintReverseOfANumber.c``` file.
- Add `PrintReverseOfANumber.c` file in print-reverse-of-a-number folder.

</details>

**Comment by harshraj8843** [comment]
Hey @PavanKumarCB, Issue #3469 already exists

If you want to contribute more issues, please raise the respective issues with `submit program` issue template https://github.com/codinasion/program/issues/new?assignees=harshraj8843&labels=add-program&template=submit-program.yml&title=%5BADD+PROGRAM%5D%3A+

**Comment by PavanKumarCB** [comment]
Alright. Thank you for letting me know how to raise new issues. When I clicked on the link to template it took me straight to create new issue. Will take care from now onwards.

**Comment by PavanKumarCB** [comment]
but i don't see a file to of a program to reverse a number in C in the respective folder

**Comment by harshraj8843** [comment]
Hey @PavanKumarCB 

Thanks for reporting this 👍🏻 

It seems like, we lost that file in the renaming process because it wasn't in the correct folder.

So, this issue is available for contribution 🤗 

###### `Rename File Script`: https://github.com/codinasion/program/blob/master/scripts/rename_files.py
