### ISSUE TITLE
find roots of quadratic equation

### ISSUE THREAD

**Issue by PavanKumarCB** [codinasion/program#7464]
### Description

Use the quadratic formula to find the roots of the quadratic equation

x = $\(-b &plusmn \sqrt\(b^2 - 4ac\)\)/2a$

The input will be the coefficients of $x^2$, $x$, and the constant $c$.

```
Input  : 1 2 1
Output : -1 -1
```

**Comment by harshraj8843** [comment]
Program added successfully :tada:

Thanks for your contribution :hugs:
