### ISSUE TITLE
Write a C program to find roots of quadratic equation

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#7472]
### Description

Write a C program to find roots of quadratic equation

Use the quadratic formula to find the roots of the quadratic equation

x = $\(-b &plusmn \sqrt\(b^2 - 4ac\)\)/2a$

The input will be the coefficients of $x^2$, $x$, and the constant $c$.

```
Input  : 1 2 1
Output : -1 -1
```

<sub>Contributed by - @PavanKumarCB</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `FindRootsOfQuadraticEquation.c` file
- Add `FindRootsOfQuadraticEquation.c` file in `program/find-roots-of-quadratic-equation` folder

</details>

**Comment by PavanKumarCB** [comment]
!assign

**Comment by Debajyati** [comment]
!assign

**Comment by Debajyati** [comment]
Okay, no problem. I'm just a beginner with a little knowledge of GitHub, and I am learning through experimenting. I didn't actually know multiple people can't be assigned for one issue. I'm sorry for this wrong practice.
