### ISSUE TITLE
Write a Scala program to find roots of quadratic equation

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#7489]
### Description

Write a Scala program to find roots of quadratic equation

Use the quadratic formula to find the roots of the quadratic equation

x = $\(-b &plusmn \sqrt\(b^2 - 4ac\)\)/2a$

The input will be the coefficients of $x^2$, $x$, and the constant $c$.

```
Input  : 1 2 1
Output : -1 -1
```

<sub>Contributed by - @PavanKumarCB</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `findRootsOfQuadraticEquation.scala` file
- Add `findRootsOfQuadraticEquation.scala` file in `program/find-roots-of-quadratic-equation` folder

</details>

**Comment by pranay136** [comment]
!assign
