### ISSUE TITLE
Write a PHP program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#75]
### Description

Write a PHP program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_volume_of_cube.php` file
- Add `find_volume_of_cube.php` file in `find-volume-of-cube` folder

</details>

**Comment by Mahak008** [comment]
!assign
