### ISSUE TITLE
Two files with similar name for one program

### ISSUE THREAD

**Issue by RiteshK-611** [codinasion/program#7519]
There are two files with similar name containing same code. 
One of the file must be removed.

[FindRootsOfQuadraticEquation.scala](https://github.com/codinasion/program/blob/master/program/find-roots-of-quadratic-equation/FindRootsOfQuadraticEquation.scala)
[findRootsOfQuadraticEquation.scala](https://github.com/codinasion/program/blob/master/program/find-roots-of-quadratic-equation/findRootsOfQuadraticEquation.scala)

This problem is giving below warning on cloning the forked repo

![image](https://user-images.githubusercontent.com/61982298/235884480-9d9a0b8b-e74e-46d2-94d8-3cd6610ac5c6.png)

**Comment by harshraj8843** [comment]
Hey @RiteshK-611 

Thanks for reporting this 🤗 

There is a bug in our `rename file script` 👉🏻 https://github.com/codinasion/program/blob/master/scripts/rename_files.py

Hopefully, we will be able to fix it soon

<sub>Reference #5809</sub>
