### ISSUE TITLE
Write a C++ program to find area of a right angled triangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#759]
### Description

Write a C++ program to find area of a right angled triangle

Area of right angled triangle = 0.5 × `Base` × `Height`

```
Base   : 2
Height : 3

Area : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAreaOfARightAngledTriangle.cpp` file
- Add `FindAreaOfARightAngledTriangle.cpp` file in `find-area-of-a-right-angled-triangle` folder

</details>

**Comment by SRR-CODER** [comment]
!assign
