### ISSUE TITLE
Write a Python program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#76]
### Description

Write a Python program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-volume-of-cube.py` file
- Add `find-volume-of-cube.py` file in `find-volume-of-cube` folder

</details>

**Comment by heyyayesh** [comment]
!assign
