### ISSUE TITLE
Write a Java program to find area of a right angled triangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#763]
### Description

Write a Java program to find area of a right angled triangle

Area of right angled triangle = 0.5 × `Base` × `Height`

```
Base   : 2
Height : 3

Area : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAreaOfARightAngledTriangle.java` file
- Add `FindAreaOfARightAngledTriangle.java` file in `find-area-of-a-right-angled-triangle` folder

</details>

**Comment by rajdip-b** [comment]
Can I be assigned this issue under Hacktoberfest2022?

**Comment by harshraj8843** [comment]
Hey @rajdip-b 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto assigned

```
!assign
```

**Comment by rajdip-b** [comment]
!assign
