### ISSUE TITLE
Write a JavaScript program to find area of a right angled triangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#764]
### Description

Write a JavaScript program to find area of a right angled triangle

Area of right angled triangle = 0.5 × `Base` × `Height`

```
Base   : 2
Height : 3

Area : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAreaOfARightAngledTriangle.js` file
- Add `FindAreaOfARightAngledTriangle.js` file in `find-area-of-a-right-angled-triangle` folder

</details>

**Comment by christiankilpatrick-dev** [comment]
!assign
