### ISSUE TITLE
Close the already merged issues

### ISSUE THREAD

**Issue by akkshayTandon** [codinasion/program#7656]
I recently contributed to the project and noticed there are some issues which are merged but they are still shown as open , so they need to the closed label on them. Here are some of them:
- close issue #126
- close issue #1660 
- close issue #1982 
- close issue #3425
- close issue #3920

**Comment by harshraj8843** [comment]
Thanks for noticing these issues 🤗 

<details>
<summary>Details</summary>

The pull request should be linked to the issue by using the keyword `Closes #ISSUE_NUMBER`

</details>

**Comment by akkshayTandon** [comment]
@harshraj8843 Can you please also close #5573 as it was merged in pull request #7133
