### ISSUE TITLE
Write a R program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#77]
### Description

Write a R program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_volume_of_cube.r` file
- Add `find_volume_of_cube.r` file in `find-volume-of-cube` folder

</details>

**Comment by YaSh8202** [comment]
!assign
