### ISSUE TITLE
Write a Rust program to find area of a right angled triangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#772]
### Description

Write a Rust program to find area of a right angled triangle

Area of right angled triangle = 0.5 × `Base` × `Height`

```
Base   : 2
Height : 3

Area : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_area_of_a_right_angled_triangle.rs` file
- Add `find_area_of_a_right_angled_triangle.rs` file in `find-area-of-a-right-angled-triangle` folder

</details>

**Comment by esivakumar18** [comment]
!assign
