### ISSUE TITLE
Write a TypeScript program to find area of a right angled triangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#775]
### Description

Write a TypeScript program to find area of a right angled triangle

Area of right angled triangle = 0.5 × `Base` × `Height`

```
Base   : 2
Height : 3

Area : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAreaOfARightAngledTriangle.ts` file
- Add `FindAreaOfARightAngledTriangle.ts` file in `find-area-of-a-right-angled-triangle` folder

</details>

**Comment by marcobuontempo** [comment]
!assign

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Greeshma-frontier, this issue is already assigned to @marcobuontempo !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
