### ISSUE TITLE
Write a Ruby program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#78]
### Description

Write a Ruby program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfCube.rb` file
- Add `FindVolumeOfCube.rb` file in `find-volume-of-cube` folder

</details>

**Comment by PraaneshSelvaraj** [comment]
!assign
