### ISSUE TITLE
Write a C# program to find factorial of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#784]
### Description

Write a C# program to find factorial of a number by recursion

Factorial of a number is the product of all the numbers from 1 to that number. For example, factorial of 5 is 5\*4\*3\*2\*1 = 120.

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindFactorialOfANumberByRecursion.cs` file
- Add `FindFactorialOfANumberByRecursion.cs` file in `find-factorial-of-a-number-by-recursion` folder

</details>

**Comment by Rachel3251** [comment]
assign
