### ISSUE TITLE
Write a Rust program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#79]
### Description

Write a Rust program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_volume_of_cube.rs` file
- Add `find_volume_of_cube.rs` file in `find-volume-of-cube` folder

</details>

**Comment by AmanjeetCogoport** [comment]
!assign
