### ISSUE TITLE
Write a Scala program to find factorial of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#799]
### Description

Write a Scala program to find factorial of a number by recursion

Factorial of a number is the product of all the numbers from 1 to that number. For example, factorial of 5 is 5\*4\*3\*2\*1 = 120.

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `findFactorialOfANumberByRecursion.scala` file
- Add `findFactorialOfANumberByRecursion.scala` file in `find-factorial-of-a-number-by-recursion` folder

</details>

**Comment by esivakumar18** [comment]
!assign
