### ISSUE TITLE
Write a Scala program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#80]
### Description

Write a Scala program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `findVolumeOfCube.sc` file
- Add `findVolumeOfCube.sc` file in `find-volume-of-cube` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
