### ISSUE TITLE
Write a Swift program to find factorial of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#800]
### Description

Write a Swift program to find factorial of a number by recursion

Factorial of a number is the product of all the numbers from 1 to that number. For example, factorial of 5 is 5\*4\*3\*2\*1 = 120.

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindFactorialOfANumberByRecursion.swift` file
- Add `FindFactorialOfANumberByRecursion.swift` file in `find-factorial-of-a-number-by-recursion` folder

</details>

**Comment by esivakumar18** [comment]
!assign
