### ISSUE TITLE
Write a Swift program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#81]
### Description

Write a Swift program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfCube.swift` file
- Add `FindVolumeOfCube.swift` file in `find-volume-of-cube` folder

</details>

**Comment by error707-persona** [comment]
Can you assign this one to me?

**Comment by harshraj8843** [comment]
Hey @error707-persona 

You can comment `!assign` on the issues you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by error707-persona** [comment]
!assign
