### ISSUE TITLE
Write a C program to convert paise to rupees

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#815]
### Description

Write a C program to convert paise to rupees

```
Input  ( Ps ) : 100
Output ( Rs ) : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertPaiseToRupees.c` file
- Add `ConvertPaiseToRupees.c` file in `convert-paise-to-rupees` folder

</details>

**Comment by DheekshaGopika** [comment]
!assign
