### ISSUE TITLE
Write a C++ program to convert paise to rupees

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#817]
### Description

Write a C++ program to convert paise to rupees

```
Input  ( Ps ) : 100
Output ( Rs ) : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertPaiseToRupees.cpp` file
- Add `ConvertPaiseToRupees.cpp` file in `convert-paise-to-rupees` folder

</details>

**Comment by yogesh-9999** [comment]
hey assing this to me

**Comment by yogesh-9999** [comment]
Hey assign this to me

**Comment by SRR-CODER** [comment]
!assign

**Comment by harshraj8843** [comment]
> Hey assign this to me

Hey @yogesh-9999 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto assigned

```
!assign
```

**Comment by harshraj8843** [comment]
Hey @SRR-CODER,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by AbhinavPrabhat01** [comment]
!assign

**Comment by gitabysss** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @gitabysss, this issue is already assigned to @AbhinavPrabhat01 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by SoumyadiptoPal** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @SoumyadiptoPal, this issue is already assigned to @AbhinavPrabhat01 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by pritish1906** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @pritish1906, this issue is already assigned to @AbhinavPrabhat01 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by roberanegussie** [comment]
!assign
