### ISSUE TITLE
Write a F# program to convert paise to rupees

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#819]
### Description

Write a F# program to convert paise to rupees

```
Input  ( Ps ) : 100
Output ( Rs ) : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertPaiseToRupees.fs` file
- Add `ConvertPaiseToRupees.fs` file in `convert-paise-to-rupees` folder

</details>

**Comment by yogesh-9999** [comment]
Hey @harshraj8843  assign this to me
