### ISSUE TITLE
Write a TypeScript program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#82]
### Description

Write a TypeScript program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfCube.ts` file
- Add `FindVolumeOfCube.ts` file in `find-volume-of-cube` folder

</details>

**Comment by error707-persona** [comment]
Hey, Can I work on this one? Please assign it to me if that's okay

**Comment by harshraj8843** [comment]
Hey @error707-persona 

Thanks for showing your interest in this project 😍 

You can simply comment `!assign` on any `good first issue` you want to contribute, it will be auto-assigned to you

```
!assign
````

**Comment by error707-persona** [comment]
!assign

**Comment by IradDoron** [comment]
!assign
