### ISSUE TITLE
Write a GO program to convert paise to rupees

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#820]
### Description

Write a GO program to convert paise to rupees

```
Input  ( Ps ) : 100
Output ( Rs ) : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_paise_to_rupees.go` file
- Add `convert_paise_to_rupees.go` file in `convert-paise-to-rupees` folder

</details>

**Comment by DheekshaGopika** [comment]
!assign
