### ISSUE TITLE
Write a Java program to convert paise to rupees

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#821]
### Description

Write a Java program to convert paise to rupees

```
Input  ( Ps ) : 100
Output ( Rs ) : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertPaiseToRupees.java` file
- Add `ConvertPaiseToRupees.java` file in `convert-paise-to-rupees` folder

</details>

**Comment by imtiyaz786** [comment]
!assign
