### ISSUE TITLE
Write a PHP program to convert paise to rupees

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#826]
### Description

Write a PHP program to convert paise to rupees

```
Input  ( Ps ) : 100
Output ( Rs ) : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_paise_to_rupees.php` file
- Add `convert_paise_to_rupees.php` file in `convert-paise-to-rupees` folder

</details>

**Comment by esivakumar18** [comment]
!assign
