### ISSUE TITLE
Write a Python program to convert paise to rupees

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#827]
### Description

Write a Python program to convert paise to rupees

```
Input  ( Ps ) : 100
Output ( Rs ) : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-paise-to-rupees.py` file
- Add `convert-paise-to-rupees.py` file in `convert-paise-to-rupees` folder

</details>

**Comment by RachitGarg-12** [comment]
Hey @harshraj8843 , can you please assign me this issue . It would be an honour , also this will be my first open source contribution . So i would be glad to contribute to this good first issue.

**Comment by anastazir** [comment]
!assign
