### ISSUE TITLE
Write a Ruby program to convert paise to rupees

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#829]
### Description

Write a Ruby program to convert paise to rupees

```
Input  ( Ps ) : 100
Output ( Rs ) : 1
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertPaiseToRupees.rb` file
- Add `ConvertPaiseToRupees.rb` file in `convert-paise-to-rupees` folder

</details>

**Comment by yogesh-9999** [comment]
hey assign this issue to  me
