### ISSUE TITLE
Write a JavaScript program to find sum of cubes of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#861]
### Description

Write a JavaScript program to find sum of cubes of numbers

Suppose you have a list of numbers, and you want to find the sum of the cubes of those numbers. For example, if you have the list `[1, 2, 3]`, you want to find the sum of the cubes of those numbers, which is `1^3 + 2^3 + 3^3 = 36`.

```
Input  : 1 2 3 4 5
Output : 225
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfCubesOfNumbers.js` file
- Add `FindSumOfCubesOfNumbers.js` file in `find-sum-of-cubes-of-numbers` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Greeshma-frontier,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by ShivamK2002** [comment]
!assign

**Comment by wheels63** [comment]
Can I take this one?

**Comment by harshraj8843** [comment]
Sure @wheels63
