### ISSUE TITLE
Write a PHP program to find sum of cubes of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#866]
### Description

Write a PHP program to find sum of cubes of numbers

Suppose you have a list of numbers, and you want to find the sum of the cubes of those numbers. For example, if you have the list `[1, 2, 3]`, you want to find the sum of the cubes of those numbers, which is `1^3 + 2^3 + 3^3 = 36`.

```
Input  : 1 2 3 4 5
Output : 225
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_sum_of_cubes_of_numbers.php` file
- Add `find_sum_of_cubes_of_numbers.php` file in `find-sum-of-cubes-of-numbers` folder

</details>

**Comment by esivakumar18** [comment]
!assign
