### ISSUE TITLE
Write a Python program to find sum of cubes of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#867]
### Description

Write a Python program to find sum of cubes of numbers

Suppose you have a list of numbers, and you want to find the sum of the cubes of those numbers. For example, if you have the list `[1, 2, 3]`, you want to find the sum of the cubes of those numbers, which is `1^3 + 2^3 + 3^3 = 36`.

```
Input  : 1 2 3 4 5
Output : 225
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-sum-of-cubes-of-numbers.py` file
- Add `find-sum-of-cubes-of-numbers.py` file in `find-sum-of-cubes-of-numbers` folder

</details>

**Comment by archi-jain** [comment]
Hey @harshraj8843 Can I work on this issue for hacktoberfest

**Comment by anshu-6537** [comment]
!assign

**Comment by mak650650** [comment]
may I work on this

**Comment by harshraj8843** [comment]
> may I work on this

Hey @mak650650 

This issue has already been assigned to someone

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by mak650650** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @mak650650, this issue is already assigned to @anshu-6537 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by mak650650** [comment]
okk

**Comment by harshraj8843** [comment]
Hey @shokushwaha, this issue is already assigned to @anshu-6537 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
