### ISSUE TITLE
Write a GO program to find volume of a sphere

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#889]
### Description

Write a GO program to find volume of a sphere

Volume of sphere = 4/3 × π × `Radius`^3

```
Radius : 2

Volume : 33.510321638291124
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_volume_of_a_sphere.go` file
- Add `find_volume_of_a_sphere.go` file in `find-volume-of-a-sphere` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign
