### ISSUE TITLE
Write a JavaScript program to find volume of a sphere

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#891]
### Description

Write a JavaScript program to find volume of a sphere

Volume of sphere = 4/3 × π × `Radius`^3

```
Radius : 2

Volume : 33.510321638291124
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfASphere.js` file
- Add `FindVolumeOfASphere.js` file in `find-volume-of-a-sphere` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
