### ISSUE TITLE
Write a R program to find volume of a sphere

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#897]
### Description

Write a R program to find volume of a sphere

Volume of sphere = 4/3 × π × `Radius`^3

```
Radius : 2

Volume : 33.510321638291124
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_volume_of_a_sphere.r` file
- Add `find_volume_of_a_sphere.r` file in `find-volume-of-a-sphere` folder

</details>

**Comment by esivakumar18** [comment]
!assign
