### ISSUE TITLE
Write a Java program to print hello world

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#9]
### Description

Write a Java program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.java` file
- Add `PrintHelloWorld.java` file in `print-hello-world` folder

</details>

**Comment by ashankritwik07** [comment]
!assign

**Comment by KaptainCS3** [comment]
assign me
