### ISSUE TITLE
Write a C program to print reverse of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#914]
### Description

Write a C program to print reverse of a string

Reverse of a string is the string with the characters in reverse order. For example, the reverse of "hello" is "olleh".

```
Input  : abcd
Output : dcba
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintReverseOfAString.c` file
- Add `PrintReverseOfAString.c` file in `print-reverse-of-a-string` folder

</details>

**Comment by anxkhn** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @anxkhn,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Osher160** [comment]
!assign
