### ISSUE TITLE
Write a C++ program to print reverse of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#916]
### Description

Write a C++ program to print reverse of a string

Reverse of a string is the string with the characters in reverse order. For example, the reverse of "hello" is "olleh".

```
Input  : abcd
Output : dcba
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintReverseOfAString.cpp` file
- Add `PrintReverseOfAString.cpp` file in `print-reverse-of-a-string` folder

</details>

**Comment by Mahak008** [comment]
!assign

**Comment by Taanvee** [comment]
Can you assign it to me?

**Comment by Rainingcity** [comment]
!assign
