### ISSUE TITLE
Write a JavaScript program to print reverse of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#921]
### Description

Write a JavaScript program to print reverse of a string

Reverse of a string is the string with the characters in reverse order. For example, the reverse of "hello" is "olleh".

```
Input  : abcd
Output : dcba
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintReverseOfAString.js` file
- Add `PrintReverseOfAString.js` file in `print-reverse-of-a-string` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
