### ISSUE TITLE
Write a Kotlin program to print reverse of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#923]
### Description

Write a Kotlin program to print reverse of a string

Reverse of a string is the string with the characters in reverse order. For example, the reverse of "hello" is "olleh".

```
Input  : abcd
Output : dcba
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintReverseOfAString.kt` file
- Add `PrintReverseOfAString.kt` file in `print-reverse-of-a-string` folder

</details>

**Comment by UsmanFani** [comment]
!assign
