### ISSUE TITLE
Write a Scala program to print reverse of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#930]
### Description

Write a Scala program to print reverse of a string

Reverse of a string is the string with the characters in reverse order. For example, the reverse of "hello" is "olleh".

```
Input  : abcd
Output : dcba
```
<details>
<summary>How to contribute</summary>

- Save the solution in `printReverseOfAString.scala` file
- Add `printReverseOfAString.scala` file in `print-reverse-of-a-string` folder

</details>

**Comment by esivakumar18** [comment]
!assign
