### ISSUE TITLE
Write a C program to find sum of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#957]
### Description

Write a C program to find sum of numbers

```
Input  : 1 2 3 4 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNumbers.c` file
- Add `FindSumOfNumbers.c` file in `find-sum-of-numbers` folder

</details>

**Comment by anxkhn** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @anxkhn,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Osher160** [comment]
!assign
