### ISSUE TITLE
Write a GO program to find sum of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#962]
### Description

Write a GO program to find sum of numbers

```
Input  : 1 2 3 4 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_sum_of_numbers.go` file
- Add `find_sum_of_numbers.go` file in `find-sum-of-numbers` folder

</details>

**Comment by MadhuS-1605** [comment]
!assign
