### ISSUE TITLE
Write a Java program to find sum of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#963]
### Description

Write a Java program to find sum of numbers

```
Input  : 1 2 3 4 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNumbers.java` file
- Add `FindSumOfNumbers.java` file in `find-sum-of-numbers` folder

</details>

**Comment by error707-persona** [comment]
!assign
