### ISSUE TITLE
Write a JavaScript program to find sum of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#964]
### Description

Write a JavaScript program to find sum of numbers

```
Input  : 1 2 3 4 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNumbers.js` file
- Add `FindSumOfNumbers.js` file in `find-sum-of-numbers` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
