### ISSUE TITLE
Write a PHP program to find sum of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#968]
### Description

Write a PHP program to find sum of numbers

```
Input  : 1 2 3 4 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_sum_of_numbers.php` file
- Add `find_sum_of_numbers.php` file in `find-sum-of-numbers` folder

</details>

**Comment by rizkytegar** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @rizkytegar,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by rizkytegar** [comment]
hi Harsh Raj, thanks for reminding me. 

I totally forgot about this project after hacktoberfest. I'll be working on some of the tasks I've defined in this repo as soon as I can. 

thank you

**Comment by esivakumar18** [comment]
!assign
