### ISSUE TITLE
Write a Python program to find sum of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#969]
### Description

Write a Python program to find sum of numbers

```
Input  : 1 2 3 4 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-sum-of-numbers.py` file
- Add `find-sum-of-numbers.py` file in `find-sum-of-numbers` folder

</details>

**Comment by EniolaAdemola** [comment]
!assign
