### ISSUE TITLE
Write a Ruby program to find sum of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#971]
### Description

Write a Ruby program to find sum of numbers

```
Input  : 1 2 3 4 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNumbers.rb` file
- Add `FindSumOfNumbers.rb` file in `find-sum-of-numbers` folder

</details>

**Comment by PraaneshSelvaraj** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @PraaneshSelvaraj,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by rafaover** [comment]
!assign
