### ISSUE TITLE
Write a Swift program to find sum of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#974]
### Description

Write a Swift program to find sum of numbers

```
Input  : 1 2 3 4 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNumbers.swift` file
- Add `FindSumOfNumbers.swift` file in `find-sum-of-numbers` folder

</details>

**Comment by esivakumar18** [comment]
!assign
