### ISSUE TITLE
Write a TypeScript program to find sum of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/program#975]
### Description

Write a TypeScript program to find sum of numbers

```
Input  : 1 2 3 4 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNumbers.ts` file
- Add `FindSumOfNumbers.ts` file in `find-sum-of-numbers` folder

</details>

**Comment by Greeshma-frontier** [comment]
!assign
